### ISSUE TITLE
Rust documentation

### ISSUE THREAD

**Issue by n1t0** [huggingface/tokenizers#10]
The main README is completely out-of-date.

We also want to provide documentation in order to prepare for the crate release. This covers the Rust documentation only, not bindings.

**Comment by ropottnik** [comment]
However, it's a great exercise for people who want to understand the code: Trying to get the example from the README.md to work as I'm currently doing 😛 

I could do a PR with an updated Readme example once I'm done.

**Comment by n1t0** [comment]
Another thing to consider is that the README is now completely out of sync with the last version on crates.io. We didn't release a Rust version for quite some time as we have unpublished dependencies. So you may want to pull `master`

**Comment by ropottnik** [comment]
Yeah, I noticed that when first using the `crates.io` version and the `master` code for reference. Quite a change.

I could also try putting the example into a testable API documentation string and have the Readme just refer to it, such that there are as few things as possible in the Readme that are likely to quickly become obsolete again.

**Comment by n1t0** [comment]
Sure, being able to test what's in the README would help a lot!
Everything that is related to the Rust documentation can fit in this issue, but feel free to open a new one if you prefer.

**Comment by ropottnik** [comment]
@n1t0 could you have a look at #373 if it is fine like this?

**Comment by strategy155** [comment]
Hello guys, how is the status for that issue? The README seems alright to me...

**Comment by ArthurZucker** [comment]
Let's close it 😉
