### ISSUE TITLE
How to tokenize data for models without tokenizer.json (SciBert use case)

### ISSUE THREAD

**Issue by LucaCappelletti94** [huggingface/tokenizers#1002]
Hello all, and thank you for making this fabulous Rust crate. 

While for most models, it works fine, this software requires the `tokenizer.json` file that some models like [SciBert](https://huggingface.co/allenai/scibert_scivocab_uncased), for some reason, lack.

Now, in the Python equivalent of this crate, this is handled somehow (I tried to follow around the code, but I honestly got lost entirely). Is there any analogous goto way to do so using this crate?

Thanks!

**Comment by Narsil** [comment]
Hi @LucaCappelletti94 ,

Thanks for your kind words.

Yes there is a way actually , the `transformers` library can do automatic conversion for you:

```
In [1]: from transformers import AutoTokenizer
tokenizer
In [2]: tokenizer = AutoTokenizer.from_pretrained("allenai/scibert_scivocab_uncased")
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 385/385 [00:00<00:00, 519kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 223k/223k [00:00<00:00, 543kB/s]

In [3]: tokenizer.save_pretrained("test")
Out[3]:
('test/tokenizer_config.json',
 'test/special_tokens_map.json',
 'test/vocab.txt',
 'test/added_tokens.json',
 'test/tokenizer.json')
```

This will give you the `tokenizer.json` you need. Other files are actually needed to work with `transformers` mainly for the semantics of tokens, but at least you get the `tokenizer.json` to work directly in rust if you want!

**Comment by LucaCappelletti94** [comment]
Ok so the goto method would be to make a small python wrapper, right? Or at least a python routine of some kind.

**Comment by Narsil** [comment]
The convertion code exists only in Python.

There are ways to do that in pure rust, but this method should work on any  `transformers` models on the hub, and since conversion should happen only once, I recommend it, it will avoid some pitfalls that might exist if the `Tokenizer` is not the one you expect and where you could end up with an erroneous `tokenizer.json` in the end.

**Comment by LucaCappelletti94** [comment]
Ok, perfect, I was able to integrate scibert in our experiment pipeline. Thank you!
