### ISSUE TITLE
`LayoutXLMProcessor` returns unexpected `offset_mapping` 

### ISSUE THREAD

**Issue by fredo838** [huggingface/tokenizers#1006]
Reposting the issue created here https://github.com/huggingface/transformers/issues/17278 as 
requested by @SaulLu 

### System Info

```shell
- `transformers` version: 4.19.1
- Platform: Linux-5.13.0-39-generic-x86_64-with-glibc2.31
- Python version: 3.10.0
- Huggingface_hub version: 0.6.0
- PyTorch version (GPU?): 1.11.0+cu102 (False)
- Tensorflow version (GPU?): 2.8.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

@NielsRogge 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
1. docker run -it --rm --entrypoint bash python
2. python3 -m pip install pip --upgrade
3. python3 -m pip install torch tensorflow pillow transformers
4. 
from transformers import LayoutXLMProcessor
from PIL import Image
import numpy as np
processor = LayoutXLMProcessor.from_pretrained("microsoft/layoutxlm-base", apply_ocr=False)
out = processor(
    text=["Hello", "there", "7.0", "Koningshof", "General", "Kenobi"],
    images=[Image.new(mode='RGB',size=(200, 200))],
    boxes=[[1,2,3,4] for _ in range(6)],
    return_offsets_mapping=True
)
reverted = processor.tokenizer.convert_ids_to_tokens(out.input_ids)
print(reverted)
is_start_of_word = np.asarray(out.offset_mapping)[:, 0] == 0
print(list(zip(reverted, is_start_of_word)))
```
prints 
```[('<s>', True), ('▁Hello', True), ('▁there', True), ('▁', True), ('7.0', True), ('▁Koning', True), ('s', False), ('hof', False), ('▁General', True), ('▁Ken', True), ('obi', False), ('</s>', True)]```

### Expected behavior

```shell
The token `"7.0"` gets converted to `('▁', True), ('7.0', True)`.
I would expect that the token `"7.0"` stays one token `('▁7.0', True)`
or that it gets converted to `('▁', True), ('7.0', False)`

Questions:
 - It could very well be that this _is_ expected behavior. Is it?
 - If not, what conversion is LayoutXLM expecting? What is the correct way to convert?
```

**Comment by SaulLu** [comment]
Thanks for openning the issue, to make it depend only on the `tokenizers` library, here's a snippet showing the issue:
```python
tokenizer = tokenizers.Tokenizer.from_pretrained("microsoft/layoutxlm-base")

texts = [" 7.0", "7.0", " hello", "hello"]

for text in texts:
    encoding = tokenizer.encode(text, add_special_tokens=False)
    print(
        repr(text), 
        [tokenizer.id_to_token(id) for id in encoding.ids], 
        encoding.offsets, 
        [text[start:end] for start,end in encoding.offsets]
    )
# ' 7.0' ['▁', '7.0'] [(1, 2), (1, 4)] ['7', '7.0'] <- looks weird
# '7.0' ['▁', '7.0'] [(0, 1), (0, 3)] ['7', '7.0'] <- looks weird
# ' hello' ['▁hell', 'o'] [(1, 5), (5, 6)] ['hell', 'o'] <- looks good
# 'hello' ['▁hell', 'o'] [(0, 4), (4, 5)] ['hell', 'o'] <- looks good
```

**Comment by Narsil** [comment]
Ok got a look (FF doesn't like precompiled_charmap)

The `pre_tokenizers` are fine, but the vocabulary is lacking `▁7.0` that's why it's splitting it in two.

Hard to say if that's normal or not, we should check the reference implementation maybe.

**Comment by fredo838** [comment]
Do you know where the reference implementation is located @Narsil ? I would like to check it.

**Comment by Narsil** [comment]
Not at all, @NielsRogge maybe ?

**Comment by NielsRogge** [comment]
The reference implementation of LayoutXLM can be found here: https://github.com/microsoft/unilm/tree/master/layoutlmft/layoutlmft/models/layoutxlm

**Comment by fredo838** [comment]
The reference implementation is based on huggingface so I guess it's just intended behaviour.

**Comment by SaulLu** [comment]
Let me just add my 2cents for the future us.

On my side, even if `▁7.0` (which is due to the fact that the sentencepiece model has `split_by_number: true` in its setting) is not part of the vocabulary, I would have expected the results to be:
```
# ' 7.0' ['▁', '7.0'] [(0, 1), (1, 4)] ['7', '7.0'] <- changed
# '7.0' ['▁', '7.0'] [(0, 0), (0, 3)] ['7', '7.0'] <- changed
# ' hello' ['▁hell', 'o'] [(1, 5), (5, 6)] ['hell', 'o'] <- same as before
# 'hello' ['▁hell', 'o'] [(0, 4), (4, 5)] ['hell', 'o'] <- same as before
```
