### ISSUE TITLE
Unable to get Camel case tokens after tokenization in huggingface

### ISSUE THREAD

**Issue by pjhamb** [huggingface/tokenizers#1017]
I am trying to tokenize text by loading a vocab in huggingface.

```
vocab_path = '....' ## have a local vocab path
tokenizer = BertWordPieceTokenizer(os.path.join(vocab_path, "vocab.txt"), lowercase=False)
text = 'The Quick Brown fox'
output = tokenizer.encode(text)
output.tokens
Out[1326]: ['[CLS]', '[UNK]', '[UNK]', '[UNK]', 'fox', '[SEP]']
```
The vocab I am using has everything in lower case. However, I want to tokenize it keeping the caps preserved.

Desired Output:
```
['[CLS]', 'The', 'Quick', 'Brown', 'fox', '[SEP]']
```
When I use lowercase=True, it recognizes the words
```
tokenizer = BertWordPieceTokenizer(os.path.join(vocab_path, "vocab.txt"), lowercase=True)
output = tokenizer.encode(text)
output.tokens
Out[1344]: ['[CLS]', 'the', 'quick', 'brown', 'fox', '[SEP]']
```
How do I get desired output using the lowercase vocab ?

**Comment by Narsil** [comment]
Hi,

What you're seeing is 100% working as intended.

The elements in the list ARE elements of your vocab, so they cannot be uppercased if your vocabulary isn't uppercased.

`lowercase=True` means you sentence input is lowercased before being shown to the model , that's how it's correctly recognized and not before.

If you want to have pieces from the original string, you need to use `offsets` (`output.offsets/output.offset_mappings`).

This will give you for every token, the start and stop index within the original sentence that lead to the token being displayed.

Does that answer your question ?

Cheers.
