### ISSUE TITLE
OPT Tokenizers have wrong "special_tokens_map"

### ISSUE THREAD

**Issue by chengxuz** [huggingface/tokenizers#1020]
Hi,

I find that the tokenizers for OPT models have possibly wrong "special_tokens_map":

```
>>> from transformers import GPT2Tokenizer
>>> tokenizer = GPT2Tokenizer.from_pretrained("facebook/opt-350m")
>>> tokenizer.special_tokens_map
{'bos_token': '</s>', 'eos_token': '</s>', 'unk_token': '</s>', 'pad_token': '<pad>'}
```

Here the strings for the `bos_token`, `eos_token`, `unk_token` are all the same, which in my mind is wrong. I also see this issue for other OPT models. I checked the downloaded vocabulary file and the head of it looks fine:
```
"<s>": 0, "<pad>": 1, "</s>": 2, "<unk>": 3, ...
```

Can I confirm if this is a bug? If so, may I ask when this will likely be fixed?

Thanks!

**Comment by Narsil** [comment]
Hey, this seems to be normal if you check the tokens it specifies that bos is actually EOS.

https://huggingface.co/docs/transformers/model_doc/opt#opt

It also says that you should use the slow tokenizer (the fast one cannot be configured 100% properly at the time) which you are so you're good to go on that end.

If you're still unsure about this, you can create an issue and tag the OPT maintainer but it seems legit.
