### ISSUE TITLE
Can't convert <tokenizers.trainers.WordPieceTrainer object at 0x173caa2b0> to Sequence

### ISSUE THREAD

**Issue by Eleo22** [huggingface/tokenizers#1025]
Hi there, 

I tried to use the function .get_new_tokens() on a very simple example but got this error:
TypeError: Can't convert <tokenizers.trainers.WordPieceTrainer object at 0x173caa2b0> to Sequence

the code is:
from transformers_domain_adaptation import VocabAugmentor

target_vocab_size =31_000 

augmentor = VocabAugmentor(
    tokenizer=tokenizer,
    cased=False,
    target_vocab_size=target_vocab_size
)

# Obtain new domain-specific terminology based on the fine-tuning corpus
new_tokens = augmentor.get_new_tokens(corpus)

Where corpus=['a big corpus....']. 
Any idea what's wrong ?

Many thanks,
Ellie

**Comment by Narsil** [comment]
Hi @Eleo22 

I have no idea what ` from transformers_domain_adaptation import VocabAugmentor`

Could you maybe take that up to `transformers_domain_adaptation` repository ? 

Or figure out a reproducible example without this using this library?
