### ISSUE TITLE
Missing documentation for `BertWordPieceTokenizer`

### ISSUE THREAD

**Issue by BlueskyFR** [huggingface/tokenizers#1031]
Hi!

I see that the following file declares `BertWordPieceTokenizer`, which cannot be found in the documentation: maybe its me or a PR was accepted without the documentation being checked?

I was also wondering if other implementations were missing from the doc

https://github.com/huggingface/tokenizers/blob/28cd3dce2a75d106572392194ff2564574c33235/bindings/python/py_src/tokenizers/implementations/bert_wordpiece.py#L1-L153

**Comment by Narsil** [comment]
Hi @BlueskyFR,

You're more than welcome to update the documentation.

`tokenizers` works without really thinking or expressing things relative to existing models like `Bert` or `GPT2`
The main documentation refers to what's called a pipeline in here (`normalizer` , `post_processor`, `pre_tokenizer` etc..).

The `implementations` folder contain a bunch of examples on how to put up standard tokenizers looking like the original implementations but they are not core objects if you want.

Does that explain everything better ?
