### ISSUE TITLE
Support for regex in Replace normalization function

### ISSUE THREAD

**Issue by stephantul** [huggingface/tokenizers#1035]
Hi,

I was wondering whether there exists regex support for the Replace Normalizer. It seems that Replace just replaces the strings verbatim right now. 

Thanks!
Stéphan

**Comment by sadra-barikbin** [comment]
Hi, yes it does:
```python
from tokenizer import Tokenizer
from tokenizers.normalizers import Replace
from tokenizers import Regex
from tokenizers.models import BPE

my_tokenizer = Tokenizer(BPE())
my_tokenizer.normalizer = Replace(Regex('[0-9]+'), '[NUM]')
```

**Comment by stephantul** [comment]
Ok, that's great! 

Thanks for the quick reply. Is this mentioned in the docs somewhere?

**Comment by Narsil** [comment]
It is here : https://huggingface.co/docs/tokenizers/components#components

However there doesn't seem to be nice code examples for this in the docs. 
PR are welcome :)
