### ISSUE TITLE
Docs say you can pass token ids to `.encode()`, but it throws an exception when you do

### ISSUE THREAD

**Issue by dirkgr** [huggingface/tokenizers#1045]
I'm looking at these docs: https://huggingface.co/docs/transformers/main/en/main_classes/tokenizer#transformers.PreTrainedTokenizer.encode
They say you can pass in token ids instead of a string. But when you try you get a `TypeError`:
```
In [2]: import transformers

In [3]: t = transformers.AutoTokenizer.from_pretrained("bert-base-uncased")

In [4]: token_ids = t.encode("I am a fish.")

In [5]: token_ids
Out[5]: [101, 1045, 2572, 1037, 3869, 1012, 102]

In [6]: t.encode(token_ids)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-16a2300ce7c1> in <module>
----> 1 t.encode(token_ids)

[stack trace goes here]

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```

**Comment by dirkgr** [comment]
@SaulLu, from the discussion on Slack.

**Comment by stephantul** [comment]
This is the wrong repository for this issue. The transformers tokenizer package are not the same as the tokenizers in this repository, although very similar.

**Comment by jmwoloso** [comment]
Aren't the "fast" tokenizers in `transformers` these rust-based ones? The `AutoTokenizer` class uses the `PreTrainedTokenizersFast` class by default. 

I've run into this exact issue this week. The `AutoTokenizer` fast implementations do not have feature parity vs model-specific tokenizers in that they cannot take tokenized input.

**Comment by ydshieh** [comment]
I confirmed that the fast tokenizer `.encode()` behaves differently.

### To reproduce

```python
import transformers

t_slow = transformers.AutoTokenizer.from_pretrained("bert-base-uncased", use_fast=False)
t_fast = transformers.AutoTokenizer.from_pretrained("bert-base-uncased")

s = "I am a fish."
tokens = t_slow.tokenize(s)
print(tokens)

token_ids = t_slow.convert_tokens_to_ids(tokens)
print(token_ids)

# slow + string
token_ids_1 = t_slow.encode(s)
print(token_ids_1)

# slow + ids
token_ids_2 = t_slow.encode(token_ids)
print(token_ids_2)

# fast+ string
token_ids_3 = t_slow.encode(token_ids)
print(token_ids_3)

# -------------------------------------------------
# This failed

# fast+ ids (failed)
token_ids_4 = t_fast.encode(token_ids)
print(token_ids_4)
```


The error for `t_fast.encode(token_ids)`.

```bash
Traceback (most recent call last):
  File "C:\Users\33611\Desktop\Project\transformers-hf\test.py", line 26, in <module>
    token_ids_4 = t_fast.encode(token_ids)
  File "C:\Users\33611\Desktop\Project\transformers-hf\src\transformers\tokenization_utils_base.py", line 2257, in encode
    encoded_inputs = self.encode_plus(
  File "C:\Users\33611\Desktop\Project\transformers-hf\src\transformers\tokenization_utils_base.py", line 2663, in encode_plus
    return self._encode_plus(
  File "C:\Users\33611\Desktop\Project\transformers-hf\src\transformers\tokenization_utils_fast.py", line 500, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "C:\Users\33611\Desktop\Project\transformers-hf\src\transformers\tokenization_utils_fast.py", line 427, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```

**Comment by ydshieh** [comment]
@Narsil @SaulLu Could you have a look on this issue and see if we should have a fix for it, whenever you find sometime :-) ? Thanks a lot.

**Comment by ydshieh** [comment]
> @Narsil @SaulLu Could you have a look on this issue and see if we should have a fix for it, whenever you find sometime :-) ? Thanks a lot.

**Comment by Narsil** [comment]
I checked, and errors happens both on `tokenizers==0.12.1` and `tokenizers==0.13.0`.

It seems odd that we can `encode` ids... Not sure what is the expected behavior there. @SaulLu  might have ideas.

**Comment by jmwoloso** [comment]
Thank you for confirming @ydshieh I actually opened a feature request a couple weeks ago in [#1058 ](https://github.com/huggingface/tokenizers/issues/1058) that also demonstrates the behavior.

@Narsil In terms of expected behavior,  that functionality has existed in the non-rust tokenizers for as long as i've used the library (since `2.11.*` days). it turns out to be pretty handy when you can't or don't want to truncate a document. It allows you to tokenize the entire doc once and then segment it and add the special tokens via encode instead of manually doing it. 

I realize since we're already touching each segment that it isn't a big stretch to manually add the special tokens, but the less we have to do manually, the better. This is more about feature parity and also expectations (i.e. i just assumed `AutoTokenizer` was manifesting a model-specific vanilla tokenizer under the hood like `DistilBertTokenizer` but it's using the fast versions instead). 

Defaulting to the fast tokenizers is nice, but also kind of a gotcha because it means that switching over to use the `Auto*` classes is (depending on your situation) not as seemless as one might assume. 

I actually re-discovered this behavior when looking at our code base and wondering why we were still using specific tokenizers instead of `AutoTokenizer`, so I changed it and it broke and then I remembered.

**Comment by Narsil** [comment]
> g why we were still using specific tokenizers instead of AutoTokenizer, so I changed it and it broke and then I remembered.

`AutoTokenizer.from_pretrained(use_fast=False)` might help you there if you want to use the "slow"  and not the fast.
(So you can maintain mostly the flag and not the whole class maybe).

Also we do have a big issue containing the differences between fast and slow tokenizers  https://github.com/huggingface/transformers/issues/17051

The biggest hold up, is that now the fast have been out for a long time, so any differences are "canon" meaning any deviation one way or another, will be breaking compatibility for some users which we highly restrain from doing.

We can deplore that those were not detected early enough indeed, but now we're in a tricky spot.

> then segment it and add the special tokens via encode instead of manually doing it.

Not sure about the segmentation, but `tokenizer._tokenizer` (the fast tokenizer object) has `tokenizer._tokenizer.processor.process(encoding)` which does add the extra tokens according ot the spec of the tokenizer.
Usually that's how `transformers` recreates python behavior by using the low level components of `tokenizers`. However I am not well versed in how it ever implemented the behavior you are describing.

**Comment by jmwoloso** [comment]
Thanks for quick reply @Narsil. 

I think you've given me some good options for bridging the gap. 

Between the lower level methods on the fast object and the `use_fast` flag (I could also probably just sub-class the tokenizer and make the default flag False as a potential solution), I think I'm all set and we can close this if @dirkgr concurs.

**Comment by dirkgr** [comment]
Using the slow tokenizer is a good workaround.

The fact that the documentation does one thing and the code does another is still a bug though. I doubt that people have come to depend on the exception throwing behavior of the fast tokenizer.

Since there is a good workaround I understand if you have more important issues to fix though.

**Comment by Narsil** [comment]
> The fact that the documentation does one thing and the code does another is still a bug though. I doubt that people have come to depend on the exception throwing behavior of the fast tokenizer.

You are entirely right ! My comment was "in general" some differences will be hard to remove. But specifically for this issue, it can probably be fixed (assuming it has been working at some point).
