### ISSUE TITLE
Custom truncation logic is really hard

### ISSUE THREAD

**Issue by dirkgr** [huggingface/tokenizers#1046]
I have a bunch of text pairs that I want to tokenize. Some of those texts are too long for the transformer, so I ask the tokenizer to truncate with `truncation="only_first"`. Sometimes, the second text by itself is too long, so truncating the first text isn’t enough. This doesn’t happen a lot, and I don’t care exactly about how this case is handled, but it needs to be handled somehow. The problem is, with the current tokenizer API, you cannot handle this case at all. I have to go all the way back to the basics and write my own padding and truncation code. All the nicety of the tokenizer library goes away.

This would be easier if #1045 was fixed. Then I could turn strings into token ids, do my own truncation, but then pass the truncated sequences back to the tokenizer to do padding and special tokens.

**Comment by dirkgr** [comment]
@SaulLu, from Slack

**Comment by Narsil** [comment]
Hi, 

Have you tried `truncation=True`, it should work as expected, no ?
Or is there something more specific ?

**Comment by dirkgr** [comment]
Let's say I have a dataset where the two fields I have for every instance are "question" and "context". I never want to truncate the question. If I truncate the question, the whole instance becomes meaningless.

For example, here is a full instance:
```
{
    "context": "The Barbie doll’s full name is Barbara Millicent Roberts, from Willows, Wisconsin. Ken's full name is Kenneth Sean Carson. He is named after the son of Mattel founders Ruth and Elliott Handler.",
    "question": "What is the middle name of Barbie?"
}
```

If I truncate the question, it might become "What is the middle name", which is unanswerable given the context. So I put the context first, and the question second, and I set truncation to `"only_first"`.

But in some degenerate instances in the dataset, the question is really long, so I have to truncate the question. That case is pretty rare, so I don't care exactly how it is handled. But the tokenizer API does not give me a way to handle this in any way. If I want to handle it at all, I have to do all my own truncation, padding, and batching, and I cannot use all the nice stuff that the tokenizer can do.

**Comment by Narsil** [comment]
Do you mind sharing code, can't you just handle the exception in that case ?

Like so :

```python
try: 
  batch = tokenizer.batch_encode(question_pairs, truncation="only_first")
except Exception:
   # Deal manually
   # Figure out the culprit pair, and exclude it from the batch ?
   batch = tokenizer.batch_encode(question_pairs_excluding_too_long, truncation="only_first")
```

**Comment by Narsil** [comment]
Or maybe it should be a pre-step in the `datasets` filtering to remove any questions larger than X (probably less that max_length since you still want a few tokens for the context, right ? )

**Comment by dirkgr** [comment]
> Figure out the culprit pair, and exclude it from the batch

With a large enough dataset (or many datasets in my case) this is not possible. For one thing, I don't know the culprit pair, so I'd have to tokenize them individually to find out which one it is. For another, excluding a sequence makes the batch smaller, which places too much weight on the other instances in the batch. What if I have more than one sequence that's too long? What if they are all too long? These seem like edge cases, but when you have enough data, you will hit all the edge cases.

If the treatment of the exception case is more complicated than just constructing the batch manually, then I might as well just construct the batch manually, without the tokenizer features.

> Or maybe it should be a pre-step in the datasets filtering to remove any questions larger than X

So, tokenize twice, once to check whether I run into a problem, and then a second time to actually construct a batch?

**Comment by Narsil** [comment]
@dirkgr I understand the issue, but I fail to see how we can actually solve your issue.

How much would you like to truncate the question when both are too long ?
How do you know if your truncated question is too  much truncated or not ?

Do you mean to use overflowing tokens in some form ?

Could you provide some python pseudo code to see what you expect to happen instead ?

**Comment by dirkgr** [comment]
A specific solution would be a way to say "truncate first, then second" or "second, then first". As you noted, it means you have to give it something like a "minimum length", so effectively the algorithm becomes "truncate the first text down to n tokens, truncate the second to make it fit into max_length". This is possibly how "only first" and "only second" should work all the time. I can't imagine many cases where people would be happy with the behavior where it does some truncation, but still not as much as the model requires.

If you think that's too specific, I get it. But the way it is now, the "only first" and "only second" options are pretty useless, unless your dataset happens to be of the right shape.

If #1045 was fixed, it would be an escape hatch. I could use the tokenizer API to make word pieces, do my own truncation, and then use the tokenizer API again to construct complete batches (with special tokens, token type ids, attention mask, etc.). This would be the real, general solution to this problem.
