### ISSUE TITLE
char positions <> token positions

### ISSUE THREAD

**Issue by tscholak** [huggingface/tokenizers#105]
Hi, great library!

I've got a question and request. Would it be possible to also return a map relating input char positions and output token positions?

Use case: calculating char span endpoints from token span endpoints for, e.g., SQuAD-type question answering.

Hope to hear from you,
Torsten

**Comment by Pierrci** [comment]
Did you check the example on the main readme? The last line might be what you're looking for:
```python
# Here is an example using the offsets mapping to retrieve the string coresponding to the 10th token:
>>> output.original_str[output.offsets[10]]
```

**Comment by tscholak** [comment]
Oh, I did skim it, but this escaped my eyes. thank you, this looks exactly like what I was asking for!

**Comment by tscholak** [comment]
follow-up question: is this functionality accessible through `transformers` already?

**Comment by tianyi-chen** [comment]
Hi,

Also wondering if this functionality is available in pertained `BertTokenizer`?

Thanks

**Comment by Pierrci** [comment]
AFAIK it's not implemented (at least for now) directly in `transformers`, but you can have a look at the code in the [question answering pipeline](https://github.com/huggingface/transformers/blob/babd41e7fa07bdd764f8fe91c33469046ab7dbd1/src/transformers/pipelines.py#L709) and then in [squad.py](https://github.com/huggingface/transformers/blob/babd41e7fa07bdd764f8fe91c33469046ab7dbd1/src/transformers/data/processors/squad.py#L86), where a `token_to_orig_map` is populated, allowing to do what you're looking for.

**Comment by julien-c** [comment]
And it's going to be implemented natively via tokenizers soon (cc @mfuntowicz)

**Comment by n1t0** [comment]
We just released the version `2.5.0`  of `transformers` that integrates the `tokenizers`: https://github.com/huggingface/transformers/releases/tag/v2.5.0.
You can now access this feature directly for the various tokenizers that are covered in this release.

**Comment by tianyi-chen** [comment]
Hi, I wasn't able to find something like `output.offsets` in either `BertTokenizer` or `BertTokenizerFast`. Which tokenizer has this token index <> char index map? Did I miss something? Thanks

**Comment by tamuhey** [comment]
Hi, you can retrieve the offsets from the original texts with this library (https://github.com/tamuhey/tokenizations).
