### ISSUE TITLE
CLIPTokenizer

### ISSUE THREAD

**Issue by kojix2** [huggingface/tokenizers#1059]
This may be a stupid question, but is CLIPTokenizer available from this library?

**Comment by Narsil** [comment]
Hi @kojix2 you can do

```python
from tokenizers import Tokenizer
tokenizer = Tokenizer.from_pretrained("openai/clip-vit-base-patch32")
```

This should work out of the box. Keep in mind that `transformers` might add functionality on top, `tokenizers` only deals with strings and gives outs ids (and offsets)

**Comment by kojix2** [comment]
Great!!
Thank you!
