### ISSUE TITLE
would huggingface like publish cpp binding for tokenizers?

### ISSUE THREAD

**Issue by mullerhai** [huggingface/tokenizers#1070]
HI:
        I use cpp env libtorch,  I like use hugggingface ,but huggingface not cpp binding, would you like publish cpp binding for it.
thanks

**Comment by Narsil** [comment]
Hi @mullerhai 

Currently, this library is basically only maintained by me, and I really don't have the time to invest into more bindings.
If you are willing to write them, that would be super welcome though !

C is probably going to be the target, not CPP as C bindings would be callable from C, and they usually enable even more bindings directly as C is a common denominator of many languages.

To be honest, when dropping low level, I tend to use https://github.com/LaurentMazare/tch-rs/ which are rust bindings to libtorch. 
This doesn't solve your issue, but it might help some readers.

**Comment by Narsil** [comment]
Hi @jamie0725 ,
No you found the correct not maintained branch.

Would C bindings help in the Java world ? It's been a while I've looked at the ecosystem.
https://crates.io/crates/jni might be another way.

If you get started on this, don't hesitate to share!
