### ISSUE TITLE
`OnlyFirst` and `OnlySecond` truncation strategies 

### ISSUE THREAD

**Issue by Pierrci** [huggingface/tokenizers#108]
The current behavior for `OnlyFirst` and `OnlySecond` truncation strategies is not the one I would expect, and diverges from the current behavior in [transformers](https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils.py#L1107-L1113):

https://github.com/huggingface/tokenizers/blob/88391dd18501ee672bee155a15f16632f2e0ae57/tokenizers/src/utils.rs#L87-L99

It currently takes only the first encoding (`OnlyFirst`) or the second one (`OnlySecond`), and then truncates it to make its length less than the desired `max_length`.

But this doesn't guarantee that the combined encodings have a length inferior to `max_length`, which is the behavior I was expecting: those strategies should take into account the combined encodings length when truncating only the first or second one.

What do you think @n1t0 @mfuntowicz?

**Comment by mfuntowicz** [comment]
I agree that I would also expect, in both case, the final - combined - length should be <= max_len, otherwise it sounds weird.
