### ISSUE TITLE
WordPiece Pair Score Calculation and Reproducibility

### ISSUE THREAD

**Issue by gdeleva** [huggingface/tokenizers#1086]
Hi,

May I ask if the following formula

score=(freq_of_pair)/(freq_of_first_element×freq_of_second_element)

is currently implemented in the WordPiece algorithm? I am a little bit confused about the words "This is because the 🤗 Tokenizers library does not implement WordPiece for the training (since we are not completely sure of its internals), but uses BPE instead." from https://huggingface.co/course/chapter6/6?fw=pt.

If not, could it be something for an enhancement?

In addition, I noticed that the training of WordPiece is not always reproducible. This has been also noticed in Issue #668. However, I was not expecting any random generator for this algorithm. Is it maybe related to finite precision problems?

Best regards,

giacomo

**Comment by Narsil** [comment]
Hi @gdeleva ,

Haven't looked deeply in the internals to confirm, but the heuristic, probably come from the use of `HashMap` or some other structure than it not deterministic by nature.

For the formula, I have no recollection, I think the score is just `freq_of_pair` . 

WorldLevel IIRC is just a greedy encoding of a BPE tokenizer. (and is implemented as such as far as I know, meaning we ARE training a BPE underthe hood, just encoding differently).

> I was not expecting any random generator for this algorithm. Is it maybe related to finite precision problems?
I'm guessing it's a structure thing.
Also keep in mind that some stuff is not cleanly defined like encoding `MMM` could be either `M + MM` or `MM + M`.
(This library *should* be consistent, but there's no definition for different implementations).

If you want to open a PR looking into this, it would be most welcome !
Please open the PR early so we can start the discussions early on, and avoid some pitfalls that might exist.

**Comment by gdeleva** [comment]
Hi @Narsil 

Thank you for the prompt reply. Do you also see two possible enhancements?

1. Change the score from `freq_of_pair`  to `(freq_of_pair)/(freq_of_first_element×freq_of_second_element)`
2. Make the WordPiece training reproducible.

The second one seems more complex. If possible, I would start from the first one.

**Comment by Narsil** [comment]
1. I don't think we should. because that would be a breaking change.

You can play with it if you want, report back if it does make a big different we can think of a non breaking change way to enable this (maybe with an option in the trainer for instance).

> Make the WordPiece training reproducible.

Nice probably a separate PR though (and make it as little code change as possible, so that we can verify we're not changing anything)
