### ISSUE TITLE
[MINOR] Weird text artifacts in documentation

### ISSUE THREAD

**Issue by cakiki** [huggingface/tokenizers#1089]
There's a bunch of repeated `{.interpreted-text role=“obj”}` in [this section](https://huggingface.co/docs/tokenizers/training_from_memory#the-most-basic-way
) of the documentation. I'm not sure whether it's also present elsewhere. 

![image](https://user-images.githubusercontent.com/3664563/197602911-e24e2845-fced-4b4f-8b84-81d4c3ab282f.png)

**Comment by Narsil** [comment]
@mishig ? Any ideas ?
