### ISSUE TITLE
How to implement customized tokenizers in Rust.

### ISSUE THREAD

**Issue by 5c4lar** [huggingface/tokenizers#1093]
I'd like to implement a customized pretokenizer in Rust and use it to build a tokenizer in python. Can I do this out of tree? Or if I have to modify the code in tokenizers, which files do I need to modify at least？

**Comment by Narsil** [comment]
Hi @ucasqsl ,

You can use Python custom pretokenizer which are the "easiest" route : https://github.com/huggingface/tokenizers/blob/main/bindings/python/examples/custom_components.py#L13

Other than that yes you would need to modify the rust source.

What kind of pre_tokenizer do you want to do ? We could probably also merge it if it's not redundant with the current existing ones !

**Comment by ucasqsl** [comment]
I'm trying to use tree-sitter to preprocess source code.  After playing around with the rust source, I have worked out a minimal working code now.
```
In [1]: from tokenizers import pre_tokenizers

In [2]: pre_tokenizers.TreeSitter
Out[2]: tokenizers.pre_tokenizers.TreeSitter

In [3]: pre_tokenizers.TreeSitter("cpp")
Out[3]: <tokenizers.pre_tokenizers.TreeSitter at 0x7fb7040521f0>

In [4]: ctok = pre_tokenizers.TreeSitter("cpp")

In [5]: ctok.pre_tokenize_str("int main() {return 0;}")
Out[5]: 
[('int', (0, 3)),
 (' ', (3, 4)),
 ('main', (4, 8)),
 ('(', (8, 9)),
 (')', (9, 10)),
 (' ', (10, 11)),
 ('{', (11, 12)),
 ('return', (12, 18)),
 (' ', (18, 19)),
 ('0', (19, 20)),
 (';', (20, 21)),
 ('}', (21, 22))]
```
I am very concerned about the efficiency of the code. Hopefully, the code obtained in this way can be parallelized. Does this use case sound interesting to you?

**Comment by Narsil** [comment]
Definitely interesting ! 

I am slightly worried about the bindings (extern C code tends to be harder to make easily portable through the various bindings + wasm) but it's definitely something that is really interesting !

**Comment by jonasknobloch** [comment]
I case someone else is interested in building a custom pretokenizer in rust, this might help: https://github.com/jonasknobloch/morphy/tree/main/src/pre_tokenizers. If you want to use a custom pretokenizer in sequence with existing ones you probably need a custom sequence implementation aswell. No python bindings - I simply trained in rust. When serializing the result make sure to not include the custom pretokenizer if you want to import via the python package.

**Comment by ArthurZucker** [comment]
Thanks for sharing @jonasknobloch
