### ISSUE TITLE
Difference between PreTrainedTokenizerFast Python and Node SentencePieceBPETokenizer

### ISSUE THREAD

**Issue by loretoparisi** [huggingface/tokenizers#1100]
We have found that while in Nodejs [Rust bindings](https://github.com/huggingface/tokenizers/blob/28cd3dce2a75d106572392194ff2564574c33235/bindings/node/native/src/models.rs#L128) of `SentencePieceBPETokenizer`  I get the following tokens and ids

```
Hello how are you tonight?
ids  [
    0, 35378, 3642,
  621,   398,   47,
   93,  9486,   18,
   32,     2
]
tokens  [
  '<s>',  '▁Hello',
  '▁how', '▁are',
  '▁you', '▁to',
  'ni',   'gh',
  't',    '?',
  '</s>'
]
```

in Python `PreTrainedTokenizerFast` class I get

```
tokenizer = AutoTokenizer.from_pretrained('microsoft/Multilingual-MiniLM-L12-H384')
tokenizer.encode("Hello how are you tonight ?")
[0, 35378, 3642, 621, 398, 179028, 705, 2]
tokenizer.convert_ids_to_tokens(ids = tokenizer.encode("Hello how are you tonight ?"))
['<s>', '▁Hello', '▁how', '▁are', '▁you', '▁tonight', '▁?', '</s>']
```

If we look at the json dictionary (we use the MiniLM [here](https://huggingface.co/microsoft/Multilingual-MiniLM-L12-H384/tree/main) in this case) there are both tokens

```
"\u2581to": 47,
```

and 

```
"\u2581tonight": 179028,
```

while the python tokenizer is loading the latter `_tonight`,  the tokenizer in Node is selecting the former `_to`
In Nodejs class tokenizer is loaded with defaults parameters `dropout` and `unkToken`, while no parameter `continuing_subword_prefix` or `end_of_word_suffix` and `fuse_unk` are specified as BPEOptions.

```node
const opts = Object.assign(Object.assign({}, this.defaultOptions), options);
        const unkToken = getTokenContent(opts.unkToken);
        let model;
        if (opts.vocabFile && opts.mergesFile) {
            const modelOptions = {
                dropout: opts.dropout,
                unkToken: unkToken,
            };
            const fromFile = promisify(models.BPE.fromFile);
            model = await fromFile(opts.vocabFile, opts.mergesFile, modelOptions);
        }
        else {
            model = models.BPE.empty();
        }

        const tokenizer = new Tokenizer(model);
```

**Comment by Narsil** [comment]
Do you mind producing simple reproducing scripts in both langage to see the difference ?

I expect you're not doing the exact same thing in both langages but it would be clearer if I was able to reproduce.

**Comment by loretoparisi** [comment]
Yes of course, thank you for your help! @paulthemagno please provide the Python code, I will retrieve Node.

**Comment by paulthemagno** [comment]
From the Python side, the code is exactly what you posted before 😊

**Python example script**
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('microsoft/Multilingual-MiniLM-L12-H384')
text = "Hello how are you tonight ?"
pt_ids = tokenizer.encode(text)
pt_tokens = tokenizer.convert_ids_to_tokens(ids = tokenizer.encode(text))

print(pt_ids)
print(pt_tokens)
```

The output should be that:
```
[0, 35378, 3642, 621, 398, 179028, 705, 2]
['<s>', '▁Hello', '▁how', '▁are', '▁you', '▁tonight', '▁?', '</s>']
```

It correctly takes the token `_tonight` as it is the longest match in the vocab and not `_to`, `ni`, `gt`, `t`.

Then, once you have the ids/tokens from Node like these ones (to make an example):
```python
node_ids  = [
    0, 35378, 3642,
  621,   398,   47,
   93,  9486,   18,
   32,     2
]
node_tokens = [
  '<s>',  '▁Hello',
  '▁how', '▁are',
  '▁you', '▁to',
  'ni',   'gh',
  't',    '?',
  '</s>'
]
```

you could compare them in this way:
```python
for i,node_token in enumerate(node_tokens):
     try:
          print(f"'{node_token}' vs '{pt_tokens[i]}'. Match:{node_token==pt_tokens[i]}")
     except:
          print(f"'{node_token}' vs null. Match: False")
```

**Comment by loretoparisi** [comment]
> Do you mind producing simple reproducing scripts in both langage to see the difference ?
> 
> I expect you're not doing the exact same thing in both langages but it would be clearer if I was able to reproduce.

@Narsil Please find in the repo [hf-tokenizers-experiments](https://github.com/loretoparisi/hf-tokenizers-experiments) a working nodejs example:

```bash
cd hf-tokenizers-experiments
npm install
cd examples/
node minilm-tokenizer
```

The code 
```javascript
const sentence = "Hello how are you tonight?";
encoded = await lpTokenizer.encode(sentence, null, {
        addSpecialTokens: addSpecialTokens,
        isPretokenized: isPretokenized
});
console.log("ids ", encoded.getIds());
console.log("tokens ", encoded.getTokens());
decoded = await lpTokenizer.decode(encoded.getIds(), skipSpecialTokens);
console.log("decoded - ", decoded); // hello how are you?
decoded = await lpTokenizer.decode(encoded.getIds(), !skipSpecialTokens);
console.log("decoded (special tokens)- ", decoded); // hello how are you?
```

should give

```
ids  [
    0, 35378, 3642,
  621,   398,   47,
   93,  9486,   18,
   32,     2
]
tokens  [
  '<s>',  '▁Hello',
  '▁how', '▁are',
  '▁you', '▁to',
  'ni',   'gh',
  't',    '?',
  '</s>'
]
decoded -  Hello how are you tonight?
decoded (special tokens)-  <s> Hello how are you tonight?</s>
```

**Comment by Narsil** [comment]
Ok. I didn't want to go looking deep into you example code, it's long and complex.

Let's have a simple example which does work.


```python
  from transformers import AutoTokenizer

  tokenizer = AutoTokenizer.from_pretrained("microsoft/Multilingual-MiniLM-L12-H384")
  tokenizer._tokenizer.save("tokenizer.json")
  print(tokenizer.encode(text))
  ```
  
  ```node
  let tokenizer = require("tokenizers");
let util = require("util");
(async () => {
    let tok = tokenizer.Tokenizer.fromFile("tokenizer.json");
    console.log("tok", tok);

    let text = "Hello how are you tonight ?";
    let encode = util.promisify(tok.encode.bind(tok));
    let encoded = await encode(text, null);
    console.log(encoded.getIds());
    console.log(encoded.getTokens());
})();
```

I see both times the same values.

Does this work for you ?

**Comment by Narsil** [comment]
Which `vocab.txt`  ? https://huggingface.co/microsoft/Multilingual-MiniLM-L12-H384/tree/main

I don't see any, this model is a  Unigram model so it can't have a `merges.txt` file, as it's a BPE only thing.
The name of the `spm` file indeed contains `bpe` in the name, but it's really a unigram model : https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py#L460-L476 (This is how `transformers` knows how to convert).

Where did you get your files ?

**Comment by loretoparisi** [comment]
> Which `vocab.txt` ? https://huggingface.co/microsoft/Multilingual-MiniLM-L12-H384/tree/main
> 
> I don't see any, this model is a Unigram model so it can't have a `merges.txt` file, as it's a BPE only thing. The name of the `spm` file indeed contains `bpe` in the name, but it's really a unigram model : https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py#L460-L476 (This is how `transformers` knows how to convert).
> 
> Where did you get your files ?

@paulthemagno could you please attach the conversion script we have used? Thank you

**Comment by paulthemagno** [comment]
Yes, don't know if it's correct because we updated it a little from an another example

```python
from transformers import AutoTokenizer

def extract(sp) -> Tuple[Dict[str, int], List[Tuple]]:
    size = sp.vocab_size
    vocab = {sp.convert_ids_to_tokens(ids = index): index for index in trange(size)}

    # Merges
    merges = []
    for piece_l in tqdm(vocab.keys(), total=sp.vocab_size):
        for piece_r in vocab.keys():
            merge = f"{piece_l}{piece_r}"
            piece_id = vocab.get(merge, None)
            if piece_id:
                merges += [(piece_l, piece_r, piece_id)]
    merges = sorted(merges, key=lambda val: val[2])
    merges = [(val[0], val[1]) for val in merges]
    
    with open("vocab.json", "w") as vocab_f:
        with open("merges.txt", "w") as merges_f:

            # Save content
            dump(vocab, vocab_f)
            merges_f.writelines(map(lambda x: f"{x[0]} {x[1]}{linesep}", merges))

    return vocab, merges

tokenizer = AutoTokenizer.from_pretrained('microsoft/Multilingual-MiniLM-L12-H384')
extract(tokenizer)
```

**Comment by Narsil** [comment]
Well that can explain something :(.

Sorry if you spend a lot of time on this, but this code **will** work and produce an output, but since the model is NOT a bpe in the first place, well, the output is... not aligned with the original tokenizer.


The code you are sharing here, is meant to only be used with BPE models, and it's a way to recover the same format as `tokenizers` expects from `spm`. It is also pretty hacky unfortunately but the 2 formats do not align well, so this was a necessity.
