### ISSUE TITLE
Infinite training ?

### ISSUE THREAD

**Issue by astariul** [huggingface/tokenizers#1103]
I'm training a SentencePieceUnigram tokenizer on my own data. But my training is never finishing ?

![Screen Shot 2022-11-10 at 2 33 25 PM](https://user-images.githubusercontent.com/43774355/201008755-59075f09-c50b-4f01-b459-d1a138fc7b27.png)

I'm just doing the following : 
```python
from tokenizers import SentencePieceUnigramTokenizer

tokenizer = SentencePieceUnigramTokenizer()
tokenizer.train_from_iterator(
    to_iter(dataset),
    vocab_size=8_000,
    show_progress=True,
    special_tokens=["<s>", "</s>", "<unk>", "<sep>", "<pad>", "<cls>", "<mask>"],
    unk_token="<unk>",
    length=len(dataset),
)
```

**Comment by Narsil** [comment]
Hmm the number of estimated steps might be wrong.

How big is the dataset ? Are you on a big machine (I think we need to merge some parallelism for Unigram training).

Please be careful when using large datasets, this library can only handle `u32` and will overflow on extremely large datasets.

**Comment by astariul** [comment]
My dataset is big but not gigantic : 60 millions sentences.
My machine is an Apple mac M1.

@Narsil Do you know a work-around for dealing with large datasets ?

**Comment by Narsil** [comment]
For unigram we still recommend using spm for training. You can convert later to this library.

Or you could open a PR to use u64 or u32 based on size of the data (it's not an easy PR). 

60million you might not hit the limit, but maybe if the data is highly repetitive (u32::max == 4 billion)

**Comment by astariul** [comment]
Thanks @Narsil !

`spm` means the [official sentence piece repository by google](https://github.com/google/sentencepiece), right ?

After training a model from that library, do you know how I can convert to a checkpoint usable in the `tokenizers` library ?

**Comment by Narsil** [comment]
You can get inspiration here: https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py

**Comment by astariul** [comment]
Thanks for the pointer @Narsil 

---

Ok so I managed to make it work with `SentencePieceUnigramTokenizer.from_spm()`. However, due to how the files are imported in the `tokenizers` library, I had to make a few changes to make it work on my computer. Here is my script for training the model using `spm`, then convert the checkpoint, and finally save it as before : 

```python
  import spm
  import transformers
  from tokenizers import SentencePieceUnigramTokenizer

  # Train the tokenizer
  spm.SentencePieceTrainer.train(
      sentence_iterator=to_iter(dataset),
      model_prefix="spm_model",
      vocab_size=8_000,
      user_defined_symbols=["<s>", "</s>", "<unk>", "<sep>", "<pad>", "<cls>", "<mask>"],
  )

  # Then convert it
  sys.path.append(transformers.utils.__path__[0])
  os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

  tokenizer = SentencePieceUnigramTokenizer.from_spm(f"{prefix}.model")

  del os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"]

  # Save the tokenizer
  tokenizer.save(out_file)
```

---

I noted that in `transformers`, the file `sentencepiece_model_pb2.py` is directly included in the library, so that it's easy to import it : 
https://github.com/huggingface/transformers/blob/61a51f5f23d7ce6b8acf61b5aa170e01d7658d74/src/transformers/convert_slow_tokenizer.py#L438

But in the `tokenizers` library, the file is not present and the users are expected to download the file by themselves, in the current working directory : 
https://github.com/huggingface/tokenizers/blob/bbae829a7225f89fed70a5df8b07de6a1c0504b7/bindings/python/py_src/tokenizers/implementations/sentencepiece_unigram.py#L148-L152

This is inconvenient to say the least. Wouldn't it be more user-friendly to take the same approach as `transformers` and directly include that file in the library ?

---

Final note : I tried training the SentencePiece tokenizer using `spm`, but I also met a lot of difficulties during training due to my dataset size... The training script is either killed or never finishing. So for now I think I will just go back to `tokenizers` and limit the size of my dataset.

@Narsil Thanks again for the help !

**Comment by Narsil** [comment]
> This is inconvenient to say the least. Wouldn't it be more user-friendly to take the same approach as transformers and directly include that file in the library ?

There are problems associated with including the file directly in the source.
It *is* more user friendly, but also potentially not in sync with SPM sources, and like you had to do, not in sync with protobuf library itself.
It's a tradeoff we're willing to make in `transformers` but not in this lib.

Also for the sheer training speed, have you tried our few open PRs to speed up EM training by using multiple threads ?

**Comment by chris-ha458** [comment]
> Or you could open a PR to use u64 or u32 based on size of the data (it's not an easy PR).
Even in ```spm``` there is a separate option 
```--train_extremely_large_corpus (Increase bit depth for unigram tokenization.) ```
This does two things, allow int64_max number of sentences, and increases the internal bitdepth used from f32 to f64 (for this my understanding is that huggingface defaults to regardless f64)

In reality, spm shows exponential scaling behavior even with 2^29 sentences(orders of magnitude lower than 2^32) or even 2^20 if the input sentences are long.

Both huggingface and spm work best when the input "sentences" are just that. well formed and delineated sentences.

More projects (like mine) are trying to input raw datasets without prerprocessing or tokenization and this is where the tokenizers are having difficulty. Especially for code with a lot of whitespaces. In this case, huggingface tokenizers are often better both for bpe and unigram.
