### ISSUE TITLE
fastBPE to HF tokenizers

### ISSUE THREAD

**Issue by kamalkraj** [huggingface/tokenizers#1106]
Hi,

How to convert the [fastBPE](https://github.com/glample/fastBPE) codes file to HF tokenizer compatible `merges.txt` and `vocab.json`

For example, [xlm](https://huggingface.co/docs/transformers/v4.24.0/en/model_doc/xlm) model tokenizer.
Original XLM Vocab files - https://github.com/facebookresearch/XLM/#pretrained-english-model are available as fastBPE 

Thanks

**Comment by Narsil** [comment]
BPE Code is almost the `merges.txt` you just need to create the ids

the `vocabulary` file seems to be almost the `vocab.json` file.

I'm guessing you could read the vocabulary file and put ids to tokens in order, and then create the `merges.txt` by simply removing the merge count and replacing by the ids of the merge. (keep the order).

Does that make sense ?

**Comment by kamalkraj** [comment]
Hi @Narsil ,

The bpecode [file](https://dl.fbaipublicfiles.com/XLM/codes_en) from https://github.com/facebookresearch/XLM/#pretrained-english-model and https://huggingface.co/xlm-mlm-en-2048/blob/main/merges.txt are identical.

For the `vocab.json` file after adding the special tokens like <s>, </s> , each vocab word is appended with `</w>` if not ended with `@@`, if ends with `@@`, removed `@@` and added.

Thanks
