### ISSUE TITLE
NormalizedString `append` method failed after calling `clear`

### ISSUE THREAD

**Issue by yanyongyu** [huggingface/tokenizers#1110]
I'm trying to normalize the whole text in token level, and call the `NormalizedString.clear` then `NormalizedString.append`, but it seems take no effect. The following small example repreduce the steps:

```python
# not work
test_str = NormalizedString("some text")
print(test_str.original, test_str.normalized)  # "some text", "some text"
test_str.clear()
print(test_str.original, test_str.normalized)  # "some text", ""
test_str.append("token")
print(test_str.original, test_str.normalized)  # "some text", ""

# work
test_str = NormalizedString("some text")
print(test_str.original, test_str.normalized)  # "some text", "some text"
test_str.append("token")
print(test_str.original, test_str.normalized)  # "some text", "some texttoken"
```

**Comment by Narsil** [comment]
The bug is in `append`. It cannot append on an empty string:

```python
test_str = NormalizedString("")
print(test_str.original, test_str.normalized)  # "", ""
test_str.append("token")
print(test_str.original, test_str.normalized)  # "", ""
```

Seems the append works be "rewriting the last `char` into the appended value. This distinction is really important for offsets (in the sense the   `NormalizedString` keeps track of offsets).

If you want to consider a fix, I would welcome a PR, but be wary, the code is subtle, quite complex, and we cannot break anything.
In general I would recommend not really using `NormalizedString` directly if possible since it's not really the core focus of this lib.

**Comment by Narsil** [comment]
https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/tokenizer/normalizer.rs#LL519C9-L519C18

**Comment by yanyongyu** [comment]
I made a workaround using `append` and `filter`. It works for me now.

```python
test_str = NormalizedString("some text")
print(test_str.original, test_str.normalized)  # "some text", "some text"
test_str.append("\x02")
test_str.filter(lambda x: x == "\x02")
print(test_str.original, test_str.normalized)  # "some text", "\x02"
test_str.append("token")
test_str.filter(lambda x: x != "\x02")
print(test_str.original, test_str.normalized)  # "some text", "token"
```

**Comment by Narsil** [comment]
Glad you found a workaround. 

Letting this open if anyone wants to tackle this because I still agree this is a bug.

**Comment by ChrisCummins** [comment]
Thanks for the workaround @yanyongyu! I was scratching my head on this for a while.

For ref here's the above workaround as a func:

```py
from tokenizers import NormalizedString

def set_normalized(normalized: NormalizedString, replacement: str) -> None:
    """Set a normalized string in-place.
    Credit @yanyongyu: https://github.com/huggingface/tokenizers/issues/1110#issuecomment-1319483288
    """
    normalized.append("\x02")
    normalized.filter(lambda x: x == "\x02")
    normalized.append(replacement)
    normalized.filter(lambda x: x != "\x02")
```

Cheers,
Chris
