### ISSUE TITLE
how to encode multiple sentences?

### ISSUE THREAD

**Issue by hrdxwandg** [huggingface/tokenizers#1111]
as we know, default tokenizer encode single sentence or two sentence(pair)。But how to encode more sentence? the num of sentence i can set by my demand.  correspondingly, the token_type_ids can add not limit 2.

For example :
sentence1 = "a b c d", sentence2 = "e f g h", sentence3 = "i j k l"
how can I get " [CLS] a b c d [SEP] e f g h [SEP] i j k l [SEP]"?
the token_type_ids list is [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]

**Comment by Narsil** [comment]
See https://github.com/huggingface/tokenizers/issues/804, closing this as a duplicate.
