### ISSUE TITLE
Adding treat_whitespace_as_suffix as a new feature to sentencepiece?

### ISSUE THREAD

**Issue by Smu-Tan** [huggingface/tokenizers#1112]
Hi, I'd like to suggest perhaps adding `--treat_whitespace_as_suffix` as a new feature to sentencepiece? since the original sentencepiece has this feature (see [here](https://github.com/google/sentencepiece/blob/master/doc/options.md)) I think it would be great for Huggingface also to have this. Thanks!

**Comment by Narsil** [comment]
@Smu-Tan you're more than welcome to contribute it if you want.

In general this library doesn't really follow `spm` architecture where normalizing and pre_tokenization is a separate step from the core algorithm.

Don't expect this to be simple, but this lib would benefit tremedously from this.
