### ISSUE TITLE
Is there any support for 'google/tapas-mini-finetuned-wtq' tokenizer? 

### ISSUE THREAD

**Issue by memetrusidovski** [huggingface/tokenizers#1114]
I'm trying to run a tokenizer in java then eventually compile it to run on android for an open domain question and answer project. I'm wondering why 'google/tapas-mini-finetuned-wtq' doesn't work with DeepJavaLibrary. For more popular models the tokenizer is working. I'm assuming there is no fast tokenizer for tapas, so i was wondering if anyone had any advice on how to go about running tapas tokenizer and model on android/java?

**Comment by Narsil** [comment]
You should probably check out https://github.com/huggingface/transformers/blob/main/src/transformers/models/tapas/tokenization_tapas.py

This is where the code you're interested lives.

And yes tapas probably uses a regular tokenizer, but it also works on tables which this library is not make for.

**Comment by memetrusidovski** [comment]
Do you think there would be any way to run the tapas tokenizer running in machine code or in Java? Im trying to get it running in the native pytorch engine, but havent had any luck

**Comment by memetrusidovski** [comment]
Does anyone know if Tapas Tokenizer can compile with Cython to run on android?

**Comment by memetrusidovski** [comment]
I am going to work on a rust version of the Table Parser as a directed research project under one of my professors next semester
