### ISSUE TITLE
How to decode with the existing tokenizer

### ISSUE THREAD

**Issue by ZhiYuanZeng** [huggingface/tokenizers#1118]
I train the tokenizer following the tutorial of the huggingface:
```python
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer
from tokenizers.pre_tokenizers import Whitespace

tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"])
tokenizer.pre_tokenizer = Whitespace()
files = [f"wikitext-103-raw/wiki.{split}.raw" for split in ["test", "train", "valid"]]
tokenizer.train(files, trainer)
tokenizer.save("tokenizer-wiki.json")
```
But I don't know how to use the existing tokenizer for decoding:
```python
tokenizer = Tokenizer.from_file("tokenizer-wiki.json")
o=tokenizer.encode("sd jk sds  sds")
tokenizer.decode(o.ids)
# s d j k s ds s ds
```
I know we can recover the output with the `o.offsets`, but what if we do not know the offsets, like we are decoding from a language model or NMT.

**Comment by Narsil** [comment]
The decoding works as intended.

There is no guarantee that `decode(encode(..))` is the identity. So `decode` will just output one possible values from the original string. It can be slightly manipulated throuhg the use of a `Decoder` but there's so much you can do. 
You can check over at `transformers` the various tokenizers/decoders, see if you find anything that matches what you want.

What do you expect in terms of output ?

**Comment by ZhiYuanZeng** [comment]
Thank you for your reply. I would expect that the output of `tokenizer.decode` can merge the subwords or the word pieces of the same word. It seems that it is possible to merge subwords if it is the byte-level BPE, or I should insert a special character in front of each word like the meta space in pretokenizer.

**Comment by Narsil** [comment]
You can use in conjunction
`pre_tokenizers.ByteLevel` with `decoders.ByteLevel` which should give you what you expect (I think).

Would that work ?

**Comment by ZhiYuanZeng** [comment]
Yes, I believe that would work. Thank you. But I think the documentation of tokenizers may need to point out this, otherwise, it will be confusing for users who want to merge subwords.
