### ISSUE TITLE
Error decoding ByeLevel BPE strings

### ISSUE THREAD

**Issue by cakiki** [huggingface/tokenizers#1119]
Hello,

I've trained a tokenizer with the following settings:

```python
VOCAB_SIZE = 70_000

unicode_normalizer = normalizers.NFKD()
accent_stripper_normalizer = normalizers.StripAccents()

bytelevel_pretokenizer = pre_tokenizers.ByteLevel(add_prefix_space=True, use_regex=True)

bytelevel_decoder = decoders.ByteLevel(add_prefix_space=True, use_regex=True)

tokenizer = Tokenizer(BPE())

tokenizer.normalizer = normalizers.Sequence([unicode_normalizer, accent_stripper_normalizer])
tokenizer.pre_tokenizer = bytelevel_pretokenizer
tokenizer.decoder = bytelevel_decoder

trainer = BpeTrainer(vocab_size=VOCAB_SIZE, show_progress=True)
```
The tokenizer works as intended, but I'm encountering this error while trying to decode strings. Here's an example trying to decode a random token from the vocab:

```python
>>> tokenizer.decoder.decode("ĠGubser")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[126], line 1
----> 1 tokenizer.decoder.decode("ĠGubser")

ValueError: Can't extract `str` to `Vec`
```

The only difference from my usual workflow is the addition of a normalizer, but I don't feel like this would cause this error.

**Comment by Narsil** [comment]
> tokenizer.decoder.decode("ĠGubser")

This is because `decode` is supposed to be called on a list of ids, not on a string.

> tokenizer.decoder.decode([612])

should work

**Comment by cakiki** [comment]
Really sorry about this. 

My confusion came from calling `tokenizer_model.convert_tokens_to_string("ĠGubser")` instead of `tokenizer_model.convert_tokens_to_string(["ĠGubser"])` which resulted in the error I reported.

Incidentally, I had to call it on a list of strings, not ids. Is that expected? i.e. `tokenizer_model.backend_tokenizer.decoder.decode(["ĠRetina"])` returns " Retina".

**Comment by Narsil** [comment]
> ncidentally, I had to call it on a list of strings, not ids. Is that expected? i.e. tokenizer_model.backend_tokenizer.decoder.decode(["ĠRetina"]) returns " Retina".

if it works it's most likely intended. A lot of nice easy to use surface has been added so in this case the strings are probably converted into ids beforehand (I would have to look at the code to make sure).
