### ISSUE TITLE
Tests fail with python binded modules/functions

### ISSUE THREAD

**Issue by mdmmn378** [huggingface/tokenizers#1122]
I've been trying to run the test cases in the python binding directory and getting the following error- 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/26161844/208231583-b792ba84-a74e-49be-ade6-f64f633b5b12.png">
Can anyone help?
Thanks in advance.

**Comment by mdmmn378** [comment]
NVM, found the solution
- DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib:$PATH  cargo test --no-default-features --lib 
[You can also modify the source file if you prefer]
Ref: https://pyo3.rs/latest/faq.html#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror 
Ref: https://stackoverflow.com/questions/46669678/telling-cargo-to-look-for-dynamic-libraries-in-conda-prefix-lib

**Comment by Narsil** [comment]
Thanks for sharing your solution !
