### ISSUE TITLE
Can't import any modules

### ISSUE THREAD

**Issue by kronkinatorix** [huggingface/tokenizers#1128]
What is says on the tin. Every module I try importing into a script is spitting out a "module not found" rror. 

Traceback (most recent call last):
  File "ab2.py", line 3, in <module>
    from tokenizers.tools import BertWordPieceTokenizer
ImportError: cannot import name 'BertWordPieceTokenizer' from 'tokenizers.tools' (/home/../anaconda3/envs/tokenizers/lib/python3.7/site-packages/tokenizers/tools/__init__.py)

Traceback (most recent call last):
  File "ab2.py", line 3, in <module>
    from transformers import BertWordPieceTokenizer
ImportError: cannot import name 'BertWordPieceTokenizer' from 'transformers' (/home/../anaconda3/envs/tokenizers/lib/python3.7/site-packages/transformers/__init__.py)

I've tried: 

import BertWordPieceTokenizer
from tokenizers.toold import AutoTokenizer 
from tokenizers import BartTokenizer

To Illustrate a few examples. 

I've installed Tokenizers in an anaconda3 venv via pip, via conda forge, and compiled from source. 

I've tried installing Transformers as well and get the same errors. I've tried installing Tokenizers and then installing Transformers and got the same errors. 

I've tried installing Transformers and then Tokenizers and gotten the same error. 

I've looked through the Tokenizers code and unless I'm missing something (entirely possible) autotokenize isn't even a part of the package? I'll admit I'm not a very experienced programmer but I'll be damned if I can find it. 

Help would be appreciated. 

System specs are:

Linux mint 21.1
RTX2080 ti
i78700k 

cudnn 8.1.1
cuda 11.2.0
Tensor rt 7.2.3
Python 3.7
(by the way, figuring out what was needed here, finding the files, and actually installing them was beyond arduous. There has to be a better way. It's the only way I could get anything at all to work though).

**Comment by Narsil** [comment]
> I've looked through the Tokenizers code and unless I'm missing something (entirely possible) autotokenize isn't even a part of the package? I'll admit I'm not a very experienced programmer but I'll be damned if I can find it.

No worries we've all been there !
Thanks for opening an issue, this is the way to go when google cannot find the answer.

Can you try:
```python
 from tokenizers.tools import BertWordPieceTokenizer
 ```

? 

`tokenizers` and `transformers` are 2 different things so it's normal to be slightly confused.
In general `transformers` is your go-to place, `tokenizers` is a specialized library, but it is not necessarily as "easy" to be consumed if you don't know what are tokenizers. 

So 
```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("xxx") # bert-base-uncased for instance
```
is probably the easiest way to get started to work with a tokenizer.

Then if you want more control to create/evolve/adapt tokenizers, then you can try out `tokenizers`. For this you should use this doc:
 https://huggingface.co/docs/tokenizers/index 
 
 to see how to use this (and you will never ever need `transformers` if you use `tokenizers` purely on its own.
 
 
 Then if you're getting started, I would also suggest using https://discuss.huggingface.co/ or our discord servers https://discuss.huggingface.co/t/join-the-hugging-face-discord/11263  which are great places to ask questions and meet other users.
 
 Does that answer your question ?
