### ISSUE TITLE
📝 Broken links between pages in docs

### ISSUE THREAD

**Issue by connorbrinton** [huggingface/tokenizers#1132]
Some of the links between pages in the documentation are broken because they reference `{{page}}.html`, but the pages are actually located at just `{{page}}` (without an `.html` suffix). Some examples of this include (broken links are bolded):
* **[The tokenization pipeline:](https://huggingface.co/docs/tokenizers/pipeline)**
  * "For more details about each model and its behavior, you can check **here**"
* **[Training from memory:](https://huggingface.co/docs/tokenizers/training_from_memory)**
  * "In the **Quicktour**, we saw how to ..."
  * "For more information on the components used here, you can check **here**"

This may not be an exhaustive list of broken links, but hopefully illustrates the pattern. Probably these links should be fixed by removing the `.html` suffix.

Thank you for maintaining the library! 😄

**Comment by hvaara** [comment]
I can take a look. Not able to assign myself to the issue, though.
