### ISSUE TITLE
Include/port SyllabiPy & LegaliPy from NLTK?

### ISSUE THREAD

**Issue by no-identd** [huggingface/tokenizers#1135]
A Jolly Yuletide to y'all. See subject — just a (well reasoned, but I lack the time it'd require to outline the reasoning behind providing it here & now) suggestion. See https://github.com/nltk/nltk/issues/2203 for some background & details

( Cc/FYI @henkc )

**Comment by Narsil** [comment]
There are no plans to add them, since they are not used (afaik) by any major Deep Learning transformers.
Do you know about any ?

The dev + maintenance cost of adding entirely new tokenizations is high so we really need it to be essential.

**Comment by no-identd** [comment]
🐣<>🥚

I saw roughly two possible outcomes before opening this, this response matching one of them. Please feel free to close, sorry for the time waste
