### ISSUE TITLE
How to port Google/SentencePiece tokenizer to HF Tokenizer

### ISSUE THREAD

**Issue by SupreethRao99** [huggingface/tokenizers#1146]
Hello,
from the documentation of T5Tokenizer, it says that its based on Sentencepiece. I've trained my sentencepiece tokenizer from the examples provided in the repository
```
import sentencepiece as spm
spm.SentencePieceTrainer.train(input='en_corpus.txt', model_prefix='English', vocab_size=8000)
```
the output of such a model is
```
English.model
English.vocab
```
the HuggingFace documentation for T5Tokenizer has the following parameters
```python
T5Tokenizer( vocab_file,  #SentencePiece file (generally has a .spm extension) 
                     eos_token = '</s>', 
                     unk_token = '<unk>', 
                     pad_token = '<pad>', 
                     extra_ids = 100, 
                     additional_special_tokens = None, 
                     sp_model_kwargs: typing.Union[typing.Dict[str, typing.Any], NoneType] = None, 
                     **kwargs )
```
I can call instantiate T5Tokenizer with the` vocab_file=English.model` and encode and decode text, but I cannot use methods such as `.tokens` or `.type_ids`. how do I go about converting the `.model` and `.vocab` files to a `.spm` file? Thank You

**Comment by SupreethRao99** [comment]
@Narsil , could you help me with this? thank you

**Comment by Narsil** [comment]
Hi @SupreethRao99 ,

Our code to convert tokenizer from `spm` to `tokenizers` is here: https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py

Do checkout the various code and options, https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py . There is a T5 converter, but your could definitely be different depending on the options you chose when training your tokenizer.

Does that help you ?

**Comment by SupreethRao99** [comment]
Thanks @Narsil, I went through the T5 converter, but I'm afraid I don't know how to use it, when I used google/SentencePiece, the output was `.vocab` and `.model` file. how do I pass it to T5Converter and save the converted tokenizer such that the saved tokenizer directory contains a `tokenizer_config.json`, `merges.txt`, `tokenizer.json`, `special_tokens.json` etc files . Thank you

**Comment by Narsil** [comment]
Use the `.model` file regularly to load your slow tokenizer within `transformers`.

Use `save_pretrained(..)` to save in a new directory, then use `convert_slow_tokenizers_checkpoints_to_fast.py` file within `transformers` to get started.

This is internal tooling, so not intended to be as streamlined as some other tools, but hopefully it's still readable enough that you can understand what's happening.

Something along the lines of :

```python
from transformers import AutoTokenizer
from transformers.convert_slow_tokenizer import convert_slow_tokenizer


checkpoint = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(checkpoint, use_fast=False)
fast_tokenizer = convert_slow_tokenizer(tokenizer)
fast_tokenizer.save(f"{checkpoint}/tokenizer.json")
```

**Comment by SupreethRao99** [comment]
Thank you @Narsil , your solution worked perfectly

**Comment by SupreethRao99** [comment]
Sure, I'll check to see if the tokenisation aligns , thank you
