### ISSUE TITLE
Control the number of (parallel) threads from python

### ISSUE THREAD

**Issue by mert-kurttutan** [huggingface/tokenizers#1149]
Hi,
I want to set the number of threads for parallel code run by `encode_batch` from python.

For the rust code, setting `RAYON_RS_NUM_CPUS` seems to do the job. But, when I use the same environment variable to control python code, the number of threads does not change and is still 4.

Is this environment variable not supposed affect calls from python? Any help is appreciated!

Note: I am not talking about turning on/off parallelism, which could be done using `encode` or `encode_batch`

**Comment by Narsil** [comment]
Have you tried https://github.com/rayon-rs/rayon/blob/8cee824f51a3a7c865f560ffb5ac9ddae43a1046/FAQ.md#how-many-threads-will-rayon-spawn ?

It seems `RAYON_RS_NUM_CPUS` is deprecated in favor of `RAYON_NUM_THREADS`.

**Comment by mert-kurttutan** [comment]
Thanks it works !!
