### ISSUE TITLE
Rust musl cross compile tokenizers: segement fault.[esaxx-rs denpendency]

### ISSUE THREAD

**Issue by ShomyLiu** [huggingface/tokenizers#1155]
Hi.
When I use `x86_64-unknown-linux-musl` to cross-compile  a rust program that uses tokenizers (from mac to linux), the compile could be successful  in my MacOS.

 However, it would come across `segment fault` error when I exec the binary program in the Linux platform.
I find out that the reason would be the ~~**`openssl` dependency** in tokenizers. I spent much time to find solutions (e.g., add openssl dependency mannuly with 'vendored'])~~ [esaxx-rs/cpp],  however not work yet.
Could anyone help with this issue?

PS: 
the Cargo.toml:
```
[dependencies]
tokenizers = "0.11.3"
openssl = { version = "0.10", features = ["vendored"] }
```
Host Platform: MacOS
Target Platform: Linux
Rust Target: x86_64-unknown-linux-musl.
```
TARGET_CXX=x86_64-linux-musl-g++ CC_x86_64_unknown_linux_musl=x86_64-linux-musl-gcc cargo build --release --target=x86_64-unknown-linux-musl
```

the rust program code sample:
```
use tokenizers::models::bpe::{BpeTrainerBuilder};
use tokenizers::{AddedToken, Result};

fn main() -> Result<()> {

    let mut trainer = BpeTrainerBuilder::new()
        .show_progress(true)
        .vocab_size(64)
        .min_frequency(2)
        .special_tokens(vec![
            AddedToken::from(String::from("<pad>"), true),
            AddedToken::from(String::from("<s>"), true),
            AddedToken::from(String::from("</s>"), true),
            AddedToken::from(String::from("<unk>"), true),
            AddedToken::from(String::from("<cls>"), true),
            AddedToken::from(String::from("<sep>"), true),
            AddedToken::from(String::from("<mask>"), true),
        ])
        .build();

    Ok(())
}
```

**Comment by Narsil** [comment]
I can't seem to reproduce locally (I have different issues when building).

However, do you need `openssl` ? It's an optional dependency.

```
tokenizers = { version = "0.11.3", default-features=false, features = ["onig"] }
```
will remove the need for openssl for instance.

**Comment by ShomyLiu** [comment]
Thanks for your reply! it indeed works when I remove the `http` features in tokenizers although there is no `onig` in v0.11.3.
BTW, are there any documents about these settings or descriptions of the features? 

Thanks again.

**Comment by ShomyLiu** [comment]
Oh, please ignore the above comment, @Narsil 
The issue is not `openssl` or `http` feature, but the `esaxx-rs/cpp`.
When I remove the `esaxx_fast` features of tokenizers in Cargo.toml, it could run well, i.e.,
```
{ version = "0.13.0", default-features=false, features = ["progressbar", "http", "cli", "onig"]}
```

Preliminarily, the reason may be that  `esaxx-rs/cpp` needs `musl-g++` compile, which could not be compatibility well.
I have tried to change the compile `TARGET_CXX` into other options `x86_64-linux-musl-g++/c++/gcc `, it does not work all.

So far, my temporary solution is to remove the `esaxx_fast` features in tokenizers.

**Comment by Narsil** [comment]
> Would you mind taking care of this issue of esaxx-rs/cpp?

This is not an issue. `musl` support is not a primary goal of this crate.

That being said, I wrote a pure rust version of `esaxx-rs` which is enabled by removing `cpp` feature and using a different function.
https://github.com/Narsil/esaxx-rs/blob/main/Cargo.toml

The rust functions are named `esaxx_rs/suffix_rs`. Yet they are slower than their cpp counterpart (I never tried to optimize, it's probable due to bound checks)

esaxx cpp is taken from here: https://github.com/google/sentencepiece/tree/master/third_party/esaxx|
It might be easier to fix the build directly in CPP.

For the rust build I'm using `cc`  which is very powerful in building the files automatically, however, I'm not sure about all the flags required to use `musl-g++` or equivalent. Or if the actual code can be compiled on musl. Knowing which is which would be nice.

**Comment by ShomyLiu** [comment]
Thanks a lot for the clear comment! I understand  `esaxx_rs/` now.

And it is surprising that when I specify the `TARGET_CXX` with the compiler in the MacOS, it could both compile and run well with esaxx-rs/cpp, and there is no segment fault with all features of tokenizers in the Linux Platform.

```
TARGET_CXX=cc/gcc/g++ TARGET_CC=x86_64-linux-musl-gcc cargo build --release --target=x86_64-unknown-linux-musl
```
The TARGET_CXX must be the native compiler in MacOS, (e.g., cc/gcc/g++), instead of the `musl` compiler (e.g., x86_64-linux-musl-gcc/cc/g++).

**Comment by Narsil** [comment]
I cannot really tell you what's happening in detail, I don't have a huge experience in cross compilation.

Just that in the end, everything is statically linked so maybe that cleans up the differences between musl and non musl (and since esaxx doesn't require libc iirc) it should be good.

**Comment by ShomyLiu** [comment]
Yeah. It finally works well with your kind help. 
Thanks again.
