### ISSUE TITLE
How to create a custome implementation of the PreTokenizer

### ISSUE THREAD

**Issue by pafi-code** [huggingface/tokenizers#1158]
So I'm trying to build a custom pre tokenizer in python that should satisfy the `PreTokenizer` interface.
I could simply follow the ducktyping principles and create a class that implements the same interface as the `PreTokenizer`. However if I want to actually subclass from the `PreTokenizer`, I get `TypeError: No constructor defined.`, when I try to create an instance.

This somewhat means that there is no default `__new__` method for the `PreTokenizer` that can be used out of the box right?
Is this intended behaviour because the PreTokenizer is something like a sealed class in the rust world? Or is this a bug in the creation of the python bindings?
(Not a rust guy. I just quickly looked into the sources)

```
class Test(tokenizer.pre_tokenizers.PreTokenizer):
    def __init__(self, parameters):
        self._parameters = parameters
    def pre_tokenize(self, pretok):
        pass    
    def pre_tokenize_str(self, sequence):
        pass
```

**Comment by Narsil** [comment]
Yes, this is not Python, so you can't do what you are used to in the python world.

Custom pre_tokenizers (and other custom objects) are crux really meant for prototyping and checking out ideas fast, but they come with a lot of caveats (namely serialization which cannot be done for instance) And these prototyping restrictions.
It's not really restrictions actually, it's just that these functions do not exist at all.

**Comment by pafi-code** [comment]
Alright, makes sense. So what would be the workflow after prototyping? Creating a PR here with the corresponding rust implementation?

**Comment by Narsil** [comment]
Well, you could start by creating an issue with what is missing. There might already be a way to do what you are trying to do.

If there's no way, and it happens to be required to run a model (ideally supported by `transformers`) then yes.
If you don't know rust something else might actually implement it. But before implementing it's usually good to be sure what we want.

does that make sense?
