### ISSUE TITLE
text is listed as optional in api but tokenizer throws error when missing

### ISSUE THREAD

**Issue by epinnock** [huggingface/tokenizers#1159]
I was following the following tutorial on finetuning and notice that this line no longer works as expected:
https://www.philschmid.de/fine-tune-flan-t5
``
    labels = tokenizer(text_target=sample["summary"], max_length=max_target_length, padding=padding, truncation=True)
``
It throws the following error:
``
TypeError: __call__() missing 1 required positional argument: 'text'
``
Yet in the api it looks like the text field in optional:
https://huggingface.co/docs/transformers/main_classes/tokenizer
``text (str, List[str], List[List[str]], optional) — The sequence or batch of sequences to be encoded. Each sequence can be a string or a list of strings (pretokenized string). If the sequences are provided as list of strings (pretokenized), you must set is_split_into_words=True (to lift the ambiguity with a batch of sequences).``

I'll take a further look into this but just wanted to post this just in case someone can spot if it's an obvious user error on my part

**Comment by ArthurZucker** [comment]
Hey! Sorry for the late reply but the documentation you seem to be looking at is the documentation for `transformers`'s. `PreTrainedTokenizer` so not really related to this repo! 
Feel free to open a PR if you want to correct either the doc or the way this input is handled.
