### ISSUE TITLE
How to initialize alphabets for ByteLevel BPE?

### ISSUE THREAD

**Issue by junrae6454** [huggingface/tokenizers#1163]
How to initialize alphabets for ByteLevel BPE?

I'm using Tokenizers to train a ByteLevel BPE tokenizer, and I'm trying to figure out how to initialize the list of allowed characters (alphabets) for the tokenizer. I want to make sure that the tokenizer only considers a specific set of characters during training, but I'm not sure how to set this up.

I try to setup initial alphabet follow rust code, 
https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/pre_tokenizers/byte_level.rs#L12-L33
```python
bs = []
for i in range(33, 126+1):
    bs.append(chr(i))
for i in range(161, 172+1):
    bs.append(chr(i))
for i in range(174, 255+1):
    bs.append(chr(i))


for i in range(256):
    if chr(i) not in test:
        bs.append(chr(2**8 + i))
```

```text
I got tokenizer.pre_tokenizer.alphabet()
! 33 b'!'
" 34 b'"'
# 35 b'#'
$ 36 b'$'
% 37 b'%'
& 38 b'&'
' 39 b"'"
( 40 b'('
) 41 b')'
* 42 b'*'
+ 43 b'+'
, 44 b','
- 45 b'-'
. 46 b'.'
/ 47 b'/'
0 48 b'0'
1 49 b'1'
2 50 b'2'
3 51 b'3'
4 52 b'4'
5 53 b'5'
6 54 b'6'
7 55 b'7'
8 56 b'8'
9 57 b'9'
: 58 b':'
; 59 b';'
< 60 b'<'
= 61 b'='
> 62 b'>'
? 63 b'?'
@ 64 b'@'
A 65 b'A'
B 66 b'B'
C 67 b'C'
D 68 b'D'
E 69 b'E'
F 70 b'F'
G 71 b'G'
H 72 b'H'
I 73 b'I'
J 74 b'J'
K 75 b'K'
L 76 b'L'
M 77 b'M'
N 78 b'N'
O 79 b'O'
P 80 b'P'
Q 81 b'Q'
R 82 b'R'
S 83 b'S'
T 84 b'T'
U 85 b'U'
V 86 b'V'
W 87 b'W'
X 88 b'X'
Y 89 b'Y'
Z 90 b'Z'
[ 91 b'['
\ 92 b'\\'
] 93 b']'
^ 94 b'^'
_ 95 b'_'
` 96 b'`'
a 97 b'a'
b 98 b'b'
c 99 b'c'
d 100 b'd'
e 101 b'e'
f 102 b'f'
g 103 b'g'
h 104 b'h'
i 105 b'i'
j 106 b'j'
k 107 b'k'
l 108 b'l'
m 109 b'm'
n 110 b'n'
o 111 b'o'
p 112 b'p'
q 113 b'q'
r 114 b'r'
s 115 b's'
t 116 b't'
u 117 b'u'
v 118 b'v'
w 119 b'w'
x 120 b'x'
y 121 b'y'
z 122 b'z'
{ 123 b'{'
| 124 b'|'
} 125 b'}'
~ 126 b'~'
¡ 161 b'\xc2\xa1'
¢ 162 b'\xc2\xa2'
£ 163 b'\xc2\xa3'
¤ 164 b'\xc2\xa4'
¥ 165 b'\xc2\xa5'
¦ 166 b'\xc2\xa6'
§ 167 b'\xc2\xa7'
¨ 168 b'\xc2\xa8'
© 169 b'\xc2\xa9'
ª 170 b'\xc2\xaa'
« 171 b'\xc2\xab'
¬ 172 b'\xc2\xac'
® 174 b'\xc2\xae'
¯ 175 b'\xc2\xaf'
° 176 b'\xc2\xb0'
± 177 b'\xc2\xb1'
² 178 b'\xc2\xb2'
³ 179 b'\xc2\xb3'
´ 180 b'\xc2\xb4'
µ 181 b'\xc2\xb5'
¶ 182 b'\xc2\xb6'
· 183 b'\xc2\xb7'
¸ 184 b'\xc2\xb8'
¹ 185 b'\xc2\xb9'
º 186 b'\xc2\xba'
» 187 b'\xc2\xbb'
¼ 188 b'\xc2\xbc'
½ 189 b'\xc2\xbd'
¾ 190 b'\xc2\xbe'
¿ 191 b'\xc2\xbf'
À 192 b'\xc3\x80'
Á 193 b'\xc3\x81'
Â 194 b'\xc3\x82'
Ã 195 b'\xc3\x83'
Ä 196 b'\xc3\x84'
Å 197 b'\xc3\x85'
Æ 198 b'\xc3\x86'
Ç 199 b'\xc3\x87'
È 200 b'\xc3\x88'
É 201 b'\xc3\x89'
Ê 202 b'\xc3\x8a'
Ë 203 b'\xc3\x8b'
Ì 204 b'\xc3\x8c'
Í 205 b'\xc3\x8d'
Î 206 b'\xc3\x8e'
Ï 207 b'\xc3\x8f'
Ð 208 b'\xc3\x90'
Ñ 209 b'\xc3\x91'
Ò 210 b'\xc3\x92'
Ó 211 b'\xc3\x93'
Ô 212 b'\xc3\x94'
Õ 213 b'\xc3\x95'
Ö 214 b'\xc3\x96'
× 215 b'\xc3\x97'
Ø 216 b'\xc3\x98'
Ù 217 b'\xc3\x99'
Ú 218 b'\xc3\x9a'
Û 219 b'\xc3\x9b'
Ü 220 b'\xc3\x9c'
Ý 221 b'\xc3\x9d'
Þ 222 b'\xc3\x9e'
ß 223 b'\xc3\x9f'
à 224 b'\xc3\xa0'
á 225 b'\xc3\xa1'
â 226 b'\xc3\xa2'
ã 227 b'\xc3\xa3'
ä 228 b'\xc3\xa4'
å 229 b'\xc3\xa5'
æ 230 b'\xc3\xa6'
ç 231 b'\xc3\xa7'
è 232 b'\xc3\xa8'
é 233 b'\xc3\xa9'
ê 234 b'\xc3\xaa'
ë 235 b'\xc3\xab'
ì 236 b'\xc3\xac'
í 237 b'\xc3\xad'
î 238 b'\xc3\xae'
ï 239 b'\xc3\xaf'
ð 240 b'\xc3\xb0'
ñ 241 b'\xc3\xb1'
ò 242 b'\xc3\xb2'
ó 243 b'\xc3\xb3'
ô 244 b'\xc3\xb4'
õ 245 b'\xc3\xb5'
ö 246 b'\xc3\xb6'
÷ 247 b'\xc3\xb7'
ø 248 b'\xc3\xb8'
ù 249 b'\xc3\xb9'
ú 250 b'\xc3\xba'
û 251 b'\xc3\xbb'
ü 252 b'\xc3\xbc'
ý 253 b'\xc3\xbd'
þ 254 b'\xc3\xbe'
ÿ 255 b'\xc3\xbf'
Ā 256 b'\xc4\x80'
ā 257 b'\xc4\x81'
Ă 258 b'\xc4\x82'
ă 259 b'\xc4\x83'
Ą 260 b'\xc4\x84'
ą 261 b'\xc4\x85'
Ć 262 b'\xc4\x86'
ć 263 b'\xc4\x87'
Ĉ 264 b'\xc4\x88'
ĉ 265 b'\xc4\x89'
Ċ 266 b'\xc4\x8a'
ċ 267 b'\xc4\x8b'
Č 268 b'\xc4\x8c'
č 269 b'\xc4\x8d'
Ď 270 b'\xc4\x8e'
ď 271 b'\xc4\x8f'
Đ 272 b'\xc4\x90'
đ 273 b'\xc4\x91'
Ē 274 b'\xc4\x92'
ē 275 b'\xc4\x93'
Ĕ 276 b'\xc4\x94'
ĕ 277 b'\xc4\x95'
Ė 278 b'\xc4\x96'
ė 279 b'\xc4\x97'
Ę 280 b'\xc4\x98'
ę 281 b'\xc4\x99'
Ě 282 b'\xc4\x9a'
ě 283 b'\xc4\x9b'
Ĝ 284 b'\xc4\x9c'
ĝ 285 b'\xc4\x9d'
Ğ 286 b'\xc4\x9e'
ğ 287 b'\xc4\x9f'
Ġ 288 b'\xc4\xa0'
ġ 289 b'\xc4\xa1'
Ģ 290 b'\xc4\xa2'
ģ 291 b'\xc4\xa3'
Ĥ 292 b'\xc4\xa4'
ĥ 293 b'\xc4\xa5'
Ħ 294 b'\xc4\xa6'
ħ 295 b'\xc4\xa7'
Ĩ 296 b'\xc4\xa8'
ĩ 297 b'\xc4\xa9'
Ī 298 b'\xc4\xaa'
ī 299 b'\xc4\xab'
Ĭ 300 b'\xc4\xac'
ĭ 301 b'\xc4\xad'
Į 302 b'\xc4\xae'
į 303 b'\xc4\xaf'
İ 304 b'\xc4\xb0'
ı 305 b'\xc4\xb1'
Ĳ 306 b'\xc4\xb2'
ĳ 307 b'\xc4\xb3'
Ĵ 308 b'\xc4\xb4'
ĵ 309 b'\xc4\xb5'
Ķ 310 b'\xc4\xb6'
ķ 311 b'\xc4\xb7'
ĸ 312 b'\xc4\xb8'
Ĺ 313 b'\xc4\xb9'
ĺ 314 b'\xc4\xba'
Ļ 315 b'\xc4\xbb'
ļ 316 b'\xc4\xbc'
Ľ 317 b'\xc4\xbd'
ľ 318 b'\xc4\xbe'
Ŀ 319 b'\xc4\xbf'
ŀ 320 b'\xc5\x80'
Ł 321 b'\xc5\x81'
ł 322 b'\xc5\x82'
Ń 323 b'\xc5\x83'
```
My question is how init_alphabet make?
I can compose CHAR_BYTES to input string if I know how to make it.
Any help or pointers would be greatly appreciated.

Thanks in advance!

**Comment by Narsil** [comment]
ByteLevel works by mapping EVERY 0-255 bytes to a single `char` (utf-8 character).

By design it exists to remove `unk` token. 
I am not sure I understand why you would want to add it again. 

In general the initial_alphabet is meant for `BPE` the model, which you can directly pass from Python. 
This would work by removing the initial `char` (mapped from 0-255)  bytes from your initial vocabulary, making them UNK.

Is that what we're trying to do.

**Comment by junrae6454** [comment]
I want to use it to make a better tokenizer.
In the language I'm working on, it seems like the performance of the model depends on how the tokens are split.
Depending on what words are in the tokenizer's vocab, it can be segmented into a better form.
Right now the tokenizer's vocab is not human readable. 
I'm trying to change this part to make it easier to read.

If CHAR_BYTES written above can be interpreted as BYTE, it can be combined and processed into utf8 form.

**Comment by Narsil** [comment]
>  Right now the tokenizer's vocab is not human readable.

You won't be able to do that while using ByteLevel. By definition you need to map some bytes to something they are not. You can find a cleverer mapping that may look prettier, but you won't get 1-1 byte mapping (because some bytes sequences are not valid utf-8).

The other thing you could do is ditch utf-8 entirely and work purely on bytes. This should be faster and cleaner. But even less readable.

> it seems like the performance of the model depends on how the tokens are split.

Indeed the tokenizer is an important piece of downstream performance.

**Comment by junrae6454** [comment]
The init alphabet of tokenizers seems to insert certain tokens as they are, and then insert those not included from 0 to 255 sequentially from the 256.
If I find a byte that is mapped 1 to 1 by reverse engineering the vocab in tokenizer.json, I think I can decode it back to utf8 form.
for example: "Ġ" indecate to ' ' mean unicode 32 "\x20"

I guess I should have explained it to Rubber Duck. 
I need to start over by defining what my curiosity is.

Thanks for taking the time to answer.
