### ISSUE TITLE
GPT-2 tokeniser's decoder is incorrect and doesn't roundtrip

### ISSUE THREAD

**Issue by hauntsaninja** [huggingface/tokenizers#1164]
```
In [1]: from transformers import GPT2TokenizerFast

In [2]: hug2 = GPT2TokenizerFast.from_pretrained("gpt2")

In [3]: hug2.decode(hug2.encode(" ?"))
Out[3]: '?'
```

`hug2.encode(" ?")` is `[5633]` which is correct

See https://github.com/openai/tiktoken/issues/34 for more details

(I work at OpenAI and wrote tiktoken)

**Comment by Narsil** [comment]
It's a known "issue" and stems from a very old default within `transformers`.

It also affects bloom. https://github.com/huggingface/transformers/pull/20846

**Comment by hauntsaninja** [comment]
This is still an issue

**Comment by ArthurZucker** [comment]
I don't really mind deprecating the cleanup_tokenization_space that is set to True by default TBH! Will see !

**Comment by ArthurZucker** [comment]
Leave it closed as it should be resolved in transformers anyways
