### ISSUE TITLE
Add custom chinese phrases, tokenizer cannot encode correctly

### ISSUE THREAD

**Issue by shayue111** [huggingface/tokenizers#1165]
I try to add some chinese phrases into tokenizer, but there are some whitespace among the encoded result of added pharses. How to fix it?

```python
from tokenizers import Tokenizer

model_id = "bert-base-chinese"
in_sentence = """我最喜欢在下雨天听歌，让人感觉到很放松"""

another_tokenizer = Tokenizer.from_pretrained(model_id)
output = another_tokenizer.encode(in_sentence)
print(output.tokens)

new_tokens = ['听歌', '下雨天']
num_added_toks = another_tokenizer.add_tokens(new_tokens)

after_tokenized_output = another_tokenizer.encode(in_sentence)
print(after_tokenized_output.tokens)
"""
['[CLS]', '我', '最', '喜', '欢', '在', '下', '雨', '天', '听', '歌', '，', '让', '人', '感', '觉', '到', '很', '放', '松', '[SEP]']
We have added 2 tokens
['[CLS]', '我', '最', '喜', '欢', '在', ' 下  雨  天 ', ' 听  歌 ', '，', '让', '人', '感', '觉', '到', '很', '放', '松', '[SEP]']
"""
```

The expect results would be `['[CLS]', '我', '最', '喜', '欢', '在', '下雨天', '听歌', '，', '让', '人', '感', '觉', '到', '很', '放', '松', '[SEP]']`

**Comment by Narsil** [comment]
What's the issue exactly ?

The tokens are correctly spotted.
If you're talking about the extra space, this is what is done in bert as normalization step, it puts spaces before and after every chinese character.
So the tokens get the same treatment and are normalized too.

If you want unnormalized tokens, you can add them as special tokens instead.

But ultimately the "tokens" you are seeing are not what really counts, what really counts are the `ids` which are the numbers used by the model.

And if you need to know where a particular Id is coming from you can just use the `offsets` feature to index within the original string the provenance of your id.

**Comment by shayue111** [comment]
> 

Thanks for your reply. I understand what you mean.

**Comment by shayue111** [comment]
> 

Thanks for your reply. I understand what you mean.
