### ISSUE TITLE
is it possible to use Metaspace pretokenizer without split them?

### ISSUE THREAD

**Issue by Maxlinn** [huggingface/tokenizers#1168]
hi to the community, recently i'd like to do some work on code, so the indentation, which is made of several spaces, has great semantics. so i think different lengths of space should be taken as different tokens. e.g. `  `  and `    `  and `        ` are different tokens.

but the vocab cannot directly save a token which is several spaces, becuase the merge table is saved as `a b`. when a (or b) is consecutive spaces, it cannot determine the merge rule, you will received an error when you load such a `tokenizer.json`.

following the trend it is suitable to replace space with metaspace “▁” (U+2581）, but the `pre_tokenizers.Metaspace` not only replaces space with metaspace, but also **split them into individuals**, that is, `    `→`"▁","▁","▁","▁"`, what is want is `"▁▁▁▁"`.

i didn't see any workaround, i can surely group different lengths of space using `pre_tokenizer.Split(tokenizers.Regex)`, but i can not replace them into metaspace, since there is no such method like `pre_tokenizer.Replace`.  but when i use `pre_tokenizer.Metaspace`, it split multiple metaspaces into single characters.

it is also not possible to maunally add "▁▁▁▁" into vocab and rules like "▁▁ ▁▁" into merge table, since the Metaspace pre_tokenizer will always split spaces into individuals. if remove the Metaspace pre_tokenizer, it cannot do anything with space and make it a <UNK>.

what should i do, thanks in advance!

**Comment by Narsil** [comment]
For the merge table containing spaces, please check out :

https://github.com/huggingface/tokenizers/pull/909

**Comment by Maxlinn** [comment]
> For the merge table containing spaces, please check out :
> 
> #909

much thanks for replying! it seems the solution proposed in #909 was to replace space with other chars like Ġ and then replace it back? that seems not much difference in replace them with metaspace.
