### ISSUE TITLE
`add_tokens` results in duplicate IDs

### ISSUE THREAD

**Issue by davidgilbertson** [huggingface/tokenizers#1169]
I'm trying to add some tokens that I expect to exist in my data, my two requirements are:
* They should not be broken up into smaller pieces when training the tokenizer
* They should not be stripped out when decoding a tokenized sequence

I can't work out how to satisfy these two requirements at the same time, maybe I'm doing it wrong, but it seems that `add_tokens` doesn't behave the way I would expect.

I would expect this code snippet to run (for IDs to be unique), but instead it errors on the assertion.
```py
from tokenizers import Tokenizer, models, trainers

bpe_model = models.BPE(unk_token="[UNK]")
tokenizer = Tokenizer(model=bpe_model)
tokenizer.add_tokens(["~ing", "~ed"])

tokenizer.train_from_iterator(
    iterator=["test~ing lick~ing kick~ing"],
    trainer=trainers.BpeTrainer(
        special_tokens=[
            "[UNK]",
            "[CLS]",
            "[SEP]",
            "[PAD]",
            "[MASK]",
        ],
    ),
)

assert tokenizer.token_to_id("~ing") != tokenizer.token_to_id("[UNK]")
```

I've also tried:
* calling `tokenizer.add_special_tokens()` but this gives different incorrect behaviour (learned tokens get the same IDs as special tokens)
* wrapping my added tokens in `AddedToken` - makes no difference.
* saving to a json file (where the vocab looks right) then loading that, but I get a different error trying to load the file I just saved: `Exception: data did not match any variant of untagged enum ModelWrapper at line 128 column 3`

Is this a bug, or am I not understanding how to use the library correctly? Any guidance would be much appreciated!

Using version: `0.13.2`

**Comment by davidgilbertson** [comment]
I also just tried this:
```py
tokenizer = Tokenizer(
    model=models.WordPiece(
        unk_token="[UNK]",
        vocab={"~ing": 100_000, "~ed": 100_001},
    ),
)
```

Hoping that this would be another way to provide extra vocab, but that just gets wiped out as soon as train is called. It would be neat if this was merged in, rather than deleted.

**Comment by Narsil** [comment]
The problem is that `added_tokens` are meant to be used **after** training, not before.

Like there is no way to treat your added tokens correctly like you expect during training. This is simply breaking the BPE algorithm. 

Would this be a possible workaround :

```python
from tokenizers import Tokenizer, models, trainers, pre_tokenizers

bpe_model = models.BPE()
tokenizer = Tokenizer(model=bpe_model)
# tokenizer.add_special_tokens(["[UNK]"])
# tokenizer.add_tokens(["~ing", "~ed"])
# tokenizer.pre_tokenizer = pre_tokenizers.Whitespace()

tokenizer.train_from_iterator(
    iterator=["test~ing lick~ing kick~ing"],
    trainer=trainers.BpeTrainer(
        special_tokens=[
            "[UNK]",
        ],
    ),
)
tokenizer.add_tokens(["~ing"])

assert tokenizer.token_to_id("~ing") != tokenizer.token_to_id("[UNK]")
```

The problem with added tokens during training is that they are simply ignored as they are not supposed to be in the original dataset. Added tokens is a means of extending an existing tokenizer, not forcing the tokenizer in a special way during training.
The special tokens are ignored just the same too btw, special tokens are just a way to represent in text form those non text ids (like unk or pad, which convey semantic meaning, without requiring a text form, the text form is a convenience). 

Does it make more sense ?

**Comment by davidgilbertson** [comment]
> Added tokens is a means of extending an existing tokenizer, not forcing the tokenizer in a special way during training

Ah, this clarified things for me! And yes adding afterwards does what I want, thank you.

May I suggest adding a warning or error message in the case of either:
* Adding tokens to a model before it's trained
* Training a tokenizer that already has added tokens

Or just a note in the docs might do the trick. I would do this myself but I don't really feel like I fully get it yet.

Otherwise, feel free to close.

**Comment by Narsil** [comment]
> Or just a note in the docs might do the trick.

That would be super nice. 

> May I suggest adding a warning or error message in the case of either:

It's an excellent suggestion, unfortunately, I'm basically the sole maintainer of this lib, and doing tons of other work, which means spending a lot of time for warning messages on this, is not something I consider high value enough to do at the moment.

However if you want to tackle it, spending time providing help and guidance is something I would definitely do !

**Comment by davidgilbertson** [comment]
That's understandable. Thanks for the guidance so far.
