### ISSUE TITLE
`normalizers.Replace` doesn't handle backreferences

### ISSUE THREAD

**Issue by davidgilbertson** [huggingface/tokenizers#1171]
Context: I would like to replace apostrophes used for contractions with a single right curly quote character, so that when I decode I can treat them differently to single quote marks (and collapse the spaces). This is easy enough with the `re` module, but I can't work out how to do it with `normalizers.Replace`.

Sample code:
```py
text = "I said 'don't do it'"  # All single straight quotes
pattern = r"(\w)'(\w)"
replacement = r"\1’\2"

text1 = normalizers.Replace(Regex(pattern), replacement).normalize_str(text)
text2 = re.sub(pattern, replacement, text)

print(f"{text1 = }")  # "I said 'do\\1’\\2 do it'"
print(f"{text2 = }")  # "I said 'don’t do it'"
```

I tried wrapping `replacement` in `Regex()` and surprisingly enough got a Python error (I figured this was all done in Rust): `Exception: invalid backref number/name`.

Is this possible?

If there's some smarter way to sort out quote spacing I'd very much appreciate a nudge in the right direction (I've seen [this issue](https://github.com/huggingface/tokenizers/issues/266)), although it would still be good generally to be able to do back references with regex.

**Comment by Narsil** [comment]
Would this workaround work ? 

```python
from tokenizers import normalizers, Regex

text = "I said 'don't do it'"  # All single straight quotes
pattern = r"'"
replacement = r"’"

pattern1 = r" ’"
replacement1 = r" '"
text1 = normalizers.Replace(Regex(pattern), replacement).normalize_str(text)
text2 = normalizers.Replace(Regex(pattern1), replacement1).normalize_str(text1)

pattern2 = r"’ "
replacement2 = r"' "
text3 = normalizers.Replace(Regex(pattern2), replacement2).normalize_str(text2)
print(text2)
```

Groups are indeed not supported, they make offset accounting extremely hard to keep track of (and are mostly not really necessary in all the tokenizers we support).

For your particular use case, I would be very careful about strings likes ''''''' or ' ' ' ' ' and other very odd things which you are unfortunately very likely to encounter in the wild and could mess up the normalization you propose.

Cheers.

**Comment by davidgilbertson** [comment]
Thanks @Narsil I had a funny feeling back references would be a nightmare for offset accounting.

Your workaround is clever, but I think would have too many false positives as you suggest; my plan was to actually have quite a strict regex to target the most commonly used English contractions, like `([a-z])'([smdrvl])`.

The following is probably a dumb suggestion, but I'm finding a need for pre-pre-processing and post-decoding-processing. That is, I would like to be able to write a plain Python function and have that applied as part of the tokenization pipeline (and accept the performance ramifications). I could imagine being able to subclass `Tokenizer` and define hook methods like `before_pre_tokenize()` and `after_decode()` in the [style of PyTorch Lightning hooks](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.core.hooks.ModelHooks.html).

Is there a recommended approach for doing this sort of thing, and in particular having a system that plays nice with `transformers` `Trainer`?

**Comment by Narsil** [comment]
>  have quite a strict regex to target the most commonly used English contractions, like ([a-z])'([smdrvl]).

This is what gpt2 does: https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/pre_tokenizers/byte_level.rs#L37 !

For your suggestion there is a way to do custom pretokenization: https://discuss.huggingface.co/t/how-to-add-additional-custom-pre-tokenization-processing/1637/2

Please read the caveats about serializing.

For the post-processor, the TemplateProcessing should be powerful enough to encapsulate most of what you want to do.
