### ISSUE TITLE
Understanding tokenizers - two approaches to training a tokenizers

### ISSUE THREAD

**Issue by gusty1g** [huggingface/tokenizers#1172]
I see these two approaches for training a tokenizer in HuggingFace:

### Approach 1
Ref: https://huggingface.co/blog/how-to-train
```
from tokenizers.implementations import ByteLevelBPETokenizer

tokenizer = ByteLevelBPETokenizer()
paths = ['wikitext-2.txt']
tokenizer.train(files=paths)
tokenizer.save_model('../data/hf_bpe')

encoding = tokenizer.encode('hello world')
print (encoding.ids)
```

### Approach 2
Ref: https://huggingface.co/course/chapter6/8
```
from tokenizers import models, trainers, Tokenizer

tokenizer = Tokenizer(model=models.WordPiece(unk_token="[UNK]"))

special_tokens = ["[UNK]", "[PAD]", "[CLS]", "[SEP]", "[MASK]"]
trainer = trainers.WordPieceTrainer(vocab_size=25000, special_tokens=special_tokens)

tokenizer.train(["wikitext-2.txt"], trainer=trainer)

encoding = tokenizer.encode("Let's test this tokenizer...", "on a pair of sentences.")
print(encoding.ids)
```

My question is what is the difference between two approaches and when should I use which approach?

If I understand correctly, in the latter approach, a model represents the tokenization algorithm. In that case, what does the trainer do?

Also, in approach 1, the tokenizer implicitly contains the model (the `.model` attribute). But it's `train` method does not contain an argument for Trainer. Why?

**Comment by Narsil** [comment]
The first one is simply some sugar on top of the second, with some defaults used by other common tokenizers ( ByteLevelBPE is the basis for GPT2 for instance)

You can see the sugar here:
https://github.com/huggingface/tokenizers/blob/main/bindings/python/py_src/tokenizers/implementations/byte_level_bpe.py

You can check all the various components of tokenization here: https://huggingface.co/docs/tokenizers/pipeline

**Comment by gusty1g** [comment]
Thanks for the reference. If I am not wrong, we can train a WordPiece model only with with a WordPieceTrainer. I am trying to understand the underlying design here - why can't trainer be an attribute of `WordPiece` model itself rather than being passed to the `train` method?

**Comment by Narsil** [comment]
There is `get_trainer()` which should return the correct trainer. The various objects are modeled after the rust objects, were the Trainer is independant of the WordPiece itself (it produces a WordPiece). We tried to add something more pythonic , but the various options, and members of objects are quite tedious to keep track of so using the Trainer is still the more "simple" (in the sense things are more explicit, but usually more verbose)

**Comment by gusty1g** [comment]
Thanks, it helps to understand better.
