### ISSUE TITLE
`add_prefix_space` adds a space after added tokens

### ISSUE THREAD

**Issue by davidgilbertson** [huggingface/tokenizers#1174]
When using `pre_tokenizers.ByteLevel(add_prefix_space=True)` (the default), a space is added after anything I've added as a token, e.g. `abc` below:

```py
from tokenizers import Tokenizer, models, trainers, pre_tokenizers, decoders

tokenizer = Tokenizer(model=models.BPE(unk_token="[UNK]"))

tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel()
tokenizer.decoder = decoders.ByteLevel()
tokenizer.train_from_iterator(
    iterator=["abc def ghi jkl s my and"],
    trainer=trainers.BpeTrainer(
        special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"],
    ),
)
tokenizer.add_tokens(["abc"])  # comment me out and it works fine

original = "my abcs and defs"

decoded = tokenizer.decode(tokenizer.encode(original).ids)

print(f"{original = }")  # 'my abcs and defs'
print(f"{decoded  = }")  # ' my abc s and defs'
```

It's as though the code is treating added tokens as sentence ends, and so then adds a space after.

I don't know if this is a bug in the encoding or the decoding, or if I just misunderstand what's supposed to happen

For context, I'm trying to craft a tokenizer that can do `original == tok.decode(tok.encode(original)` (and handle added tokens). `ByteLevelBPETokenizer` does this but treats the first word of a sentence separate which I don't want.

**Comment by Narsil** [comment]
this is going to be handled here: https://github.com/huggingface/tokenizers/pull/1095

**Comment by ArthurZucker** [comment]
This was fixed so closing properly!
