### ISSUE TITLE
ImportError ... tokenizers.cpython... undefined symbol: onig_region_free

### ISSUE THREAD

**Issue by xiota** [huggingface/tokenizers#1176]
Python 3.10.9.  Tokenizers 0.13.2.  `onigurumacffi` is installed.  Following error on import:

```
>>> import tokenizers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/tokenizers/__init__.py", line 80, in <module>
    from .tokenizers import (
ImportError: /usr/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-x86_64-linux-gnu.so: undefined symbol: onig_region_free
```

**Comment by Narsil** [comment]
Any more information ? How did you install ?

`pip install tokenizers` should be enough on all plateforms,there's no need for `onigrumacffi` so I'm not sure what's the issue, but it looks like a bad dynamic lib being present in PATH.

**Comment by xiota** [comment]
I installed `onigrumacffi` because seemed like it could be related to `undefined symbol: onig_region_free`.

I'm tryihng to make a package to install to system folders.  Building with:
```
python -m build --no-isolation --wheel
python -m installer --compile-bytecode 1 --destdir "$pkgdir" dist/*.whl
```

Will try again after completely removing rust.

**Comment by Narsil** [comment]
onig is a C dependency that is indeed required. 

Can you try installing from source with `cd bindings/python && pip install -e .` to see if it works for you ?

**Comment by xiota** [comment]
Removed all traces of rust and tokenizer that I could find, reinstalled rust, then rebuilt.  Now imports without error.  Maybe some rust cache voodoo?
