### ISSUE TITLE
error LNK2038

### ISSUE THREAD

**Issue by qdwang** [huggingface/tokenizers#1178]
When `cargo build` my project with only two deps:
```
[dependencies]
tch = "0.10.3"
tokenizers = "0.13.2"
```

This error came out:
`= note: libtorch_sys-6c1049f81ce711d6.rlib(torch_api.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libesaxx_rs-325b40a662eef64d.rlib(esaxx.o)`

complete error info here: https://gist.github.com/qdwang/6b12cad56e6e68e52264c9c0c6c0e5b0

BUT the most weird thing is, build in **release** mode has no errors at all. And the built exe file works perfectly. 
Don't know what's going on...

Debug build with only `tch` or only `tokenizers` won't cause any problem. The issue only comes at both dependencies are added. And running a `cargo clean` won't help.

I also posted the issue in the tch-rs's repo: https://github.com/LaurentMazare/tch-rs/issues/641

**Comment by Narsil** [comment]
Interesting, I see this: https://www.google.com/search?client=firefox-b-d&q=windows+error+LNK2005

esaxx does build some files https://github.com/Narsil/esaxx-rs/tree/main/src

headers seem properly protected but my cpp fu is not very familiar with Windows.
