### ISSUE TITLE
How to load my custom "tokenizer.json" file into BartTokenizer?

### ISSUE THREAD

**Issue by Luoyang144** [huggingface/tokenizers#1186]
Hello, I'm tring to train a new tokenizer on my own dataset, here is my code:
 
`from tokenizers import Tokenizer`
`from tokenizers.models import BPE`
`from tokenizers.trainers import BpeTrainer`

`unk_token = '<UNK>' 
spl_tokens = ['<UNK>', '<SEP>', '<MASK>', '<CLS>'] ` 

tokenizer = Tokenizer(BPE(unk_token=unk_token))
trainer = BpeTrainer(special_tokens=spl_tokens)
tokenizer.train(files=["text.txt"], trainer=trainer)
tokenizer.save("bart/tokenizer.json")

Then what should I do to read this file into `BartTokenizer` ?

**Comment by Luoyang144** [comment]
Get error below:
File "xxxx/Huggingface/transformers-main/src/transformers/utils/hub.py", line 382, in cached_file
    f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
OSError: ./bart/ does not appear to have a file named config.json. Checkout 'https://huggingface.co/./bart//None' for available files.

**Comment by Luoyang144** [comment]
Maybe I find the problem, after add `tokenizer.pre_tokenizer = Whitespace()`, it works and I can load it with `PreTrainedTokenizerFast`. 
So can you explain why this is the case?

**Comment by Narsil** [comment]
Both error do not seem to be linked.
The first error says the directory is missing `config.json` which is indeed required by `transformers` to read the entire model (including the tokenizer, which uses several files).

For `tokenizers` , it is a lower level library and `tokenizer.json` is enough `Tokenizer.from_file("tokenizer.json")` However you asked to read it with `BartTokenizer`  which is a transformers class and hence require more files that just `tokenizer.json`.

The use of a pre_tokenizer is not mandatory afaik, but it's rare it's not filled. However I don't think the error you currently showed was linked to that. 
If you still want to dive into the issue, if you could provide both the folder used and the code to load along that would enable me to reproduce the issue. 

Cheers !

**Comment by Narsil** [comment]
If there's a way to reproduce on dummy data, that would enable you to share without sharing anything privileged I guess (like train on 1 random sentence, with minimal options).
