### ISSUE TITLE
Why INT64?

### ISSUE THREAD

**Issue by kmosunoff** [huggingface/tokenizers#1187]
Hello guys, thank you for this excellent library!

I was wondering why you decided to return int64 `input_ids` and not int32? I can barely imagine a vocabulary of 2 billion tokens (int32), so is there any reason to go with int64 IDs? Moreover, it has a couple of drawbacks:
1. int64 requires twice more memory;
2. it may take more time to move input_ids to GPU memory;
3. now I have to cast them down to int32 values manually since TensorRT does not support int64.

Thank you for your suggestions!

**Comment by Narsil** [comment]
All ids are in u32:

https://github.com/huggingface/tokenizers/blob/7bfab489798b53f60805cf56fc2e2438f53a864e/tokenizers/src/tokenizer/encoding.rs#L147

Not sure what you're referring to ?

**Comment by kmosunoff** [comment]
> All ids are in u32:
> 
> https://github.com/huggingface/tokenizers/blob/7bfab489798b53f60805cf56fc2e2438f53a864e/tokenizers/src/tokenizer/encoding.rs#L147
> 
> Not sure what you're referring to ?

Sorry, I didn't provide an example.
When I use AutoTokenizer from transformers and set return_tensors="pt", I receive tensors of torch.int64 type.

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
encoded = tokenizer("one two three", return_tensors="pt")
print(encoded.input_ids.dtype)
torch.int64
```

**Comment by Narsil** [comment]
Oh @kmosunoff it's the default integer type for PyTorch. `long`. I think a lot of ops will fail if you use a different int type.

Usually the extra size is minimal compared to the result of the model.

**Comment by Narsil** [comment]
(Technically you also need i64 to get enough space for all possible u32 since i32 doesn't cover enough space. I have never seen a tokenizer with a vocab size so big that this would actually be relevant but still.)

**Comment by kmosunoff** [comment]
Got it, thank you for the answer Nicolas :)
