### ISSUE TITLE
Documentation of add_prefix_space for use in Tokenizer::from_pretrained

### ISSUE THREAD

**Issue by kwalcock** [huggingface/tokenizers#1190]
This error message

```
You need to instantiate RobertaTokenizerFast with add_prefix_space=True to use it with pretokenized inputs.
```

I get when trying to tokenize pretokenized inputs in Python with

```python
tokenizer = AutoTokenizer.from_pretrained(name, add_prefix_space=False) # Needs to be True
token_input = tokenizer(words, is_split_into_words = True)
```

leads me to believe that when in Rust I want to do the same thing, I need to somehow set a value to true when getting the tokenizer.  I can't seem to find any documentation or an example of how to do this.

```rust
let tokenizer = Tokenizer::from_pretrained("roberta-base", None)?; // Needs to be Some(<something>)
```

Can someone provide pointers/documentation suitable for someone who does not understand Rust?

**Comment by Narsil** [comment]
Hi,

There is no way to modify the tokenizer in such a way within rust.
What you want is to modify the `tokenizer.pre_tokenizer` object.

Unfortunately, I cannot give you more help that just using the rustdoc and the general docs to understand how everything is structured.

**Comment by kwalcock** [comment]
Thanks for the tip.
