### ISSUE TITLE
Inconsistent Masking of DataCollatorForLanguageModeling and DataCollatorForWholeWordMask for Short Sentences

### ISSUE THREAD

**Issue by MBAnslow** [huggingface/tokenizers#1193]
In the following data collators, there is a subtle but very important difference in how labels are masked. This can have a dramatic effect on learning from short sentences.

In DataCollatorForLanguageModeling, a bernoulli distribution is sampled from to decide whether to mask a token. As a consequence, some sentences are not masked at all. 

- We get zero loss sentences in our batch which artificially lowers the batch mean. 
- The smaller the sentence, the more likely this will occur.
- No learning occurs for these sentences in the batch so they take up memory and computation for nothing.

Just imagine the case of a developer working on tweets for example. Given an average tweet length of 5 words and an mlm probability of 0.3. An average of ~ 0.168837 tweets will not be masked on a single epoch. 

```
DataCollatorForLanguageModeling

in def torch_mask_tokens(self, inputs: Any, special_tokens_mask: Optional[Any] = None) -> Tuple[Any, Any] of 
         ...
        probability_matrix.masked_fill_(special_tokens_mask, value=0.0)
        masked_indices = torch.bernoulli(probability_matrix).bool()
        labels[~masked_indices] = -100  # We only compute loss on masked tokens
        ...
```

In the WholeWordMask, a random sample is also taken, but a minimum of 1 mask is required.
       
```
DataCollatorForWholeWordMask

in  def _whole_word_mask(self, input_tokens: List[str], max_predictions=512) 
        ...
        num_to_predict = min(max_predictions, max(1, int(round(len(input_tokens) * self.mlm_probability))))
        ...
```

This also introduces a big bias for short sentences. Length 1 sentences will always be masked. Length 2 sentences will be masked at least 50% of the time. Length 3 sentences will be masked at least 33% of the time etc.  This would not match the fixed mlm probability the user specifies.

I'm not really sure how best to handle masking batches of mixed long and short sentences. The easiest thing to do would be to just throw away unmasked examples in the first case. How to do masking well with mixed long and short sentences is probalby a research question. However, it's important to be consistent and clear in the documentation about what the implementation choices were.

**Comment by ArthurZucker** [comment]
Hey, this is unrelated to tokenizers no ?
