### ISSUE TITLE
error: pyo3_runtime.PanicException: likelihood is NAN. Input sentence may be too long

### ISSUE THREAD

**Issue by skye95git** [huggingface/tokenizers#1198]
Hi, I try to train sentencepiece tokenizer using `SentencePieceUnigramTokenizer`:
```
paths = [str(x) for x in Path(f"{train_data_path}/").glob("**/*.txt")]

tokenizer = SentencePieceUnigramTokenizer()
tokenizer.train(files=paths, vocab_size=50_265, special_tokens=[
            "<pad>", "</s>", "<unk>", "<s>", "<mask>"
    ])

tokenizer.save(f'{tokenizer_save_dir}/tokenizer_config.json')
```
There is an error: pyo3_runtime.PanicException: likelihood is NAN. Input sentence may be too long.

How to fix it?

**Comment by Narsil** [comment]
Any way we can reproduce locally ?

How large is the dataset ?

The NaN was created during the unigram training algorithm. The error message seems to imply that the sentence is too long, and indeed it can occur if there's not enough pre_tokenization going on (a way to hard split input sentences into manageable chunks). 
Does the same dataset work with `sentencepiece`?

**Comment by skye95git** [comment]
> Any way we can reproduce locally ?
> 
> How large is the dataset ?
> 
> The NaN was created during the unigram training algorithm. The error message seems to imply that the sentence is too long, and indeed it can occur if there's not enough pre_tokenization going on (a way to hard split input sentences into manageable chunks). Does the same dataset work with `sentencepiece`?


T5 uses the SentencePiece tokenizer too. You can run the follow script to reproduce locally:
```python
from datasets import load_dataset
from transformers import AutoTokenizer

raw_datasets = load_dataset("code_search_net", "python")
print(raw_datasets["train"])

def get_training_corpus():
    dataset = raw_datasets["train"]
    for start_idx in range(0, len(dataset), 1000):
        samples = dataset[start_idx : start_idx + 1000]
        yield samples["whole_func_string"]

training_corpus = get_training_corpus()
print(next(training_corpus))

old_tokenizer = AutoTokenizer.from_pretrained("t5-base")
print(len(old_tokenizer))

example = '''def add_numbers(a, b):
    """Add the two numbers `a` and `b`."""
    return a + b'''

tokens = old_tokenizer.tokenize(example)
print(tokens)
print(len(tokens))

tokenizer = old_tokenizer.train_new_from_iterator(training_corpus, 50265)
tokens = tokenizer.tokenize(example)
print(tokens)
print(len(tokens))
```

It show the same error: `pyo3_runtime.PanicException: likelihood is NAN. Input sentence may be too long.`

**Comment by huangd1999** [comment]
I have the same problem when I execute the script.

**Comment by Narsil** [comment]
I looked at t5-base: https://huggingface.co/t5-base/raw/main/tokenizer.json

There seem to not be a lot of pretokenization, which means the entire functions are sent as-is to the training algorithm. I'm pretty sure this is what causes NaNs to occur. I *think* sentencepiece would yield the same errors. Is there any way you could modify the tokenizer to add some form of pretokenization (Splitting on function boundaries or something like that ?) Or just preventing sending super large functions to it ?

**Comment by mrghofrani** [comment]
Did you manage to solve this? @skye95git

**Comment by DavidRamosArchilla** [comment]
> > Any way we can reproduce locally ?
> > How large is the dataset ?
> > The NaN was created during the unigram training algorithm. The error message seems to imply that the sentence is too long, and indeed it can occur if there's not enough pre_tokenization going on (a way to hard split input sentences into manageable chunks). Does the same dataset work with `sentencepiece`?
> 
> T5 uses the SentencePiece tokenizer too. You can run the follow script to reproduce locally:
> 
> ```python
> from datasets import load_dataset
> from transformers import AutoTokenizer
> 
> raw_datasets = load_dataset("code_search_net", "python")
> print(raw_datasets["train"])
> 
> def get_training_corpus():
>     dataset = raw_datasets["train"]
>     for start_idx in range(0, len(dataset), 1000):
>         samples = dataset[start_idx : start_idx + 1000]
>         yield samples["whole_func_string"]
> 
> training_corpus = get_training_corpus()
> print(next(training_corpus))
> 
> old_tokenizer = AutoTokenizer.from_pretrained("t5-base")
> print(len(old_tokenizer))
> 
> example = '''def add_numbers(a, b):
>     """Add the two numbers `a` and `b`."""
>     return a + b'''
> 
> tokens = old_tokenizer.tokenize(example)
> print(tokens)
> print(len(tokens))
> 
> tokenizer = old_tokenizer.train_new_from_iterator(training_corpus, 50265)
> tokens = tokenizer.tokenize(example)
> print(tokens)
> print(len(tokens))
> ```
> 
> It show the same error: `pyo3_runtime.PanicException: likelihood is NAN. Input sentence may be too long.`

Replacing the `get_training_corpus` function for this one worked for me:

```python
def get_training_corpus(threshold=256):
    dataset = raw_datasets["train"]
    for start_idx in range(0, len(dataset), 1000):
        samples = dataset[start_idx : start_idx + 1000]
        samples = [sample for sample in samples['whole_func_string'] if len(sample) < threshold]
        yield samples
```
