### ISSUE TITLE
Tokenizer import error 

### ISSUE THREAD

**Issue by diogocortiz** [huggingface/tokenizers#120]
I run my experiment today, but I am getting msg error saying that some classes from tokenizers are not found.

> ImportError: cannot import name 'BertWordPieceTokenizer'

I am using the standard import.

`from tokenizers import (ByteLevelBPETokenizer, BPETokenizer, SentencePieceBPETokenizer, BertWordPieceTokenizer)`

The code was running perfectly last friday. I saw you released a new transformers version. Did it change tokenizers?

**Comment by diogocortiz** [comment]
I tried in a new environment. I installed tokenizer via pip, but when I try to `from tokenizers import (ByteLevelBPETokenizer, BPETokenizer, SentencePieceBPETokenizer, BertWordPieceTokenizer)`, I am still getting  error:

> ImportError: cannot import name 'BertWordPieceTokenizer' from 'tokenizers' (/usr/local/lib/python3.7/site-packages/tokenizers/__init__.py)

**Comment by diogocortiz** [comment]
Hmm. It seems that if I install transformers via pip prior to tokenizer, it installed tokenizer in someway.
If I get a new instance and do that:
`pip install transformers`

When, I do that:
`pip install tokenizers`

I got the following msg:

> Requirement already satisfied: tokenizers in /usr/local/lib/python3.7/site-packages (0.0.11)

And if I tried to import, I got this error msg:

> ImportError: cannot import name 'BertWordPieceTokenizer' from 'tokenizers'

I was wondering if it is a problem related to the new Transformers you realeased last friday.

**Comment by n1t0** [comment]
Hi @diogocortiz, can you try to open the `init.py` file you linked when showing your error? I suspect it to be malformed somehow. I don’t know exactly how pip rewrite these files when they already exist but I think you may have to remove all the files manually and reinstall the package to make it work.

**Comment by diogocortiz** [comment]
I have already tried in different servers. For example, if I install only tokenizers, it works perfectly. However, as soon as I install transformers, I can not import BertWordPieceTokenizer. It seems that this new version of transformers is overwriting tokenizers.

**Comment by diogocortiz** [comment]
I figured out that when I install transformers it is overwriting tokenizer init file.

usr/local/lib/python3.7/site-packages/tokenizers/__init__.py

`__version__ = "0.0.11"

from .tokenizers import Tokenizer, models, decoders, pre_tokenizers, trainers, processors
~                  `

Then I need to manually uninstall tokenizer (it was installed by transformers) and reinstall it via pip.
I got this warning:

> transformers 2.4.1 has requirement tokenizers==0.0.11, but you'll have tokenizers 0.2.1 which is incompatible.

and that init file
`
__version__ = "0.2.1"

from .tokenizers import Tokenizer, Encoding
from .tokenizers import decoders
from .tokenizers import models
from .tokenizers import normalizers
from .tokenizers import pre_tokenizers
from .tokenizers import processors
from .tokenizers import trainers
from .implementations import (
    ByteLevelBPETokenizer,
    BPETokenizer,
    SentencePieceBPETokenizer,
    BertWordPieceTokenizer
)
~ `

And then the import works. This bug started last friday.

**Comment by n1t0** [comment]
Yes, for now only the `0.0.11` version of tokenizers is compatible with transformers. We are working on an update that will handle newer versions.
So if you need both libraries, you will need to stick to the `0.0.11` (unless you don’t use it through transformers). In this case, please uninstall tokenizers entirely before re-installing the target version, so that the file does not get overwritten by pip.

**Comment by diogocortiz** [comment]
Thank you, @n1t0 . I will do that! 
Any plans to release this update?

BR,
Diogo

**Comment by n1t0** [comment]
Yes, we should release this pretty soon. You can follow the progress here https://github.com/huggingface/transformers/pull/2674

**Comment by diogocortiz** [comment]
Thank you for your attention. I will close this case. =D

**Comment by manishiitg** [comment]
i am still getting this error. how exactly to solve this?

**Comment by diogocortiz** [comment]
After you install transformers, you need to unistall tokenizers and install again tokenizers. 

I am using Colab, so I am doing this workaroung until they release the new version:

!pip install transformers
!pip uninstall tokenizers
!pip install tokenizers

Hope it helps you!

**Comment by manishiitg** [comment]
Thanks, this solved the issue

**Comment by zycalice** [comment]
I am having the same problem; is there a better solution as of now?

**Comment by Narsil** [comment]
@zycalice 

Do you mind sharing what's your environment, how you installed `tokenizers` , with what version ?

**Comment by zycalice** [comment]
> @zycalice
> 
> Do you mind sharing what's your environment, how you installed `tokenizers` , with what version ?

So I initially have it with transformer, so I uninstalled tokenizers from my IDE PyCharm and reinstalled from PyCharm. It seems the version is still tokenizers==0.12.1. Is the version the issue?

**Comment by Narsil** [comment]
Well, everything seems to be working normally for `tokenizers==0.12.1`.

You're the first report of anything not working, and since not much changed since `0.11.6` I am not sure where the problem could come from.

Do you know what environment you are running ? (PyCharm maybe handles a virtualenv or a conda ?)
Do you mind sharing your OS, python version ?

**Comment by zycalice** [comment]
> Well, everything seems to be working normally for `tokenizers==0.12.1`.
> 
> You're the first report of anything not working, and since not much changed since `0.11.6` I am not sure where the problem could come from.
> 
> Do you know what environment you are running ? (PyCharm maybe handles a virtualenv or a conda ?) Do you mind sharing your OS, python version ?

I now use tokenizers~=0.10.1 and now it works.
I use Mac, python 3.9, but I noticed my transformers version is 4.9.1. Could it be that my transformer version is outdated?

**Comment by brando90** [comment]
@diogocortiz is there a concise summary of what fixed this? I still get these issues, details here: https://github.com/huggingface/transformers/issues/15062
