### ISSUE TITLE
tokenizer.add_tokens() will use duplicate id if called before tokenizer.train()

### ISSUE THREAD

**Issue by liujuncn** [huggingface/tokenizers#1200]
The behavior of tokens added by tokenizer.add_tokens() is different from Trainer's special_tokens, and will not be added in front of the model's vocab, and trainer will reuse their ids while training.

If call tokenizer.add_tokens() after tokenizer.train(), will not have this problem.

What I expect is that before tokenizer.train(), added tokens and special_tokens behave similarly, while the results of subsequent train() satisfy the vocab_size constraint.

**Comment by liujuncn** [comment]
Reproduce example,

trainer = BpeTrainer(...)
tokenizer.add_tokens(RESERVED_TOKENS)
tokenizer.train_from_iterator(...)

It will reuse the id by RESERVED_TOKENS and trainer.

**Comment by liujuncn** [comment]
If this logic is implemented, then problems like #1109 can be solved by first adding the previous tokens and then training on the new data set.

**Comment by ArthurZucker** [comment]
This is currently not supported and is similar to #1281. If you want the vocab to start with tokens they should be special
