### ISSUE TITLE
rust crate: cannot install rust crate without the default features

### ISSUE THREAD

**Issue by samsja** [huggingface/tokenizers#1202]
Hey, first thanks for the great crate !

I want to install tokenizers in a rust project with cargo with the minimal dependency possible.

I see that the `default` features include several dependencies that I don't need like HTTP or cli.

Therefore I tried to install by using `default-features = false`. But I am getting an error in the cargo build step because of some `onig` import even though the onig passage is suppose to be optional.

Here are the step to reproduce

1 - `cargo new test_cargo`
2 - ` cd test_cargo`
3 - edit Cargo.toml:

```toml
[package]
name = "test_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizers = { version = "0.13.2", default-features = false }
```

4 - cargo build
error : 
```console
  Compiling tokenizers v0.13.2
error[E0432]: unresolved import `onig`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/tokenizers-0.13.2/src/utils/onig.rs:3:5
  |
3 | use onig::Regex;
  |     ^^^^ help: a similar path exists: `super::onig`

error[E0433]: failed to resolve: use of undeclared crate or module `onig`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/tokenizers-0.13.2/src/utils/onig.rs:12:60
   |
12 |     pub fn find_iter<'r, 't>(&'r self, inside: &'t str) -> onig::FindMatches<'r, 't> {
   |                                                            ^^^^ use of undeclared crate or module `onig`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `tokenizers` due to 2 previous errors
```

**Comment by Narsil** [comment]
Hi @samsja 

`onig` is not optional. Or more correctly, either it or `fancy-regex` is required.  `onig` is the true default in this crate, but to get `unstable_wasm` we had to enable `fancy-regex`. (It's a different engine, so it might contain differences with `onig` which is why it'  marked as unstable.

This is sort of breaking the features disposition, if you have better suggestions I'm all ears (Removing all components requiring `onig` feel like a big stretch and lot of work to maintain).

**Comment by samsja** [comment]
Okay now I understand. Not sure how we can express the dependency X or Y in cargo.toml. 

Thanks for the answers

**Comment by mert-kurttutan** [comment]
I am not sure if you already solved issue. In case you did not, I also came across this issue, the only thing I had to do additionally is to add dependency of onig as follows
```
tokenizers = { git = "https://github.com/huggingface/tokenizers", branch="main", features = ["onig"], default-features = false}

```

**Comment by mert-kurttutan** [comment]
You can also use version instead of git link, it still works OK.
