### ISSUE TITLE
SentencePieceUnigramTokenizer vs sentencepiece implementation on repetitive letters

### ISSUE THREAD

**Issue by tsinggggg** [huggingface/tokenizers#1213]
Hello, this is nothing important but just out of curiosity, would you please help me with some possible explanations about this discrepancy between sentencepiece implementation of unigram model vs huggingface implementation?

For an odd number of consecutive and repetitive characters, a token of length 1 will always be the last one from sentencepiece unigram but for huggingface implementation, this length 1 token will always appear first. I might not have described it well but the example below should be pretty clear. I think the cause should be somewhere deep in the code base, it'd be great if you could share some insights. Thank you!

steps to replicate:

in command line:

```
echo "hello bye goodbye what's up good mood oo" > train.txt
wget https://raw.githubusercontent.com/google/sentencepiece/master/python/src/sentencepiece/sentencepiece_model_pb2.py
```

in python:
```
from sentencepiece import SentencePieceProcessor
import sentencepiece
import tokenizers
sentencepiece.SentencePieceTrainer.Train('--input=train.txt --model_prefix=m --vocab_size=23')
sp_model = SentencePieceProcessor()
sp_model.Load("m.model")
sentence = 'nooooo'
print(sp_model.encode_as_pieces(sentence))


hf_tokenizer = tokenizers.implementations.SentencePieceUnigramTokenizer.from_spm("m.model")
print(hf_tokenizer.encode(sentence).tokens)
```

Output:
![image](https://user-images.githubusercontent.com/20978879/230497266-eae270ba-2d6f-451b-b3af-6607ea2f18bc.png)

**Comment by tsinggggg** [comment]
Looks like a related issue: https://github.com/google/sentencepiece/issues/747

**Comment by Narsil** [comment]
Indeed. Another one for this is floating imprecision. Everything in this lib is in `f32` where as iirc sentencepiece uses a mix of f32 + f64 leading to different kind of imprecision.
