### ISSUE TITLE
Feature Request: benchmarks compare with sentencepiece

### ISSUE THREAD

**Issue by DamonsJ** [huggingface/tokenizers#1214]
Is there official benchmark data that tokenizers compare with sentencepiece?
will you provide?

**Comment by Narsil** [comment]
Not really.

There are many flags and knobs in both libraries which do affect performance.
In general my estimation is that BPE is much faster in this lib, and unigram faster in sentencepiece (by a slight margin).
But it does depend on the data and the pretokenization/normalization components

While this is being said, both are fast enough that most likely they won't be the bottleneck but the ML models used downstream will be.

Then this lib aims to be more general and tunable and calculating offsets during tokenization (which is useful for applications like NER and do come at a compute cost).

This libs uses only u32 and doesn't allow using u64 which are necessary when training on HUGE datasets (your mileage may vary, but whenever a u32 overflow could happen, think 10Gb+). 
Also Unigram training is functional, but we could never replicate 100% the exact same training so I advocate a sane carefulness here.

**Comment by DamonsJ** [comment]
well, fine!
Thanks for replying!
By the way, sentencepiece treat input as sentence while tokenizers treat input as word, I mean you don't need to pre-tokenize when I using sentencepiece, right? so, they are different algorithm. And cannot be compared in terms of efficiency and results,  right?

**Comment by Narsil** [comment]
> , I mean you don't need to pre-tokenize when you are using sentencepiece, right? so, they are different algorithms. And cannot be compared in terms of efficiency and results, right?

Both are doing the same thing. There are some hard pre-tokenization done in sentencepiece last time I checked (it's been a while). 
In the end, they are doing exactly the same work but what I am saying is that even `tokenizers` efficiency can widely vary depending on the tokenizer and the data it's tokenizing. And there are probably some combos which can exhibit super high efficiency, and others super bad one. Maybe those profiles depend with spm.

In any case, it's beyond the point, they are roughly on the same speed level.

If you are interested in speed of tokenization, let me recommend you check out

https://github.com/microsoft/BlingFire
https://github.com/VKCOM/YouTokenToMe
https://github.com/openai/tiktoken

None are exactly having the same feature set, but all interesting if performance is what matters to you.

**Comment by DamonsJ** [comment]
Thanks very much!
it helps me a lot !
