### ISSUE TITLE
Using ByteLevel decoding to decode Chinese appears garbled.: 没 有 � 加 价 的 行 为

### ISSUE THREAD

**Issue by Alex-Songs** [huggingface/tokenizers#1215]
Using ByteLevel decoding to decode Chinese appears garbled: 没 有 � 加 价 的 行 为

**Comment by Narsil** [comment]
Hi, this can definitely happen, it depends on the underlying tokenizer + model.

Can you provide with a more reproducible script ? But it's not necessarily a bug. ByteLevel produces bytes, if the model outputs bytes which are not valid utf-8 then this happens.

**Comment by Alex-Songs** [comment]
@Narsil Thanks

**Comment by Narsil** [comment]
Ok I will close this for now, feel free to reopen.
