### ISSUE TITLE
question about function count_pairs in bpe trainer

### ISSUE THREAD

**Issue by DamonsJ** [huggingface/tokenizers#1219]
I am reading the code of bpe trainer.
in function count_pairs(tokenizers/src/models/bpe/trainer.rs), you calculate the initial charact pair in words.
what does ".reduce"(https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/models/bpe/trainer.rs#:~:text=%7C%7C%20(-,HashMap,-%3A%3Anew( ) part means in this rust code ?
I mean when you count informations needed in filter ".map"(https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/models/bpe/trainer.rs#:~:text=.-,map,-(%7C(i%2C%20word)
, you got whatever you want.

**Comment by Narsil** [comment]
reduce is very general : https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.reduce

Then we need the pairs, but also their neighbors.

A B C D -> pairs `[(A, B), (B, C), (C, D)]` but we also need to know that `(A, B)` has (C, D) as right neighbor and no left neighbord.

That way, when we actually do a merge, we can update the entire structure to remove `(A, B)` and update all neighbors such that we are in a similar state to calculate the next merge.

Does that make sense ?

**Comment by DamonsJ** [comment]
Thanks!
I know what you want to do with merges, that will complete in  filter ".map".
I mean if I translate this function to cpp, it will be like :

`
void Trainer::count_pairs(std::vector<Word>& words,
                          std::vector<uint32_t>& counts,
                          FlatHashMap_PairKey_i32Value& pair_counts,
                          FlatHashMap_PairKey_SetValue& where_to_update)
{
    for (int i = 0; i < words.size();++i) {
        auto &word = words[i];
        int symbol_size = word.symbols.size();
       
        for (int j = 0;j < symbol_size -1; ++j) {
            CPair cur_pair = std::make_pair(word.symbols[j].c, word.symbols[j+1].c);
            // Initialize pair_counts and where_to_update for this pair if we just saw it
            if (pair_counts.find(cur_pair) == pair_counts.end()) {
                pair_counts.insert(std::make_pair(cur_pair, 0));
            }
            auto count = counts[i];
            auto &sets = where_to_update[cur_pair]; 
            sets.insert(i);
            pair_counts[cur_pair] = pair_counts[cur_pair] + count; 
        }
    }
}
`
maybe there are some difference between c and rust ?

**Comment by Narsil** [comment]
Hmm, I don't know. Sorry  I don't have time to debug your cpp code.

But it should be translatable yes.

Closing for now. Feel free to reopen
