### ISSUE TITLE
Disable "Using ..._token, but it is not set yet." message?

### ISSUE THREAD

**Issue by mawilson1234** [huggingface/tokenizers#1221]
I have a script that works with many different models. As part of this script, I do some post-processing on sentences to reformat them and remove special tokens that exist for some models (though I do not want to remove all special tokens). Among these tokens are `bos_token`, `sep_token`, etc.

The formatting occurs in a loop that processes the results. Every time I try to do something like the below, another message is added to the log file:
```python
input_texts = []
for inputs, pred_sequence in zip(input_ids, results):
    ...
    input_texts.append(
        tokenizer.decode(inputs)
            .replace(tokenizer.sep_token or "", "")
            .replace(tokenizer.pad_token or "", "")
            .replace(tokenizer.bos_token or "", "")
            .strip()
            .replace("  ", " ")
    )
    ...
```
If the tokenizer doesn't have one of these special tokens defined, it displays a message every time I access the attribute during the loop. As far as I can tell, this is not a message displayed via a logging function (it doesn't use the log format), and appears to just be printed directly, so adjusting the logging level doesn't seem to change anything.

Is there a way to disable showing this message? I could at least get it to not show up more than once by doing this:
```python
input_texts = []
sep_token = tokenizer.sep_token or ""
pad_token = tokenizer.pad_token or ""
bos_token = tokenizer.bos_token or ""
for inputs, pred_sequence in zip(input_ids, results):
    ...
    input_texts.append(
        tokenizer.decode(inputs)
            .replace(sep_token, "")
            .replace(pad_token, "")
            .replace(bos_token, "")
            .strip()
            .replace("  ", " ")
    )
    ...
```
But it'd be nicer if I could get it to avoid cluttering up my log files entirely.

**Comment by Narsil** [comment]
Have you tried

`tokenizer.decode(inputs, skip_special_tokens=True)` ? 

Should be much easier I think.

**Comment by mawilson1234** [comment]
Yes, but I want to keep the position of mask tokens in the input; `skip_special_tokens=True` gets rid of those. Is there a way to keep them while skipping the rest?

**Comment by mawilson1234** [comment]
Looking around, it seems like the `all_special_tokens` property could solve this.
```python
input_texts = []
for inputs, pred_sequence in zip(input_ids, results):
    ...
    input_text = tokenizer.decode(inputs)
    for token in tokenizer.all_special_tokens:
        if token != tokenizer.mask_token:
            input_text = input_text.replace(token, "")
    
    input_text = input_text.strip().replace("  ", " ")
    
    input_texts.append(input_text)
    ...
```

**Comment by Narsil** [comment]
Glad you found a fix, and thanks for sharing.
