### ISSUE TITLE
bytelevel(), Unigram best practices

### ISSUE THREAD

**Issue by chris-ha458** [huggingface/tokenizers#1224]
unigram is usually used / associated with the Metaspace() pretokenizer.
However, byte_fallback does not seem to be implemented in the unigram() model
(although it is done in BPE)
for general purpose generative LLM training we must turn to bytelevel() pretokenizer.

However bytelevel() is associated with its own whitespace processing and also its own decoder.

As it stands huggingface decoders does not have sequence()  implemented that might allow
both metaspace and bytelevel() to be used in the decoder stage.

one workaround might be using the postprocessor
we might be able to use bytelevel() post processor and then use the metaspace() decoder.

What is the standard for approaching this? in other words, what did the developers intend?

**Comment by Narsil** [comment]
Bytefallback for Unigram is on the way:

https://github.com/huggingface/tokenizers/pull/1217

ByteLevel and Metaspace can play along in this lib, so you can technically get it to work.
Postprocessors and decoders and pre_tokenizers can all be chained into sequences so normally you have full control into what's being done in the model. 
It could be confusing to select all parts correctly for your given problem space, but it's possible (Metaspace does a bit too much imo, ByteLevel also needs to not use a regex in pretokenization for instance).

**Comment by chris-ha458** [comment]
Now I realize that MetaSpace pretokenizer is more about how to deal with whitespaces and less about the downstream tokenization algorithm.
Unigram, as an algorithm does not depend on Metaspace()
