### ISSUE TITLE
sequence_ids and token_to_sequence return incorrect result for left padding

### ISSUE THREAD

**Issue by peter-sk** [huggingface/tokenizers#1229]
When using left padding, the sequence ids are not shifted accordingly.

# minimal upstream example:

```
from transformers import GPT2TokenizerFast
t = GPT2TokenizerFast.from_pretrained("gpt2")
t.add_special_tokens({'pad_token': '[PAD]'})
t.padding_side = "left"
e = t("ABC","DEF",padding="max_length",max_length=3)
print(list(zip(e['input_ids'],e.sequence_ids())))
```

# expected output:
`[(50257, None), (24694, 0), (32988, 1)]`

# actual output:
`[(50257, 0), (24694, 1), (32988, None)]`

**Comment by peter-sk** [comment]
@Narsil looks like you know something about GPT2 tokenizers 👍

**Comment by Narsil** [comment]
Indeed this is a bug ! Prepared a PR for it.. Thanks for the report and reproducible example !
