### ISSUE TITLE
Implementing maximum token length in BPE (like SPM max_sentencepiece_length)

### ISSUE THREAD

**Issue by chris-ha458** [huggingface/tokenizers#1230]
I think work on the  source(trainer,model, and module), bindings and documentation would be necessary to implement this. Are the developers of tokenizers interested in such functionality?
I made a PR for the main part. propagating the settings seems like the only thing necessary now.
What kind of tests would you want to see before merging?

_Originally posted by @chris-ha458 in https://github.com/huggingface/tokenizers/issues/1228#issuecomment-1525771937_

**Comment by Narsil** [comment]
Yep. For the bindings, I can take care of it. It's relatively tedious, work, and definitely not trivial if you've never done it (Just lot of places to adjust things to get the docs and functionality work correctly).

If you are ok with making the same functionality with the other approach I suggest (which  again I *think* would be better) then I'll take care of the bindings.

**Comment by chris-ha458** [comment]
Max_sentencepiece_length function implemented by #1228
