### ISSUE TITLE
Npm error during tokenizers installation

### ISSUE THREAD

**Issue by Barbariskaa** [huggingface/tokenizers#1231]
npm install tokenizers@latest
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'tokenizers@0.13.1',
npm WARN EBADENGINE   required: { node: '>=10 < 11 || >=12 <14' },
npm WARN EBADENGINE   current: { node: 'v18.15.0', npm: '9.6.4' }
npm WARN EBADENGINE }
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path C:\Users\user\node_modules\tokenizers
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install
npm ERR! 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.13.1/index-v0.13.1-node-v108-win32-ia32-unknown.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
npm ERR! node-pre-gyp info using node@18.15.0 | win32 | ia32
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "C:\Users\user\node_modules\tokenizers\bin-package\index.node" (not found)
npm ERR! node-pre-gyp http GET https://tokenizers-releases.s3.amazonaws.com/node/0.13.1/index-v0.13.1-node-v108-win32-ia32-unknown.tar.gz
npm ERR! node-pre-gyp http 403 https://tokenizers-releases.s3.amazonaws.com/node/0.13.1/index-v0.13.1-node-v108-win32-ia32-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.13.1/index-v0.13.1-node-v108-win32-ia32-unknown.tar.gz
npm ERR! node-pre-gyp ERR! stack     at PassThrough.<anonymous> (C:\Users\user\node_modules\node-pre-gyp\lib\install.js:142:27)
npm ERR! node-pre-gyp ERR! stack     at PassThrough.emit (node:events:525:35)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\user\node_modules\needle\lib\needle.js:538:9)
npm ERR! node-pre-gyp ERR! stack     at Object.onceWrapper (node:events:628:26)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:542:22)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:324:12)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd C:\Users\user\node_modules\tokenizers
npm ERR! node-pre-gyp ERR! node -v v18.15.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\user\AppData\Local\npm-cache\_logs\2023-04-28T09_06_55_904Z-debug-0.log
[2023-04-28T09_06_55_904Z-debug-0.log](https://github.com/huggingface/tokenizers/files/11351911/2023-04-28T09_06_55_904Z-debug-0.log)

I've tried to use VPN, in case if my ISP blocks requests, but to no avail.

**Comment by Narsil** [comment]
node 18 is not supported, only node <=14.

We need to rewrite entirely the bindings to support newer version, but there's not enough bandwidth in the team, help would be appreciated here.

Also you could use the `wasm` build too possibly. (Check `unstable_wasm` feature).

**Comment by Narsil** [comment]
CLosing, feel free to reopen
