### ISSUE TITLE
Is SentencePieceBPETokenizer officially supported?

### ISSUE THREAD

**Issue by keunwoochoi** [huggingface/tokenizers#1236]
I can't find any official API / document / example about it. My IDE also rants that it can't find reference in the import line

```python
from tokenizers import SentencePieceBPETokenizer
```

This makes me wonder if `SentencePieceBPETokenizer` is not officially supported. Am I missing something?

Thanks.

**Comment by Narsil** [comment]
It is.

However, we find too many misconceptions were happening with that class (and other `implementations` friends).
That's why the docs now focus on the `components` to allow users to create any tokenizer by assembling its pieces.

**Comment by keunwoochoi** [comment]
Thanks for the answer, @Narsil.
I understand that and have some follow-up questions.
- Would it make sense though to make the class visible to IDE? 
- Probably, the doc can still include some built-in implementations such as `SentencePieceBPETokenizer` by explaining what kind of `components` they consist of? While googling, I realized some other folks were also wondering about `SentencePieceBPETokenizer`. That's prob because it's not included in any official example code (afaik), but probably there are other types of implementation that are a bit under documented, too.

**Comment by Narsil** [comment]
> Would it make sense though to make the class visible to IDE?

Sure, it should be already, isn't it ? What kind of IDE are you using. If you can provide a PR that would be welcome.

> by explaining what kind of components they consist of?

The best doc in this case is the code itself: 
https://github.com/huggingface/tokenizers/blob/main/bindings/python/py_src/tokenizers/implementations/sentencepiece_bpe.py#L26

PRs are welcome to update the docs, but keep in mind we really want to focus on components in general.

**Comment by keunwoochoi** [comment]
i also believe it should! especially when i am successfully importing it. 
i don't have very deep knowledge on how they work, but based on `[tokenizers/__init__.py](https://github.com/huggingface/tokenizers/blob/main/bindings/python/py_src/tokenizers/__init__.py#L99)`, it should be visible. (iirc some other modules such as `torch` also has some issues like this, but i haven't looked into any deeper)

i am using Pycharm. i'd like to find a fix and like to make a PR if i know how! i'll probably ask.. ChatGPT once i get back on my personal laptop.

on doc: gotcha, thanks for the answer. i guess, instead of explaining all the implementations, i can even simply summarize your answer. i believe it'd be helpful for beginners like me.

**Comment by keunwoochoi** [comment]
haha, it was a half joke but indeed, it was a trick situation for me to figure out because i have no experience in working on packaging python + other languages.

that said, by asking around i learned that my IDE is only looking into `__init__.pyi` and not `__init__.py`. the former doesn't have imports for the Tokenizer implementations hence IDE cries about it, but the latter have them hence the code works.

as `__init__.py` is generated content, the fix would involve something more deep but this seems beyond what i can quickly do. i'm okay with closing this issue if you'd like. thanks for the help.
