### ISSUE TITLE
Creating a tokenizer for flaubert in rust

### ISSUE THREAD

**Issue by larochef** [huggingface/tokenizers#1238]
I would like to create a tokenizer for https://huggingface.co/flaubert/flaubert_base_uncased

From what I understand, this model is needing a bpe tokenizer. Since there is no tokenizer.json file in the repo, I can not use the "magical" method create the tokenizer from it.

I have some small rust repo (https://github.com/numind-tech/flaubert_tokenizer/tree/main/tokenizer) trying to load the data, but failing to do so,  what would be needed for it to work?

The failing part is the BPE model creation.

**Comment by larochef** [comment]
@Narsil I did try it, but, from my understanding, the tokenizer is a slow / legacy one and won't export a tokenizer.json file (at least I didn't see it when I tried it). If we can have a tokenizer.json file it would for sure be great and way more simple.

Here is the result from save_pretrained:

```
('new_flaubert/tokenizer_config.json',
 'new_flaubert/special_tokens_map.json',
 'new_flaubert/vocab.json',
 'new_flaubert/merges.txt',
 'new_flaubert/added_tokens.json')
```
and if I add `legacy_format=False` I get the following error:

`ValueError: Only fast tokenizers (instances of PreTrainedTokenizerFast) can be saved in non legacy format.`

**Comment by Narsil** [comment]
My bad ! 

I read `new_flaubert/tokenizer_config.json'` as `tokenizer.json`. 

Flaubert doesn't have a fast tokenizer, and it will be almost impossible to port, it uses `sacremoses`  (as the old issue suggests).

And `sacremoses` is a complex piece of code for the normalization, so using the BPE from purely the `merges` and `encodes` is likely to create issues.

You can create the BPE from the `merges.txt` and `vocab.json` but you're going to miss a lot of preprocessing code: 
Like here:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/flaubert/tokenization_flaubert.py#L449

Does this make sense ?

**Comment by larochef** [comment]
It does make sense, yes.
If I understand well, to use this model with rust, I would need to ensure the whole pipeline is implemented.

It doesn't explain all I think though, is the error I faced due to the fact that the python implementation is more permissive than the rust one? could there be some issue with the data?

Anyway, thank you for your time, I didn't make alot of progress but at least I have a clear answer on this.

**Comment by Narsil** [comment]
I cannot access your repo btw:
https://github.com/numind-tech/flaubert_tokenizer/tree/main/tokenizer

> It doesn't explain all I think though, is the error I faced due to the fact that the python implementation is more permissive than the rust one? could there be some issue with the data?

The rust API is usually more conservative than Python yes.
The data could most certainly be flawed in some way. Vocab can contain holes, and merges can be malformed

**Comment by s-bernard** [comment]
@Narsil The repo is public now.

**Comment by Narsil** [comment]
Thanks I confirm the vocab.json + merges.txt is wrong.

It is indeed missing `Token `aboursorama</w>` out of vocabulary`.

What does that mean ?

It means that the merge is unusable. Rust version properly crashes because the files are inconsistent. 
I am guessing the Python equivalent just does something weird instead of properly detecting this.

I tried cleaning up the merges but there's a lot of such tokens. It really looks like the tokens are actually missing from the vocab, but it would require a lot of deepdiving to find the proper original thing (if the original files are even valid themselves, this is not always the case).
