### ISSUE TITLE
Fail trying to find sentence-transformer

### ISSUE THREAD

**Issue by rasrov** [huggingface/tokenizers#1242]
Hi!

I'm getting error on my java application when I trying to start it.
`detailMessage -> Model "sentence-transformers/all-mpnet-base-v2" on the Hub doesn't have a tokenizer`

I'm ussing `redis-om-spring` library and and this library is ussing `ai.djl.huggingface` dependency with version `0.21.0`.

Redis-om-library are ussing this model:
```
"sentence-transformers/all-mpnet-base-v2": {
    "application": "nlp/text_embedding",
    "cpu_only": true,
    "downloads": 553260,
    "result": "success",
    "sha1": "bd44305fd6a1b43c16baf96765e2ecb20bca8e1d",
    "size": 405283582
  }
```

I have tried to find this tokenizer model into https://huggingface.co/models, but I don't found any model starting with "sentence-transformers".

**Comment by Narsil** [comment]
Hi @rasrov there is a partial outage currently happening for these models.

Our teams are hard at work fixing it.
Thank you for your patience.

**Comment by rasrov** [comment]
Working! 🚀
