### ISSUE TITLE
Path to implementing --max_sentence_length

### ISSUE THREAD

**Issue by chris-ha458** [huggingface/tokenizers#1259]
With #1257 merged, I would like to further discuss the possibilities regarding  --max_sentence_length implementation.
To recap,--max_sentence_length is an option exposed in [spm](https://github.com/google/sentencepiece/blob/master/doc/options.md) that allows a length cap on individual input sentences.
The rationale for that feature is twofold and described in spm's protobuf (equivalent to json): 
[sentencepiece/src/sentencepiece_model.proto](https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto)
```
// Longer input tends to bring the following risks:
// * Overflow during EM training (unigram language model only)
// * Performance drop because of O(n log n) cost in BPE.
```
I feel that those are useful traits that the huggingface tokenizer could also have.

Implementing it would require some consideration.
Since this diverges from default behavior, we shouldn't implement in a way that exposes the option to use it in the first place.

Some ideas:
1. implement as new pretokenizer.(lengthcheck(min_length,max_length) )
2. simply extend upon #1257 and add a check for maximum length in the trainer.
3. Don't implement this function.

The first option would be the cleanest way, and we wouldn't have to worry about backward compatibility.
One would have to intentionally add it.
An issue with this approach could be that the lengthcheck isn't strictly a pretokenizer. It's more of a preprocessor.
Also it would have to be disabled during inference. I am not aware of a method to do this.

The second option is the easiest way, and i think I might be able to do most if not all of the work including bindings
(following #1228)
If we keep the default as no maximum length limit than previous approaches or people training new tokenizers will not be affected.
Also this would only influence the training process so there is no issue with train vs inference discrepancy.

One drawback for this approach could be from bringing preprocessing logic into the training logic, but since this preprocessing is unique to training i don't think it's a significant issue.
Another drawback could be that this wouldn't affect BPE as the implementation in spm does.
This isn't that much of a problem since we could easily implement a similar option there when the need arises.
. It is extremely rare from my corpuses for natural language corpuses to have longer than 4192 characters without any kind of linebreak or punctuation that would cause other tokenizers to separate it. Usually, a "sentence" longer than 4192 characters would be code. There are code in certain programming languages where the WHOLE file is just ascii and whitespace. 
No newline or linebreaks. It gets fed into the training algorithm as is. 
This has been a problem for unigram algorithm but not as much for BPE. So If it was up to me, I would just add this for unigram but not BPE.

Lastly, not adding this option at all is also an option.
Both number 1,2 have certain drawbacks, and neither might align with the longterm vision of this project.
In such a case, leaving this feature unaddressed would be a disappointing but acceptable position to me.

In any case, I would be happy to take point on implementation of this feature whichever path is agreed upon.

Feel free to mention alternatives.

**Comment by chris-ha458** [comment]
@ArthurZucker 
Thanks for taking a look
As per my PR #1262 , I realized that atleast for my current data - tokenizer pipeline,
The main bottleneck is not in the unigram model process but rather the normalization-pretokenization pipeline.

As such unless some other party(either from the developers or from downstream users of tokenizers) recognizes a need for this functionality at this time I think I will likely focus on preprocessing pipeline parallelization.

**Comment by Narsil** [comment]
Hey 2. is the way to go, but it actually already exists: https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/models/unigram/trainer.rs#L67

It has a different name which is inherited from sentencepiece, but works exactly the same.

**Comment by Narsil** [comment]
Thanks for the clarification, I was indeed thiking about the first one.

The second one should be handled by pre_tokenization or the user. 
I don't understand why you would want to truncate input from the user on his behalf *by default*. Seems very odd to me.
currently it's rather easy to implement, simply filter out (or truncate) sentences you feed the trainer and you're good to go, no ?

**Comment by chris-ha458** [comment]
That's a reasonable standpoint.
Actually that has been how i've been implementing it.
Example : I'm using a huggingface dataset -> batched into iterator -> fed into huggingface tokenizer
with dataset.filter() used somewhere in the middle to achieve that goal.

This is handled by sentencepiece but obviously the internal and external structures and design goals of these two codebases are different.

I am trying to build a spm settings to huggingface tokenizer wrapper(many open source codebases use spm and provide cli scripts to replicate their results) and I was just wondering if this is something that should be handled in the wrapper or in tokenizers itself.

I have no reason to insist for this feature beyond this so I think i can move on to other features.
Closing.
