### ISSUE TITLE
Documentation Update Request: tokenizers.normalizers.Replace and tokenizers.Regex

### ISSUE THREAD

**Issue by piquan** [huggingface/tokenizers#1261]
I recently experienced confusion while attempting to use the `tokenizers.normalizers.Replace` normalizer in a Python program to replace multiple consecutive whitespaces with a single space in the `tokenizers` library. From the existing documentation, it wasn't clear how to use the `tokenizers.normalizers.Replace` function's support for regular expressions, specifically, that I needed to use the `tokenizers.Regex` class to create a regex pattern.

Here's a brief overview of the confusion:
- The Hugging Face documentation (https://huggingface.co/docs/tokenizers/components#normalizers) describes the `Replace` normalizer as replacing a "custom string or regexp." However, the example provided (`Replace("a", "e")`) only shows usage with a string, not a regex pattern.
- The API documentation for `Replace` (https://huggingface.co/docs/tokenizers/v0.13.3/en/api/normalizers#tokenizers.normalizers.Replace) is sparse and doesn't provide any information on how to use it with regular expressions.
- I couldn't find any current documentation resources explaining the usage of the `tokenizers.Regex` class.

As a result, it took some trial and error to discover that I needed to use `tokenizers.Regex` to create a regular expression pattern for `tokenizers.normalizers.Replace`, like so: `tokenizers.normalizers.Replace(tokenizers.Regex(r"\s{2,}"), " ")`.

To help prevent similar confusion in the future, could the documentation for `tokenizers.normalizers.Replace` and `tokenizers.Regex` be updated to clearly explain the usage of regular expressions and provide relevant examples?

Thanks for your attention to this matter.

**Comment by chris-ha458** [comment]
I can confirm that a similar situation exists for the split() pretokenizer.
https://huggingface.co/docs/tokenizers/api/pre-tokenizers#tokenizers.pre_tokenizers.Split
I learned this the hard way.

**Comment by chris-ha458** [comment]
Would this PR #1264 address your concerns? Do you feel like further documentation would be necessary?

**Comment by piquan** [comment]
It didn't change either of the two places I specifically looked at: https://moon-ci-docs.huggingface.co/docs/tokenizers/pr_1264/en/api/normalizers#tokenizers.normalizers.Replace and https://moon-ci-docs.huggingface.co/docs/tokenizers/pr_1264/en/components#normalizers .

It looks like it did update https://moon-ci-docs.huggingface.co/docs/tokenizers/pr_1264/en/api/pre-tokenizers#tokenizers.pre_tokenizers.Split , but that's different enough from the `Replace` normalizer that I wouldn't tend to look there.
