### ISSUE TITLE
how to use train_new_from_iterator() attribute with facebook/bart-base model tokenizer 

### ISSUE THREAD

**Issue by Saitaruntulabandula** [huggingface/tokenizers#1265]
this is my code 
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-base")

from tqdm.auto import tqdm

length = 1000
iter_dataset = iter(dataset)
def batch_iterator(batch_size=100):
    for _ in tqdm(range(0, length, batch_size)):
        yield [next(iter_dataset)['text'] for _ in range(batch_size)]

tokenizer=tokenizer.train_new_from_iterator(batch_iterator(),vocab_size=12500,initial_alphabet=base_vocab)

but its raising an error "AttributeError: 'BartTokenizer' object has no attribute 'train_new_from_iterator'"  Here this code was used in gpt2 model its running fine on it but its not working in bart. I also gone through the documentation part of train_new_from_iterator() attribute there it mentioned that it will work for the Fast tokenizers only where bart is also a fast tokenizer. Please provide proper code. Thx

**Comment by chris-ha458** [comment]
in your code, you are not using the huggingface tokenizer library directly
as you can see in the [AutoTokenizer documentation](https://huggingface.co/docs/transformers/main/en/model_doc/auto#transformers.AutoTokenizer) 
the AutoTokenizer class does not support training from new. it is meant for use as part of a pretrained tokenizer.

As for training a new from groundup, refer to the following documentation:
https://huggingface.co/learn/nlp-course/chapter2/4?fw=pt

https://huggingface.co/docs/tokenizers/training_from_memory

**Comment by ArthurZucker** [comment]
On point @chris-ha458 thanks for answering this quick!
