### ISSUE TITLE
broken link at the documentation of tokenizers/quicktour

### ISSUE THREAD

**Issue by youkaichao** [huggingface/tokenizers#1267]
Hi, it seems that the link https://huggingface.co/transformers/tokenizer_summary.html referred by https://huggingface.co/docs/tokenizers/quicktour is broken :(

**Comment by Narsil** [comment]
Thanks for notifying, https://huggingface.co/docs/transformers/v4.29.1/en/tokenizer_summary#summary-of-the-tokenizers
