### ISSUE TITLE
Include Extra Whitespace after Decode

### ISSUE THREAD

**Issue by karan-dalal** [huggingface/tokenizers#1274]
Hi. I'm trying to do some text completion with a language model. I want to iteratively generate tokens, then append them to the original prompt, then repeat the process. An example:

Prompt: "Please complete the sentence. She went to the"
Response: "park and"
Prompt 2: "Please complete the sentence. She went to the park and"
Response: "had a fun time."

I'm tokenizing as follows:
`source = tokenizer(batch, return_tensors="pt", padding=True)`
`tokenizer.batch_decode(
                completions[start_idx : start_idx + tokenization_batch_size],
                skip_special_tokens=True,
 )`

So here's my issue. When I decode a response, it doesn't include a space before it. Thus, when I concatenate the response to the previous prompt, I get "She went to thepark and..." Hardcoding a space doesn't work, because sometimes the prompt itself is between tokens ("She went to the pa").

Is there anyway to preserve the space when decoding? There might be some nifty trick that I'm not familiar with. Thanks!

**Comment by Narsil** [comment]
Your answer should be here: https://github.com/huggingface/tokenizers/issues/1141

Short answer, it's not possible in general (for any given tokenizer).
It should be available for generative tokenizers (they just use a configuration which allow for it), even though the code is slightly convoluted.

**Comment by karan-dalal** [comment]
Thanks Narsil!
