### ISSUE TITLE
[Question] When is "Ġ" added in the pre-tokenization step?

### ISSUE THREAD

**Issue by hkvision** [huggingface/tokenizers#1282]
https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/pre_tokenizers/byte_level.rs
Hi I'm bit new to tokenization and I want to ask in the ByteLevel pre-tokenizer, where is "Ġ" added in the implementation? Seems I fail to find such logic.
Thanks for any help!

**Comment by Narsil** [comment]
You were in the correct file it's here : https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/pre_tokenizers/byte_level.rs#L12-L33

The function simoply maps `' '` to `Ġ`

**Comment by hkvision** [comment]
Oh yes, I did see this code piece but didn't realize the actual meaning.
Now I understand char 32(space) would be mapped to char 288 (Ġ).
Thank you!
