### ISSUE TITLE
Bart custom tokenizer

### ISSUE THREAD

**Issue by BakingBrains** [huggingface/tokenizers#1283]
Hello,

I am trying to replicate the same tokenizer as mention in ```hyunwoongko/asian-bart-zh``` for arabic
I followed huggingface [tutorial](https://huggingface.co/learn/nlp-course/chapter6/8?fw=pt), but if I check the ```tokenizer.json``` file
I can see the ```normalizer``` section is null, where as the ```tokenizer.json``` in ```hyunwoongko/asian-bart-zh```  
contains `{"type": "Precompiled", "precompiled_charsmap": "....."}`.  Not sure what am I  missing.

Any suggestions here?

Thanks and reagrds.

**Comment by BakingBrains** [comment]
Thank you @Narsil 
Yeah, I have checked the custom tokenizer gives same ids.

Can you please suggest how can I train Tokenizer as same as MBART or how can I train a custom tokenizer with single language using MBART, example arabic using MBART tokenizer. I have followed the guide but still I feel I am missing some info.

**Comment by chris-ha458** [comment]
@Narsil Can you document what precompiled does?
I know it exists for sentencepiece compatibility but, an explanation of what it does, how and why would be appreciated.

I assume its implementing sentencepiece unique "NFKC-like" normalization, but if thats the case I can't see how that code would be implementing that.

**Comment by Narsil** [comment]
> @Narsil Can you document what precompiled does?

Ask sentencepiece, every is copied verbatim from there here, and it's quite opaque: https://github.com/Narsil/esaxx-rs
It's a trie structure to do the replacements but is laid out in a self referential array. That's best (potentially wrong) explanation I can give you.

And sentencepiece supports arbitrary normalization, and their "NFKC" is not actually NFKC, they decided to remove and insert a few rules.
