### ISSUE TITLE
DataCollatorForLanguageModeling call of tokenizer.pad causes crash

### ISSUE THREAD

**Issue by condor-cp** [huggingface/tokenizers#1284]
The call of tokenizer.pad on a dataset with 'labels' and return_tensors="pt" causes crash
Minimal gist to reproduce : 
tokenizers==0.13.3
torch==2.0.1

```[python]
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilroberta-base")

tokenizer.pad(
    {
        "input_ids": [[0, 51, 51, 2], [0, 10, 11, 12, 13, 2]],
        "labels": [[0, 51, 51, 2], [0, 10, 11, 12, 13, 2]],
    },
    return_tensors="pt",
)
```

Causes : 
```[shell]
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`labels` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```

Only "input_ids" get padded to the maximal input length in the batch, and so "labels" cannot be converted to a pytorch tensor.

In the case input_ids and labels are not padded manually before, this causes DataCollatorForLanguageModeling to crash here : https://github.com/huggingface/transformers/blob/e84bf1f734f87aa2bedc41b9b9933d00fc6add98/src/transformers/data/data_collator.py#L732C16-L732C16, before "labels" are padded a few line after here : https://github.com/huggingface/transformers/blob/e84bf1f734f87aa2bedc41b9b9933d00fc6add98/src/transformers/data/data_collator.py#L748C13-L748C13

I suspect the conversion to pytorch tensor should be done after this line https://github.com/huggingface/transformers/blob/e84bf1f734f87aa2bedc41b9b9933d00fc6add98/src/transformers/data/data_collator.py#L748C13-L748C13 and not before.

**Comment by Narsil** [comment]
Can you open an PR on `transformers` and not here ? This isn't linked to this lib it seems.

**Comment by condor-cp** [comment]
Yes indeed, sorry.
