### ISSUE TITLE
Question: Dose tokenizers.Tokenizer has pad() method like transformers PretrainedTokenizer?

### ISSUE THREAD

**Issue by ZeguanXiao** [huggingface/tokenizers#1287]
Or some other utilities to dynamically pad list of list token_ids? Or how to create a transformers PretrainedTokenizer based on my custom tokenizers.Tokenizer?

**Comment by ZeguanXiao** [comment]
Found in [transformers](https://huggingface.co/docs/transformers/v4.30.0/en/fast_tokenizers) and [this issue](https://github.com/huggingface/tokenizers/issues/953).

**Comment by Narsil** [comment]
Thanks for reporting your findings I'm sure readers will appreciate !
