### ISSUE TITLE
How to make python binding tokenization run on multiple cores?

### ISSUE THREAD

**Issue by Tomarchelone** [huggingface/tokenizers#130]
I tried passing RAYON_RS_NUM_CPUS=4 to python script but it still runs on a single core

**Comment by n1t0** [comment]
Hi @Tomarchelone! In order to take advantage of the multithreading features, you need to call `encode_batch` instead of `encode`.  By doing so, all the sequences you give to `encode_batch` will be treated in parallel using the specified number of threads.

**Comment by Tomarchelone** [comment]
Thanks a lot!
