### ISSUE TITLE
Loading and Hosting pre-trained spm SentencePieceUnigram tokenizer

### ISSUE THREAD

**Issue by meliksahturker** [huggingface/tokenizers#1301]
I have a SentencePieceUnigram tokenizer that was trained and saved with the spm package.
I convert it to Tokenizers object by
`import tokenizers`
`tokenizer = tokenizers.SentencePieceUnigramTokenizer.from_spm('SentencePiece_32k_Tokenizer.model')`
and then I can save it using either
`tokenizer.save()`
or
`tokenizer.save_model()`
First one produces a binary file without extension, while the second one produces a unigram.json file.

What I need is to host my custom model and its tokenizer on huggingface hub.
What is the correct way to convert, save be able to load and host my SentencePieceTokenizer?

**Comment by Narsil** [comment]
Converting from `spm`  to `tokenizers` is not exactly as straightforward as this.

Here are some converters we have written: https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py
You can take inspiration to convert yours. But it's up to you to verify that the choices you made are consistent and produce the same ids (so that your model will actually work).

Otherwise "slow" tokenizer will just call the SPM model under the hood and that also works

**Comment by meliksahturker** [comment]
@Narsil Thanks for the response.

I have tried convert_slow_tokenizer as below:

`import sentencepiece as spm`
`from transformers import convert_slow_tokenizer`

`spm_tokenizer = spm.SentencePieceProcessor('SentencePiece_32k_Tokenizer.model')`
`spm_converter = convert_slow_tokenizer.SpmConverter(spm_tokenizer)`

which results in the error below:
`AttributeError: 'SentencePieceProcessor' object has no attribute 'vocab_file'`

Also tried loading the object as tokenizers' SentencePieceUnigramTokenizer and pass it to the converter as below:
`import tokenizers`
`hf_tokenizer = tokenizers.SentencePieceUnigramTokenizer.from_spm('SentencePiece_32k_Tokenizer.model')`
`spm_converter = convert_slow_tokenizer.SpmConverter(hf_tokenizer)`

which results in the same error.

Havent found anything like a guide for the conversion other than the source code.
What is the correct way to convert and save?

**Comment by Narsil** [comment]
You need to look at the source code and understand what's going on.

There is no automatic method for it and there cannot be really, the 2 libraries function quite differently.
If your spm model looks like something already existing, it should be relatively easy to make yours, if not you'll have to understand how it works.
