### ISSUE TITLE
Possible infinite loop in Encoding merge

### ISSUE THREAD

**Issue by timkaas** [huggingface/tokenizers#1304]
If encoding has any overflow, will this recursive call to `merge_with` not cause an infinite loop?

https://github.com/huggingface/tokenizers/blob/bb38f390a61883fc2f29d659af696f428d1cda6b/tokenizers/src/tokenizer/encoding.rs#L417

**Comment by Narsil** [comment]
Can you produce a reproducible example ?

Overflows will cause all sorts of headaches yes.
