### ISSUE TITLE
Get the eos_token and eos_token_id in Rust

### ISSUE THREAD

**Issue by junsoo999** [huggingface/tokenizers#1305]
Hello, I am newbie in this field.

I am making the simple C++ bindings for our application. 
I found basic function calls like `encode`, `decode`, and `from_str`.
However, I cannot find the function call to get the `eos_token` and `eos_token_id`.

In python,  an instance of the `AutoTokenizer` can give the information of the `eos` but I don't know how to do it in original Rust code.

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(".")
tokenizer.eos_token
tokenizer.eos_token_id
```

Can you give me an example code that returns the `eos` information?

**Comment by Narsil** [comment]
This library does not know what eos is, and has no information about it.

It will use special tokens as told so, but has no semantic information. Usually transformers carries around `tokenizer_config.json` and `special_tokens.json` to get those.
