### ISSUE TITLE
Exception: Error while attempting to build Precompiled normalizer: Cannot parse precompiled_charsmap

### ISSUE THREAD

**Issue by kellymarchisio** [huggingface/tokenizers#1307]
When calling SentencePieceUnigramTokenizer().from_spm() on a sentencepiece model trained with "identity" normalization, I get the following error:
`Exception: Error while attempting to build Precompiled normalizer: Cannot parse precompiled_charsmap`

The breakage is [here](https://github.com/huggingface/tokenizers/blob/main/bindings/python/py_src/tokenizers/implementations/sentencepiece_unigram.py#L178), because precompiled_charsmap is b'' when there is no normalization.  Can you please add code to handle when precompiled_charsmap is empty?

**Comment by Narsil** [comment]
Fixed by #1308
