### ISSUE TITLE
Added tokens not getting encoded in gpt2 tokenizer

### ISSUE THREAD

**Issue by jaykasundra2** [huggingface/tokenizers#1309]
I am trying to add vocabulary in the existing GPT2 tokenizer.

**Step 1: Train a tokenizer on custom data**

```
from tokenizers import (decoders, models, normalizers, pre_tokenizers, processors, trainers, Tokenizer)
new_tokenizer = Tokenizer(models.BPE())
new_tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)
trainer = trainers.BpeTrainer(vocab_size=500, special_tokens=["<|endoftext|>"])
new_tokenizer.train([train_file], trainer=trainer)
new_tokenizer.post_processor = processors.ByteLevel(trim_offsets=False)
new_tokenizer.decoder = decoders.ByteLevel()

new_tokenizer = GPT2TokenizerFast(tokenizer_object=new_tokenizer)
new_tokenizer.save_pretrained("new_tokenizer_gpt2")
new_tokenizer
```

> GPT2TokenizerFast(name_or_path='', vocab_size=466, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=True)

**Step 2: Load GPT2 Tokenizer**
```
gpt2_tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
print(len(gpt2_tokenizer.get_vocab()))
gpt2_tokenizer
```

> 50257
> GPT2TokenizerFast(name_or_path='gpt2', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=True)

**Step 3: Add new vocabulary to GPT2Tokenizer**
```
gpt2_tokenizer.add_tokens(list(new_tokenizer.get_vocab()))
gpt2_tokenizer.save_pretrained("extended_tokenizer_gpt2")
print(len(gpt2_tokenizer.get_vocab()))
gpt2_tokenizer
```

> 50602
> GPT2TokenizerFast(name_or_path='gpt2', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, clean_up_tokenization_spaces=True)
> 

**Step 4: Confirm the changes**
```
text = "अनुराग"
gpt2_tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
new_tokenizer = GPT2TokenizerFast.from_pretrained("new_tokenizer_gpt2")
extended_tokenizer = GPT2TokenizerFast.from_pretrained("extended_tokenizer_gpt2")

print(len(gpt2_tokenizer.encode(text)))
print(gpt2_tokenizer.encode(text))
print(len(new_tokenizer.encode(text)))
print(new_tokenizer.encode(text))
print(len(extended_tokenizer.encode(text)))
print(extended_tokenizer.encode(text))
```

> 11
> [11976, 227, 11976, 101, 24231, 223, 11976, 108, 48077, 11976, 245]
> 7
> [82, 57, 96, 126, 87, 85, 106]
> 11
> [11976, 227, 11976, 101, 24231, 223, 11976, 108, 48077, 11976, 245]

Here, The new_tokenizer is giving the correct encoding but the extended_tokenizer is giving same encoding as the gpt2_tokenizer. What am I missing?

**Comment by Narsil** [comment]
> GPT2TokenizerFast(name_or_path='gpt2', vocab_size=50257, 

It seems the vocab_size isn't actuallly updated by `add_tokens`.

This is pretty odd, could you share your tokenizer.json somewhere so we could take a look ?

@ArthurZucker FYI (in case you know already, no need to investigate)

**Comment by jaykasundra2** [comment]
@Narsil: Regarding the vocab_size, I think it does not update `voab_size` attribute but `len(gpt2_tokenizer.get_vocab())` gives the correct vocab_size. (refer to `step 3` output - 50602 vs. 50257)

I did few experiments and it seems to update the vocabulary correctly, I need to add the `decoded` tokens as below
```
vocab_tokens = list(new_tokenizer.get_vocab())
decoded_tokens = [new_tokenizer.decoder.decode([token]) for token in vocab_tokens]
gpt2_tokenizer.add_tokens(decoded_tokens)
gpt2_tokenizer.save_pretrained("extended_tokenizer_gpt2")
```
```
text = "अनुराग 1972 में निर्मित एक हिन्दी फ़िल्म"
gpt2_tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
new_tokenizer = GPT2TokenizerFast.from_pretrained("new_tokenizer_gpt2")
extended_tokenizer = GPT2TokenizerFast.from_pretrained("extended_tokenizer_gpt2")

print(len(gpt2_tokenizer.encode(text)))
print(gpt2_tokenizer.encode(text))
print(len(new_tokenizer.encode(text)))
print(new_tokenizer.encode(text))
print(len(extended_tokenizer.encode(text)))
print(extended_tokenizer.encode(text))
```

> 59
> [11976, 227, 11976, 101, 24231, 223, 11976, 108, 48077, 11976, 245, 28225, 106, 24231, 229, 11976, 224, 28225, 101, 11976, 123, 11976, 108, 24231, 235, 11976, 106, 11976, 123, 11976, 97, 28225, 237, 11976, 243, 28225, 117, 11976, 123, 11976, 101, 24231, 235, 11976, 99, 24231, 222, 28225, 104, 11976, 120, 11976, 123, 11976, 110, 24231, 235, 11976, 106]
> 26
> [1004, 226, 205, 204, 233, 222, 231, 239, 208, 205, 206, 221, 208, 213, 272, 220, 208, 212, 206, 228, 211, 288, 416, 219, 206, 221]
> 26
> [50520, 51356, 54058, 52228, 53854, 51679, 54249, 53796, 52419, 54058, 52757, 53410, 52419, 53476, 53358, 53663, 52419, 54032, 52757, 51374, 51175, 51200, 53907, 51950, 52757, 53410]
> 

Strange but this seems to have added tokens correctly, hoping this might be the right way to add the tokens.

**Comment by Narsil** [comment]
Doesn't seem right to have to jump through those hoops.

I'll close anyway, since you have solved your issue.

@ArthurZucker for a final look.

**Comment by ArthurZucker** [comment]
It's a bit complicated to have a proper look, if you can share any of the tokenizers would help. Otherwise, I think this falls in the various issue we have with `add_tokens` and is not related to `tokenizers` but rather to `transformers`.
