### ISSUE TITLE
sentencepiece and importing with .from_spm do not encode the same way

### ISSUE THREAD

**Issue by kellymarchisio** [huggingface/tokenizers#1311]
I trained a sentencepiece Unigram model with the sentencepiece package.   I now try to load models with sentencepiece model with the sentencepiece library versus HuggingFace and encode a sentence, and I get different results.  I am not using sampling, so these should be the same: the highest-likelihood tokenization.  Am I missing something?  How can I get HF to produce the "correct" tokenization that the sentencepiece package produces?  

Steps to reproduce:
```
hf_tokenizer = SentencePieceUnigramTokenizer().from_spm(LOCAL_MODEL)
spm_tokenizer = spm.SentencePieceProcessor(model_file=LOCAL_MODEL)

x = "hello this is a sentence"

hf_encode = hf_tokenizer.encode(x).tokens # ['▁', 'hello', '▁this', '▁is', '▁', 'a', '▁sentence'] 
spm_encode = spm_tokenizer.encode_as_pieces(s) ['▁', 'hello', '▁this▁is▁a', '▁sentence']
```

**Comment by Narsil** [comment]
> hf_tokenizer = SentencePieceUnigramTokenizer().from_spm(LOCAL_MODEL)

is not a one stop shop to do the conversions. It might notable add preprocessing that might be killing this.

In `transformers` we carefully assemble the various `tokenizers` piece to make it look like the settings of the SPM:https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py

The method you are using does the same with predefined options: https://github.com/huggingface/tokenizers/blob/main/bindings/python/py_src/tokenizers/implementations/sentencepiece_unigram.py#L146

Here i'm guessing you used special flags in SPM to not get whitespace splitting so the `Metaspace` automatically added is something you shouldn't want, correct ?

**Comment by kellymarchisio** [comment]
Indeed - I set —split-by-whitspace to False, and I do allow whitespace-only tokens. Is it possible to have the HuggingFace implementation respect these options?

**Comment by Narsil** [comment]
Just do not add `Metaspace` I think.

Check `LlamaConverter` in the link I sent, you should have another way of handling the "_" metaspace of SPM

**Comment by kellymarchisio** [comment]
OK, like LlamaConverter, I have changed the normalizer and decoders in the .from_spm method to the below, and removed the pre_tokenizer:
```
tokenizer.normalizer = normalizers.Sequence(
            [
                normalizers.Prepend(prepend="▁"),
                normalizers.Replace(pattern=" ", content="▁"),
            ]
        )
tokenizer.decoder = decoders.Sequence(
            [
                decoders.Replace("▁", " "),
                decoders.Strip(content=" ", left=1),
            ]
        )
```
I now get the desired tokenization for this sentence, as below:
```
hf_encode = hf_tokenizer.encode(x).tokens # ['▁', 'hello', '▁this', '▁is', '▁', 'a', '▁sentence'] 
spm_encode = spm_tokenizer.encode_as_pieces(x) ['▁', 'hello', '▁this▁is▁a', '▁sentence']
```
A funny thing happens when we have repeated characters, though.   Given two tokenizations (presumably of equal probability), HF and SPM choose the tokens in different order.  I have verified this over numerous strings.  Is there a way to reconcile this ordering?
```
hf_tokenizer.encode(']]]').tokens # ['▁', ']', ']]']
spm_tokenizer.encode_as_pieces(']]]') # ['▁', ']]', ']']

# (Underscores, not MetaSpaces)
hf_tokenizer.encode('__________').tokens # ['▁', '_', '___', '___', '___'] 
spm_tokenizer.encode_as_pieces('__________') # ['▁', '___', '_', '___', '___']
```

**Comment by Narsil** [comment]
No. Unfortunately both are correct, and it all comes down to sort stability and float precision.

If you look SPM doesn't use stable sort, so actually it can lead to different tokenizations in the same string...
You can check this for more information about all this: https://github.com/huggingface/tokenizers/pull/401#issue-696517135

**Comment by StephennFernandes** [comment]
hey @Narsil @kellymarchisio , sorry as its the wrong place to ask this question. but could you guys please tell me how to convert the sentencepiece model to huggingface tokenizers format. 

i get an error when i use the `.save_pretrained()` method 

```
AttributeError: 'SentencePieceUnigramTokenizer' object has no attribute 'save_pretrained'
```
