### ISSUE TITLE
BpeTrainer is too slow compared to YouTokenToMe. Why?

### ISSUE THREAD

**Issue by saberiato** [huggingface/tokenizers#1313]
Hi,

I have trouble training a BPE tokenizer using HuggingFace tokenizers:

- Corpus: ~13 billions characters (~13 GB)
- Tokenizer: Byte Pair Encoding (BPE)
- Vocabulary Size: 512

I trained the BPE tokenizer via YouTokenToMe with 8 threads... and it finished in **less than 10 minutes.**
However, I'm trying to train the BPE tokenizer using BpeTrainer (`tokenizers.trainers.BpeTrainer`) with 256 threads... and it has not finished yet **after more than 10 hours.**

Why?

**Comment by saberiato** [comment]
Thanks for the reply,
I'm using DNA sequences and a sentence in the corpus is something like ACCGGTCATCGTCA (a sequence of A C T Gs), and initial tokens (alphabet) are A, C, T, and G. So, I guess no pre-tokenization is needed, and I used BpeTrainer without any pre-tokenization.
Do you suggest any specific pre-tokenizer for my case? a tokenizer to take each character (A,C,T,G) as a token (there is no whitespace or any other characters).

**Comment by Narsil** [comment]
For DNA I think you would need : https://huggingface.co/docs/tokenizers/v0.13.3/en/api/trainers#tokenizers.trainers.BpeTrainer.max_token_length

Having this will prevent tokens from being longer than `max_token_length`. This will cap the computation and it should work faster.
However you will be unable to have tokens longer than this limit (no idea if there's a "good" default for your data)

**Comment by saberiato** [comment]
Sure, I'll try it, but when the vocab size is set to 512, the maximum token length would be less than 10 characters, so it shouldn't be a problem.

**Comment by Narsil** [comment]
Oh you're probably right, it requires a new release...

Glad to know it's a desired feature.
I will probably wait a few days before making such a release, having a bit of issues with some platforms with `safetensors` release.

In the meantime, could you try installing from source to check it out ?

**Comment by gautierdag** [comment]
Yep interested in this feature :) ! And yes can confirm installing from source works.

**Comment by Narsil** [comment]
Backports I just mean merging those CD changes back here before creating a release

**Comment by Yikai-Liao** [comment]
I am curious that does setting `max_token_length` really reduce the training time to the same scale as YouTokenToMe?
