### ISSUE TITLE
`processor.added_tokens()` and the actual number of tokens added by `processor.process_encodings()` are defined separately, but there is nothing checking that they align

### ISSUE THREAD

**Issue by boyleconnor** [huggingface/tokenizers#1314]
The value procduced by `processor.added_tokens()` and the number of tokens actually added by `processor.process_encodings()` are two values that are defined separately (e.g. [with](https://github.com/huggingface/tokenizers/blob/efea6c72464428cabbf6332a16243e55963ba175/tokenizers/src/processors/bert.rs#L35) [BERT](https://github.com/huggingface/tokenizers/blob/efea6c72464428cabbf6332a16243e55963ba175/tokenizers/src/processors/bert.rs#L43)), but are required to be the same in order for `Tokenizer.encode()` to function correctly. If, in the future, a new processor is added or an existing one is modified, and there is any discrepancy between these values, it can lead to wonky non-crashing behavior, such as truncating the wrong number of characters.

Therefore, there should be a check that these values are in fact the same, which I have implemented in PR #1312

**Comment by boyleconnor** [comment]
I'm tagging @ArthurZucker to review this because that is who is indicated in Transformers' [`CONTRIBUTING.md`](https://github.com/huggingface/transformers/blob/d533465150532b0c5de167b574e59f64c68b1154/.github/ISSUE_TEMPLATE/bug-report.yml)

**Comment by ArthurZucker** [comment]
Woops sorry I'll have a look
