### ISSUE TITLE
Breaking changes in a minor version update.

### ISSUE THREAD

**Issue by jafioti** [huggingface/tokenizers#1323]
The most recent version release on crates.io (0.13.4) changes the public facing api to accept a slice instead of a vec, and it was release with only a minor version bump. Now all crates that use tokenizers as a dependency and don't force a minor version get semver'ed up to this release and break. Please yank the release and change a major version

**Comment by Narsil** [comment]
Sorry I don't have the bandwidth to do this.

It should be a simple fix anyway.

But duly noted, I'm sorry I overlooked that breaking change. I used to look mostly at the python layer for breaking change, but more and more users are actually using the Rust layer now.
I'll work on making not happening again.
