### ISSUE TITLE
Having problem with loading pretrained tokenizer.

### ISSUE THREAD

**Issue by bkhanal-11** [huggingface/tokenizers#1325]
Thank you for the awesome work.

I am currently trying to train Roberta on Nepali text. However I came across following issue while trying to train tokenizer for Roberta.

Training part:
```python
from tokenizers import ByteLevelBPETokenizer

# Initialize a tokenizer
tokenizer = ByteLevelBPETokenizer(lowercase=False, add_prefix_space=False)

vocab_size = 10000
min_frequency = 3
special_tokens=["<s>",
                "<pad>",
                "</s>",
                "<unk>",
                "<mask>",
                ]
# Customize training
tokenizer.train(files="nepali.txt", 
                vocab_size=vocab_size, 
                min_frequency=3,
                special_tokens=special_tokens,
                show_progress=True,
                )
                
#Save the Tokenizer to disk
tokenizer.save_model("roberta")
```

While trying to load this tokenizer as following:
```python
from transformers import RobertaTokenizer
# Create the tokenizer from a trained one
Rtokenizer = RobertaTokenizer.from_pretrained("roberta")
```

I am getting the following warning:
```bash
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertTokenizer'. 
The class this function is called from is 'RobertaTokenizer'.
```

What could be the issue here? I looked into multiple resources but was unable to find fitting solution.

**Comment by Narsil** [comment]
To load it you should do 

```
tokenizer.save("tokenizer.json")
tokenizer = Tokenizer.from_file("roberta/tokenizer.json")
```

`RobertaTokenizer` is a `transformers` object, if you want to use it, you're going to need to create the tokenizer with `transforemrs`
That or use the same `config.json` `tokenizer_config.json` and `special_tokens_map.json`iirc.
All those files are necessarily to link for `tokenizers` which knows only how to encode sentences, into semantic knowledge about some of those tokens (like EOS, BOS) to control the model appropriately,.

Closing pre-emptively feel free to reopen.
