### ISSUE TITLE
ByteLevelBPETokenizer ignores enable_padding, add_tokens, add_special tokens. Always same vocab.

### ISSUE THREAD

**Issue by Tenoke** [huggingface/tokenizers#133]
I made the mistake of using the tokenizers library with a ByteLevelBPETokenizer, which uses the 0th and 1st for '!' and '\' no matter what I do. Adding special tokens, enabling padding, adding tokens etc. all result in the exact same vocabulary.

I particularly want to reserve token 0 for padding and token 1 for masking, so I can start my training anew (after a while of wasted time). Is that possible without me manually editing the vocab?? Further, is the ByteLevelBPETokenizer currently WIP and something that shouldn't be used overall?

For the time being I've remapped the first 2 tokens in positions 0 and 1 to free them up. In case anyone with similar needs looks at this issue:
```
vocab = json.load(open('256bytebpe-vocab.json'))
vocab["!"] = 256
vocab["\""] = 257
json.dump(vocab, open('256bytebpe-res-vocab.json', 'w'))
```

**Comment by n1t0** [comment]
Hi @Tenoke. The special tokens are added to the vocabulary while training it. If you didn't add the special tokens during this step, unfortunately, adding them afterwards won't shift every original ids.

If you want to add some special tokens while training, it is actually really simple:
```python
from tokenizers import ByteLevelBPETokenizer

files = [ "./text-0.txt", "./text-1.txt" ]

tokenizer = ByteLevelBPETokenizer()
tokenizer.train(files, special_tokens=["<PAD>", "<MASK>"])

# If you want to save the trained vocabulary:
tokenizer.save("./", "custom")

print(tokenizer.token_to_id('<PAD>'))
```
The tokens are added in the order you provide them. So, if you try using this snippet, you'll see that it actually outputs `0`, as you would expect it.

**Comment by Tenoke** [comment]
Thanks, that helps for the future!

Though add_tokens,  add_special_tokens, enable_padding, disable_padding still don't seem to do anything. Without docs it is hard to distinguish which features are mocks and which work (e.g. add_special_token vs special_tokens key in .train like here)

Is there a way to add a token after training without fully-retraining and without editing the vocab file manually?

**Comment by n1t0** [comment]
There are no mocks, everything should work. 

- `add_tokens` adds the given tokens on top of the vocabulary. So it allocates ids starting from the end, and expect all previous ids to have been allocated contiguously.
- `add_special_tokens` just lets the tokenizer know about special tokens in its vocabulary, adding these if they don't already exist. These special tokens need to be handled differently so the tokenizer needs to know about them.
- `enable_padding` enables padding using the various options you give to it (cf https://github.com/huggingface/tokenizers/blob/master/bindings/python/tokenizers/__init__.pyi#L231-L249). As you will see in the doc, if you encode a batch, it will by default, pad to the longest sequence in the batch. If you want to pad to a given `max_length`, then you have to specify it.

If you want these tokens to have an id like `0`, you will have to train your vocabulary properly.

**Comment by Tenoke** [comment]
@n1t0 Did you actually test if it's working. I understand it should add them at the end. If it is working fine why is the vocab identical on save?

`!cat 256bytebpe-vocab.json`
> {"!":0,"\"":1,"#":2,"$":3,"%":4,"&":5,"'":6,"(":7,")":8,"*":9,"+":10,",":11,"-":12,".":13,"/":14,"0":15,"1":16,"2":17,"3":18,"4":19,"5":20,"6":21,"7":22,"8":23,"9":24,":":25,";":26,"<":27,"=":28,">":29,"?":30,"@":31,"A":32,"B":33,"C":34,"D":35,"E":36,"F":37,"G":38,"H":39,"I":40,"J":41,"K":42,"L":43,"M":44,"N":45,"O":46,"P":47,"Q":48,"R":49,"S":50,"T":51,"U":52,"V":53,"W":54,"X":55,"Y":56,"Z":57,"[":58,"\\":59,"]":60,"^":61,"_":62,"`":63,"a":64,"b":65,"c":66,"d":67,"e":68,"f":69,"g":70,"h":71,"i":72,"j":73,"k":74,"l":75,"m":76,"n":77,"o":78,"p":79,"q":80,"r":81,"s":82,"t":83,"u":84,"v":85,"w":86,"x":87,"y":88,"z":89,"{":90,"|":91,"}":92,"~":93,"¡":94,"¢":95,"£":96,"¤":97,"¥":98,"¦":99,"§":100,"¨":101,"©":102,"ª":103,"«":104,"¬":105,"®":106,"¯":107,"°":108,"±":109,"²":110,"³":111,"´":112,"µ":113,"¶":114,"·":115,"¸":116,"¹":117,"º":118,"»":119,"¼":120,"½":121,"¾":122,"¿":123,"À":124,"Á":125,"Â":126,"Ã":127,"Ä":128,"Å":129,"Æ":130,"Ç":131,"È":132,"É":133,"Ê":134,"Ë":135,"Ì":136,"Í":137,"Î":138,"Ï":139,"Ð":140,"Ñ":141,"Ò":142,"Ó":143,"Ô":144,"Õ":145,"Ö":146,"×":147,"Ø":148,"Ù":149,"Ú":150,"Û":151,"Ü":152,"Ý":153,"Þ":154,"ß":155,"à":156,"á":157,"â":158,"ã":159,"ä":160,"å":161,"æ":162,"ç":163,"è":164,"é":165,"ê":166,"ë":167,"ì":168,"í":169,"î":170,"ï":171,"ð":172,"ñ":173,"ò":174,"ó":175,"ô":176,"õ":177,"ö":178,"÷":179,"ø":180,"ù":181,"ú":182,"û":183,"ü":184,"ý":185,"þ":186,"ÿ":187,"Ā":188,"ā":189,"Ă":190,"ă":191,"Ą":192,"ą":193,"Ć":194,"ć":195,"Ĉ":196,"ĉ":197,"Ċ":198,"ċ":199,"Č":200,"č":201,"Ď":202,"ď":203,"Đ":204,"đ":205,"Ē":206,"ē":207,"Ĕ":208,"ĕ":209,"Ė":210,"ė":211,"Ę":212,"ę":213,"Ě":214,"ě":215,"Ĝ":216,"ĝ":217,"Ğ":218,"ğ":219,"Ġ":220,"ġ":221,"Ģ":222,"ģ":223,"Ĥ":224,"ĥ":225,"Ħ":226,"ħ":227,"Ĩ":228,"ĩ":229,"Ī":230,"ī":231,"Ĭ":232,"ĭ":233,"Į":234,"į":235,"İ":236,"ı":237,"Ĳ":238,"ĳ":239,"Ĵ":240,"ĵ":241,"Ķ":242,"ķ":243,"ĸ":244,"Ĺ":245,"ĺ":246,"Ļ":247,"ļ":248,"Ľ":249,"ľ":250,"Ŀ":251,"ŀ":252,"Ł":253,"ł":254,"Ń":255}

`tokenizer = ByteLevelBPETokenizer('256bytebpe-vocab.json', '256bytebpe-merges.txt')
`
```
tokenizer.add_tokens(['test'])
tokenizer.save('.', 'test')
```

`!cat test-vocab.json`
>{"!":0,"\"":1,"#":2,"$":3,"%":4,"&":5,"'":6,"(":7,")":8,"*":9,"+":10,",":11,"-":12,".":13,"/":14,"0":15,"1":16,"2":17,"3":18,"4":19,"5":20,"6":21,"7":22,"8":23,"9":24,":":25,";":26,"<":27,"=":28,">":29,"?":30,"@":31,"A":32,"B":33,"C":34,"D":35,"E":36,"F":37,"G":38,"H":39,"I":40,"J":41,"K":42,"L":43,"M":44,"N":45,"O":46,"P":47,"Q":48,"R":49,"S":50,"T":51,"U":52,"V":53,"W":54,"X":55,"Y":56,"Z":57,"[":58,"\\":59,"]":60,"^":61,"_":62,"`":63,"a":64,"b":65,"c":66,"d":67,"e":68,"f":69,"g":70,"h":71,"i":72,"j":73,"k":74,"l":75,"m":76,"n":77,"o":78,"p":79,"q":80,"r":81,"s":82,"t":83,"u":84,"v":85,"w":86,"x":87,"y":88,"z":89,"{":90,"|":91,"}":92,"~":93,"¡":94,"¢":95,"£":96,"¤":97,"¥":98,"¦":99,"§":100,"¨":101,"©":102,"ª":103,"«":104,"¬":105,"®":106,"¯":107,"°":108,"±":109,"²":110,"³":111,"´":112,"µ":113,"¶":114,"·":115,"¸":116,"¹":117,"º":118,"»":119,"¼":120,"½":121,"¾":122,"¿":123,"À":124,"Á":125,"Â":126,"Ã":127,"Ä":128,"Å":129,"Æ":130,"Ç":131,"È":132,"É":133,"Ê":134,"Ë":135,"Ì":136,"Í":137,"Î":138,"Ï":139,"Ð":140,"Ñ":141,"Ò":142,"Ó":143,"Ô":144,"Õ":145,"Ö":146,"×":147,"Ø":148,"Ù":149,"Ú":150,"Û":151,"Ü":152,"Ý":153,"Þ":154,"ß":155,"à":156,"á":157,"â":158,"ã":159,"ä":160,"å":161,"æ":162,"ç":163,"è":164,"é":165,"ê":166,"ë":167,"ì":168,"í":169,"î":170,"ï":171,"ð":172,"ñ":173,"ò":174,"ó":175,"ô":176,"õ":177,"ö":178,"÷":179,"ø":180,"ù":181,"ú":182,"û":183,"ü":184,"ý":185,"þ":186,"ÿ":187,"Ā":188,"ā":189,"Ă":190,"ă":191,"Ą":192,"ą":193,"Ć":194,"ć":195,"Ĉ":196,"ĉ":197,"Ċ":198,"ċ":199,"Č":200,"č":201,"Ď":202,"ď":203,"Đ":204,"đ":205,"Ē":206,"ē":207,"Ĕ":208,"ĕ":209,"Ė":210,"ė":211,"Ę":212,"ę":213,"Ě":214,"ě":215,"Ĝ":216,"ĝ":217,"Ğ":218,"ğ":219,"Ġ":220,"ġ":221,"Ģ":222,"ģ":223,"Ĥ":224,"ĥ":225,"Ħ":226,"ħ":227,"Ĩ":228,"ĩ":229,"Ī":230,"ī":231,"Ĭ":232,"ĭ":233,"Į":234,"į":235,"İ":236,"ı":237,"Ĳ":238,"ĳ":239,"Ĵ":240,"ĵ":241,"Ķ":242,"ķ":243,"ĸ":244,"Ĺ":245,"ĺ":246,"Ļ":247,"ļ":248,"Ľ":249,"ľ":250,"Ŀ":251,"ŀ":252,"Ł":253,"ł":254,"Ń":255}

```
tokenizer.add_special_tokens(['test'])
tokenizer.save('.', 'test')
```
`!cat test-vocab.json`

> {"!":0,"\"":1,"#":2,"$":3,"%":4,"&":5,"'":6,"(":7,")":8,"*":9,"+":10,",":11,"-":12,".":13,"/":14,"0":15,"1":16,"2":17,"3":18,"4":19,"5":20,"6":21,"7":22,"8":23,"9":24,":":25,";":26,"<":27,"=":28,">":29,"?":30,"@":31,"A":32,"B":33,"C":34,"D":35,"E":36,"F":37,"G":38,"H":39,"I":40,"J":41,"K":42,"L":43,"M":44,"N":45,"O":46,"P":47,"Q":48,"R":49,"S":50,"T":51,"U":52,"V":53,"W":54,"X":55,"Y":56,"Z":57,"[":58,"\\":59,"]":60,"^":61,"_":62,"`":63,"a":64,"b":65,"c":66,"d":67,"e":68,"f":69,"g":70,"h":71,"i":72,"j":73,"k":74,"l":75,"m":76,"n":77,"o":78,"p":79,"q":80,"r":81,"s":82,"t":83,"u":84,"v":85,"w":86,"x":87,"y":88,"z":89,"{":90,"|":91,"}":92,"~":93,"¡":94,"¢":95,"£":96,"¤":97,"¥":98,"¦":99,"§":100,"¨":101,"©":102,"ª":103,"«":104,"¬":105,"®":106,"¯":107,"°":108,"±":109,"²":110,"³":111,"´":112,"µ":113,"¶":114,"·":115,"¸":116,"¹":117,"º":118,"»":119,"¼":120,"½":121,"¾":122,"¿":123,"À":124,"Á":125,"Â":126,"Ã":127,"Ä":128,"Å":129,"Æ":130,"Ç":131,"È":132,"É":133,"Ê":134,"Ë":135,"Ì":136,"Í":137,"Î":138,"Ï":139,"Ð":140,"Ñ":141,"Ò":142,"Ó":143,"Ô":144,"Õ":145,"Ö":146,"×":147,"Ø":148,"Ù":149,"Ú":150,"Û":151,"Ü":152,"Ý":153,"Þ":154,"ß":155,"à":156,"á":157,"â":158,"ã":159,"ä":160,"å":161,"æ":162,"ç":163,"è":164,"é":165,"ê":166,"ë":167,"ì":168,"í":169,"î":170,"ï":171,"ð":172,"ñ":173,"ò":174,"ó":175,"ô":176,"õ":177,"ö":178,"÷":179,"ø":180,"ù":181,"ú":182,"û":183,"ü":184,"ý":185,"þ":186,"ÿ":187,"Ā":188,"ā":189,"Ă":190,"ă":191,"Ą":192,"ą":193,"Ć":194,"ć":195,"Ĉ":196,"ĉ":197,"Ċ":198,"ċ":199,"Č":200,"č":201,"Ď":202,"ď":203,"Đ":204,"đ":205,"Ē":206,"ē":207,"Ĕ":208,"ĕ":209,"Ė":210,"ė":211,"Ę":212,"ę":213,"Ě":214,"ě":215,"Ĝ":216,"ĝ":217,"Ğ":218,"ğ":219,"Ġ":220,"ġ":221,"Ģ":222,"ģ":223,"Ĥ":224,"ĥ":225,"Ħ":226,"ħ":227,"Ĩ":228,"ĩ":229,"Ī":230,"ī":231,"Ĭ":232,"ĭ":233,"Į":234,"į":235,"İ":236,"ı":237,"Ĳ":238,"ĳ":239,"Ĵ":240,"ĵ":241,"Ķ":242,"ķ":243,"ĸ":244,"Ĺ":245,"ĺ":246,"Ļ":247,"ļ":248,"Ľ":249,"ľ":250,"Ŀ":251,"ŀ":252,"Ł":253,"ł":254,"Ń":255}

**Comment by n1t0** [comment]
The vocabulary files are generated during the training. They won't ever get modified after that. So if you add tokens, they get added to the Tokenizer, but they won't be saved. This is not a choice but related to the way BPE works. If you want to understand exactly why we can't, I invite you to read more about the BPE algorithm.

You can try the following to check that a token gets added:
```
print(tokenizer.encode('mylongunknowntoken').tokens)
tokenizer.add_tokens([ 'mylongunknowntoken' ])
print(tokenizer.encode('mylongunknowntoken').tokens)
```

The same will apply to your special tokens.

**Comment by Tenoke** [comment]
You should be able to add a padding token (in the sense of reserving that id), there's no real reason to be unable to. It obviously works if I manually change the vocab file, and obviously works if you manually pass special_tokens to train, as you showed.

At any rate, the methods in question *are* dummy methods for this tokenizer, as I said and don't do what you described beforehand. Why not remove them if you don't support them?

**Comment by Tenoke** [comment]
Also, your own example shows exactly what's broken here! 

```
print(tokenizer.encode('mylongunknowntoken').tokens)
tokenizer.add_tokens([ 'mylongunknowntoken' ])
print(tokenizer.encode('mylongunknowntoken').tokens)
tokenizer.save('.', 'test')
tokenizer = ByteLevelBPETokenizer('./test-vocab.json', './test-merges.txt')
print(tokenizer.encode('mylongunknowntoken').tokens)
```
>['m', 'y', 'l', 'o', 'n', 'g', 'u', 'n', 'k', 'n', 'o', 'w', 'n', 't', 'o', 'k', 'e', 'n']
['mylongunknowntoken']
['m', 'y', 'l', 'o', 'n', 'g', 'u', 'n', 'k', 'n', 'o', 'w', 'n', 't', 'o', 'k', 'e', 'n']

Are you telling me the 'the BPE Algorithm' makes it so you can only add tokens at runtime but never save the state of the tokenizer for future use? That you should manually add them every time instead of it being something carried through save and load?

**Comment by n1t0** [comment]
At the moment we only provide saving a `Model` (`BPE` or `WordPiece` for example). The saving of a `Tokenizer` has not been implemented yet (cf https://github.com/huggingface/tokenizers/issues/15).

I am trying to propose solutions to you with the current state of the library. Of course, being able to save everything would be better. I know there is a lack of documentation, and features, and so many other things that we need to work on. What I don't know is where I have been blaming you...

You wanted to add special tokens to your vocabulary. I provided you with multiple solutions:
 - You can re-train your vocabulary, adding the special tokens during this phase.
 - You can add `tokens`/`special tokens` on top of your existing vocabulary. Indeed you will have to do it every time you load the tokenizer for now.

Feel free to open another issue if you find a bug.

**Comment by Tenoke** [comment]
Thanks, the initial solution was indeed helpful. 
Nonetheless, I disagree with some of your comments which were clearly misleading and pushing the blame on things like the BPE algorithm instead of simply being upfront that the things I had a problem with are not fully implemented, which is of course perfectly fine.

**Comment by jbmaxwell** [comment]
Forgive me for jumping on this thread... I've been trying to use the tokenizer from the new "from scratch" training tutorial at huggingface.co, but I immediately hit the error: `Exception has occurred: ImportError
cannot import name 'ByteLevelBPETokenizer' from 'tokenizers' (/home/james/anaconda3/envs/torch/lib/python3.7/site-packages/tokenizers/__init__.py)`
This is a fresh install of transformers into a fresh environment. Any thoughts about what might be wrong?

**Comment by julien-c** [comment]
@jbmaxwell If you installed transformers in your virtual env, it currently pulls an older version of tokenizers. 

You can install the latest version tokenizers in a different venv, or just run 
```
pip uninstall tokenizers
pip install tokenizers==0.4.2
```

Alternatively, wait for the next release of transformers which will bump the dependency (also cc @mfuntowicz)

**Comment by jbmaxwell** [comment]
@julien-c Thanks so much, that's solved it!

**Comment by cahya-wirawan** [comment]
Sorry for writing again in this closed issue. I just have the same issue with Tenoke above where I forgot to add the special token "<|endoftext|>" when I trained the tokenizer. Since the tokenizer doesn't have this special token, my language model's pre-training crashed when a document/sentence has this token (the transformers.tokenizer knows it is a special token, but this token is  mapped to None).

I could train the tokenizer again from the beginning, but it takes around 150 minutes for 16GB dataset, and it already run using all 80 cpus. Therefore it would be great to have the possibility to read the pre-trained tokenizer, add new special tokens, and save it again without re-train again from the beginning, of course if it is feasible at all.

Thanks a lot for this great software BTW.

**Comment by Tenoke** [comment]
I'm really not sure why this is still not possible but I'd recommend just adding it manually to the vocab file.

**Comment by cahya-wirawan** [comment]
The other issue if I train the tokenizer again from the beginning is that the new special token I added "<|endoftext|>" is mapped to 0, and therefore will shift all other tokens. This makes the language model trained with the old tokenizer don't work properly anymore and need to be trained again from scratch using the new tokenizer. Maybe this can be avoided if I only map the new token "<|endoftext|>" to the end of the vocabulary without retraining the tokenizer.

**Comment by Tenoke** [comment]
Yes, that's exactly what I've done on the projects where I've used this library.

**Comment by n1t0** [comment]
@cahya-wirawan Maybe you can just do
```python
tokenizer.add_special_tokens([ "<|endoftext|>" ])
```
It should add it at the end of the vocabulary this way. Note that if you want to treat this token as a special token, you have to call this anyway, otherwise, the tokenizer doesn't know it is a special token and will try to tokenize it.

Also, using the `0.8.0` (rc version asof now, but soon to be released), the `tokenizer.save` method now saves the entire tokenizer, and not just the BPE as it was the case when this issue was raised by @Tenoke.

**Comment by cahya-wirawan** [comment]
Thanks all for the info and suggestion
