### ISSUE TITLE
Encoding emoji doesn't match with UTF-8 representation

### ISSUE THREAD

**Issue by Norawit29** [huggingface/tokenizers#1336]
I trained the tokenizer using ByteLevelBPETokenizer with tweets that include emojis. 

```
#### Initialize tokenizer
tokenizer = ByteLevelBPETokenizer()

#### Customize training
tokenizer.train(files=paths, vocab_size=52_000, min_frequency=2,
                show_progress=True,
                special_tokens=[
    "<s>",
    "<pad>",
    "</s>",
    "<unk>",
    "<mask>",
])

```
However, I have noticed that when I encode the emoji '😭,' I receive the result 'ðŁĺŃ.' Upon further investigation, I attempted to map these four symbols to their UTF-8 Hex representation. I found that it doesn't match with '\xF0\x9F\x98\xAD,' which is the correct UTF-8 representation of the crying emoji and some of those symbols are also not in the 256 unique chars.

Thanks

**Comment by ArthurZucker** [comment]
Did you try to set `unicode_normalizer` to `True`? when initializing the `tokenizer`? Think this could help

**Comment by Norawit29** [comment]
Thank you very much for your help. However, I ran into another error.
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In[7], line 8
>       5 paths = sample
>       7 # Initialize tokenizer
> ----> 8 tokenizer = ByteLevelBPETokenizer(unicode_normalizer=True)
>      10 # Customize training
>      11 tokenizer.train(files=paths, vocab_size=52_000, min_frequency=2,
>      12                 show_progress=True,
>      13                 special_tokens=[
>    (...)
>      18     "<mask>",
>      19 ])
> 
> File ~\anaconda3\envs\test_cuda\lib\site-packages\tokenizers\implementations\byte_level_bpe.py:45, in ByteLevelBPETokenizer.__init__(self, vocab, merges, add_prefix_space, lowercase, dropout, unicode_normalizer, continuing_subword_prefix, end_of_word_suffix, trim_offsets)
>      42 normalizers = []
>      44 if unicode_normalizer:
> ---> 45     normalizers += [unicode_normalizer_from_str(unicode_normalizer)]
>      47 if lowercase:
>      48     normalizers += [Lowercase()]
> 
> File ~\anaconda3\envs\test_cuda\lib\site-packages\tokenizers\normalizers\__init__.py:25, in unicode_normalizer_from_str(normalizer)
>      23 def unicode_normalizer_from_str(normalizer: str) -> Normalizer:
>      24     if normalizer not in NORMALIZERS:
> ---> 25         raise ValueError(
>      26             "{} is not a known unicode normalizer. Available are {}".format(normalizer, NORMALIZERS.keys())
>      27         )
>      29     return NORMALIZERS[normalizer]()
> 
> ValueError: True is not a known unicode normalizer. Available are dict_keys(['nfc', 'nfd', 'nfkc', 'nfkd'])
> 

I tried to set

> unicode_normalizer='nfkc' 

when initializing the tokenizer but also get the same result which was 'ðŁĺŃ.'

**Comment by ArthurZucker** [comment]
I would recommend also to make sure you are using the `byte_fallback` option when initialising the model.
