### ISSUE TITLE
Does train_new_from_iterator messes up the old_tokenizer ids? 

### ISSUE THREAD

**Issue by palash04** [huggingface/tokenizers#1337]
I want to train a new tokenizer for non-english language as well as english.
Say, I choose the base tokenizer as **gpt2**

old_tokenizer = AutoTokenizer.from_pretrained('gpt2')

Now, after doing the following, with my corpus just non-english
```
new_tokenizer = old_tokenizer.train_new_from_iterator(corpus, vocab_size=100000)
```
I see that the tokenization of english text from new_tokenizer has messed up compared to tokenization of english text from old_tokenizer.

Can't I leverage the state of tokenizer from old_tokenizer for english texts, and learn non-english texts in new_tokenizer?

2nd question:
train_new_from_iterator by default uses bpe or word piece or unigram algo?

@ArthurZucker

**Comment by ArthurZucker** [comment]
I don't think that the ids should be messed up, however the sampling might be different. This is because if you happen to see more words like `Hello` than `He` in your new corpus, then `_Hello` will have more chance of being split as `_Hello` than `_He` + `llo`. 
cc @Narsil
