### ISSUE TITLE
How are special chars like \u0120 (Ġ) being handled in tokenizer?

### ISSUE THREAD

**Issue by ekagra-ranjan** [huggingface/tokenizers#1340]
Hi! The GPT2 tokenizer converts leading space with \u0120 (Ġ) as [per this](https://github.com/openai/gpt-2/issues/80#issuecomment-487202159). It uses [this function](https://github.com/openai/gpt-2/blob/master/src/encoder.py#L9) to create a mapping from the character `space` (32 in unicode) -> `Ġ` (288 in unicode) after adding 256. 

The tokenizer mapping from token id to token would be containing chars like `Ġ` but when we use HF's `tokenizer.decode()` then it gives back the original space instead of `Ġ`. Can someone please point me to the code in [HF tokenizer](https://github.com/huggingface/tokenizers) which has this logic of converting `Ġ` back to `space`?

@n1t0 @Narsil @ArthurZucker

**Comment by ekagra-ranjan** [comment]
Thanks you for the answer! I will check it out and will definitely use forum next time 🤗

**Comment by go-ahead-maker** [comment]
@ekagra-ranjan hi,
I recently found the same issue when I used `onnxruntime-extensions` lib to export GPT2TokenizerFast HF tokenizer model.
when I test it in decode part, I found that `Ġ` is kept, but original hf tokenizer will handle it with space like:

original hf tokenizer output:
`['<|im_start|>User:<image>Can you describe this image?<end_of_utterance>\nAssistant:']`
onnx tokenizer output:
`'<|im_start|>User:<image>CanĠyouĠdescribeĠthisĠimage?<end_of_utterance>ĊAssistant:']`

have you find the logic about how to deal with Ġ and Ċ ?

**Comment by ArthurZucker** [comment]
cc @xenova

**Comment by xenova** [comment]
I imagine you're referring to https://github.com/microsoft/onnxruntime-extensions/blob/main/docs/custom_ops.md? :) Indeed, there seem to be many TODOs there, but if you want to handle them yourself, you should be able to do something similar to https://github.com/huggingface/transformers/blob/936aeb70abe14cfbc70fb4d4d0c7b1864a21cc54/src/transformers/models/gpt2/tokenization_gpt2.py#L37-L58

That's how you would convert back to the original string:
```py
bs = (list(range(ord("!"), ord("~") + 1)) + list(range(ord("¡"), ord("¬") + 1)) + list(range(ord("®"), ord("ÿ") + 1)))
cs = bs[:]
n = 0
for b in range(2**8):
    if b not in bs:
        bs.append(b)
        cs.append(2**8 + n)
        n += 1
cs = [chr(n) for n in cs]

unicode_to_bytes = dict(zip(cs, bs))

# Example
tokenizer_output = '<|im_start|>User:<image>CanĠyouĠdescribeĠthisĠimage?<end_of_utterance>ĊAssistant:'

# Final post-processing
final_output = ''.join([chr(unicode_to_bytes[x]) if x in unicode_to_bytes else x for x in tokenizer_output])
# '<|im_start|>User:<image>Can you describe this image?<end_of_utterance>\nAssistant:'
```
