### ISSUE TITLE
ByteLevelBPETokenizer: training duration of different  vocab sizes

### ISSUE THREAD

**Issue by Byshev333** [huggingface/tokenizers#1346]
Using ByteLevelBPETokenizer and the same 2GB data, the training durations are quite similar when training with different vocabulary sizes. Is this normal? （Machine configuration: 250 cores, 1000GiB memory）

Start training bbpe tokenizer...
Output File: bpe-bytelevel-2G-32k
vocab_size: 32000
--- 1087.87921500206 seconds ---

Start training bbpe tokenizer...
Output File: bpe-bytelevel-2G-64k
vocab_size: 64000
--- 1120.0059537887573 seconds ---

Start training bbpe tokenizer...
Output File: bpe-bytelevel-2G-80k
vocab_size: 80000
--- 1169.397242307663 seconds ---

Start training bbpe tokenizer...
Output File: bpe-bytelevel-2G-128k
vocab_size: 128000
--- 1238.1877241134644 seconds ---

Start training bbpe tokenizer...
Output File: bpe-bytelevel-2G-256k
vocab_size: 256000
--- 1374.4955639839172 seconds ---

**Comment by ArthurZucker** [comment]
I think this depends on the complexity + size of the dataset you are training on. Nothing really shocking to me here!
