### ISSUE TITLE
LNK1112 Error on Windows

### ISSUE THREAD

**Issue by Mansterteddy** [huggingface/tokenizers#135]
Hi,

I can build python binding on Ubuntu, however, when I want to build python binding on Windows, I always met this error: **_fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'_**, I have changed the toolchain from nightly to nightly-2019-11-01, but it doesn't work.
 Do you have any idea?

Best Wishes!

**Comment by n1t0** [comment]
What is your process to compile on windows? Did you run `cargo build`?

**Comment by Mansterteddy** [comment]
Thanks for your reply! On Windows, I run `cargo build` under tokenizers folder, it works well. But when I run `python setup.py install` under python folder, it outputs above error.

**Comment by mfuntowicz** [comment]
Hi @Mansterteddy , 

Do you observe the same error by running `pip install .` from the python folder ?

**Comment by Mansterteddy** [comment]
Hi @mfuntowicz ,

Thanks for your reply! Yes, I observe the same error:
**_fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'_**
**_error: cargo failed with code: 101_**

`pip install . `outputs another line:
**_ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly_**

Do you have any idea?

Best Wishes!

**Comment by n1t0** [comment]
I just got the same problem while trying to build for Python 32-bit on windows. I was able to fix it by making sure that both Python and the selected Rust toolchain matched:
- If you build for a python 32-bit version you should use rust `nightly-i686-pc-windows-msvc`.
- For python 64-bit you should use rust `nightly-x86_64-pc-windows-msvc`

Let me know how it goes!

**Comment by Mansterteddy** [comment]
It works, thanks a lot!
