### ISSUE TITLE
show_progress=True parameter of trainers.WordPieceTrainer does nothing & the Trainer does not support GPU

### ISSUE THREAD

**Issue by shivanraptor** [huggingface/tokenizers#1350]
I have the following codes:
```
tokenizer = Tokenizer(models.WordPiece(unk_token="[UNK]"))
special_tokens = ["[UNK]", "[PAD]", "[CLS]", "[SEP]", "[MASK]"]
trainer = trainers.WordPieceTrainer(vocab_size=2500, special_tokens=special_tokens, show_progress=True)
tokenizer.train_from_iterator(get_training_corpus(), trainer=trainer)
```
where `get_training_corpus()` is an iterator function for getting sentences from an Excel file.

The parameter `show_progress=True` does nothing. No progress is shown.

By the way, this `WordPieceTrainer` is unable to utilize GPU, as it does not support `TrainingArguments` or `device` parameter.

**Comment by Narsil** [comment]
> is unable to utilize GPU

Tokenizers never use the GPU.

Otherwise what you shared is not enough to be able to reproduce your issue therefore we cannot help you. I'm pretty sure your get_training_corpus is getting stuck getting the data somehow.

**Comment by shivanraptor** [comment]
I have made a minimal example in Google Colab:
https://colab.research.google.com/drive/12yMnNEwR6jyEdcg8nK17vgaU3vDMtl6H?usp=sharing

No progress is shown at all.

**Comment by shivanraptor** [comment]
Thanks for the update. May I know how can I use the updated `tokenizer`? wait for the next version?
