### ISSUE TITLE
Support for apply_chat_template

### ISSUE THREAD

**Issue by xfalcox** [huggingface/tokenizers#1351]
From my reading of the apply_chat_template function in transformers, the new chat template feature will be serialized and stored in the tokenizers file.

Will this library parse and expose it then?

**Comment by Narsil** [comment]
No. the chat template is a python only feature, which this library will not read or use.

At least for the time being, this space of prompting is evolving rather quickly right now.

**Comment by xfalcox** [comment]
Could it just parse it from the tokenizers file and make it readable for downstream consumers? No need for the `apply_chat_template`, which won't make sense. 

But exposing the raw template would be useful.
