### ISSUE TITLE
Different `encode` behavior between Python and Rust

### ISSUE THREAD

**Issue by clarkmcc** [huggingface/tokenizers#1354]
In Python I'm training a Tokenizer like this
```python
tokenizer = Tokenizer(BPE())
trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"])
tokenizer.pre_tokenizer = Sequence([
    CharDelimiterSplit(";"),
    Digits(individual_digits=True),
    WhitespaceSplit()
])
tokenizer.add_special_tokens([
    AddedToken(" ", lstrip=False, rstrip=False)
])
# .. train
```

And when I run

```python
tokenizer.encode("Foo bar")
```

I get (notice the space is preserved)
```
['F', 'oo', ' ', 'b', 'ar']
[39, 2081, 0, 64, 321]
```

But when I load this tokenizer up in Rust and run
```rust
tokenizer.encode("Foo bar", true)
```

I get (notice the white space is missing)
```
["F", "oo", "b", "ar"]
[39, 2081, 64, 321]
```

**Comment by ArthurZucker** [comment]
Hey, that's because adding the `' '` character is a very odd thing to do. 
If you load the tokenizer in rust you should try to check the `tokenizer.get_added_tokens_decoder()` to see if the token was properly addded or not. 
I can check if this is a bug or intended not to be supported!

**Comment by Narsil** [comment]
Can you provide the actual tokenizer file so we can take a look.

There shouldn't be any difference between the 2, but looking at your snipped, I suspect you're running the python version directly after training, which might mean it might be in a different state that what would be saved on disk.
That would definitely a bug, but I think a bit more likely than Rust being different from Python.

**Comment by clarkmcc** [comment]
@ArthurZucker I have an textual entity extractor and some of the entities are multi-word so spaces are critical. Is there a more idiomatic way to address that?

As requested, looks like the space isn't in here:

```
{
    3: AddedToken {
        content: "[PAD]",
        single_word: false,
        lstrip: false,
        rstrip: false,
        normalized: false,
        special: true,
    },
    4: AddedToken {
        content: "[MASK]",
        single_word: false,
        lstrip: false,
        rstrip: false,
        normalized: false,
        special: true,
    },
    2: AddedToken {
        content: "[SEP]",
        single_word: false,
        lstrip: false,
        rstrip: false,
        normalized: false,
        special: true,
    },
    1: AddedToken {
        content: "[CLS]",
        single_word: false,
        lstrip: false,
        rstrip: false,
        normalized: false,
        special: true,
    },
    0: AddedToken {
        content: "[UNK]",
        single_word: false,
        lstrip: false,
        rstrip: false,
        normalized: false,
        special: true,
    },
}
```

**Comment by clarkmcc** [comment]
@Narsil I've attached an example tokenizer that exhibits the behavior. I tested your hypothesis and it looks like the Python version exhibits the same behavior as the Rust version when loaded from the file.

```python
tokenizer = Tokenizer.from_file("example.json")
tokenizer.encode("foo bar").tokens
```

[example.json.zip](https://github.com/huggingface/tokenizers/files/12832414/example.json.zip)

**Comment by ArthurZucker** [comment]
Not sure the issue persist, after saving and loading both had the same outputs and we don't have access to the training script / the code you used so feel free to close it.

**Comment by clarkmcc** [comment]
Yeah, you wouldn't see the issue from the file. Wasn't this issue this: 
> I suspect you're running the python version directly after training, which might mean it might be in a different state that what would be saved on disk.
That would definitely a bug

**Comment by ArthurZucker** [comment]
Yes it would but I don't think the reproducer you shared is enough for this right? 😅

**Comment by clarkmcc** [comment]
The file can't be used to reproduce (since the bug is specifically related to not loading from a file), but the initial bug report has the code, and the tokenizer can even be recreated from the file. So there should be everything needed to resolve the issue.

Btw, not saying someone needs to fix this for me, just pointing out this is still an issue and (as far as I'm aware) everything is provided to reproduce. If the code snippets and/or tokenizer file are not sufficient, Im happy to send you whatever you need.

**Comment by ArthurZucker** [comment]
Thanks. I mean the way you trained it is missing, would help me reproduce if there is a full snippet 🤗
