### ISSUE TITLE
Difference between slow and fast GPT2 tokenizers

### ISSUE THREAD

**Issue by goerch** [huggingface/tokenizers#1363]
Please see this [comment](https://github.com/ggerganov/llama.cpp/issues/3502#issuecomment-1753847439) by @jploski.

**Comment by jploski** [comment]
> Hey! Could you share a full reproducer? Would help me a lot to have the output of `transformers-cli env` as well. 🤗

https://github.com/jploski/llama.cpp/tree/hf-issue-1363/tests/hf-issue-1363

(env output included in README.md)

**Comment by goerch** [comment]
This [comment](https://github.com/ggerganov/llama.cpp/issues/3502#issuecomment-1755852080) is explaining the problem. Not sure if I should close this then?

**Comment by ArthurZucker** [comment]
Probably yes! Unless the changes need to be propagated to the slow tokenizer?

**Comment by goerch** [comment]
Thanks!

**Comment by cebtenzzre** [comment]
Hm, as a transformers user I would normally assume that the slow and fast tokenizers are both correct. If only the fast tokenizer is correct, this should be documented somewhere.

**Comment by jploski** [comment]
> Hm, as a transformers user I would normally assume that the slow and fast tokenizers are both correct. If only the fast tokenizer is correct, this should be documented somewhere. (Maybe it is, and I'm just not aware.)

I agree, these differences in functionality are confusing and would deserve at least a mention in the documentation (https://huggingface.co/docs/transformers/main_classes/tokenizer). I note that for the *TokenizerFast even the tokenizer_file parameter is currently entirely undocumented.

**Comment by ArthurZucker** [comment]
We are trying to get the same results for fast and slow, but in this specific case Falcon used the GPT2TokenizerFast with a custom template processor. We can add a `FalconTokenizer` in transformers to be equivalent, but I believe the best we can do is:
- add support for template processing in transformers (using jinja?)
- update the documentation where you feel it's needed. 

Would any of you like to open a PR to update the documentation however you feel? You can ping me for  review 🤗
