### ISSUE TITLE
cannot install with yarn & missing module in npm

### ISSUE THREAD

**Issue by MaelAbgrall** [huggingface/tokenizers#1365]
Hello

I'm trying to use the node binding for tokenizers, and, as in the title, yarn fails to install the package.
with yarn 1
```
Error: Couldn't find package "tokenizers-darwin-arm64@0.13.3" required by "tokenizers@latest" on the "npm" registry.
Error: Couldn't find package "tokenizers-win32-ia32-msvc@0.13.3" required by "tokenizers@latest" on the "npm" registry.
```

with yarn 3
```bash
➤ YN0000: ┌ Resolution step
➤ YN0035: │ tokenizers-android-arm-eabi@npm:0.13.3: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/tokenizers-android-arm-eabi
➤ YN0000: └ Completed in 2s 274ms
➤ YN0000: Failed with errors in 2s 277ms
```

Similarly, I tried to install it with npm, but then I'm getting the following error while running my code:
```Error: Cannot find module 'tokenizers-linux-x64-gnu'```

Can someone help?

thanks

**Comment by berrazuriz1** [comment]
Did you fix it?

**Comment by MaelAbgrall** [comment]
nope, I gave up

**Comment by ArthurZucker** [comment]
cc @Narsil I have no idea about this one 😅

**Comment by Narsil** [comment]
Oh we didn't release anything on NPM since the move the napi-rs because it changed the whole release cycle.

```
cd bindings/node
yarn build
```

Should already be something to workaround it.

@ArthurZucker Do you want to mess with node builds ? :) 
I'd like to find the time for it tbh.
