### ISSUE TITLE
Can not load tokoenizer from_pretrained through http_proxy since 0.14.0

### ISSUE THREAD

**Issue by jtsai-quid** [huggingface/tokenizers#1373]
Hi hf,

I encountered an issue where I couldn't load the tokenizer using from_pretrained via the http_proxy in version 0.14.0, while it worked successfully in version 0.13.3.
This caused the fast tokenizer initialization issue in TGI 1.1.0.
https://github.com/huggingface/text-generation-inference/issues/1108

Here is the code snippet that I use to test for testing.

```rust
//# tokenizers = { version = "0.14.0", features = ["http"] }

use tokenizers::tokenizer::{Result, Tokenizer};
use tokenizers::{FromPretrainedParameters};

fn main() -> Result<()> {
        let authorization_token = std::env::var("HUGGING_FACE_HUB_TOKEN").ok();
        let params = FromPretrainedParameters {
            revision: None.clone().unwrap_or("main".to_string()),
            auth_token: authorization_token.clone(),
            ..Default::default()
        };

        let tokenizer = Tokenizer::from_pretrained("TheBloke/Llama-2-13B-chat-GPTQ", Some(params))?;

        let encoding = tokenizer.encode("Hey there!", false)?;
        println!("{:?}", encoding.get_tokens());
    Ok(())
}
```
Error output
```
> http_proxy=http://squid:3128 https_proxy=http://squid:3128 cargo play run.rs
   Compiling p4u7iybabtwyzvxf2zdtkustjgod2 v0.1.0 (/tmp/cargo-play.4U7iybABTwyZVxF2ZDTKUstjgod2)
    Finished dev [unoptimized + debuginfo] target(s) in 3.14s
     Running `/tmp/cargo-play.4U7iybABTwyZVxF2ZDTKUstjgod2/target/debug/p4u7iybabtwyzvxf2zdtkustjgod2`
Error: RequestError(Transport(Transport { kind: Io, message: None, url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("huggingface.co")), port: None, path: "/TheBloke/Llama-2-13B-chat-GPTQ/resolve/main/tokenizer.json", query: None, fragment: None }), source: Some(Custom { kind: TimedOut, error: "timed out reading response" }) }))
```
 
I suspect that this is related to the client refactoring in [here](https://github.com/huggingface/tokenizers/blame/v0.14.0/tokenizers/src/utils/from_pretrained.rs#L62-L69)

Thanks and appreciate for any help from you!

**Comment by ArthurZucker** [comment]
Indeed. Could you try with the latest release? Otherwise I'll have look at what I can do!

**Comment by jtsai-quid** [comment]
Just try the version `0.14.1` and the error still occurs. 😞

**Comment by jtsai-quid** [comment]
hi @ArthurZucker ,
Would this PR fix this issue? 
https://github.com/huggingface/hf-hub/pull/34

**Comment by ArthurZucker** [comment]
Ah! Yeah most probably because now we use the hf-hub api to load files, so if proxy is an issue there, will affect us.
