### ISSUE TITLE
add_tokens has no effect in llama fast tokenizer

### ISSUE THREAD

**Issue by tiandiweizun** [huggingface/tokenizers#1374]
tokenizer=AutoTokenizer.from_pretrained("d:/models/Llama-2-7b-chat-hf")
print(model.tokenize("你是谁"))   //  ['▁', '你', '是', '<0xE8>', '<0xB0>', '<0x81>']
model.add_tokens("谁")
print(model.tokenize("你是谁"))  // ['▁', '你', '是', '<0xE8>', '<0xB0>', '<0x81>'] 

when load in slow mode，it is ok。   // AutoTokenizer.from_pretrained("d:/models/Llama-2-7b-chat-hf", use_fast=False )

**Comment by ArthurZucker** [comment]
Hey, you should add the token using `tokenizer.add_tokens(AddedToken("谁", normalized = False))` should do the trick 😉 You can now check the content of the added tokens using `tokenizer.added_tokens_decoder`

**Comment by ArthurZucker** [comment]
This is probably because of `normalized=False` for that token! If the normalizer is a replace

**Comment by GradientGuru** [comment]
> This is probably because of `normalized=False` for that token! If the normalizer is a replace

Hi ArthurZ, thanks for you reply.

I find that the problem happens even before save_pretrained() creating a tokenizer.json file. Allow me to rephrase the problem again:

My directory is:

my_tokenizer--
        |-- tokenizer.model
        |-- tokenizer_config.json

tokenizer.model is a sentencepiece BPE trained model, "▁\n" is a type=4 user defined symbol in it. 
By the way, "\n" is also a type=4 (user defined token), "▁" is a type=1 (NORMAL) token with very low score.

when I tokenize " \n" (a space before \n):
A: spm.SentencePieceProcessor().Load("my_tokenizer/tokenizer.model") will tokenize as  ["▁\n"] (which is correct)
B: tokenizer = AutoTokenizer.from_pretrained("my_tokenizer")  will tokenize as ["▁\n"] (which is correct)
C: tokenizer = LlamaTokenizerFast.from_pretrained("my_tokenizer") will tokenize as ["▁", "\n"],  (which is wrong)

when I tokenize "▁\n" ("▁" itself but not a real space before \n):
all three tokenizers will tokenize as ["▁\n"] (which is correct)

It seems 99.9% difference are happens on user defined tokens starting with "▁". There is no problem for NORMAL (type=1) tokens starting with ▁ .

The question is:
1. How to make LlamaTokenizerFast behave same as sentencepiece?
2. If there is no solution to 1, is there another way I can transforms the tokenizer.model into a tokenizer.json, such that I can use fast Tokenizer next time?
