### ISSUE TITLE
Error: Cannot find module 'tokenizers-linux-x64-musl'

### ISSUE THREAD

**Issue by Madnex** [huggingface/tokenizers#1384]
Hi! I get the following error when I try to load the tokenizers: `Error: Cannot find module '@anush008/tokenizers-linux-x64-musl'`. I am using a docker container with node:18-alpine. 

I peeked at the [index.js ](https://github.com/huggingface/tokenizers/blob/main/bindings/node/index.js)file and saw that the `isMusl` check is for Node 10? What exactly is it checking? And why does the corresponding module not exist anymore?

See also the issue [here](https://github.com/Anush008/tokenizers/issues/1).

**Comment by ArthurZucker** [comment]
Not sure if the package was properly installed or not and would need a full traceback + reproducer otherwise

**Comment by madhurjya-acko** [comment]
@Madnex were you able to resolve this in your case? I am having the same issue.

**Comment by Madnex** [comment]
Sorry, no did not manage. And did not continue with that solution :/

**Comment by ArthurZucker** [comment]
@madhurjya-acko this should be fix I reckon depending on the version of tokenizers you are installing + the version of python you have

**Comment by PylotLight** [comment]
@ArthurZucker Nope still getting this issue with fastembed-js using tokenizers. 
Still getting glibc/musl errors on Alpine for this one. 
Do I create a new issue, or can we reopen this one?

**Comment by flancast90** [comment]
Getting the same issue here in fastembed-js
