### ISSUE TITLE
is there a javascript version for tokenizers

### ISSUE THREAD

**Issue by Zwe1** [huggingface/tokenizers#1387]
we want to count token length of user inputs in web runtime, so it's important for us to provide a javascript version for tokenizers, typescript will be better. All my sincerely thanks for supporting~

**Comment by ArthurZucker** [comment]
The [`tokenizer.js`](https://github.com/xenova/transformers.js) library should be of interest to you! Also part of the 🤗 ecosystem. Tokenization implemented [here](https://github.com/xenova/transformers.js/blob/main/src/tokenizers.js)
