### ISSUE TITLE
Get length of encoding object

### ISSUE THREAD

**Issue by tomhosking** [huggingface/tokenizers#139]
What's a good way to get the length of an `Encoding` object? Neither of the following intuitive methods work:

```
from tokenizers import BertWordPieceTokenizer

tok = BertWordPieceTokenizer('./data/bert-vocabs/bert-base-cased-vocab.txt')

output = tok.encode('This is a sentence')
>> Encoding(num_tokens=6, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing, original_str, normalized_str])

output.num_tokens
>> AttributeError: 'Encoding' object has no attribute 'num_tokens'

len(output)
>> TypeError: object of type 'Encoding' has no len()
```

**Comment by julien-c** [comment]
What do you mean by length of an `Encoding`? The number of tokens?

**Comment by tomhosking** [comment]
Sorry, yes - the number of tokens. It's shown in the string representation as `num_tokens` but isn't an attribute of the `Encoding` object. I can do `len(output.tokens)` but this isn't as pythonic as I would have expected.

**Comment by n1t0** [comment]
Thank you @tomhosking for suggesting this. We added the `__len__` implementation on the `Encoding` object in d8a73c89a70bc50e140aed131a8986a6ce9c11a5. It will be included in the next release!
