### ISSUE TITLE
added_tokens with bytemap charaters in ByteLevel could not be decoded correctly

### ISSUE THREAD

**Issue by DOGEwbx** [huggingface/tokenizers#1392]
I just found that if added tokens contain some characters that exist in the byte map for ByteLevel preprocessor could not be decoded correctly.
This is a script to reproduce the problem with version 0.14.1
```python
from tokenizers import Tokenizer
from tokenizers import normalizers
from tokenizers.pre_tokenizers import (
    ByteLevel,
)
from tokenizers.models import BPE
from tokenizers import decoders
tokenizer = Tokenizer(BPE())
tokenizer.normalizer = normalizers.Sequence([])

tokenizer.pre_tokenizer = Sequence(
    [
        ByteLevel(add_prefix_space=False, use_regex=False),
    ])
tokenizer.add_tokens(["ilÖveyou"])
# Ö is the character representing for 0xf6
tokenizer.decoder = decoders.ByteLevel()
encode_result = tokenizer.encode("ilÖveyou")
print(encode_result.ids)
print(tokenizer.decode(encode_result.ids))
```
the output wil be 
```
[0]
il�veyou
```

I believe the problem comes from 
https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/tokenizer/mod.rs#L832-L836
I don't think added token should be sent to bytelevel decoder for it is extacted before pretokenize.

**Comment by DOGEwbx** [comment]
is it possible to let added_tokens_map_r of AddedVocabulary store the mapping of id to tokens after pre-tokenization? so that it can generate the same output after decoder?

**Comment by ArthurZucker** [comment]
It's not possible no, normalizers are use for that purpose however. And you can also add the token like this:
Since the text is first splitted and normalized, and then pre_tokenized, adding the pre-tokenized version of the token to the `added_tokens_map_r` will still not work. 
In this case you could use a `StripAccents` normalizer to make sure accents are stripped, but this will also affect all the other tokens.

**Comment by DOGEwbx** [comment]
Ah I see. Thanks for your explaination. Is there any planning on solving this bug?

**Comment by ArthurZucker** [comment]
A pr for a fix that is backward compatible is welcome! Otherwise I won't have time to dive in this 🤗

**Comment by ArthurZucker** [comment]
https://github.com/meta-llama/llama3/issues/67#issuecomment-2072952721 TLDR this should help: 
```python3
>>> from tokenizers import AddedToken, pre_tokenizers
>>> from transformers import AutoTokenizer
>>> pre_tokenizers.ByteLevel(False,False).pre_tokenize_str("Bác")
[('BÃ¡c', (0, 3))]
>>> tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B")
>>> tokenizer.add_tokens(AddedToken("BÃ¡c", normalized=False,special=False))
>>> tokenizer.decode(tokenizer.encode("Bác"))
'<|begin_of_text|>Bác'
```

**Comment by ArthurZucker** [comment]
Re-opening as the merge on main will be reverted for a better fix soon
