### ISSUE TITLE
unable to install on python 3.12 via pip

### ISSUE THREAD

**Issue by binary-husky** [huggingface/tokenizers#1393]
Reproducing:

1. conda create -n py12 python=3.12
2. conda activate py12
3. pip install tokenizers
```
pip install tokenizers
Collecting tokenizers
  Using cached tokenizers-0.15.0.tar.gz (318 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


```

**Comment by ArthurZucker** [comment]
You need to have cargo installed because we did not push wheels for mac with py>3.10. @Narsil should we try go up to 3.11 / 3.12 or are we limited by the runners ?

**Comment by binary-husky** [comment]
> You need to have cargo installed because we did not push wheels for mac with py>3.10. @Narsil should we try go up to 3.11 / 3.12 or are we limited by the runners ?

No, I using x86 windows os, not mac. Additionally, I still cannot install tokenizers after `tokenizers`. (In python 3.11, everything is fine)

**Comment by ArthurZucker** [comment]
Sorry for the confusion. You have to [install rust](https://doc.rust-lang.org/book/ch01-01-installation.html#installing-rustup-on-windows), and probably not through pip. We compiled the wheels for python up to 3.11 not above

**Comment by Narsil** [comment]
@ArthurZucker Would you be up to do a patch release with adding 3.12 support ?

**Comment by ArthurZucker** [comment]
Sure, I'll work on this this week 😉

**Comment by Narsil** [comment]
> ELF load command past end of file

This means corrupted file, probably unfinished download or something along those lines, delete the folder a install again I think.

**Comment by ArthurZucker** [comment]
See #1406 that will try to release for windows x python 3.12

**Comment by ArthurZucker** [comment]
Christmas delays planning a release for tomorrow 🤗

**Comment by t5k6** [comment]
Another option is to install tokenizers through conda, that way you will not need to install Rust and cargo:
`conda install -c conda-forge tiktoken==0.4.0`

You would also need to install tokenizers though conda:
`conda install conda-forge::tokenizers`

**Comment by Tendo33** [comment]
Encountering the same error.
