### ISSUE TITLE
Use NodeJs:  Cannot find module 'tokenizers-darwin-arm64'

### ISSUE THREAD

**Issue by guotingchao** [huggingface/tokenizers#1403]
#### Step 1
After installing the tokenizers package with npm, I tried to call the test from the application class, and it returned the following message
```
Error: Cannot find module 'tokenizers-darwin-arm64'
```

#### Step 2
Then I tried to install this tokenizers-darwin-arm64 package
The result returns the following information
```
Couldn't find any versions for "tokenizers-darwin-x64" that matches "0.13.3"
? Please choose a version of "tokenizers-darwin-x64" from this list: (Use arrow keys)
```

#### Step 3
Then I chose any version of 0.13.4-rc2

```
Error: Couldn't find package "tokenizers-freebsd-x64@0.13.3" required by "tokenizers@^0.13.3" on the "npm" registry.
```

#### Question :

*Does it support MacOs with the M system-on-chip?*

**Comment by ArthurZucker** [comment]
Not sure we release new packages for npm recently

**Comment by EasyVector** [comment]
for any one trying to solve this issue, this script might be helpful, you could save this shell script into your project as "postinstall.sh"
```shell
DIR="tokenizer_folder"
if [ -d "$DIR" ]; then
  # Take action if $DIR exists. #
  echo "${DIR} EXISTS"
else
  echo "${DIR} not exists, try to clone"
  git clone https://github.com/huggingface/tokenizers tokenizer_folder --depth 1
fi

# try to find node
find_node_file() {
  local PATH_TO_SEARCH=$1
  local NODE_FILE=$(find "$PATH_TO_SEARCH" -name '*.node' -depth 1)
  if [[ -n "$NODE_FILE" ]]; then
    echo "$NODE_FILE"
  else
    echo "'.node' not found"
  fi
}

# Save to variable
FOUND_NODE_FILE=$(find_node_file tokenizer_folder/bindings/node)
if [ ! -n "$FOUND_NODE_FILE" ]; then
  cd tokenizer_folder/bindings/node
  npm i
  yarn
  yarn build
  cd ../../../
fi

FOUND_NODE_FILE=$(find_node_file tokenizer_folder/bindings/node)
if [ -n "$FOUND_NODE_FILE" ]; then
  echo "$FOUND_NODE_FILE"
  cp "$FOUND_NODE_FILE" node_modules/tokenizers
fi

```

then add this into your package.json
```
...
  "scripts": {
    "postinstall": "sh postinstall.sh",
  },
...
```

then re run `npm i`, the binding file will be built & copied to project, and the error could be gone.

**Comment by aaronclong** [comment]
@ArthurZucker do you think a new build would fix this?

**Comment by aaronclong** [comment]
I think I found the issue, but please let me know if I am off base. The `package.json` 's `files` property seems to be missing all the binaries's names in it. I made a small pr to address this and some CI/CD necessary upgrades.
https://github.com/huggingface/tokenizers/pull/1459

**Comment by loretoparisi** [comment]
> ```shell
> # rust should be installed
> if command -v rustc >/dev/null 2>&1; then
>     echo "Rust is installed."
> else
>     echo "Rust is not installed."
>     echo "Please install Rust from https://www.rust-lang.org/learn/get-started."
>     exit 1
> fi
> ```

Thanks @EasyVector this seems a solution, but aftering successfully building I get a a runtime error

```
/.../node_modules/tokenizers:1
����
SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
```

This happens when loading the bindings in node like

```javascript
const { SentencePieceBPETokenizer, BertWordPieceTokenizer, ByteLevelBPETokenizer, BPETokenizer } = require("tokenizers");
```

**Comment by unlucio** [comment]
just installed this node package and I got the same error.

`npm install tokenizers@latest`

but I got version 0.13.3, while[ the one in this package.json](https://github.com/huggingface/tokenizers/blob/main/bindings/node/package.json) is "0.15.3-dev0", and yet the repos tags go up to v0.21.0 😵‍💫

I'm a bit confused.

**Comment by tangkunyin** [comment]
@unlucio Maybe you can use [turingscript/tokenizers](https://github.com/turingscript/tokenizers) or choose another way...

This official lib seems doesn't support node well 🤷‍♂️

**Comment by julien-c** [comment]
we'd love to improve Node support in this library
