### ISSUE TITLE
Tokenizer **not saving/loading** correctly after adding tokens, then training

### ISSUE THREAD

**Issue by dinhanhx** [huggingface/tokenizers#1409]
## Background

Tokenizers version: 0.15.0

Kaggle notebook: https://www.kaggle.com/code/inhanhv/tokenizer-not-saving-right?scriptVersionId=154123882

## An empty tokenizer

Firstly, I initialize an empty tokenizer, but with some special tokens and some tokens (byte_fallback tokens in this case). 

```python
from tokenizers import Tokenizer
from tokenizers import decoders, pre_tokenizers
from tokenizers.models import BPE
from tokenizers.processors import TemplateProcessing
from tokenizers.trainers import BpeTrainer
from tokenizers import AddedToken

from datasets import load_dataset

dataset = load_dataset("tapaco")

def topaco_generator():
    for i in dataset['train']:
        yield i['paraphrase']

bpe_trainer = BpeTrainer()

tokenizer = Tokenizer(BPE(byte_fallback=True))

tokenizer.add_special_tokens(["<unk>", "<s>", "</s>", "<pad>"])
tokenizer.add_tokens([AddedToken(content=f"<0x{i:02X}>", single_word=False, normalized=False, special=False) for i in range(256)])

tokenizer.pre_tokenizer = pre_tokenizers.Sequence(
    [pre_tokenizers.Metaspace(), pre_tokenizers.Digits(individual_digits=True)]
)
tokenizer.enable_padding(pad_id=3, pad_token="<pad>")
tokenizer.post_processor = TemplateProcessing(
    single="<s> $A </s>",
    pair="<s> $A </s> $B </s>",
    special_tokens=[
        ("<s>", 1),
        ("</s>", 2),
    ],
)
tokenizer.decoder = decoders.Sequence(
    [
        decoders.Metaspace(),
        decoders.ByteFallback(),
    ]
)
```

At this point, if you print out `print(tokenizer.get_added_tokens_decoder())`. You notice that special tokens' and added tokens' indices go from 0 to 259. This is expected behaviour. 

## Training the tokenizer

Secondly, I train the tokenizer. Then I print out the added tokens again, the expected behaviour happens again. 

```python
tokenizer.train_from_iterator(topaco_generator(), trainer=bpe_trainer)
print(tokenizer.get_added_tokens_decoder())
```

## Saving then loading the tokenizer

Finally, I save the tokenizer then load it, 

```python
tokenizer.save("topaco_tokenizer.json")
del tokenizer
tokenizer = Tokenizer.from_file("topaco_tokenizer.json")
print(tokenizer.get_added_tokens_decoder())
```

At this point, special tokens' and added tokens' indices are different compared to before saving.

**Comment by ArthurZucker** [comment]
Might actually be the same as #1354

**Comment by dinhanhx** [comment]
After inspecting json file produced by `tokenizer.save("topaco_tokenizer.json")`, I think there is something unusual with `tokenizer = Tokenizer.from_file("topaco_tokenizer.json")`. `added_tokens` is added after the vocab.

**Comment by ArthurZucker** [comment]
That is expected, if they are not part of the vocab they are added after, at the end. If you want them at the beginning you gotta add them before, in the normal vocab not the added vocab.

**Comment by dinhanhx** [comment]
Shouldn't the saving function preserve the order as the way before it saves tokenizers?  

> If you want them at the beginning you gotta add them before, in the normal vocab not the added vocab.

So how should I load my json file to do so? Can you provide code example? I'm still bit confused.

**Comment by ArthurZucker** [comment]
Ok I'll re dive into this but it should not you are right

**Comment by ArthurZucker** [comment]
I'll add some code examples sorry

**Comment by ArthurZucker** [comment]
Ok, training does not support bytefallback (meaning the tokens should be added in the `Trainer` not before. That is pretty much what is messing the logic. Unless we allow for an initial vocabulary. 
If you'd like to open a PR feel free to do so! 🤗 
I'll try to find some bandwidth in the coming month
