### ISSUE TITLE
Support PyArrow arrays as tokenizer input

### ISSUE THREAD

**Issue by mariosasko** [huggingface/tokenizers#1415]
Most data processing libraries (Datasets, Polars, Pandas, DuckDB, etc.) are integrated with PyArrow, so native (zero-copy if possible) support for PyArrow arrays as input to avoid the unnecessary PyArrow to Python/NumPy conversion (pretty slow for string arrays) would be nice.
 
PS: PyArrow has recently added support for the PyCapsule interface, which should help with the implementation.

**Comment by ArthurZucker** [comment]
Would you like to open a PR for this? 🤗

**Comment by mariosasko** [comment]
Marking this issue as a good first issue. If it doesn't get addressed after a while, I'll take a stab at it.

**Comment by WenheLI** [comment]
Interested in this. Can someone get it assigned to me?

**Comment by mariosasko** [comment]
@WenheLI  Assigned :)

**Comment by mariosasko** [comment]
Sure! The idea is to use the [`arrow`](https://crates.io/crates/arrow) crate (e.g., with `ArrayData.from_pyarrow`) to decode PyArrow `StringArray`/`LargeStringArray`s (when they are given as input to the `Tokenizer`). You can find the relevant code [here](https://github.com/huggingface/tokenizers/blob/main/bindings/python/src/tokenizer.rs) (maybe [this PR](https://github.com/huggingface/tokenizers/pull/379) can also help, which has done the same thing for NumPy arrays).

To build the project, check this [workflow file](https://github.com/huggingface/tokenizers/blob/main/.github/workflows/python.yml), in particular the [part](https://github.com/huggingface/tokenizers/blob/main/.github/workflows/python.yml#L104) that installs the dependencies.

**Comment by shreya-51** [comment]
hello! @WenheLI are you still working on this?

**Comment by WenheLI** [comment]
@shreya-51 - Hi! Sorry for the late reply. And yes, I am still working on that

**Comment by phot-ai-lab** [comment]
@mariosasko can you please take a look at this?

**Comment by granthamtaylor** [comment]
Hi folks. I would like to take a stab at this.

I came across this problem while working on [relflow](https://github.com/relflow/relflow) ... I am trying to embed tens of thousands of small strings that are already formatted in Arrow. I have some performance sensitive use cases and the materialization of nested python objects has been bothering me.

Can someone assign ?

**Comment by granthamtaylor** [comment]
@ArthurZucker I apologize in advance if this is overreaching. I am but a humble end user eager for a resolution. I completely understand if PR #2400 is not up to the standards of HF.

I see a ~5% case-dependent increase in throughput and a ~20% decrease in peak memory usage when using Arrow under heavy load.

These gains are fairly modest and introduce additional dependencies.
