### ISSUE TITLE
ModuleNotFoundError: No module named 'tokenizers.tokenizers'

### ISSUE THREAD

**Issue by supreetkt** [huggingface/tokenizers#1416]
I'm trying to use a package which uses the tokenizers package internally. While using that package, I get the following error:

`ModuleNotFoundError: No module named 'tokenizers.tokenizers'`

The package has the following code:
`from tokenizers import Tokenizer`

I used traceback to find the root-cause and it seems to be due to the following:

`from .tokenizers import Tokenizer `

File \"/opt/python/tokenizers/__init__.py\", line 78, in <module>\n    
from .tokenizers import (\nModuleNotFoundError: No module named 'tokenizers.tokenizers'\n", so specifically: https://github.com/huggingface/tokenizers/blob/11462596d11d886e501091e28acbe1174385087a/bindings/python/py_src/tokenizers/__init__.py#L78

**Comment by ArthurZucker** [comment]
Not sure this is related to `tokenizers` or to the version they are using / the plateform you are using. py 3.12 does not have bindings yet I need to push them this week

**Comment by StefanoGiu** [comment]
Same issue for me

**Comment by Alen9805** [comment]
Same issue for me

**Comment by ArthurZucker** [comment]
Could you make sure you are using a pyhon version for which a release of tokenizers exists? 🤗

**Comment by koyelac** [comment]
Hello am also facing the same issue. I cloned openvoice repository and created an environment based on python version 3.9 as mentioned by the developers and now am facing this issue. Can anybody help please.
