### ISSUE TITLE
Unsupported platform for tokenizers

### ISSUE THREAD

**Issue by KolbySisk** [huggingface/tokenizers#1418]
When trying to use tokenizers I get this error: `Cannot find module 'tokenizers-win32-x64-msvc'`

After install the package it works fine locally, but when I try to deploy to Vercel I get this error: 

```
npm ERR! notsup Unsupported platform for tokenizers-win32-x64-msvc@0.13.4-rc1: wanted {"os":"win32","cpu":"x64"} (current: {"os":"linux","cpu":"x64"})
```

I'm guessing I need to install `tokenizers-linux-x64-gnu` on Vercel, but I don't see anyone else reporting this problem so I'm wondering if I'm doing something wrong here.

**Comment by ArthurZucker** [comment]
Your understanding is correct; you'll need to install the appropriate package for the Linux environment, such as tokenizers-linux-x64-gnu. (for the vercel env)
