### ISSUE TITLE
Inconsistency with original implementation (control characters)

### ISSUE THREAD

**Issue by kkaehler** [huggingface/tokenizers#142]
Comment [here](https://github.com/huggingface/tokenizers/blob/master/tokenizers/src/normalizers/bert.rs#L20) indicates that `Cc, Cf, Cn or Co` are all considered control characters, however `is_control` actually [only consider](https://doc.rust-lang.org/std/primitive.char.html#method.is_control) `Cc` to be a control character which differs from the python logic [here](https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_bert.py#L515) which just checks that the category starts with `C`.

For an example, let's take 🤪:

```rust
fn main() {
    println!("{}", '🤪'.is_control());
}

-> false
```

While in the [python implementation](https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_bert.py#L515)
```python

def _is_control(char):
    """Checks whether `chars` is a control character."""
    # These are technically control characters but we count them as whitespace
    # characters.
    if char == "\t" or char == "\n" or char == "\r":
        return False
    cat = unicodedata.category(char) # <- returns `Cn`
    if cat.startswith("C"):
        return True
    return False

-> True
```

This implementation seems more correct - but could change behavior (maybe? missing token -> `[UNK]`).

**Comment by n1t0** [comment]
Hey @kkaehler. Indeed the comment is talking about the behavior of `is_control`, the function being defined, and indicates that the definition is quite large, including `Cc, Cf, Cn or Co`. Now, just under this comment, we call [is_other()](https://github.com/huggingface/tokenizers/blob/master/tokenizers/src/normalizers/bert.rs#L23) which is part of the `rust-unicode-categories` library, with its code being available [here](https://github.com/behnam/rust-unicode-categories/blob/master/src/lib.rs#L141). As you can see, it checks if the given `char` is part of `Cc, Cf, Cn or Co`.

That's why we define our own `is_control` and don't use the one from the standard library, for which you sent some documentation. Does it make sense?

**Comment by kkaehler** [comment]
@n1t0 ah - apologies. In haste I missed that `is_other` is in the unicode_categories package. I am seeing an issue with this specific character 🤪(and others) where they are being stripped in the old library but not in the new library (they always return `[UNK]` since it's out of vocabulary). This seemed like the logical place where the issue would be. Any other ideas?

**Comment by n1t0** [comment]
Well that's weird indeed. I'm getting the exact same output when trying on my side:
```python
>>> from tokenizers import BertWordPieceTokenizer
>>> from transformers import BertTokenizer

>>> tok_rust = BertWordPieceTokenizer('./data/bert-base-cased-vocab.txt', lowercase=False, add_special_tokens=False)
>>> tok_tran = BertTokenizer.from_pretrained('bert-base-cased')

>>> print(tok_rust.encode("Hello 🤪 friend").tokens)
['Hello', '[UNK]', 'friend']

>>> print(tok_tran.tokenize("Hello 🤪 friend"))
['Hello', '[UNK]', 'friend']
```

Could you try to isolate the behavior and share some code to reproduce it?

**Comment by kkaehler** [comment]
An older version, but I just double checked on 2.4.1 to the same result.

```$ python
Python 3.6.5 (default, Dec 11 2019, 20:36:09)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>> transformers.__version__
'2.4.1'
>>> tok_tran = transformers.BertTokenizer.from_pretrained('bert-base-cased')
>>> print(tok_tran.tokenize("Hello 🤪 friend"))
['Hello', 'friend']
```

Going a level deeper - I also see this:
```python
>>> from transformers.tokenization_bert import _is_control
>>> _is_control('🤪')
True
```

**Comment by n1t0** [comment]
Ok, so when I tried executing your last snippet, It gave me `False`. So I tried using the same version of Python that you have (`3.6.5`) and I finally got the same result as you, which is weird.

So after digging one step deeper, see:
```
Python 3.7.3 (default, Nov 29 2019, 12:17:36)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import unicodedata
>>> unicodedata.category('🤪')
'So'
```
and
```
Python 3.6.5 (default, Feb 13 2020, 19:38:03)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import unicodedata
>>> unicodedata.category('🤪')
'Cn'
```

Not sure there is much I can do about this.

**Comment by kkaehler** [comment]
Clearly we need to change interpreters mid-tokenization! 😁 

Strange bug - wonder why that is. This only impacted a tiny, tiny portion of our corpus so we can move forward on our end.

Really appreciate you taking a look.

**Comment by kkaehler** [comment]
FWIW this is why
https://docs.python.org/3/whatsnew/3.7.html#unicodedata
