### ISSUE TITLE
WordPiece Algorithm

### ISSUE THREAD

**Issue by ahmedbahaaeldin** [huggingface/tokenizers#144]
Where i can find the WordPiece python code that train on the vocab ? Like how is it decided to merge tokens by frequency or count ?

**Comment by n1t0** [comment]
Hi @ahmedbahaaeldin. 

The training of WordPiece is done in Rust, not in Python. We just provide Python bindings for this.

I can try to explain here how it is done nonetheless. The training part of WordPiece is actually very similar to the classic BPE, except that the various tokens that are part of a word, get the `##` prefix attached to them. So the merges are done exactly like for BPE:  the most frequent pairs of tokens get merged until we reached the wanted vocabulary size.

If you want to check the actual code of the training, you can find it here: https://github.com/huggingface/tokenizers/blob/master/tokenizers/src/models/bpe/trainer.rs

**Comment by ahmedbahaaeldin** [comment]
@n1t0 thank you so much. Can you please tell me how you calculate how frequent pairs are instead of raw count ? Using this formula ‘’’= log( count of pair ) - log ( count first token in pair ) - log ( count second token in pair’’’
