### ISSUE TITLE
tokenizers.cpython-311-darwin.so wrong architecture

### ISSUE THREAD

**Issue by Casper-Mars** [huggingface/tokenizers#1447]
Name: tokenizers
Version: 0.13.3
Summary: Fast and Customizable Tokenizers
Home-page: https://github.com/huggingface/tokenizers
Author: Anthony MOI
Author-email: anthony@huggingface.co
License: Apache License 2.0
Location: /opt/homebrew/lib/python3.11/site-packages
Requires:
Required-by: chromadb, transformers

CPU: M1
OS: macOS

Errors:
dlopen(/opt/homebrew/lib/python3.11/site-packages/tokenizers/tokenizers.cpython-311-darwin.so, 2): no suitable image found.  Did find:
	/opt/homebrew/lib/python3.11/site-packages/tokenizers/tokenizers.cpython-311-darwin.so: mach-o, but wrong architecture
	/opt/homebrew/lib/python3.11/site-packages/tokenizers/tokenizers.cpython-311-darwin.so: mach-o, but wrong architecture

Any idea to solve this issue?

**Comment by ArthurZucker** [comment]
Could you try with a more recent version of tokenizers? the builds for python3.11 were not released
