### ISSUE TITLE
when compile with tch-rs library , encounter static libcpmt.lib and dynamic msvcprt.lib conflict link error

### ISSUE THREAD

**Issue by devdoer3** [huggingface/tokenizers#1454]
when compile with tokenizers and tch-rs library , encounter static libcpmt.lib and dynamic  msvcprt.lib conflict link error.
My program use tokenizers 0.15.0 and tch-rs 0.14.0 , such as below:

```
use anyhow::Result;
use tokenizers::Tokenizer;
use tch;
fn main() -> Result<()> {
    //load model
    let model_file = "anyhow_to_the_model_path";
    let model =tch::CModule::load(model_file)?;  
    println!("model loaded");     
   Ok(())
    
}
```
The cargo reports: "error: linking with `link.exe` failed: exit code: 1169"
error LNK2038:  detect “RuntimeLibrary” non-match value “MD_DynamicRelease” non-match value “MT_StaticRelease”(libesaxx_rs-0ddd131668a89c52.rlib(esaxx.o) )

**Comment by devdoer3** [comment]
The reason is esaxx pakcage build.rs use staitc link crt. Below codes are from[ esaxx build.rs](https://github.com/Narsil/esaxx-rs/blob/main/build.rs)
```
#[cfg(feature = "cpp")]
#[cfg(not(target_os = "macos"))]
fn main() {
    cc::Build::new()
        .cpp(true)
        .flag("-std=c++11")
        .static_crt(true)
        .file("src/esaxx.cpp")
        .include("src")
        .compile("esaxx");
}
```

**Comment by ArthurZucker** [comment]
Could you open the issue on the corresponding repo? This is not controllable in `tokenizers`
