### ISSUE TITLE
How to load tokenizer trained by sentencepiece or tiktoken

### ISSUE THREAD

**Issue by jordane95** [huggingface/tokenizers#1469]
Hi, does this lib supports loading pre-trained tokenizer trained by other libs, like `sentencepiece` and `tiktoken`? Many models on hf hub store tokenizer in these formats

**Comment by ArthurZucker** [comment]
For sentencepiece it is mostly `transformers` and for `tiktoken` we don't have one directly 😢 It's planned for both!

**Comment by ArthurZucker** [comment]
@xenova if you can share some automations!

**Comment by xenova** [comment]
Here's my tiktoken-to-hf conversion script: https://gist.github.com/xenova/a452a6474428de0182b17605a98631ee
And then we already have a SPM converter :)

**Comment by ArthurZucker** [comment]
Transformers now has https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py#L1478 

an "official" tiktoken converter
