### ISSUE TITLE
Assign `<unusedXX>` tokens with `special_tokens` without growing vocab size

### ISSUE THREAD

**Issue by jacobwjs** [huggingface/tokenizers#1473]
``
I'm trying to modify `google/gemma-7b` tokenizer for instruction tuning purposes. My goal is to replace some of the "unused" tokens that were specifically added to the tokenizer for my own defined "custom" tokens. I want these custom tokens to be treated as "special" (i.e. not normalized, stripped, etc.), however this seems like an impossible task.

What I would like to do is some version of the following,

```python
tokenizer = AutoTokenizer.from_pretrained("google/gemma-7b")

custom_tokens = ['<|im_start|>', '<|im_end|>']
unused_tokens = ['<unused1>', '<unused2>']

tokenizer.add_special_tokens({'additional_special_tokens': custom_tokens, 'tokens_to_replace': unused_tokens})
```

Given that many models/tokenizers being open-sourced specifically reserve some set of unused tokens for this purpose, I would like to make use of them without growing the vocabulary, and subsequently not having to adjust the model's embedding dimensions.

I've tried manually manipulating the vocab, and assigning appropriate dicts on the forward and reverse pass (encoder, decoder), but nothing seems to work.

How can I achieve my goals of making use of unused tokens, ensuring they are treated as "special", and not growing the vocabulary of the tokenizer and model embedding?

**Comment by ArthurZucker** [comment]
That is something we should do indeed

**Comment by ArthurZucker** [comment]
I'll take this one on in a bit!

**Comment by ArthurZucker** [comment]
opened a PR !

**Comment by berserkr** [comment]
Was this ever handled?

**Comment by jacobwjs** [comment]
> Was this ever handled?

@berserkr I wish. There was some work done in https://github.com/huggingface/tokenizers/pull/1570, but seems pending still :/

**Comment by ArthurZucker** [comment]
Wow sorry. I think I stopped because its kinda hard for Unigram you will stil be parsing the old unused. But I can make it for next release!
