### ISSUE TITLE
`cargo build` fails for python bindings when `--locked` is passed for `v0.15.1` and `v0.15.2`

### ISSUE THREAD

**Issue by CobaltCause** [huggingface/tokenizers#1477]
I noticed that at least the git tags listed in the title forgot to update `Cargo.lock` in addition to `Cargo.toml`. This discrepancy causes `cargo build --locked` to fail with an error like this:

```
error: the lock file /.../tokenizers/bindings/python/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

Passing `--locked` is required for e.g. certain distro packaging methodologies. Also, it means that running `cargo build` without `--locked` will work but leave your git tree dirty, which is kinda weird.

Obviously this isn't really retroactively fixable, but hopefully this can be avoided in future releases. Maybe a check for this can be added in CI?

**Comment by CobaltCause** [comment]
​

**Comment by ArthurZucker** [comment]
This is fixed
