### ISSUE TITLE
tokenizers-linux-x64-musl is not found when running inside node apline docker

### ISSUE THREAD

**Issue by madhurjya-acko** [huggingface/tokenizers#1480]
Whenever trying to use inside a docker container with node alpine (it uses musl instead of glibc)
tokenizers-linux-x64-musl is not present while importing tokenizers

**Comment by ArthurZucker** [comment]
HEy this is most probably related to the version of python that you are using

**Comment by PylotLight** [comment]
@ArthurZucker  How does that work given this is for js?
