### ISSUE TITLE
Discrepancy Between GitHub Release and NPM Package Version & Missing Dependencies

### ISSUE THREAD

**Issue by superBertBerg** [huggingface/tokenizers#1489]
Hello,

I've encountered two issues with the https://www.npmjs.com/package/tokenizers package that I believe need attention:

1. **Version Discrepancy:** The latest release on GitHub is `v0.15.2` (Feb 12), while the NPM package is still at `0.13.3`. This gap means that users of the NPM package are missing out on the latest features and fixes. That also applies to the binaries which exist.
    
2. **Missing Dependencies:** The older NPM version lacks several dependencies, such as `tokenizers-darwin-arm64` ([link](https://www.npmjs.com/package/tokenizers-darwin-arm64)), critical for ARM-based systems.
    

I was able to clone the repository, build, and use the project without any issues, which suggests the current GitHub version is stable. Could you provide insight into the following:

- Is the NPM package version lag intentional, or is an update planned?
- Are the missing dependencies like `tokenizers-darwin-arm64` intended to be excluded from the NPM release?

Your guidance on these points would be greatly appreciated as it impacts project integration.

Thank you.

**Comment by superBertBerg** [comment]
https://github.com/huggingface/tokenizers/issues/1480#issue-2215750786 that is 100% the same issue
https://github.com/huggingface/tokenizers/issues/1403 that as well i guess

**Comment by meichangsu1** [comment]
+1

**Comment by superBertBerg** [comment]
+1 that is still an issue ...

**Comment by ArthurZucker** [comment]
I don't have knowledge on NPM to make updates, and I think we push for tokenizer.js !

**Comment by unlucio** [comment]
This issue is still not solved, do you guys need help in publishing to npm?
If you do I'm willing to help

**Comment by ArthurZucker** [comment]
Te be honest we partly dropped support as the version do not really match anymore: the update to rust were propagated to the python api but not to the npm part. we recommend using `transformers.js`

**Comment by unlucio** [comment]
@ArthurZucker thanks for the heads up.
