### ISSUE TITLE
Tokenizer saving/loading

### ISSUE THREAD

**Issue by n1t0** [huggingface/tokenizers#15]
We need to provide a way to save and load tokenizers to/from files.
Things that need to be saved:
 - [ ] Each part (Normalizer, PreTokenizer, ..) and their options
 - [ ] Added tokens / special tokens
 - [ ] The model's vocabulary

We can approach this in multiple ways, but in the end, we would like to have a single self-contained file that represents a tokenizer. We will probably need to have some scripts to convert existing models to this new format.

**Comment by lukedeo** [comment]
Any update on status for this? Trying to avoid writing custom saving / loading logic if I can.

**Comment by yukw777** [comment]
Could we also have a way to load tokenizers from memory using some kind of stream? This is especially important when I start up my model server. We've had incidents where our k8s nodes became unresponsive as we were loading the model from the disk as the CPUs were overwhelmed with IO bursts. So I'd like to stream the tokenizer directly into memory without hitting the disk.

**Comment by n1t0** [comment]
This is now part of the `0.8.0.dev1` pre-release.

@yukw777 You can check `from_str` and `from_buffer` on `Tokenizer` that should let you do exactly what you want to!

**Comment by yukw777** [comment]
Hi @n1t0, thanks for taking care of this issue! Could you tell me when the official release of v0.8.0 will come out so that I can plan accordingly?

**Comment by n1t0** [comment]
I'd say either this week, or the next one @yukw777.
