### ISSUE TITLE
[Question] Can I use ByteLevelBPETokenizer for Hindi language?

### ISSUE THREAD

**Issue by nikhilno1** [huggingface/tokenizers#150]
I would like to know which tokenizer can I use to train a Hindi LM from scratch? Please share if there is any good material. Thanks.

**Comment by julien-c** [comment]
Hi @nikhilno1 the first two sections of https://huggingface.co/blog/how-to-train might be helpful to you.

**Comment by nikhilno1** [comment]
Hi Julien, apologies if my question wasn't clear. I did go through it before posting the question. In that, it is being suggested to use "byte-level Byte-pair encoding tokenizer" for Esperanto language. My question was whether I can use the same tokenizer for Hindi language. If there is any material that talks about which type of tokenizer works bests for what type of language, that will also do. I think the same tokenizer should work but wanted to be sure before proceeding with it. Thanks.

**Comment by mapmeld** [comment]
I had the same question. Using the byte-level Byte-pair encoding gave me encoding errors in vocabulary JSON (examples: "Ġà¤ķà¤°à¤®à¤¨", "à¤¾à¥ĩà¥ĩ") could be workable if you find that they're consistent. I instead will use BertWordPieceTokenizer (also available here in Tokenizers).

Looking around at other options: looks like Hindi tokenization is usually done on word-level, as seen in https://anoopkunchukuttan.github.io/indic_nlp_library/ (recently cited by mBART: https://arxiv.org/abs/2001.08210 ) or https://pypi.org/project/mosestokenizer/ (used by LASER: https://github.com/facebookresearch/LASER/blob/master/source/lib/text_processing.py )

**Comment by nikhilno1** [comment]
Thank you @mapmeld for the pointers.

**Comment by julien-c** [comment]
I would suggest training a byte-level BPE indeed.

@mapmeld What do you mean by encoding errors in the vocabulary? If you mean that the tokens look "weird" in `vocab.json`, this is not in itself an issue – the model stores bytes in an encoded format. That's the case if you look at the GPT2 tokenizer too.

**Comment by kushalj001** [comment]
@nikhilno1 did you figure out anything regarding the tokenization of Hindi for Bert and other language models?
