### ISSUE TITLE
Issue in installing rudalle on google colab, !pip install rudalle

### ISSUE THREAD

**Issue by deepanshh786** [huggingface/tokenizers#1500]
error: subprocess-exited-with-error
  
  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects

**Comment by ArthurZucker** [comment]
This probably just the version of python that was not supported!
