### ISSUE TITLE
offline installation

### ISSUE THREAD

**Issue by HankLiu10** [huggingface/tokenizers#1502]
Hi!

I'm seeking for an tutorial for tokenizers installation on linux aarch64 server.

I've already install rust in offline environment, then what to do next?

Thanks!

**Comment by HankLiu10** [comment]
for more details, I tried execute 
pip install -e . 
in directory: binding/python

however, it seems not working:

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Obtaining file:///home/weiqiang/lhc/pkgs/tokenizers-main/bindings/python
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0xffff9ac4c2b0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /pypi/simple/maturin/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0xffff9ac4c250>: Failed to establish a new connection: [Errno -2] Name or service not known')': /pypi/simple/maturin/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0xffff9abeb310>: Failed to establish a new connection: [Errno -2] Name or service not known')': /pypi/simple/maturin/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0xffff9abeb520>: Failed to establish a new connection: [Errno -2] Name or service not known')': /pypi/simple/maturin/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0xffff9abeb730>: Failed to establish a new connection: [Errno -2] Name or service not known')': /pypi/simple/maturin/
      ERROR: Could not find a version that satisfies the requirement maturin<2.0,>=1.0 (from versions: none)
      ERROR: No matching distribution found for maturin<2.0,>=1.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ArthurZucker** [comment]
you need rust to compile this from source!
