### ISSUE TITLE
Is there way to access built vocabulary info after training (like most frequent words/tokens)

### ISSUE THREAD

**Issue by mandubian** [huggingface/tokenizers#151]
I need to know the most common tokens to perform some data augmentation on my datasets. But I haven't found any way to access that kind of info from python tokenizer. Trainer seems to provide a `process_tokens` function but it is not reachable from python API.
Any way to do that now or should it be added?

**Comment by n1t0** [comment]
Provided a way to retrieve the vocabulary with https://github.com/huggingface/tokenizers/pull/208. Will be released started from the `0.7.0-rc3`.

So using `get_vocab` on the `Tokenizer` you can now retrieve the mapping `tokens <-> ids`. The vocabularies generally map (at least for now) the ids starting from the most frequent tokens, so the lower the id, the most frequent the token.
