### ISSUE TITLE
Breaking changes in v0.19.1 for tiktoken/llama3

### ISSUE THREAD

**Issue by sanderland** [huggingface/tokenizers#1512]
```
import tokenizers
def show_tokenization(tok, s):
    ids = tok.encode(s, add_special_tokens=False).ids
    print([(i, tok.decode([i])) for i in ids])

def show_tokenization_from_id(tok, id):
    s = tok.decode([id])
    print(f"id {id} decodes to {s!r}, which encodes to...")
    show_tokenization(tok, s)

fb_tok = tokenizers.Tokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B")
show_tokenization_from_id(112328)
```

v0.19.0
id 112328 decodes to ' Arthropoda', which encodes to...
[(1676, ' Ar'), (98643, 'throp'), (14320, 'oda')]

v0.19.1
id 112328 decodes to ' Arthropoda', which encodes to...
[(112328, ' Arthropoda')]

I have good evidence that the new behaviour is how the model was trained, but the announcement of the patch release should perhaps be a little louder in advising to e.g. retokenize all training data for particular model families.

**Comment by thusinh1969** [comment]
I am waiting for #1513 break changes to happend to start continual pretrain LlaMA with extended vocab et all.

Not sure when this merge will happend as it is critical for LLaMA-3 for non-English corpus.

Cheers,
Steve

**Comment by sanderland** [comment]
@thusinh1969 What are you finding wrong with 0.19.1?

**Comment by thusinh1969** [comment]
> @thusinh1969 What are you finding wrong with 0.19.1?

The decoder was buggy for added token when we want to extend vocab for non-English. Being fixed I think.
Steve

**Comment by ArthurZucker** [comment]
Yep the breaking change will be reverted, but we will still ship the new addition of tokens for BPE. Just gimme a week!
