### ISSUE TITLE
Llama3 tokenizer with Incorrect offset_mapping

### ISSUE THREAD

**Issue by justin-shao** [huggingface/tokenizers#1517]
When tokenizing with the llama-3 tokenizer in tandem with **return_offsets_mapping=True**, the resulting offset_mapping does not align with the behavior outlined in docs.

Example:
```
model_name = "meta-llama/Meta-Llama-3-8B"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True, padding_side="left")
print(tokenizer(["Sample input"], return_offsets_mapping=True))
```
will yield:
```
{'input_ids': [[128000, 18031, 1988]], 'attention_mask': [[1, 1, 1]], 'offset_mapping': [[(0, 0), (0, 0), (6, 6)]]}
```
Offset_mapping should have tuples representing `(char_start, char_end)`  for each token.

**Comment by ArthurZucker** [comment]
Hey! This seems to be expected no? The documentation might be wrong,  but there are no offsets here (trim_offsets is set to False I think): 
```['Sample', 'Ġinput']``` are the two tokens

**Comment by davidb-cerebras** [comment]
@ArthurZucker I don't think this would be expected -- `return_offsets_mapping` for other tokenizers gives the mapping of character index to token. See below for Mistral output 
```
(Pdb) from transformers import AutoTokenizer
(Pdb) tok_mistral = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")
(Pdb) tok_mistral(["Sample input"], return_offsets_mapping=True)
{'input_ids': [[1, 27797, 2787]], 'attention_mask': [[1, 1, 1]], 'offset_mapping': [[(0, 0), (0, 6), (6, 12)]]}
(Pdb) tok_mistral.convert_ids_to_tokens([1, 27797, 2787])
['<s>', '▁Sample', '▁input']
(Pdb) "Sample input"[0:6]
'Sample'
(Pdb) "Sample input"[6:12]
' input'
```
