### ISSUE TITLE
Convert huggingface tokenizer into sentencepiece format

### ISSUE THREAD

**Issue by RRaphaell** [huggingface/tokenizers#1524]
I have a huggingface tokenizer for the BERT model (google-bert/bert-base-cased) which includes three files: tokenizer.json, tokenizer_config.json, and vocab.txt. I would like to convert this tokenizer into the SentencePiece tokenizer format, which uses a single .model file. 
How can I perform this conversion?

**Comment by ArthurZucker** [comment]
Sorry but I have not idea how to go back to sentencepiece 😅 the format is not super open. 
What is the motivation?
