### ISSUE TITLE
Link to download the training text in `docs/source/quicktour.rst` is broken

### ISSUE THREAD

**Issue by 14jdelap** [huggingface/tokenizers#1526]
In [Quicktour](https://huggingface.co/docs/tokenizers/quicktour)  the link to download the [wikitext-103](https://blog.einstein.ai/the-wikitext-long-term-dependency-language-modeling-dataset/) file is broken because the response is a 403.

```
➜  tokenizer-training wget https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-103-raw-v1.zip
--2024-05-09 12:39:46--  https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-103-raw-v1.zip
Resolving s3.amazonaws.com (s3.amazonaws.com)... 3.5.12.14, 52.216.89.134, 52.217.197.112, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|3.5.12.14|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-05-09 12:39:46 ERROR 403: Forbidden.
```

**Comment by ArthurZucker** [comment]
Hey! WOuld you like to open a PR for a fix?

**Comment by 14jdelap** [comment]
Hey! I tried to find another link for the same dataset online but couldn't find one — otherwise I would've done a PR with the fix :)

**Comment by 14jdelap** [comment]
But if you point me to where I can find the dataset I'm happy to send the PR

**Comment by ArthurZucker** [comment]
Maybe using this one: https://huggingface.co/datasets/Salesforce/wikitext or one that is on the hub would be nice!
