### ISSUE TITLE
possible to train tokenizer from gzip instead of txt files ?

### ISSUE THREAD

**Issue by vgoklani** [huggingface/tokenizers#153]
Hey there,

Is it possible to train the tokenizer using gzipped files instead of txt files?

Thanks!

**Comment by n1t0** [comment]
The documentation for the latest version of `tokenizers` includes an example showing how to train with gzip files: https://huggingface.co/docs/tokenizers/python/v0.10.0/tutorials/python/training_from_memory.html#using-gzip-files
