### ISSUE TITLE
Training HuggingFace tokenizer - ignore_merges

### ISSUE THREAD

**Issue by ykoyfman** [huggingface/tokenizers#1537]
Looking through Llama3 changes, I see that "ignore_merges" was added as a property to support conversion from tiktoken models.  Can a native HF tokenizer be trained using this property? It's not clear if this is possible with, say, `train_new_from_iterator`.   CC @ArthurZucker  - Thanks

**Comment by ArthurZucker** [comment]
I think that it's not the case yet, but we should support it!

**Comment by ArthurZucker** [comment]
(Anyone feel free to open a PR if you have time!)
