### ISSUE TITLE
llama3 tokenizer doesn't round trip

### ISSUE THREAD

**Issue by josharian** [huggingface/tokenizers#1543]
```python
>>> tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B")
>>> tokenizer("hello !")
{'input_ids': [128000, 15339, 758], 'attention_mask': [1, 1, 1]}
>>> tokenizer.decode([128000, 15339, 758])
'<|begin_of_text|>hello!'
```

Observe that the input has a space before the `!` and the output does not.

**Comment by josharian** [comment]
This does not reproduce using the upstream llama3 tokenizer.model and tiktoken.

**Comment by ArthurZucker** [comment]
I think the same issue was mentioned, that is because of the `transformers` layer's `clean_up_tokenization_spaces`. See this: https://github.com/huggingface/transformers/issues/31187

**Comment by ArthurZucker** [comment]
We are gonna deprecate and remove this flag 😉
