### ISSUE TITLE
How to use `TokenizerBuilder`?

### ISSUE THREAD

**Issue by polarathene** [huggingface/tokenizers#1549]
I expected `TokenizerBuilder` to produce a `Tokenizer` from the `build()` result, but instead `Tokenizer` wraps `TokenizerImpl`.

No problem, I see that it impl `From<TokenizerImpl> for Tokenizer`, but it's attempting to do quite a bit more for some reason? Meanwhile I cannot use `Tokenizer(unwrapped_build_result_here)` as the struct is private 🤔 (_while the `Tokenizer::new()` method won't take this in either_)

---

```rs
let mut tokenizer = Tokenizer::from(TokenizerBuilder::new()
    .with_model(unigram)
    .with_decoder(Some(decoder))
    .with_normalizer(Some(normalizer))
    .build()
    .map_err(anyhow::Error::msg)?
);
```

```rs
error[E0283]: type annotations needed
   --> mistralrs-core/src/pipeline/gguf_tokenizer.rs:139:41
    |
139 |     let mut tokenizer = Tokenizer::from(TokenizerBuilder::new()
    |                                         ^^^^^^^^^^^^^^^^^^^^^ cannot infer type of the type parameter `PT` declared on the struct `TokenizerBuilder`
    |
    = note: cannot satisfy `_: tokenizers::PreTokenizer`
    = help: the following types implement trait `tokenizers::PreTokenizer`:
              tokenizers::pre_tokenizers::bert::BertPreTokenizer
              tokenizers::decoders::byte_level::ByteLevel
              tokenizers::pre_tokenizers::delimiter::CharDelimiterSplit
              tokenizers::pre_tokenizers::digits::Digits
              tokenizers::decoders::metaspace::Metaspace
              tokenizers::pre_tokenizers::punctuation::Punctuation
              tokenizers::pre_tokenizers::sequence::Sequence
              tokenizers::pre_tokenizers::split::Split
            and 4 others
note: required by a bound in `tokenizers::TokenizerBuilder::<M, N, PT, PP, D>::new`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokenizers-0.19.1/src/tokenizer/mod.rs:314:9
    |
314 |     PT: PreTokenizer,
    |         ^^^^^^^^^^^^ required by this bound in `TokenizerBuilder::<M, N, PT, PP, D>::new`
...
319 |     pub fn new() -> Self {
    |            --- required by a bound in this associated function
help: consider specifying the generic arguments
    |
139 |     let mut tokenizer = Tokenizer::from(TokenizerBuilder::<tokenizers::models::unigram::Unigram, tokenizers::NormalizerWrapper, PT, PP, tokenizers::DecoderWrapper>::new()
    |                                                         +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

Why is this an issue? Isn't the point of the builder so that you don't have to specify the optional types not explicitly set?

> ```
> cannot infer type of the type parameter `PT` declared on the struct `TokenizerBuilder`
> ```

I had a glance over the source on github but didn't see an example or test for using this API and the docs don't really cover it either.

---

Meanwhile with `Tokenizer` instead of `TokenizerBuilder` this works:

```rs
let mut tokenizer = Tokenizer::new(tokenizers::ModelWrapper::Unigram(unigram));
tokenizer.with_decoder(decoder);
tokenizer.with_normalizer(normalizer);
```

**Comment by polarathene** [comment]
In the meantime, I've implemented this alternative workaround (using [`buildstructor`](https://crates.io/crates/buildstructor)):

```rs
struct TokenizerX;
#[buildstructor::buildstructor]
impl TokenizerX {
    #[builder]
    fn try_new<'a>(
        with_model: ModelWrapper,
        with_decoder: Option<Decoder<'a>>,
        with_normalizer: Option<Normalizer<'a>>,
    ) -> Result<Tokenizer> {
        let mut tokenizer = Tokenizer::new(with_model);

        // Handle local enum to remote enum type:
        if let Some(decoder) = with_decoder {
            let d = DecoderWrapper::try_from(decoder)?;
            tokenizer.with_decoder(d);
        }
        if let Some(normalizer) = with_normalizer {
            let n = NormalizerWrapper::try_from(normalizer)?;
            tokenizer.with_normalizer(n);
        }

        Ok(tokenizer)
    }
}
```

Usage:

```rs
let mut tokenizer: Tokenizer = TokenizerX::try_builder()
    .with_model(model)
    .with_decoder(decoder)
    .with_normalizer(normalizer)
    .build()?;
```

---

The local to remote enum logic above is for the related `DecoderWrapper` + `NormalizeWrapper` enums which were also a bit noisy to use / grok, so I have a similar workaround for those:

```rs
let decoder = Decoder::Sequence(vec![
    Decoder::Replace("_", " "),
    Decoder::ByteFallback,
    Decoder::Fuse,
    Decoder::Strip(' ', 1, 0),
]);

let normalizer = Normalizer::Sequence(vec![
    Normalizer::Prepend("▁"),
    Normalizer::Replace(" ", "▁"),
]);
```

[More details at `mistral.rs`](https://github.com/EricLBuehler/mistral.rs/pull/389).

**Comment by ArthurZucker** [comment]
The builder is I believe mostly used fro training

**Comment by polarathene** [comment]
@ArthurZucker perhaps you could better document that? Because by naming convention and current docs comment it implies it is the [builder pattern for the `Tokenizer` struct](https://docs.rs/tokenizers/latest/tokenizers/tokenizer/struct.TokenizerBuilder.html):

> Builder for `Tokenizer` structs.

It provides an API that matches what you'd expect of a builder API, and it's `build()` method returns a type that is used to construct a `Tokenizer` struct (_which also has a `From` impl for this type_):

https://github.com/huggingface/tokenizers/blob/1ff56c0c70b045f0cd82da1af9ac08cd4c7a6f9f/tokenizers/src/tokenizer/mod.rs#L464-L484

https://github.com/huggingface/tokenizers/blob/1ff56c0c70b045f0cd82da1af9ac08cd4c7a6f9f/tokenizers/src/tokenizer/mod.rs#L419-L436

https://github.com/huggingface/tokenizers/blob/1ff56c0c70b045f0cd82da1af9ac08cd4c7a6f9f/tokenizers/src/tokenizer/mod.rs#L408-L417

---

As the issue reports though, that doesn't seem to work very well, the builder API is awkward to use. You could probably adapt it to use `buildstructor` similar to how I have shown above with my `TokenizerX` workaround type (_which also does a similar workaround for `Decoder` / `Normalizer` inputs to provide a better DX, but that is not required_).

Presently, due to the reported issue here the builder offers little value vs creating the tokenizer without a fluent builder API.
