### ISSUE TITLE
ByteLevelBPETokenizer | Some unicode characters cause the token position to not match the char position

### ISSUE THREAD

**Issue by w-is-h** [huggingface/tokenizers#156]
Tested using: Ubuntu 18.04, Python 3.7 and tokenizers==0.5.0

I've found a small problem with one of the tokenizers, to recreate it run:
```
from tokenizers import ByteLevelBPETokenizer
text = "i ⭢ j"
with open("/tmp/tmp.txt", "w") as f:
    f.write(text)
tokenizer = ByteLevelBPETokenizer()
tokenizer.train("/tmp/tmp.txt")

doc = tokenizer.encode(text)
print(doc.tokens)
print(doc.offsets)
print(len(text))


### Outputs
"""
['i', 'Ġ', 'â', 'Ń', '¢', 'Ġ', 'j']
[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7)]
5
"""
```

As you can see from the prints the offsets are strange and the tokenized text is longer than the original. I'm not sure if this is desired, but it creates many problems when mapping the tokens back to the original string. Also, it does not happen with other tokenizers e.g. the BertWordPieceTokenizer.

**Comment by n1t0** [comment]
Indeed the offsets are wrong when a char get split up. Thank you @w-is-h for noticing this!

**Comment by w-is-h** [comment]
Hi @n1t0 , awesome, thanks for the fix. Can you please confirm that this is now the correct output (as it is still a bit strange): 

```
from tokenizers import ByteLevelBPETokenizer
text = "i ⭢ j"
with open("/tmp/tmp.txt", "w") as f:
    f.write(text)
tokenizer = ByteLevelBPETokenizer()
tokenizer.train("/tmp/tmp.txt")

doc = tokenizer.encode(text)
print(doc.tokens)
print(doc.offsets)
print(len(text))


### Outputs
"""
['i', 'Ġ', 'â', 'Ń', '¢', 'Ġ', 'j']
[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (3, 4), (4, 5)]
5
"""
```

The offsets are now correct, as nothing goes over the position 5, but you get multiple tokens on the exact same position, is all of this fine and desired?

**Comment by n1t0** [comment]
It is not. The offsets for `'â', 'Ń', '¢'` should be `(2, 3), (2, 3), (2, 3)`, since it represents only one character (the `⭢`)
