### ISSUE TITLE
How can we output the progress bars within a jupyter notebook?

### ISSUE THREAD

**Issue by ohmeow** [huggingface/tokenizers#157]
... in particular when we run `tokenizer.train(...)`

**Comment by n1t0** [comment]
Indeed, this is a known limitation of the library we use to show progress. Unfortunately, it won't show anything if not attached to a "real" terminal, so it does not work in Notebooks.

**Comment by jonaspleyer** [comment]
Has there been any update on this? What would be necessary steps to resolve this issue. I have a large library and have so far been very satified with indicatif but this might be a dealbreaker in the long run.

**Comment by n0kovo** [comment]
> Indeed, this is a known limitation of the library we use to show progress

So uh, could this "known limitation" maybe be considered, you know, an... issue?
Considering  that a pretty huge chunk of `tokenizers` users primarily use Jupyter/Colab etc.?
Just thinking out loud 🤷
