### ISSUE TITLE
Allow Pretrained Loading of Saved Tokenizers from Transformers Library

### ISSUE THREAD

**Issue by ackjake** [huggingface/tokenizers#161]
Currently I don't see a way to load saved tokenizers from the Tokenizers library into the Transformers PreTrained Tokenizer class. This would help integrate into the existing code bases that use the Transformers library.

**Comment by loopdigga96** [comment]
#59 This issue already were discussed. I am also interested in it

**Comment by n1t0** [comment]
With the latest releases of `transformers` and `tokenizers`, this is now very easy:
```python
from tokenizers import Tokenizer
from transformers import PreTrainedTokenizerFast

tokenizer = Tokenizer(...) # Any Tokenizer built with this library
tokenizer.save("my-tokenizer.json)

transformers_tokenizer = PreTrainedTokenizerFast(fast_tokenizer_file="my-tokenizer.json")
```
