### ISSUE TITLE
Space after unnormalized token is added when `use_fast=True` for Llama tokenizer

### ISSUE THREAD

**Issue by Butanium** [huggingface/tokenizers#1613]
Related to: https://github.com/huggingface/transformers/issues/25073

In my current project, I'd like to add a special token that doesn't insert a space to the next token.
Currently, I need to specify `use_fast=False` in order for this to work. However:
- This is unclear to me why I should expect slow and fast tokenizer to behave in different ways
- This finding doesn't generalize to e.g. gemma tokenizer which never add such space
- Maybe this should be an explicit option in the tokenizer_kwargs?
```py
from transformers import AutoTokenizer
fast_tokenizer = AutoTokenizer.from_pretrained("meta-llama/llama-2-7b-hf", use_fast=True)
slow_tokenizer = AutoTokenizer.from_pretrained("meta-llama/llama-2-7b-hf", use_fast=False)
tok = fast_tokenizer.bos_token
s = f'a:{tok}->'
print(f"fast: {fast_tokenizer.tokenize(s)}\nslow: {slow_tokenizer.tokenize(s)}")
>>> fast: ['▁a', ':', '<s>', '▁->']
>>> slow: ['▁a', ':', '<s>', '->']
```

**Comment by Butanium** [comment]
Oh wait @ArthurZucker is that what you're fixing here: https://github.com/huggingface/tokenizers/pull/1568 ?

**Comment by Butanium** [comment]
Same issue with unnormalized non-special tokens:
```py
from tokenizers import AddedToken
from transformers import AutoTokenizer
tok_name = "meta-llama/llama-2-7b-hf"
fast_tokenizer = AutoTokenizer.from_pretrained(tok_name, add_perfix_space=True, use_fast=True)
slow_tokenizer = AutoTokenizer.from_pretrained(tok_name, add_perfix_space=False, use_fast=False)
tok = "<special>"
t = AddedToken(
    tok, normalized=False, special=False
 )
fast_tokenizer.add_tokens([t])
slow_tokenizer.add_tokens([t])
s = f'hello:{tok}->'
print(f"fast: {fast_tokenizer.tokenize(s)}\nslow: {slow_tokenizer.tokenize(s)}")
```

**Comment by Butanium** [comment]
And there is even more differences when you add `normalized=True` ...
```py
from tokenizers import AddedToken
from transformers import AutoTokenizer
tok_name = "meta-llama/llama-2-7b-hf"
fast_tokenizer = AutoTokenizer.from_pretrained(tok_name, add_perfix_space=True, use_fast=True)
slow_tokenizer = AutoTokenizer.from_pretrained(tok_name, add_perfix_space=False, use_fast=False)
tok = "<special>"
t = AddedToken(
    tok, normalized=True, special=True
 )
fast_tokenizer.add_tokens([t], special_tokens=True)
slow_tokenizer.add_tokens([t], special_tokens=True)
s = f'hello:{tok}->'
print(f"fast: {fast_tokenizer.tokenize(s)}\nslow: {slow_tokenizer.tokenize(s)}")
>>> fast: ['▁hello', ':', '<', 'special', '>', '->']
>>> slow: ['▁hello', ':', '<special>', '->']
```

**Comment by ArthurZucker** [comment]
See #1357

**Comment by Butanium** [comment]
Hey @ArthurZucker, thanks for your answer. I'm using 0.19.1 which should have the fix.
I'm really confused right now. Why isn't the fact that `use_fast` alters the behavior of the tokenizer an issue?
My more practical question is, is there a way to add a token s.t.:
```py
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model, ...) # magic kwargs
# magically add <special>
s = f'a:<special>->'
print(tokenizer.tokenize(s)})
```
will always prints `[ {whatever}, '<special>', '->']` where the key point here is that there is a `->` and not a `_->` token

**Comment by Butanium** [comment]
Ok so I should do some unit test and choose different kwarg depending on the tokenizer to get the same behavior?

**Comment by ArthurZucker** [comment]
No, sorry. Basically you can just check the tokenizer's pre_tokenizer. If it's metaspace, the `prepend_scheme` should be set to `first` instead of `always`
