### ISSUE TITLE
STATUS_ENTRYPOINT_NOT_FOUND

### ISSUE THREAD

**Issue by impurity-dev** [huggingface/tokenizers#1623]
```rust
use tokenizers::tokenizer::{Result, Tokenizer};

fn main() -> Result<()> {
    let tokenizer = Tokenizer::from_pretrained("bert-base-cased", None)?;
    let encoding = tokenizer.encode("Hey there!", false)?;
    println!("{:?}", encoding.get_tokens());
    Ok(())
}
```
```toml
tokenizers = { version = "0.20.0", features = ["http"] }
```

I have the sample program from the docs, with only a main.rs and tokenizers as the dependency. I am trying to create a tokenizer from a pretrained model in rust, but every time I run the `cargo run`, I get an error... Note, `cargo build` works fine.

`cargo run` output.
```
Compiling my-service v0.1.0 (E:\workspace\github\my-service)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 45.41s
     Running `target\debug\my-service.exe`
error: process didn't exit successfully: `target\debug\my-service.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```

What is odd to me is that I run it with the debugger and I can see the code working, and finishing the functions, I just don't understand why `cargo run` doesn't complete correctly.

I'm quite new to rust + cuda, so there's a world that i broken something in my setup. However, candle-core seems to work and I don't think this package uses anything specific for external setup.

**Comment by impurity-dev** [comment]
After a bit of reading the issue threads, I stumbled upon this configuration
```toml
tokenizers = { version = "0.20.0", default-features = false, features = ["onig", "http"] }
```
Which appears to fix the issue... Unsure why or what was wrong, but I'm sure someone is likely to encounter this.

**Comment by ArthurZucker** [comment]
Hey! Yes you need to compile with the `https` feature for sure! Thanks for digging 🤗
