### ISSUE TITLE
Allow handle a large number of files for Tokenizer training

### ISSUE THREAD

**Issue by andy-yangz** [huggingface/tokenizers#163]
Currently, I am handling a dataset with more than 10000 txt files. When I use "**/*.txt" I get the following error.
![image](https://user-images.githubusercontent.com/23011317/75102123-9875fc00-5621-11ea-8b94-6f8ad31179ef.png)
Although I know it will be quite simple to just handle it by cat them together, I still wonder can there be an improvement to handle this directly.

**Comment by julien-c** [comment]
You might be able to tweak your `ulimit -n` (max amount of file descriptors)

**Comment by n1t0** [comment]
This should also be fixed directly in the next release: 4023bb202ccfc264e4b303a473d650f649aa0c9b
