### ISSUE TITLE
ByteLevelBPETokenizer doesn't merge

### ISSUE THREAD

**Issue by apeguero1** [huggingface/tokenizers#164]
With this vocabulary
{"A":0,"B":1,"AB":2}
and this merge file
A B
tokenizer.encode("AB").ids merges the two bytes and returns [2]  as expected.

However, with {"A":0,"0":1,"A0":2} and A 0
running tokenizer.encode("A0").ids doesn't merge and returns [0,1].

Is this expected?

**Comment by n1t0** [comment]
Yes this is expected. The byte-level pre-tokenizer prevents `A0` to be considered as a single word.
