### ISSUE TITLE
Error installing the tokenizers library with Python 3.13

### ISSUE THREAD

**Issue by KEYTRON** [huggingface/tokenizers#1657]
Expected behavior

The library should install successfully.

Current behavior

An error is raised:
error: the configured Python interpreter version (3.13) is newer than PyO3's maximum supported version (3.12)

Additional Information

**Issue with tokenizers installation**

**Versions:**
- Tokenizers version: Not installed (failed to install)
- PyO3 version: Not installed (failed to install)
- Operating system: macOS 15.0.1
- Python version: 3.13.0
- pip version: 24.2

**Description:**
I encountered an issue while trying to install the `tokenizers` package. The build process fails due to a compatibility issue with the version of PyO3 and the installed version of Python (3.13.0). 

The error message indicates that the configured Python interpreter version (3.13) is newer than PyO3's maximum supported version (3.12). 

**Steps to reproduce:**
1. Create a virtual environment.
2. Run the command `pip install tokenizers`.
3. Observe the error messages regarding the build process.

**Error log:**
[tokenizers_installation_issue.log.txt](https://github.com/user-attachments/files/17422944/tokenizers_installation_issue.log.txt)

**Please provide guidance on how to resolve this issue.**

**Comment by ArthurZucker** [comment]
#1646 is meant to adresse this, and there is a tracker #1639 !

**Comment by yz-al** [comment]
Blocked on this.
