### ISSUE TITLE
Runtime Error in Python 3.8

### ISSUE THREAD

**Issue by msharp9** [huggingface/tokenizers#1691]
My Github Action pipeline failed on importing Transformers after upgrading from tokenizers 0.20.3 to 0.20.4.  Specifically early on this line in my pytest code: `from transformers import AutoModel, AutoTokenizer` 

It passed for python 3.9, 3.10, 3.11, but failed specifically for the Python 3.8.  This is the error:

```
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback): 
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/tokenizers/tokenizers.abi3.so: undefined symbol: PyInterpreterState_Get
```

Looking at the release logs there was a change to abi3: https://github.com/huggingface/tokenizers/releases/tag/v0.20.4.  I'm assuming it's related.

**Comment by kopyl** [comment]
I can't even install it on Python3.8 😭 

<img width="804" alt="image" src="https://github.com/user-attachments/assets/a82df002-4621-4129-8a26-a2c24c81a203">

**Comment by praykabam** [comment]
> I can't even install it on Python3.8 😭 Installing the latest version from git with `pip install git+....` does not work as well.
> 
> This prevents from installing one of the most important ML library – `transformers`.
> 
> I was able to install transformers by installing the previous version of tokenizers with `pip install tokenizers==0.20.3`
> 
> <img alt="image" width="804" src="https://private-user-images.githubusercontent.com/17604849/390227658-a82df002-4621-4129-8a26-a2c24c81a203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzYxMjIsIm5iZiI6MTczMjY3NTgyMiwicGF0aCI6Ii8xNzYwNDg0OS8zOTAyMjc2NTgtYTgyZGYwMDItNDYyMS00MTI5LThhMjYtYTJjMjRjODFhMjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyNTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMzVlYzNiYjdiNTQ2YmE3NTVjOTJhM2EyOGJmMDFhNzFlMzVhMTUyOTg1MTQyZmQ0ZGI4OTkwNTU4MGE3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A6f16DsU4U-eAV2lp1rnU0w0weK16tz-A6-KHGtSRhs">

Same for me

**Comment by xxxjjhhh** [comment]
same for me

my docker env


---

43.94   Downloading tokenizers-0.20.4.tar.gz (343 kB)
43.99   Installing build dependencies: started
46.34   Installing build dependencies: finished with status 'done'
46.35   Getting requirements to build wheel: started
46.40   Getting requirements to build wheel: finished with status 'done'
46.41     Preparing wheel metadata: started
46.48     Preparing wheel metadata: finished with status 'error'
46.48     ERROR: Command errored out with exit status 1:
46.48      command: /usr/bin/python3 /tmp/tmp5xdpfc7d prepare_metadata_for_build_wheel /tmp/tmpxat8knxf
46.48          cwd: /tmp/pip-install-ok9by77y/tokenizers
46.48     Complete output (6 lines):
46.48     
46.48     Cargo, the Rust package manager, is not installed or is not on PATH.
46.48     This package requires Rust and Cargo to compile extensions. Install it through
46.48     the system's package manager or via https://rustup.rs/
46.48     
46.48     Checking for Rust toolchain....

**Comment by xxxjjhhh** [comment]
Problem only occurs in version 3.8

test
3.9 ok
3.10 ok

**Comment by ArthurZucker** [comment]
Yep, I'll try to push the 3.8 version, this is kind of a breaking change that comes from the recent ABI update that we needed. Sorry all!

**Comment by ArthurZucker** [comment]
Abi wheels were introduced in #1674, to reduce the crazy amount of wheels we had

**Comment by ArthurZucker** [comment]
We are gonna yank the release, to have 0.21.0 instead

**Comment by ArthurZucker** [comment]
Closing as the release is yanked!

**Comment by DrownFish19** [comment]
<img width="1232" alt="image" src="https://github.com/user-attachments/assets/a964f668-4914-45e7-ae27-7d4093e13a5f" />

For 0.21.0， remove the abi3 feature, then tokenizers can be compiled.
