### ISSUE TITLE
new release for node-binding and general question w.r.t. node releases

### ISSUE THREAD

**Issue by schiller-manuel** [huggingface/tokenizers#170]
The last release (0.4.1) of node binding is from 14 days ago, so it does not contain the latest fixes. Could you please release a new version for node as well?

What is the versioning scheme used for tokenizers? The rust lib is at 0.7, the python binding at 0.5.2.

Ideally, a new release of both node and python bindings should be released when the rust library is updated, right?

**Comment by Pierrci** [comment]
Hi @schiller-manuel, we try to advance the different bindings at the same pace but it's not always easy (for example, I was out-of-office last week). We will probably publish an updated version for node today or tomorrow. In the meantime, feel free to open a PR if you feel you miss something that you need quickly :)

Regarding the difference in version numbers, we try to follow semantic versioning and all the parts are still considered as "unstable" (<1.0.0). Sometimes we might be introducing breaking changes in the node bindings only, leading to a switch from 0.4.0 to 0.5.0 for example, sometimes in the python ones... without necessary any breaking changes in the rust part.

We envision more stability and unicity in the versioning once we decide we have finally reached a stable state. (@n1t0 feel free to add some input/correct me on this part!)
