### ISSUE TITLE
How in the world can I use a Unigram tokenizer with hf?

### ISSUE THREAD

**Issue by Zirunis** [huggingface/tokenizers#1702]
I'm think I'm going insane. I have trained a tokenizer using google's sentencepiece tokenizer. It produces a .model and a .vocab file. I now want to use this tokenizer for my hf t5 model. It doesn't work. No matter what I try. Either a CUDA crash without an error message or tokenization straight up produces tokens that don't exist.

Here is everything I found:

- [This script](https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py) which is supposed to transform slow tokenizers into fast ones. I don't think I even have a slow tokenizer to begin with? Also no documentation on how to use this anywhere. 

- [This explanation](https://github.com/huggingface/tokenizers/issues/1146#issuecomment-1383764650) how to do exactly what I want except that I read it 12 times and my brain hurts but I still don't understand anything.

- [This forum thread](https://discuss.huggingface.co/t/loading-pretrained-sentencepiece-tokenizer-from-fairseq/1326/3) which discusses the same issue and even has a proposed solution but it is 4 years old and I don't know what protobuf is and whether I need it.

Also the huggingface website which contains videos with horrendous audio quality and the strongest french accents I have ever heard explaining the concepts behind the tokenization techniques but not a single code snippet on how to actually use huggingface's tokenizers.

What I want:
To train a unigram model and use it with huggingface transformers.

1. Either by transforming my .model and .vocab into a huggingface tokenizer OR
2. by training a unigram tokenizer using huggingface tokenizer directly

As I understand it, some people at huggingface have put a lot of work into writing some amazing code to transform any tokenizer into a huggingface tokenizer, it is just not properly documented anywhere. Please help me out.

**Comment by ArthurZucker** [comment]
Arf I am so sorry, you are right 😅 
Here is a small snippet of how to do this easily:
```python
from transformers import SPMConverter

class DummyTokenizer:
    def __init__(model_path="tokenizer.model"):
        self.vocab_file = model_path

class ToTokenizers(SPMConverter):
    def __init__(model_path="tokenizer.model"):
        super().__init__(*args)
        self.original_tokenizer = DummyTokenizer(model_path)

converter_tokenizer = ToTokenizers(path_to_your_file).converted()
```

**Comment by Zirunis** [comment]
Thank you for the quick reply! So that means that the .vocab file is not needed at all?

**Comment by ArthurZucker** [comment]
Yep, the `.vocab` file is gonna be created from the `sentencepiece.model`

**Comment by Zirunis** [comment]
I did not get your code to work, among other reasons because I was unable to import SpmConverter.
Neither your suggested 
```python
from transformers import SPMConverter
```
nor
```python
from transformers import SpmConverter  # correct class name?
```
worked.

However that led me down the rabbit hole of trying to understand the code and after smashing my head against the wall repeatedly I ended up with the following which worked (only because I'm using a T5Tokenizer though, I would've been screwed if I needed a custom one):
```python
from transformers import T5Tokenizer, PreTrainedTokenizerFast, convert_slow_tokenizer
tokenizer = PreTrainedTokenizerFast(tokenizer_object=convert_slow_tokenizer.convert_slow_tokenizer(T5Tokenizer("tokenizer.model", legacy=False)))
```

If this is the only way of doing this, I think it's seriously messed up. But maybe I'm just incompetent and there is a more straightforward way.

**Comment by Zirunis** [comment]
Closing this as - although ugly - I got it to work as described.

**Comment by ArthurZucker** [comment]
Will be adding a new converter that should make it easier! On my TODO! 🤗
