### ISSUE TITLE
Can not add large custom vocab to RobertaTokenizerFast

### ISSUE THREAD

**Issue by DarshanPatel11** [huggingface/tokenizers#175]
I have around **65K** tokens in my custom vocab file and I want to include in the DistilRoberta model to finetune it on my corpus.  I added it on RobertaTokenizer and it was added successfully, but the Tokenization process is very slow. Even with using multiprocessing it is showing that It will take around **200 hrs**.  So I tried to use RobertaTokenizerFast but couldn't add my custom vocab. It failed with an error as follows:
```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CompiledTooBig(10485760)', /__w/tokenizers/tokenizers/tokenizers/src/tokenizer/mod.rs:672:22```
So is there any workaround to add my custom vocab and fast tokenization.
Also, I have a question that Roberta/GPT2 has a "Ġ" character in the vocab, so should I add it as a prefix to my vocab, or not?

**Comment by ameet-1997** [comment]
This issue is still not fixed. It throws the exact same error even with the newest version of tokenizers.

Adding up to `25000` tokens works. Anything more than that doesn't work.

**Comment by ameet-1997** [comment]
@n1t0 , just in case this is useful.

**Comment by n1t0** [comment]
The associated PR increased the capacity a lot, but it is not unlimited. Unfortunately, I believe there is no easy way to increase it even more. I would advise against adding so many tokens anyway as it would make the tokenizer extremely slow.

What kind of use-case makes you add so many tokens?

**Comment by SokolovYaroslav** [comment]
Hi everyone!

I'm trying to fit a custom BPE tokenizer on ~87 million words to make a vocabulary with a size 16384. And I got the same exception: `CompiledTooBig(10485760)`. Also, I've added 1041 special tokens as an argument for the `BpeTrainer`.
I'm training the BPE with the `train_from_iterator` method.

I don't think that my case is somehow large, so I'd rather think that exception isn't expected.

**Comment by kaankork** [comment]
Hi everyone, I'm experiencing the same issue with around 100K new words to add. 
It seems that one possible workaround would be to take the words in a batch of 25000 each time (since @ameet-1997 mentioned this is the limit) and keep iterating until all of them are added.

**Comment by pjuangph** [comment]
How is this issue closed? there's no resolution

**Comment by catsbergers** [comment]
I also have this issue.  Batching to under 25k does not resolve it.

**Comment by Narsil** [comment]
@catsbergers Do you mind providing a script to reproduce ?

Many things have changed since this first issue was made and it's highly unlikely you are encountering the same bug (`CompileTooBig` does not exist anymore for instance).

And slowness of any kind can come from many sources, it can be working as expected (BPE with poor pre_tokenizations is extremely slow for instance) or it could very well be a bug in the lib (we fixed a couple of things recently in that area).

Also which version of `tokenizers` are you running ?
