### ISSUE TITLE
Get most frequent tokens in pre-trained tokenizers

### ISSUE THREAD

**Issue by amir-rahnama** [huggingface/tokenizers#177]
Is it possible to get the most frequent tokens in the vocabulary of pretrained tokenizers?

**Comment by n1t0** [comment]
Provided a way to retrieve the vocabulary with https://github.com/huggingface/tokenizers/pull/208. Will be released started from the `0.7.0-rc3`.

So using `get_vocab` on the `Tokenizer` you can now retrieve the mapping `tokens <-> ids`. The vocabularies generally map (at least for now) the ids starting from the most frequent tokens, so the lower the id, the most frequent the token.

**Comment by tin-chata** [comment]
I think you need to expose the `get_vocab` function in the file `base_tokenizer.py`
