### ISSUE TITLE
"Too many open files" when training a ByteLevel BPETokenizer

### ISSUE THREAD

**Issue by surisdi** [huggingface/tokenizers#178]
Hi, when training a ByteLevelBPETokenizer given a list of `.txt` files, using a code like the following one:
```
from tokenizers import ByteLevelBPETokenizer
tokenizer = ByteLevelBPETokenizer()
tokenizer.train(text_files)
```
if the `text_files` list of `.txt` files is larger than ~1000 files, an "Exception: Too many open files (os error 24)" error appears. A possible solution would be to join all files into a larger one, but sometimes it is not convenient. Is there anything that can be done from the `tokenizers` library? 

Thanks!

**Comment by julien-c** [comment]
Which version of `tokenizers` are you running? @n1t0 recently solved a similar issue.

**Comment by surisdi** [comment]
I am running version 0.5.2

**Comment by julien-c** [comment]
I think fix is on master in 4023bb202ccfc264e4b303a473d650f649aa0c9b

**Comment by surisdi** [comment]
Great, thanks!

**Comment by n1t0** [comment]
Indeed, this has been fixed on master, but not yet released (cf https://github.com/huggingface/tokenizers/issues/163). In the meantime @surisdi, the limit on the number of files that can be opened is actually something set in your OS, so you can increase it. Check this for more information: https://easyengine.io/tutorials/linux/increase-open-files-limit/

**Comment by n1t0** [comment]
`0.6.0` has been released, and should have this working out-of-the-box now!
