### ISSUE TITLE
C/C++ binding interface

### ISSUE THREAD

**Issue by roman-kruglov** [huggingface/tokenizers#185]
Do you guys plan to officially support such a binding? It seems pretty logical, after all Rust produces native code. We have a product in C++ and need to implement a RoBERTa \ GPT2 \ BPE tokenizer. The options are either reimplement it from the python version from transformers or use this rust implementation.

**Comment by julien-c** [comment]
We'd welcome an external contribution to add this support, @roman-kruglov

**Comment by glennkroegel** [comment]
@julien-c Does this mean if we want to use pytorch's jit scripting we are kind of stuck? Not much in the way of using a pytorch module in a Rust app with this tokenizer.

**Comment by Narsil** [comment]
You can use [tch-rs](https://github.com/LaurentMazare/tch-rs) to load models and use tokenizers from Rust if that's a viable option for you.

**Comment by glennkroegel** [comment]
> You can use [tch-rs](https://github.com/LaurentMazare/tch-rs) to load models and use tokenizers from Rust if that's a viable option for you.

If people think it's stable / reliable then it should be fine.

**Comment by alexeyr** [comment]
@julien-c I am planning to work on this.

**Comment by alexeyr** [comment]
I expect to make a draft PR this week (or early next week). It will only have enough classes for BERT tokenizer, to get feedback on the API and design. However, I need [`string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view) (and possibly `optional`). This means one of 3 options, in order of my own preference:

1. Copy https://github.com/martinmoene/string-view-lite/blob/master/include/nonstd/string_view.hpp and the license.
2. Include the repository as a submodule. Most of it isn't actually needed, but I remember there is a way to fetch only the necessary files.
3. Require C++17.

I would strongly prefer to avoid 3. If this repository already had submodules, I'd definitely go with option 2, but adding the first one is a bigger burden IMO. Which would you prefer?

**Comment by n1t0** [comment]
That's great news @alexeyr! I'm looking forward to seeing this!

I think you can go with copying it for now, that seems totally fine.

**Comment by alexeyr** [comment]
One more question then (I was planning to ask in the draft PR, but can as well do it now). For error handling, use exceptions or `expected<T, E>` (which is like the Rust `Result` and again will require a single-header dependency)? Unfortunately, 

1. idiomatic C++ is quite split on this, with many libraries defining their own `Result`-like types;
2. currently the second option still requires exceptions to be enabled, but some future cxx version is likely to change this.

**Comment by n1t0** [comment]
What would you be your take on this? Does being opinionated on this (by picking our preferred `Result`-like types) makes it harder for somebody to use it?

**Comment by alexeyr** [comment]
A bit, yes (especially if they prefer a more "advanced" option like https://boostorg.github.io/leaf/). 

Actually, I thought of a way to make it configurable, so it will throw exceptions by default and let users define macros before including our header files to use a `Result`-like. Let me just try it out and see if it works...

**Comment by alexeyr** [comment]
Looks like it does work (at least compiles):

https://github.com/alexeyr/tokenizers/blob/c35c14833d3b2506616dd859dc73d550255201e2/bindings/cpp/src/tokenizers_util.h#L27-L48

https://github.com/alexeyr/tokenizers/blob/613e208ab5944e8f9d1488ff66947f8580f2d14d/bindings/cpp/src/redefine_result_tests.cpp#L5-L27

**Comment by alexeyr** [comment]
So it took much longer than expected, but here it is.

**Comment by alexeyr** [comment]
Normalizers, pre-tokenizers, and models are done. I will try to finish the remaining parts on Friday, but don't expect any more significant API changes. So if anybody wants to review what is there, now is a good time.

**Comment by mtszkw** [comment]
Hi, how is it going? Are you still working on this one, @alexeyr?

**Comment by alexeyr** [comment]
Hello. I've got sick (and am sick again now). And the project I was working on this for has been cancelled. I'll finish what I have when I get better.

**Comment by mtszkw** [comment]
> Hello. I've got sick (and am sick again now). And the project I was working on this for has been cancelled. I'll finish what I have when I get better.

Oh, okay. Hope you feel better soon!

**Comment by xloem** [comment]
I wasn't sure how to use alexy's bindings to load a file, but although I'm not familiar with rust I got bindings to work well enough to tokenize strings. I just tried things and looked up the errors I encountered until it worked. I figure this could be helpful to others.

test.cpp
```
#include "target/cxxbridge/tinytokenizers/src/lib.rs.h"

#include <iostream>
#include <string>

int main()
{
    rust::Box<Tokenizer> tokenizer = from_file("tokenizer.json");
    rust::Box<Encoding> encoding = tokenizer->encode("Hello, world. Hello, world. Hello, world.", true);
    for ( auto & token : encoding->get_ids()) {
        std::cout << token << " ";
    }
    std::cout << std::endl;
}
```

Cargo.toml
```
[package]
name = "tinytokenizers"
version = "0.1.0"
edition = "2021"

[lib]
name = "tinytokenizers"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
tokenizers = "0.11"

[build-dependencies]
cxx-build = "1.0"
```

build.rs
```
fn main() {
    cxx_build::bridge("src/lib.rs")
        //.file("src/blobstore.cc")
        .compile("tinytokenizers");
}
```

src/lib.rs
```
use tokenizers::tokenizer::{Result, Tokenizer as HFTokenizer, Encoding as HFEncoding};

#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type Tokenizer;
        type Encoding;
        fn from_file(file: &String) -> Result<Box<Tokenizer>>;
        fn encode(self: &Tokenizer, input: String, add_special_tokens: bool) -> Result<Box<Encoding>>;
        fn get_ids(self: &Encoding) -> &[u32];
    }
}

fn from_file(file: &String) -> Result<Box<Tokenizer>> {
    Ok(Box::new(Tokenizer{tokenizer:HFTokenizer::from_file(file)?}))
}

struct Tokenizer {
    tokenizer: HFTokenizer,
}

impl Tokenizer {
    fn encode(&self, input: String, add_special_tokens: bool) -> Result<Box<Encoding>> {
        Ok(Box::new(Encoding{encoding:self.tokenizer.encode(input, add_special_tokens)?}))
    }
}

struct Encoding {
    encoding: HFEncoding
}

impl Encoding {
    fn get_ids(&self) -> &[u32] {
        self.encoding.get_ids()
    }
}
```

linux shell commands
```
cargo build --release
make test LDLIBS='-Ltarget/release -ltinytokenizers -pthread -lssl -lcrypto -ldl'
./test # needs tokenizer.json in same folder
```

**Comment by songkq** [comment]
Sharing a Nice work. https://github.com/mlc-ai/tokenizers-cpp

**Comment by geraldstanje** [comment]
hi any feedback?

**Comment by geraldstanje** [comment]
any infos?

**Comment by ntcuong777** [comment]
Hi guys, is the tokenizer for C++ still on track?

**Comment by guyluz11** [comment]
.

**Comment by jixiedaima** [comment]
.

**Comment by lterrac** [comment]
Hi, is this still planned or was it dismissed?
