### ISSUE TITLE
Questions about token ids in my trained vocabulary vs. Transformers pre-trained vocabulary

### ISSUE THREAD

**Issue by dizzySummer** [huggingface/tokenizers#191]
I have tried different encoding methods that you offered. There are two questions I would like to check with you:

1) Taking the example of BertWordPieceTokenizer: In my vocabulary, the id for [CLS] is 1 and for [SEP] is 2. In your pre-trained vocabulary, the id for [CLS] is 101 and for [SEP] is 102. So the question is when feeding my trained tokens to your pre-trained models e.g. Bert-Base uncased, will my tokens cause any confusion to your pre-trained model and then produce a lower accuracy as the result?  In other words,  the model expected to get 101 as a starting point but got 1 ...

2) What is the right way to set "add_prefix_space" to True in ByteLevelBPETokenizer? I have tried:

     a) from tokenizers import ByteLevelBPETokenizer
         tokenizer = BertWordPieceTokenizer(add_prefix_space=True)

     b)  from tokenizers import ByteLevelBPETokenizer
          tokenizer = BertWordPieceTokenizer()
         tokenizer.add_prefix_space=True

 None of them works. Any comments? Thank you!

**Comment by n1t0** [comment]
Hey @dizzySummer!

1. Every pre-trained model available in `transformers` ships with its own tokenizer. When a model has been trained with a tokenizer, you can't switch it afterwards, unfortunately. Special tokens like `[CLS]` and `[SEP]` may have a different ID as you saw, but any other token in the vocabulary can also be different. So using such a tokenizer wouldn't make any sense for the pre-trained model. If you want to use the`bert-base-uncased` model available in `transformers`, then you should definitely use the `bert-base-uncased` tokenizer also provided in `transformers`.

2. Your first example should work, but you need to initialize a `ByteLevelBPETokenizer` and not a `BertWordPieceTokenizer` which doesn't support this option.

**Comment by dizzySummer** [comment]
Hi @n1t0,

Thanks for your reply! I have been thinking a situation that when such a corpus is not available for some reasons. For example, it’s a special research field or the language belongs to a low resource one. So when a pertained tokenizer is not available and I made my own, I shouldn’t connect it to the pertained model otherwise it will confuse the machine or? 

I would like to know the right way to do it. Thank you!

**Comment by dizzySummer** [comment]
Close now where there is no easy solution. (especially when everybody is worried about pandemic :D). Thanks anyway!
