### ISSUE TITLE
Training a model from in-memory data

### ISSUE THREAD

**Issue by loicbarrault** [huggingface/tokenizers#198]
Hi,
How could I change the code so that it is possible to train a model from  in-memory data instead of using files?
Basically, changing
`tokenizer.train(["wiki.test.raw"], vocab_size=20000)`
by 
`tokenizer.train(data_array, vocab_size=20000)`
considering that **data_array** is e.g. an array of sentences ["First sentence", "second sentence...].
Thanks for your work!
Best, Loic

**Comment by Luckick** [comment]
Refer to https://huggingface.co/docs/tokenizers/training_from_memory for example.
