### ISSUE TITLE
Encode text dataset to items with equal length 

### ISSUE THREAD

**Issue by jwallat** [huggingface/tokenizers#199]
Hi, 

I am trying to load a text dataset (wikitext-103) for language modeling with the transformers library. Since pre-processing the dataset with the transformers tokenizer takes fairly long (> 30 minutes), I am looking at using the faster tokenizers library. 

What I want to do is getting my dataset split into encoded chunks of equal size (in my case with BERT the block size is 512). Is there a function that does exactly that? 

The transformers' run_language_modeling [example](https://github.com/huggingface/transformers/blob/20139b7c8d88f380f1e4e0ae2baf0b0ac9351039/examples/run_language_modeling.py#L86) does it this way: 

`
            tokenized_text = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(text))`

`
                for i in range(0, len(tokenized_text) - block_size + 1, block_size):  
                self.examples.append(tokenizer.build_inputs_with_special_tokens(tokenized_text[i : i + block_size]))`

From what I can tell, in the tokenizers lib, there are no functions for the single steps of tokenization, converting lists of tokens to ids and only adding special tokens to an otherwise prepared encoded list of ids.

Is there maybe another way to get this done?

**Comment by n1t0** [comment]
Hi @jwallat. If you enable truncation and set the max length to 512, the `tokenizers` library should do exactly what you expect.

Here is a quick example of how to enable truncation and get the overflowing encodings:
```python
tokenizer = CharBPETokenizer('vocab.json', 'merges.txt')
tokenizer.enable_truncation(512)

output = tokenizer.encode(text)
print(output)
print(output.overflowing)
```

As a side note, you can now use the fast tokenizers directly from `transformers` if you specify `use_fast=True` in the `from_pretrained` call.

**Comment by jwallat** [comment]
Oh, nice. Exactly what I was looking for. Thanks!
