### ISSUE TITLE
Direct subtokenization for BertWordPieceTokenizer, and tokenizer that records original whitespace for reconstruction

### ISSUE THREAD

**Issue by Santosh-Gupta** [huggingface/tokenizers#204]
Context: I am trying to incorporate this tokenizer library into my preprocessing and prediction pipelines for Bert question and answering. This involves taking position IDs from the Bert output, and making them back to where they were in the original non-normalized text. 

For now, my pipeline does the following:

originaltext -> tokenize (including white space tokens) -> filter out white space tokens -> use transformers tokenizer to normalize subtokenize tokens.

Doing tokenization this way allows to make maps which can point an index from one set of tokens to another; this is ultimately used for highlighting an answer within it's original text using Bert outputs which gives indexes that point to answers in the bert subtokens. 

For the last step, I am using `tokenizer.tokenize(token)`. I am wondering if there's an equivalent for this library. I see that BertWordPieceTokenizer has a `token_to_id` attribute, but this seems to be for tokens where are already in Bert's vocab; it does not subtokenize/normalize tokens. For example, `BertWordPieceTokenizer.token_to_id('biologicalificationize')` will not give an id. 

As for recording whitespaces, currently I am using spaCy for the original split, which also includes whitespaces as tokens in cases where there just isn't a simple ' ' between words. For example, the spaCy tokenized version of 'this \n sentence \t now', will be tokenized to 'this', '\n', 'sentence', '\t', 'now'. These tokens also have a 'whitespace_' attribute to which contains the exact whitespaces in between words. 

I am wondering if any of the tokenizers have something like a 'whitespace_' attribute, to assist in recreation of text from the tokens. A usable alternative would be to record everything that was filtered out, and

**Comment by n1t0** [comment]
Have you tried using the provided `offsets` that come embedded on the output of `encode`? They should let you access the original text and extract an answer, without having to do the mapping by yourself.
