### ISSUE TITLE
Is it possible to convert the tokenized tokens back to sentence?

### ISSUE THREAD

**Issue by Hhhhhhhhhhao** [huggingface/tokenizers#211]
Hi, 

Given a tokenizer, if I have I list of tokens (only tokens, no offsets)

['_I', '_feel', '_the', '_magi, 'c', '.']

How can I convert the tokens back to a sentence?

**Comment by erip** [comment]
`''.join(['_I', '_feel', '_the', '_magi', 'c', '.']).replace('_', ' ').strip()` seems like it should work?

**Comment by n1t0** [comment]
You can also call the `decoder` on the `Tokenizer`:
```python
decoded = tokenizer.decoder.decode(['_I', '_feel', '_the', '_magi, 'c', '.'])
print(decoded)
# "I feel the magic."
```
