### ISSUE TITLE
tokenizer fails for large dataset

### ISSUE THREAD

**Issue by vr25** [huggingface/tokenizers#214]
Hi,

I am trying to replicate this blog-post: https://huggingface.co/blog/how-to-train

I am doing okay for a small set of files but it throws the following error for a larger dataset:

[00:00:00] Count pairs                              █████████████████████████████ 11219    /    11219
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/conda/feedstock_root/build_artifacts/tokenizers_1583876217402/work/tokenizers/src/models/bpe/trainer.rs:373:34
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
  15: rayon::iter::plumbing::Folder::consume_iter
  16: rayon::iter::plumbing::Producer::fold_with
  17: rayon::iter::plumbing::bridge_producer_consumer::helper
  18: std::panicking::try::do_call
  19: __rust_try
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  22: rayon_core::registry::WorkerThread::wait_until_cold
  23: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 3613222800
Aborted

Thanks!

**Comment by ncoop57** [comment]
I'm having the same issue with a dataset

**Comment by n1t0** [comment]
Can you provide some way to reproduce this bug?

**Comment by n1t0** [comment]
Fixed by https://github.com/huggingface/tokenizers/pull/286
