### ISSUE TITLE
NodeJS Build Error

### ISSUE THREAD

**Issue by ayir** [huggingface/tokenizers#217]
I have been trying to use the node bindings of tokenizers for a project with tf-js but when I build the project I run into a weird issue. 

```
/PycharmProjects/chrome-extension/node_modules/tokenizers/bindings/native.js:1:23: 
Cannot resolve dependency '../bin-package' at '/PycharmProjects/chrome-extension/node_modules/tokenizers/bin-package'
> 1 | const native = require("../bin-package");
    |                       ^
  2 | module.exports = native;
```

Platform - Mac OS10.14 
Tokenizers Version: 0.6.1

**Comment by Pierrci** [comment]
Hi @ayir, can you tell me which version of Node.js you're using?

**Comment by Pierrci** [comment]
Are you trying to create a chrome extension (from your path in the first line)? If so, you can only use Tokenizers in a Node.js environment, and a chrome extension is not such an environment unfortunately :/

**Comment by n1t0** [comment]
Closing this, feel free to reopen if needed,
