### ISSUE TITLE
How to load sentencepiece model file into SentencePieceBPETokenizer?

### ISSUE THREAD

**Issue by acmilannesta** [huggingface/tokenizers#225]
I tried to load pretrained Xlnet sentencepiece model file (spiece.model), But the ```SentencePieceBPETokenizer``` requires vocab and merges file. How can I create these two files?
Thanks!

**Comment by sdadas** [comment]
You can use [sentencepiece_extractor.py](https://github.com/huggingface/tokenizers/blob/master/bindings/python/scripts/sentencepiece_extractor.py) to convert your sentencepiece model to vocab and merges format. However, the converted model doesn't always work exactly as the original. For some sentences, it produces a different list of pieces. 

I'm not sure if this is a bug, or a known limitation of the conversion process and it is not possible to replicate the original model accurately.

**Comment by n1t0** [comment]
Indeed, this script doesn't allow an exact match with sentencepiece at the moment. We are currently working on improving the compatibility and providing support for the Unigram model though. It should land in tokenizers in the coming month or so.

**Comment by acmilannesta** [comment]
> Indeed, this script doesn't allow an exact match with sentencepiece at the moment. We are currently working on improving the compatibility and providing support for the Unigram model though. It should land in tokenizers in the coming month or so.

Thank you! I just would like to get the offset map. If I used the transformers.XLNetTokenizer, I could get the offset by using the ```encode_plus``` and ```return_offsets_mapping ``` but it will give implementation error.

**Comment by n1t0** [comment]
Indeed, this will be possible once we support the `Unigram` that is used for these tokenizers. cf https://github.com/huggingface/tokenizers/issues/53

**Comment by KeremTurgutlu** [comment]
Does it mean it's not possible to construct a pretrained `xlm-roberta-base` tokenizer similar to `AutoTokenizer.from_pretrained("xlm-roberta-base")` ? It would be very nice to speed up processing with the Rust implementation :)
