### ISSUE TITLE
gpt2 returns word-level tokens with byte-level bpe

### ISSUE THREAD

**Issue by petulla** [huggingface/tokenizers#228]
hi I'm using huggingface's pretrained gpt2-large vocab.json and merge.txt to tokenize at the byte level. But i seem to be getting back word-level tokens. 

Is this the level of subword tokenization expected? I wasn't able to find an example of loading a pre-trained gpt2 vocab for tokenization.

```
bgpt2 = ByteLevelBPETokenizer(vocab_file='/gpt2/large/vocab.json', merges_file="/gpt2/large/merges.txt", add_prefix_space=True)

b = bgpt2.encode("This is a combination of a sentence about separate Apple products.")
print(b.tokens)
print(b.ids)
```
Output
```
['ĠThis', 'Ġis', 'Ġa', 'Ġcombination', 'Ġof', 'Ġa', 'Ġsentence', 'Ġabout', 'Ġseparate', 'ĠApple', 'Ġproducts', '.']
[770, 318, 257, 6087, 286, 257, 6827, 546, 4553, 4196, 3186, 13]
```

I do see if I try:

```
b = bgpt2.encode("Ilikeeatingapple")
print(b.tokens)
print(b.ids)
```

BPE returns:

```
['ĠI', 'like', 'eating', 'apple']
[314, 2339, 30041, 18040]
```

I just assumed the words would be broken down into finer subunits.

**Comment by n1t0** [comment]
Hi @petulla. This is a byte-level tokenizer, but it doesn't mean that you will only see bytes. The byte here is the smallest token you can find. The 256 first tokens in the vocabulary actually represent single bytes. But then your tokenizer learns some bigger tokens, composed from smaller ones, up to the target vocabulary size. In this case, the vocabulary you are using simply learned about those words so it has tokens to represents them. Does it make sense?

**Comment by Narsil** [comment]
Hi @ZeyiLiao ,

this is a very old issue, do you mind creating a new post ?
But looking at your message is seems you might want to take a look at https://discuss.huggingface.co/ where you can probably already find the answer to your question (If you don't just ask there).

And try to give more examples, I didn't really understand what you didn't understand.
