### ISSUE TITLE
New Tokens Aren't Saved

### ISSUE THREAD

**Issue by AdityaSoni19031997** [huggingface/tokenizers#233]
Let's say i am new tokens to existing `tokenizers.ByteLevelBPETokenizer`; Upon calling `tokenizers.ByteLevelBPETokenizer.save()`, I was expecting it will save the vocab_file etc including the new tokens i have added so that i can load it from there next time going forward; But to my surprise, it doesn't happen that way;

Code to reproduce the same,

```
TOKENIZER = tokenizers.ByteLevelBPETokenizer(
        vocab_file=f"{ROBERTA_PATH}/vocab.json", 
        merges_file=f"{ROBERTA_PATH}/merges.txt", 
        lowercase=True,
        add_prefix_space=True
)
new_tks = ["your_fav_tok_1",  "your_fav_tok_2", ...]
TOKENIZER.add_tokens(new_tks)
TOKENIZER.save(".") # save them
>Tokenizer(vocabulary_size=50268, model=ByteLevelBPE, add_prefix_space=True, lowercase=True, dropout=None, unicode_normalizer=None, continuing_subword_prefix=None, end_of_word_suffix=None)

# now let's reload from the cached version;

NEW_TOKENIZER = tokenizers.ByteLevelBPETokenizer(
    vocab_file=f"./vocab.json", # saved file
    merges_file=f"./merges.txt", #saved_file
    lowercase=True,
    add_prefix_space=True
)
NEW_TOKENIZER
>Tokenizer(vocabulary_size=50265, model=ByteLevelBPE, add_prefix_space=True, lowercase=True, dropout=None, unicode_normalizer=None, continuing_subword_prefix=None, end_of_word_suffix=None)
```

tokenizers_version -> '0.5.2'

**Comment by Nix07** [comment]
I am also facing this issue. The newly added tokens do not get saved using `tokenizer.save()` method.

**Comment by AdityaSoni19031997** [comment]
You can re-add them again;

**Comment by n1t0** [comment]
Indeed. At the moment the `ByteLevelBPETokenizer` and any other implementation we provide only save the vocabulary of their model. So here you end up with a `BPE` vocabulary, but not an entire saved `Tokenizer`.

This will be possible when we have https://github.com/huggingface/tokenizers/issues/15 on which I am working. So the support should arrive probably in the next month or so.

Closing this issue, please continue the conversation in https://github.com/huggingface/tokenizers/issues/15 if needed.
