### ISSUE TITLE
Any plan to binding to java?

### ISSUE THREAD

**Issue by ericxsun** [huggingface/tokenizers#242]

**Comment by erip** [comment]
I was curious about this, too. I might try to cobble together a PR to generate JNI bindings.

**Comment by julien-c** [comment]
We'd welcome a PR.

**Comment by Pierrci** [comment]
There was a very early effort by @mfuntowicz on https://github.com/huggingface/tokenizers/tree/java-binding using Kotlin, maybe it can be a good starting point (or feel free to start from scratch again if you prefer!)
