### ISSUE TITLE
Training own Tokenizer

### ISSUE THREAD

**Issue by yeozertas** [huggingface/tokenizers#243]
Hello,
I can find some tokenizers which I can use as tokenizer and create my own vocabulary (BertWordPieceTokenizer, ByteLevelBPETokenizer, SentencePieceBPETokenizer and like that). 
However, I have one question? Is it possible to train my own tokenizer with my rules? 
For example; Don't split "-" words , but split "_" words .

**Comment by n1t0** [comment]
Hi @yeozertas. The tokenizers you mentioned (`ByteLevelBPETokenizer`, `BertWordPieceTokenizer`, ..) are implementations we provide to showcase what's possible. You can actually build a `Tokenizer` all by yourself, specifying exactly the parts that you would like to use, and then train it for example. If you want to check the actual code of these implementations, here it is: https://github.com/huggingface/tokenizers/blob/master/bindings/python/tokenizers/implementations/

A `Tokenizer`, as defined in this library, works as a pipeline. The text that you provide goes through the following steps:
 1. Normalization through a `Normalizer`: This is where you transform the raw text as you want it. Lower-casing, Unicode normalization, stripping accents, etc.. would be normalization steps.
 2. PreTokenization through a `PreTokenizer`: This is the step that takes care of splitting the text somehow. If for example you want to split on `_`, then you can attach the `CharDelimiterSplit` to your tokenizer.
 3. Actual Tokenization, through what we call the `Model`: This is the most important part of your `Tokenizer`, the actual tokenization algorithm that will be used. To this day, we provide `BPE`, `WordPiece` and the `WordLevel` models.

There are some other components that can be attached to your `Tokenizer` if needed but the 3 above are the most important. The only one that is actually mandatory is the `Model`. You can find a list with each component and their documentation here: [Normalizer](https://github.com/huggingface/tokenizers/blob/master/bindings/python/tokenizers/normalizers/__init__.pyi), [PreTokenizer](https://github.com/huggingface/tokenizers/blob/master/bindings/python/tokenizers/pre_tokenizers/__init__.pyi), [Model](https://github.com/huggingface/tokenizers/blob/master/bindings/python/tokenizers/models/__init__.pyi).

Now that you know all this, I'll show you a quick example of a `BPE` tokenizer, that just splits on `_`, after having lowercased the text:
```
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.normalizers import Lowercase
from tokenizers.pre_tokenizers import CharDelimiterSplit

# We build our custom tokenizer:
tokenizer = Tokenizer(BPE()) 
tokenizer.normalizer = Lowercase()
tokenizer.pre_tokenizer = CharDelimiterSplit('_')

# We can train this tokenizer by giving it a list of path to text files:
tokenizer.train(files, special_tokens=["[UNK]"])

# And now it is ready, we can save the vocabulary with
tokenizer.model.save('./save_directory', 'tokenizer-name')

# And simply use it
tokenizer.encode('Hello_there!')
```

**Comment by yeozertas** [comment]
Thanks for your reply. Actually I want to tokenize dates as one token like 16.02.2019, 16 Feb 2019 and so on. But I couldn't find any pretokenizer for that. How can I handle this?

**Comment by yeozertas** [comment]
Thanks for your reply. Actually I want to tokenize dates as one token like 16.02.2019, 16 Feb 2019 and so on. I created my own tokenizer on Python with no huggingface tokenizer module. How can I bind it with huggingface tokenizer?

**Comment by ivanjacobsec** [comment]
Hi thx for the example.
It worked for me with the following modif
`tokenizer = Tokenizer(BPE.empty()) `

**Comment by n1t0** [comment]
This library can help you train tokenizers in an unsupervised manner, but not really with hardcoded rules like for dates. This is something that you will need to do manually, and regular expressions are probably better suited for this use case.
