### ISSUE TITLE
Simple WordLevelTokenizer

### ISSUE THREAD

**Issue by jaymody** [huggingface/tokenizers#244]
I was wondering if there are plans to implement a plain `WordLevelTokenizer` implementation that splits only via whitespace (similar to https://github.com/huggingface/tokenizers/issues/3774 and https://github.com/huggingface/tokenizers/issues/232).

I see that much of the infrastructure for that is already in place, so I attempted to create it myself (this one is specific to BERT for post processing):

``` python
class WordLevelBertTokenizer(BaseTokenizer):
    """ WordLevelBertTokenizer
    Represents a simple word level tokenization for BERT.
    """

    def __init__(
        self,
        vocab_file: Optional[str] = None,
        unk_token: Union[str, AddedToken] = "[UNK]",
        sep_token: Union[str, AddedToken] = "[SEP]",
        cls_token: Union[str, AddedToken] = "[CLS]",
        pad_token: Union[str, AddedToken] = "[PAD]",
        mask_token: Union[str, AddedToken] = "[MASK]",
        lowercase: bool = False,
        unicode_normalizer: Optional[str] = None,
    ):
        if vocab_file is not None:
            tokenizer = Tokenizer(WordLevel(vocab_file))
        else:
            tokenizer = Tokenizer(WordLevel())

        # Let the tokenizer know about special tokens if they are part of the vocab
        if tokenizer.token_to_id(str(unk_token)) is not None:
            tokenizer.add_special_tokens([str(unk_token)])
        if tokenizer.token_to_id(str(sep_token)) is not None:
            tokenizer.add_special_tokens([str(sep_token)])
        if tokenizer.token_to_id(str(cls_token)) is not None:
            tokenizer.add_special_tokens([str(cls_token)])
        if tokenizer.token_to_id(str(pad_token)) is not None:
            tokenizer.add_special_tokens([str(pad_token)])
        if tokenizer.token_to_id(str(mask_token)) is not None:
            tokenizer.add_special_tokens([str(mask_token)])

        # Check for Unicode normalization first (before everything else)
        normalizers = []

        if unicode_normalizer:
            normalizers += [unicode_normalizer_from_str(unicode_normalizer)]

        if lowercase:
            normalizers += [Lowercase()]

        # Create the normalizer structure
        if len(normalizers) > 0:
            if len(normalizers) > 1:
                tokenizer.normalizer = Sequence(normalizers)
            else:
                tokenizer.normalizer = normalizers[0]

        tokenizer.pre_tokenizer = pre_tokenizers.WhitespaceSplit()

        if vocab_file is not None:
            sep_token_id = tokenizer.token_to_id(str(sep_token))
            if sep_token_id is None:
                raise TypeError("sep_token not found in the vocabulary")
            cls_token_id = tokenizer.token_to_id(str(cls_token))
            if cls_token_id is None:
                raise TypeError("cls_token not found in the vocabulary")

            tokenizer.post_processor = processors.BertProcessing(
                (str(sep_token), sep_token_id), (str(cls_token), cls_token_id)
            )

        parameters = {
            "model": "WordLevel",
            "unk_token": unk_token,
            "sep_token": sep_token,
            "cls_token": cls_token,
            "pad_token": pad_token,
            "mask_token": mask_token,
            "lowercase": lowercase,
            "unicode_normalizer": unicode_normalizer,
        }

        super().__init__(tokenizer, parameters)
```

However when I pass in a valid `vocab_file` that looks like this:
```
{
  "0": "[PAD]",
  "1": "[UNK]",
  "2": "[CLS]",
  "3": "[SEP]",
  "4": "[MASK]",
  "5": "violence",
  "6": "threes",
  ...
  "44040": "fanaticism",
  "44041": "tendency",
  "44042": "stopover",
  "44043": "peacemaker"
}
```
it doesn't actually load the vocab dict in this line `tokenizer = Tokenizer(WordLevel(vocab_file))`. This results in an error being thrown at 
```python
if sep_token_id is None:
    raise TypeError("sep_token not found in the vocabulary")
```
As the tokenizers internal vocab is empty.

I know that this is a WIP repository, so what I'm asking may not be possible atm, but if it is, would anyone be able to shed some light on what I need to fix? Are there plans to add tokenizer implementations for simple tokenizers like the one above?

**Comment by jaymody** [comment]
Woops, that was a silly mistake on my end, that fixed my issue. I also had to pass in the `unk_token` to the `WordLevel` constructor, since it was giving me an error when trying to tokenize strings with unknown tokens in them. @n1t0  Are there any plans to add simple tokenizers like this under implementation? I wouldn't minding taking up the task of creating a more general/robust implementation of a simple whitespace tokenizer.

**Comment by n1t0** [comment]
Awesome, I'm glad it fixed it! You are right there is no `WordLevel` trainer at the moment, but we'll add one. 

Otherwise, there is no plan to add simple tokenizers like this one since it is extremely simple to write your own one, for your own needs. I think it doesn't make sense to provide a class for every possible tokenizer.

**Comment by kkpsiren** [comment]
Great work guys but any updates on the ```WordLevel``` implementation? Implementing the above to the 02-transformers.ipynb notebook is not trivial.

**Comment by rpoli40** [comment]
@n1t0 I paid attention there is a new code https://github.com/huggingface/tokenizers/tree/master/tokenizers/src/models
What is the difference between wordpiece and wordlevel tokenization? How can it be used in https://huggingface.co/blog/how-to-train if I want to create my own tokenizer that splits only via whitespace or ",". I have only sequence of numbers instead of text in my input. For example: 12345 3456 66645 9883333.
