### ISSUE TITLE
Need help ASAP 🙏

### ISSUE THREAD

**Issue by mrm8488** [huggingface/tokenizers#246]
Hi, guys.
I was admitted in TFRC. I have 30 days to use their TPUs for researching. I have found they have a template for training a RoBERTa like model in its TPUs.
The problem is that it is for English and they use GPT2/encoder.json and GPT2/vocab.bpe.
I need to create both files for my Spanish corpus. Huggingface/Transformers has a tuto to do It but it is not generated a bpe file. Do you know how could I create that files or something that works instead? I will add follow the code they use:

**Comment by mrm8488** [comment]
```bash
mkdir -p gpt2_bpe
wget -O gpt2_bpe/encoder.json https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json
wget -O gpt2_bpe/vocab.bpe https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/vocab.bpe
for SPLIT in train valid test; do \
    python -m examples.roberta.multiprocessing_bpe_encoder \
        --encoder-json gpt2_bpe/encoder.json \
        --vocab-bpe gpt2_bpe/vocab.bpe \
        --inputs wikitext-103-raw/wiki.${SPLIT}.raw \
        --outputs wikitext-103-raw/wiki.${SPLIT}.bpe \
        --keep-empty \
        --workers 60; \
done
```

**Comment by mrm8488** [comment]
And they load both files like this
```python
class MultiprocessingEncoder(object):

    def __init__(self, args):
        self.args = args

    def initializer(self):
        global bpe
        bpe = get_encoder(self.args.encoder_json, self.args.vocab_bpe)
```

**Comment by n1t0** [comment]
I think `vocab.bpe` corresponds to the `merges.txt` generated with `tokenizers`, and similarly `encoder.json` is the `vocab.json` from `tokenizers`.

**Comment by mrm8488** [comment]
So,
```python
bpe = get_encoder(vocab.json, merges.txt)
```
Should work? 
Thanks in advance!

**Comment by mrm8488** [comment]
Hi, @n1t0. I trained my RoBERTa model on Spanish corpus and tokenized it with tokenizers library in the same way that it is done in Training a MLM from scratch colab:

```python
from pathlib import Path
from tokenizers import ByteLevelBPETokenizer

paths = [str(x) for x in Path("./data").glob("**/*.txt")]

# Initialize a tokenizer
tokenizer = ByteLevelBPETokenizer()

# Customize training
tokenizer.train(files=[paths], vocab_size=52_000, min_frequency=2, special_tokens=[
    "<s>",
    "<pad>",
    "</s>",
    "<unk>",
    "<mask>",
])
```

Then I did

```sh
for SPLIT in train valid test; do \
    python -m examples.roberta.multiprocessing_bpe_encoder \
        --encoder-json vocab.json \
        --vocab-bpe merges.txt \
        --inputs corpus.${SPLIT}.raw \
        --outputs corpus.${SPLIT}.bpe \
        --keep-empty \
        --workers 60; \
done
```
Everything seemed to work fine. Training finished OK. But today I tried the final model and I found this:

```python
from transformers import  AutoTokenizer, AutoModelWithLMHead

tokenizer = AutoTokenizer.from_pretrained("mrm8488/RuPERTa-base")

model = AutoModelWithLMHead.from_pretrained("mrm8488/RuPERTa-base")

from transformers import pipeline

roberta_pipeline = pipeline("fill-mask", model=model, tokenizer=tokenizer, topk=50)

roberta_pipeline("el sol es <mask> siempre")

#Output:
[{'score': 0.8408392071723938,
  'sequence': '<s> el sol es<mask> siempre</s>',
  'token': 4},
 {'score': 0.00802671816200018,
  'sequence': '<s> el sol es� siempre</s>',
  'token': 170},
 {'score': 0.00783813651651144,
  'sequence': '<s> el sol eslí siempre</s>',
  'token': 1354},
 {'score': 0.006041793618351221,
  'sequence': '<s> el sol es" siempre</s>',
  'token': 6},
 {'score': 0.003937535919249058,
  'sequence': '<s> el sol esler siempre</s>',
  'token': 2220},
 {'score': 0.0038569695316255093,
  'sequence': '<s> el sol es</s> siempre</s>',
  'token': 2},
 {'score': 0.0025600173976272345,
  'sequence': '<s> el sol es< siempre</s>',
  'token': 32},
...
```
As you can see, it does not make sense... Did I miss anything in the tokenization and binarization process described below?
Thank you in advance!

**Comment by n1t0** [comment]
This might be related to a bug that was fixed on `transformers` side, and part of the latest released `2.9.0`. Seems to work when I try it, can you confirm @mrm8488?

**Comment by mrm8488** [comment]
But, do I have to create the tokenizer again?

**Comment by n1t0** [comment]
I ran your code snippet with the last version of `transformers`:

```
from transformers import  AutoTokenizer, AutoModelWithLMHead

tokenizer = AutoTokenizer.from_pretrained("mrm8488/RuPERTa-base")

model = AutoModelWithLMHead.from_pretrained("mrm8488/RuPERTa-base")

from transformers import pipeline

roberta_pipeline = pipeline("fill-mask", model=model, tokenizer=tokenizer, topk=50)

roberta_pipeline("el sol es <mask> siempre")
```

**Comment by mrm8488** [comment]
Ok, latest version is fine tuned for LM on Spanish Wikipedia

**Comment by n1t0** [comment]
I'm not sure I am following you here

**Comment by mrm8488** [comment]
I think the problem was from my side. I had to fine tune the model for LM first to obtain coherent results. Thanks, again

**Comment by n1t0** [comment]
Oh ok! There was also a bug with the `<mask>` token for Roberta in a previous version of `tokenizers`. Nothing to change on your side, just needed an up-to-date version and the latest `transformers` brought that. Happy that everything is working fine now!

**Comment by mrm8488** [comment]
Thank you so much for the support!
