### ISSUE TITLE
How to add some new special tokens to a pretrained tokenizer?

### ISSUE THREAD

**Issue by ky941122** [huggingface/tokenizers#247]
Hi guys. I want to add some new special tokens like `[XXX]` to a pretrained `ByteLevelBPETokenizer`, but I can't find how to do this in python.

**Comment by jaymody** [comment]
Looks like you can add special tokens to the tokenizer via:

```
tokenizer = ByteLevelBPETokenizer(...)  
tokenizer.add_special_tokens(["[XXX]"])
```

**Comment by ky941122** [comment]
> Looks like you can add special tokens to the tokenizer via:
> 
> ```
> tokenizer = ByteLevelBPETokenizer(...)  
> tokenizer.add_special_tokens(["[XXX]"])
> ```

thanks for replying, but this method seems to expand the vocab. How can I make the pretrained transformers model's embedding layer to match it?

**Comment by jaymody** [comment]
If you're using a pretrained roberta model, it will only work on the tokens it recognizes in it's internal set of embeddings thats paired to a given token id (which you can get from the pretrained tokenizer for roberta in the `transformers` library). I don't see any reason to use a different tokenizer on a pretrained model other than the one provided by the `transformers` library. I guess I'm confused about what you're trying to achieve.

**Comment by n1t0** [comment]
There is no way to add a **new** token to a tokenizer without changing the vocabulary. Otherwise, as @jaymody pointed out, `.add_special_tokens` is the way to go.

**Comment by djstrong** [comment]
We can add a special token to a tokenizer. How to expand embedding layer in pretrained model for the new token? It can be randomly initialized and optionally finetuned.

**Comment by Ar9av** [comment]
Following

> We can add a special token to a tokenizer. How to expand embedding layer in pretrained model for the new token? It can be randomly initialized and optionally finetuned.

**Comment by anuragshas** [comment]
> We can add a special token to a tokenizer. How to expand embedding layer in pretrained model for the new token? It can be randomly initialized and optionally finetuned.

Following

**Comment by djstrong** [comment]
Try this and give feedback:
```
special_tokens_dict = {'additional_special_tokens': ['[C1]','[C2]','[C3]','[C4]']}
num_added_toks = model.tokenizer.add_special_tokens(special_tokens_dict)
model.model.resize_token_embeddings(len(model.tokenizer))
```

**Comment by n1t0** [comment]
Also, feel free to ask on https://discuss.huggingface.co which is more suited for general questions and discussions.

**Comment by Ar9av** [comment]
> Try this and give feedback:
> 
> ```
> special_tokens_dict = {'additional_special_tokens': ['[C1]','[C2]','[C3]','[C4]']}
> num_added_toks = tokenizer.add_special_tokens(special_tokens_dict)
> model.resize_token_embeddings(len(tokenizer))
> ```

Thanks but how are new embeddings initialised? Are they random? Won't that be wrong

**Comment by djstrong** [comment]
They are random and you can set them as you like or finetune.

**Comment by sachinruk** [comment]
@djstrong Just a question about adding special tokens as above, would it change the embedding values of the existing words that are in the pretrained tokenizer?

Just trying to make sure that it's only the values that are randomly intialised.

**Comment by djstrong** [comment]
No, it would not change embeddings in pretrained model.

**Comment by nrjvarshney** [comment]
So, If I finetune a model, then the embedding of the new token will be learned and of the old tokens will stay the same? @sachinruk

**Comment by dhumketu** [comment]
> So, If I finetune a model, then the embedding of the new token will be learned and of the old tokens will stay the same? @sachinruk

No, when you finetune, any embedding can change by definition. But the change "amount" will depend on your data set size.

**Comment by AlafateABULIMITI** [comment]
Hi all,

I have try the method above, that worked! I want to ask one more question. When I reload my model from my checkpoint, it gave me the `size mismatch`, does someone know how to fix this? Thank you!

**Comment by Narsil** [comment]
@AlafateABULIMITI  Can you provide more context about this error itself, and ideally some minimal example to reproduce ?

**Comment by Narsil** [comment]
> Maybe I can look how manually save model with save_pretrained.

Maybe, sorry I don't really know `pytorch-lightning`, I have used it in the past, it's a great library, but I have the intuition something is not happening correctly in the interaction of `pytorch-lightning` and `transformers` here. 

Btw, next time don't hesitate to open an new issue with a reference to the old one, it helps make issues become more searchable.

Cheers.

**Comment by AlafateABULIMITI** [comment]
Thank you @Narsil !

**Comment by brando90** [comment]
> Try this and give feedback:
> 
> ```
> special_tokens_dict = {'additional_special_tokens': ['[C1]','[C2]','[C3]','[C4]']}
> num_added_toks = tokenizer.add_special_tokens(special_tokens_dict)
> model.resize_token_embeddings(len(tokenizer))
> ```

this is measleading. It doesn't add them, it overwrites them afaik.

All I want to do is add all standard special tokens in case they aren't there e.g. `<s>` sep token is not in t5 for some reason. 

I wrote this but not super happy with it.

```
def does_t5_have_sep_token():
    tokenizer: PreTrainedTokenizerFast = AutoTokenizer.from_pretrained('t5-small')
    assert isinstance(tokenizer, PreTrainedTokenizerFast)
    print(tokenizer)
    print(f'{len(tokenizer)=}')
    # print(f'{tokenizer.all_special_tokens=}')
    print(f'{tokenizer.sep_token=}')
    print(f'{tokenizer.eos_token=}')
    print(f'{tokenizer.all_special_tokens=}')

    special_tokens_dict = {'additional_special_tokens': ['<bos>', '<cls>', '<s>'] + tokenizer.all_special_tokens }
    num_added_toks = tokenizer.add_special_tokens(special_tokens_dict)

    print(f'{tokenizer.sep_token=}')
    print(f'{tokenizer.eos_token=}')
    print(f'{tokenizer.all_special_tokens=}')



if __name__ == '__main__':
    does_t5_have_sep_token()
    print('Done\a')
```

**Comment by brando90** [comment]
https://discuss.huggingface.co/t/how-to-add-all-standard-special-tokens-to-my-tokenizer-and-model/21529

**Comment by CryingBI** [comment]
@djstrong hi, can you show me how to setup them to constant?


> They are random and you can set them as you like or finetune.

**Comment by CryingBI** [comment]
> No need to add anything. Just change the vocab.txt and set the "additional_special_tokens" arg in BertTokenizer.from_pretrained().
> 
> Ref: https://huggingface.co/docs/transformers/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.from_pretrained

Thank you ^^. I have found it. But I am looking for the way to set the representation of special tokens constant after training one task.

I am working on BERT model in relation extraction problems in continuous learning context. My model consists of 2 main blocks: 1 is the BERT encoder and 1 is the projection head.

Pairs (E11, E12) and (E21, E22) will wrap between entities.
I want the representation of the above 4 tokens, after going through the BERT encoder block through each Task, will have exactly the same representation. How should I do it?, thanks.
