### ISSUE TITLE
token_to_id return None

### ISSUE THREAD

**Issue by lingdavid** [huggingface/tokenizers#250]
tokenizers version: 0.7.0
`tokenizer = BertWordPieceTokenizer(vocab_file='./vocabulary/vocab_small.txt', lowercase=True)
print(tokenizer.token_to_id("...")`
output is 'None',not a int number.
oov token will return None,it is a bug or?

**Comment by n1t0** [comment]
It is the expected behavior. You are trying to get the id associated with a token, but it does not exist. Choosing to use some other id, in this case, is up to you.
