### ISSUE TITLE
ValueError: logits and labels must have the same shape ((None, 1) vs ())

### ISSUE THREAD

**Issue by Rose-25** [huggingface/tokenizers#253]
a part of relative code

import tensorflow_datasets as tfds
imdb, info = tfds.load('imdb_reviews/subwords8k', with_info=True, as_supervised=True)

train_data, test_data = imdb['train'], imdb['test']
tokenizer = info.features['text'].encoder

import tensorflow.keras as keras
embedding_dim = 64

model = keras.Sequential([
    keras.layers.Embedding(tokenizer.vocab_size, embedding_dim),
    keras.layers.GlobalAveragePooling1D(),
    keras.layers.Dense(6, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.summary()

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

history = model.fit(train_data, epochs=10, validation_data=test_data)

ValueError: logits and labels must have the same shape ((None, 1) vs ())
there are  not any code of padding sequences,so how can i resolve it

**Comment by neo2049** [comment]
I am also experiencing the same issue.

**Comment by n1t0** [comment]
It seems to me that this is an issue with `tfds`, I don't really see the link with `tokenizers` (this project)

**Comment by Rose-25** [comment]
> I am also experiencing the same issue.

Maybe the point is 'tokenizer = info.features['text'].encoder',Setting a different shape between logits and labels defaultly?

**Comment by Rose-25** [comment]
> It seems to me that this is an issue with `tfds`, I don't really see the link with `tokenizers` (this project)

I think the tokenizer is used in the first layer of the model I mentioned

**Comment by barrycforever** [comment]
I ran into this problem too.

As stated by Samo Šela in the Coursera Natural Language Processing in TensorFlow course (week 2):

> I suppose you had a problem with the dimensionality of the training data.
> E.g.: ValueError: logits and labels must have the same shape ((None, 1) vs ())
> 
> ... A solution is to add the missing dimension to the labels:
> 
> ```
> train_data = train_data.map(lambda x_text, x_label: (x_text, tf.expand_dims(x_label, -1)))
> test_data = test_data.map(lambda x_text, x_label: (x_text, tf.expand_dims(x_label, -1)))
> 
> ```

**Source:** https://www.coursera.org/learn/natural-language-processing-tensorflow/discussions/weeks/2/threads/Ve2CRz4IT4utgkc-CE-Lxg

**Comment by Chacha-J** [comment]
adding a flatten layer before the output layer helps

**Comment by rbi-international** [comment]
It worked. Thanks!!!
