### ISSUE TITLE
encoding problem when training for Russian 

### ISSUE THREAD

**Issue by janyfe** [huggingface/tokenizers#254]
```
from tokenizers import ByteLevelBPETokenizer

# path = [txt files with some text in Russian]

# Initialize a tokenizer
tokenizer = ByteLevelBPETokenizer()

# Customize training
tokenizer.train(files=paths, vocab_size=52_000, min_frequency=2, special_tokens=[
    "<s>",
    "<pad>",
    "</s>",
    "<unk>",
    "<mask>",
])

# Save files to disk
tokenizer.save(".", "dbg_bpe")

from tokenizers.implementations import ByteLevelBPETokenizer

tokenizer = ByteLevelBPETokenizer(
    './dbg_bpe-vocab.json',
 './dbg_bpe-merges.txt'
)

z = tokenizer.encode('честное слово написано прям руками')

print(z.tokens)

['ÑĩÐµÑģÑĤ', 'Ð½Ð¾Ðµ', 'ĠÑģÐ»Ð¾Ð²Ð¾', 'ĠÐ½Ð°Ð¿Ð¸ÑģÐ°Ð½Ð¾', 'ĠÐ¿ÑĢÑıÐ¼', 'ĠÑĢÑĥÐºÐ°Ð¼Ð¸']
```

Is it possible to train tokenizer for Russian?

**Comment by janyfe** [comment]
`import ftfy
repaired = [ftfy.fix_text(elem) for elem in z.tokens]

for b, g in zip(z.tokens, repaired):
    print(b, g)

ÑĩÐµÑģÑĤ ÑĩÐµÑģÑĤ
Ð½Ð¾Ðµ ное
ĠÑģÐ»Ð¾Ð²Ð¾ ĠÑģÐ»Ð¾Ð²Ð¾
ĠÐ½Ð°Ð¿Ð¸ÑģÐ°Ð½Ð¾ ĠÐ½Ð°Ð¿Ð¸ÑģÐ°Ð½Ð¾
ĠÐ¿ÑĢÑıÐ¼ ĠÐ¿ÑĢÑıÐ¼
ĠÑĢÑĥÐºÐ°Ð¼Ð¸ ĠÑĢÑĥÐºÐ°Ð¼Ð¸

ftfy.explain_unicode('Ð½Ð¾Ðµ')
U+00D0  Ð       [Lu] LATIN CAPITAL LETTER ETH
U+00BD  ½       [No] VULGAR FRACTION ONE HALF
U+00D0  Ð       [Lu] LATIN CAPITAL LETTER ETH
U+00BE  ¾       [No] VULGAR FRACTION THREE QUARTERS
U+00D0  Ð       [Lu] LATIN CAPITAL LETTER ETH
U+00B5  µ       [Ll] MICRO SIGN

ftfy.explain_unicode('ное')
U+043D  н       [Ll] CYRILLIC SMALL LETTER EN
U+043E  о       [Ll] CYRILLIC SMALL LETTER O
U+0435  е       [Ll] CYRILLIC SMALL LETTER IE`

**Comment by GladiatorX** [comment]
I think tokenizer.train function should accept utf-8 encoding

**Comment by janyfe** [comment]
It should, but as far as I concern it doesn't. I might be wrong though. I used utf-8 encoded txt files for training and got the result shown in the first comment.

**Comment by GladiatorX** [comment]
Make sure train function decode's the utf-8 encoded string

**Comment by n1t0** [comment]
You are using the byte-level BPE. It operates with bytes, not Unicode characters.
Please read this: https://github.com/huggingface/tokenizers/issues/203#issuecomment-605105611

**Comment by janyfe** [comment]
@n1t0 @GladiatorX  Thank you for your answers!

I read #203 comment. If I'm not mistaken to decode token ids into human-readable subwords I have to merge two single-byte Unicode chars into one two-byte Unicode char so that for example U+00D0  Ð  and  U+00BD  ½  become U+043D  н (Russian letter [an]). It's rather inconvenient, but I see that this is by design behaviour.

**Comment by n1t0** [comment]
You can also probably use a `ByteLevel` decoder (the part used by the `ByteLevelBPETokenizer` to decode) if you want to see the human-readable tokens:
```python
>>> from tokenizers.decoders import ByteLevel
>>> decoder = ByteLevel()
>>> decoder.decode([ 'ĠÑģÐ»Ð¾Ð²Ð¾' ])
' слово'
```

**Comment by janyfe** [comment]
@n1t0 Great! Thank you a lot!

**Comment by GladiatorX** [comment]
I use same code to train it on Marathi language, but on running above code to decode it to human-readable token my colab session crashes with this WARNING _thread  '<unnamed>' panicked at 'no entry found for key', /__w/tokenizers/tokenizers/tokenizers/src/pre_tokenizers/byte_level.rs:183:26_  

Try reproducing it by decoding following tokens

- Ġà¥§à¥¯à¥ «
- à¤£ à¤µà¤¤

`decoder.decode([ 'à¤£ à¤µà¤¤' ])`

**Comment by n1t0** [comment]
@GladiatorX the byte-level decoder can only decode byte-level tokens, not any random string. Your examples contain spaces, and these are not part of the byte-level alphabet.
`decoder.decode` takes a list of tokens to decode, so 
`decoder.decode([ 'à¤£', 'à¤µà¤¤' ])` will behave as you would expect.

**Comment by n1t0** [comment]
Closing this issue as everything should be resolved. Feel free to reopen otherwise!
