### ISSUE TITLE
Is tokenizers suitable for sentence segmentation?

### ISSUE THREAD

**Issue by mustaszewski** [huggingface/tokenizers#256]
Hello,
rather than posting an issue, I'd like to ask whether Tokenizers can be used for the task of sentence segmentation (i.e. splitting raw text input into sentences). For my task in mind, only the sentence boundary detection would be required. I am interested in Tokenizers for this task because it supports multilingual models and is trainable.

**Comment by ck37** [comment]
My understanding is that Tokenizers would not be able to provide that level of linguistic analysis to estimate sentence boundaries. I believe spacy is most commonly used for that: https://spacy.io/usage/linguistic-features#sbd

**Comment by n1t0** [comment]
Indeed, this is not something that you can do with this library at the moment.
