### ISSUE TITLE
Advice for training BertWordPieceTokenizer multilingual tokenizer?

### ISSUE THREAD

**Issue by shenkev** [huggingface/tokenizers#257]
Is there any advice for training the BertWordPieceTokenizer for handling different languages? Are there any "gotchas" to consider in the authors' experience training the tokenizer for bert-base-multilingual-cased? Some specific questions,

- should we balance sentences for different languages?
- should we undersample the training file for the tokenizer if it's very large? I have 100M sentences
- is the training pipeline script for bert-base-multilingual-cased available somewhere?

**Comment by n1t0** [comment]
This kind of question should now be asked on the [:hugs: Forum](https://discuss.huggingface.co) where the chances of getting help from the community are higher.
