### ISSUE TITLE
Automatically Adding SOS/EOS Tokens

### ISSUE THREAD

**Issue by glennkroegel** [huggingface/tokenizers#263]
Hi guys,

Is there a way to prepend/append start of text + end of text tokens?

I'm basically trying to recreate the functionality of the BertTokenizer (on a smaller, completely different dataset) with the [CLS] and [SEP] tokens automatically being added with no changes to the raw text.  

The decoder should also just remove them and return the original text as expected.

**Comment by n1t0** [comment]
Have you looked at the provided `BertWordPieceTokenizer`?

**Comment by glennkroegel** [comment]
Yeah. 

Since I want a new vocabulary I'm basically doing the following:

```

tokenizer = BertWordPieceTokenizer() # vocab_size = 0
tokenizer.train('train_text.json', min_frequency=10) # vocab_size = 5000

tokenizer.encode('this is a sentence.').ids
>> [166, 142, 20, 3096, 8] # just tokens from the sentence

```
If I look for the [CLS] and [SEP] tokens in tokenizer.get_vocab() they are indeed there since they are default values on initialization of tokenizer.

Moreover, if you do two inputs as follows:

```

tokenizer.encode('this is a sentence.', 'and a 2nd sentence.').ids
>> [166, 142, 20, 3096, 8, 95, 20, 10, 84, 3096, 8] 

```
This doesn't insert a [SEP] in between (8 = '.' , 95 = 'and') either.

Basically just trying to replicate the tokenizers from the transformers library but not be constrained to the vocab used in the respective model while getting the advantages here of having an option to select min_frequency, vocab_sz etc. 

Not a huge deal to do it manually but just making sure I'm not doing something stupid or that there is no plan to implement this. Thanks!

**Comment by n1t0** [comment]
Ok, I think here you should actually save your tokenizer after the training by doing:
```python
tokenizer.save(".", "some-name")
```
and then reload it from these files when you want to use it:
```python
tokenizer = BertWordPieceTokenizer("./some-name-vocab.txt")
```

This is due to the fact that when we initialize it the first time, these tokens don't exist since it wasn't trained yet. This means that they don't have any associated ID and we cannot setup the code that add these special tokens.

**Comment by glennkroegel** [comment]
Exactly what I want, thanks.
