### ISSUE TITLE
Issues with ByteLevelBPETokenizer encoder.

### ISSUE THREAD

**Issue by iyor** [huggingface/tokenizers#264]
Hi,

I used hf/tokenizers to make a custom vocabulary. As a sanity check, I'm trying to run the ByteLevelBPETokenizer on the vocabulary but things aren't adding up. One token in said vocabulary is `ĠOHÃ¢`. Running,
```python3
tokenizer = ByteLevelBPETokenizer('custom_vocab.json', 'custom_vocab_merges.txt')
tokenizer.encode(' OHÃ¢').tokens
tokenizer.encode(' OHÃ¢').ids
```
yields,
```python3
['ĠOH', 'Ãĥ', 'Â¢']
[0, 11700, 820, 17600, 2]
```
Shouldn't I be getting a single token id (plus the start-of-sentence and end-of-sentence tokens), since I'm trying to encode a token right out of the vocabulary? Also the tokens don't actually look correct. Decoding again gets me back the original string though...

**Comment by n1t0** [comment]
Hi @iyor.

The `ByteLevelBPETokenizer` encodes the input into byte-level characters. So in the vocabulary, you see these tokens after the encoding step. If you want to check that it encodes into said tokens, you would have to first decode the token, to get the expected input.

`'ĠOHÃ¢'` is actually a token for `' OHâ'`.

**Comment by iyor** [comment]
Hi, thanks for the quick response. This makes sense, thanks.
