### ISSUE TITLE
BertWordPieceTokenizer is not reversible for quotation marks

### ISSUE THREAD

**Issue by tomhosking** [huggingface/tokenizers#266]
Encoding then decoding a string containing single and double quotation marks does not return the original string. Single quotes are combined with adjacent words and doubles are padded with an additional space.

```
import tokenizers
from tokenizers import BertWordPieceTokenizer

tok = BertWordPieceTokenizer("../data/bert-vocabs/bert-base-uncased-vocab.txt", lowercase=True)

toks = tok.encode("this sentence contains 'single quotes' and \"double quotes\" in the middle.")

print(tokenizers.__version__)
print(tok.decode(toks.ids))
```

Output:
> 0.7.0
> this sentence contains'single quotes'and " double quotes " in the middle.

Expected:
> this sentence contains 'single quotes' and "double quotes" in the middle.

Edit: I think I see why this may be more complex than I thought:
`print(tok.decode(tok.encode("It's not clear whether peoples' use of 'single quotes' and \"double quotes\" is reversible.").ids))`
> it's not clear whether peoples'use of'single quotes'and " double quotes " is reversible.

Given that the BERT vocab is fixed, I guess there's no way of getting this right for all use cases?

**Comment by n1t0** [comment]
Indeed, we don't have enough information left while decoding to ensure the output matches the input. We have a cleanup step that takes care of the most common cases, but I don't think we can get it right for all uses cases.

**Comment by tomhosking** [comment]
Hi @n1t0!

Thanks for confirming - sounds like I need to use a different model!

**Comment by davidgilbertson** [comment]
Are there some models/decoders better than others at putting apostrophes back in the right place? Any guidance on how to get the best results with apostrophe spacing would be great.
