### ISSUE TITLE
Memory Limit

### ISSUE THREAD

**Issue by NaxAlpha** [huggingface/tokenizers#267]
Hi,
I have 100+GB of text corpus and want to train sentence piece tokenizer. But when I tried to train on those files, it first tried to read all of them in memory which made it impossible to train on entire dataset. 

Next I tried to sample a ~10GB corpus and tried to train on that. It is successfully able to read all the files in memory but Tokenize word phase takes a lot more memory (in my case it used up all the 100GB of RAM while still at ~30%).

I would prefer to train tokenizer on entire dataset rather than just a chunk but chunk would be fine if it works. Can anyone please help me out on how to reduce this memory requirement?

Thanks

**Comment by yangjianxin1** [comment]
I had the same problem，how could you solve the problem? @NaxAlpha

**Comment by NaxAlpha** [comment]
Since this is not a deep learning model, it would not scale with more data. So the idea is to train tokenizer on a small chunk of data i.e. 1GB of text max works very well.
