### ISSUE TITLE
Is ByteLevelBPETokenizer working with cyrillics?

### ISSUE THREAD

**Issue by purgenetik** [huggingface/tokenizers#268]
I'm trying to run tokenizer with Russian language, but have problem with encodings. The full colab notebook is available here https://colab.research.google.com/drive/1aURDJAt1HqDCZVlYH1_K8YCBrbot5Wx5?usp=sharing
The encode of input file is ok:

![image](https://user-images.githubusercontent.com/9008124/82142767-643c6100-9847-11ea-8834-0c6643cf5994.png)

But after passing though tokenizer I see non-cyrillic symbols in vocab.json and merges.txt and tokenizer run gives the same problem.

![image](https://user-images.githubusercontent.com/9008124/82142882-6b17a380-9848-11ea-9872-be741e026e89.png)

How one can correctly process Cyrillic language and is it possible?
Cheers,
Yuri

**Comment by zirlman** [comment]
Hey. I've had the same problem a couple of months ago. Ended up using SentencePiece tokenizer.

**Comment by kaunghtetsan275** [comment]
This issue is already pinned. Check it out here #203 

related issues: #223 #254

**Comment by purgenetik** [comment]
Hi guys, thanks you a lot for your quick answers! Especially to @ kaunghtetsan275 with last phrase, so,  I have found solution in #254 (also available in the same colab notebook mentioned above). It’s nor clear though for me whether tokenizer techniques works well treating by bytes not letters. E.g. “Mama” word has not been split in token. It could problem of small training sample, but it’s not so small, and case is rather simple… So, question to validity of this tool to work with non-latin languages remains open IMHO…:
![image](https://user-images.githubusercontent.com/9008124/82152961-5ac5ef80-986d-11ea-8744-4e6b1cf7588f.png)

Anyway thanks everybody for answers and good luck!

**Comment by purgenetik** [comment]
Behavior is poor with words contained repeated tokens:

![image](https://user-images.githubusercontent.com/9008124/82153331-6f0aec00-986f-11ea-97a4-c6f2743ead85.png)

Should be ма ма па па му му жу жу ха ха ха

**Comment by purgenetik** [comment]
> Hey. I've had the same problem a couple of months ago. Ended up using SentencePiece tokenizer.

thanks, will try

**Comment by n1t0** [comment]
Hi @purgenetik and thank you for your interest in the `tokenizers` library. Here are a few things I'd like to help clarify:

- The algorithm in charge of doing the tokenization here is still the Byte-Pair-Encoding (BPE). The fact that it operates on bytes or characters doesn't change how it works internally. BPE is a well-proven algorithm and is an industry-standard today, that often allows models to reach state-of-the-art results.

- The fact that it operates on bytes actually makes it more fine-grained in that it will be able to understand some characters better, by being able to decompose them. When working with Unicode characters, if you want to support every single character, your need a base vocabulary of at least 143,859 tokens just to cover the initial alphabet (as of Unicode 13.0). Now, when you work with bytes, your initial alphabet just requires 256 characters (the number of unique values a byte can represent). Every other token will be composed of these 256 initial characters.

- The fact that `мама` gets a single token is actually a good thing. It just means that the algorithm decided that this word is important enough to deserve a single token. BPE actually starts by separating everything into characters, and then gradually builds tokens from these characters. So, when you see a single word, with its own token, it's actually a sign that everything works fine. A word that is actually quite rare will probably be built from multiple tokens (subwords), but a word that you use often, like `the` in English deserves to have its own token. Does it make sense?

I hope all of this will help you understand the results you have been seeing. I am actually very excited by what the byte-level processing brings to the table, and I think it should be well suited to work with non-latin languages.

Cheers!

**Comment by n1t0** [comment]
Closing this, feel free to reopen if you need anything else!
