### ISSUE TITLE
indicatif compilation feature flag?

### ISSUE THREAD

**Issue by ericmcbride** [huggingface/tokenizers#270]
We are using Flutter/Dart for cross compiling for Desktop / iOS / Droid applications, and I had to fork HuggingFace tokenizers in order to get Cargo Lipo to work.  Indicatif progress bar has a dependency on termios (https://docs.rs/termios/0.3.2/termios/) that only supports the following Operating System platforms:
- linux
- macos
- freebsd
- openbsd
- netbsd
- dragonfly
- solaris

Whenever running cargo lipo to target iOS platforms hugging face will bomb out everytime because it cannot find the target operating system.  
```
error[E0433]: failed to resolve: could not find `target` in `os`
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.3.2/src/lib.rs:210:31
    |
210 |     fn deref(&self) -> &::os::target::termios {
    |                               ^^^^^^ could not find `target` in `os`
```

When I forked and deleted the deps on indactif, everything compiled great.

**Comment by n1t0** [comment]
Hi @ericmcbride and thank you for the detailed report!

I guess we could indeed use a compilation feature flag. Would you be interested in doing a PR for this?

Are you planning on writing some bindings to use it with Flutter/Dart?

**Comment by ericmcbride** [comment]
@n1t0  Yeah I can for sure work on a PR when I get some spare time.  We aren't writing bindings persay, but we are using darts FF to call some rust code for ML.
