### ISSUE TITLE
SentencePieceBPETokenizer splits <mask> and <pad> tokens even after adding them to special tokens

### ISSUE THREAD

**Issue by kuppulur** [huggingface/tokenizers#275]
Hi,
 
I am trying to train a **_SentencePieceBPETokenizer_** on my data, which I want to further use in creating a RoBERTa language model. Tokens look good, but the tokenizer is also splitting mask and pad tokens **_('▁<', 'm', 'as', 'k', '>')_**. Could anyone explain if this is what is expected or if I am making a mistake somewhere?

```
from tokenizers import SentencePieceBPETokenizer
paths = [str(x) for x in Path("./my_data/").glob("**/*.txt")]
tokenizer = SentencePieceBPETokenizer()
tokenizer.train(files=paths, vocab_size=25000, min_frequency=2, special_tokens=[
    "<s>",
    "<pad>",
    "</s>",
    "<unk>",
    "<mask>",
])
tokenizer.save(".", "MyBERTu")
```
tokenizers == 0.7.0

**Comment by n1t0** [comment]
Hi @kuppulur. With `0.7.0` the `.save` method only saves the BPE vocabulary, not everything else that is related to the tokenizer. This is something that we are currently working on. (cf #272).
Anyway, this means that the special_tokens are not being saved. So when you load your tokenizer, you have to keep calling `add_special_tokens` for now:
```
tokenizer.add_special_tokens([ "<s>", "<pad>", "</s>", "<unk>", "<mask>" ])
```
This will let the tokenizer know about these, and it won't split them.

**Comment by kuppulur** [comment]
Thanks @n1t0 It works
