### ISSUE TITLE
[Question/Doubt]

### ISSUE THREAD

**Issue by mrm8488** [huggingface/tokenizers#279]
How can it be create a "spiece.model" with tokenizers library? @n1t0

**Comment by n1t0** [comment]
I guess the `spiece.model` file you are talking about is a file used by SentencePiece. We will soon add support for the Unigram model, and a way to convert `spiece.model` files to what the tokenizers library expects (cf #53).
However, if you want to create a `spiece.model` file specifically, then you should use SentencePiece as the only intent of this format, is to be used with SentencePiece.

Let me know if I didn't understand your question correctly!

**Comment by mrm8488** [comment]
Thank you so much. I want to create a new one for fine tuning the Reformer available on the HF hub. By now it is only available the tokenizer of "crime and punish" and "enwiki8" tokenizer is not in the list of tokenizers to download so I thought to create a new one

**Comment by n1t0** [comment]
Ok then indeed at the moment you will have to use SentencePiece. We will provide an easier way to re-train these tokenizers using this library soon!
