### ISSUE TITLE
Prevent changes in the characters

### ISSUE THREAD

**Issue by sinaahmadi** [huggingface/tokenizers#281]
Hi,

Sorry, I could not find a better title for this issue.

I am training a model using the WordPiece method as follows:

```
    vocab_size = 50000
    # Initialize a tokenizer
    tokenizer = BertWordPieceTokenizer(clean_text=True, handle_chinese_chars=False, strip_accents=True, lowercase=False)

    # And then train
    tokenizer.train(
        files,
        vocab_size,
        min_frequency=2,
        show_progress=True,
        special_tokens=["[PAD]", "[UNK]", "[CLS]", "[SEP]", "[MASK]"],
        limit_alphabet=1000,
        wordpieces_prefix="##",
    )

    tokenizer.save('./', 'output-wordpiece_%s'%str(vocab_size))
```

Everything is fine and the tokenizer works too. However, some of the characters are automatically changed. This looks like an automatic normalization. Is there any way to prevent such modifications? I also tried `BertWordPieceTokenizer(clean_text=False, handle_chinese_chars=False, strip_accents=False, lowercase=False)` but the problem does not get solved either. I only want the text get tokenized without any further modification.

Thanks.

**Comment by n1t0** [comment]
Could you give us some examples of the kind of modifications you see?

**Comment by sinaahmadi** [comment]
I am not sure if the text will help as it is Kurdish (Arabic-based script).

This is the original text:
`ئەو ناوچەیە کە شتێ تێدا دەژی`

When tokenizing the text with my model trained with `wordpiece`, "**ئ**ەو" gets changed to "**ي**ەو" as follows:
`يەو ناوچەیە کە شت ێ تێدا دەژی`

It seems to be happening only to that character [ئ](https://www.compart.com/en/unicode/U+0626) (called Hamza) being replaced by [ي (y)](https://www.compart.com/en/unicode/U+064A). Just to know, those two characters have two different Unicode values.

**Comment by n1t0** [comment]
Thank you for providing more details!

On the page you sent for [Yeh with Hamza above](https://www.compart.com/en/unicode/U+0626), you can see the `Decomposition` line. When `strip_accents=True`, we decompose it to [Yeh](https://www.compart.com/en/unicode/U+064A) and [Hamza above](https://www.compart.com/en/unicode/U+0654) and the [Hamza above](https://www.compart.com/en/unicode/U+0654) which is a `Nonspacing Mark` gets removed.

Now, if the `strip_accents` option is set to `False`, this shouldn't happen. Did you train it again when you tried with every options to `False`?

**Comment by sinaahmadi** [comment]
Thanks for getting back to me, Anthony @n1t0 .

Yes, I also tried with all the options set to `False` but the problem seems to persist. The following is the output of a new model with all options set to `False` but with a bigger vocabulary size: 

[CLS] **ي** ##ەو ناوچەیە کە شت ##ێ تێدا دەژی [SEP]

Again, Hamza is replaced by Yeh.

Do you think it is related to how I encode sentences? Is it correct that I assume that word pieces are in fact tokens and `##` should be replaced by space?

```
    WordPiece = BertWordPieceTokenizer(model, lowercase=False)
    WordPieceEncoder = WordPiece.encode(text)
    for token in ["[PAD]", "[UNK]", "[CLS]", "[SEP]", "[MASK]", "##"]:
           sentence_tokenized = " ".join(WordPieceEncoder.tokens).replace(token, " ")
    print(" ".join(sentence_tokenized.split()))
```

**Comment by n1t0** [comment]
If you want to decode, you should be able to use `WordPiece.decode(WordPieceEncoder.ids)` directly. It will take care of removing the special tokens automatically.

`##` means that a token is the continuation of the previous one, without space. So there should be a space between tokens, except if the second one starts with `##`.

A quick test on my side:
```python
Python 3.7.3 (default, Apr 15 2020, 10:51:02)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tokenizers
>>> text = "ئەو ناوچەیە کە شتێ تێدا دەژی"
>>> tok = tokenizers.BertWordPieceTokenizer(strip_accents=True, clean_text=False, lowercase=False)
>>> text == tok.normalize(text)
False
>>> tok.normalize(text)
'يەو ناوچەیە کە شتێ تێدا دەژی'
>>> tok = tokenizers.BertWordPieceTokenizer(strip_accents=False, clean_text=False, lowercase=False)
>>> text == tok.normalize(text)
True
```

**Comment by sinaahmadi** [comment]
Thanks very much. I was initializing the tokenizer with inappropriate arguments. `BertWordPieceTokenizer(model, strip_accents=False, clean_text=False, lowercase=False)` solved the problem.
