### ISSUE TITLE
Thread panic when saving tokenizer

### ISSUE THREAD

**Issue by jeremyjordan** [huggingface/tokenizers#284]
I'm using the `CharBPETokenizer(split_on_whitespace_only=True)` for a project. It trains on my corpus without an issue but when I try to save the tokenizer, I'm getting the following error which is killing the Python process :`thread '<unnamed>' panicked at 'no entry found for key', /__w/tokenizers/tokenizers/tokenizers/src/models/mod.rs:27:66`

Minimal reproducible example:

```
import os
from pathlib import Path
from tokenizers import CharBPETokenizer

os.environ['RUST_BACKTRACE'] = 'full'

a = Path('a.txt')
a.write_text("""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer condimentum accumsan orci, sit amet euismod dui 
efficitur eu. Nam quis dolor sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
Curabitur volutpat felis tellus, at tempor magna mollis tincidunt. Pellentesque finibus nec mauris vitae tempor. Phasellus hendrerit 
eu ipsum vitae mattis. Ut id tristique purus. Cras ac #HELLO odio, eget rhoncus eros. Donec risus turpis, accumsan nec fermentum 
et, pharetra id massa. Praesent facilisis egestas urna nec scelerisque. Sed ullamcorper consectetur diam, ac accumsan lacus 
pellentesque in. Nulla facilisi. Curabitur risus massa, auctor et feugiat ut, ultricies ac magna. Class aptent taciti sociosqu ad 
litora torquent per conubia nostra, per inceptos himenaeos. Morbi consectetur nibh ut tincidunt suscipit. Aliquam bibendum lectus in 
odio ornare malesuada. Suspendisse dui libero, aliquet a est in, volutpat consequat metus. Fusce sodales imperdiet velit, et egestas 
ante maximus at. Vivamus urna dolor, lacinia eu nibh tincidunt, euismod posuere ante. Sed in elit hendrerit, vehicula nulla et, 
elementum magna.""")

b = Path('b.txt')
b.write_text("""In #HELLO vehicula risus nec sagittis. In ipsum lectus, luctus nec tellus id, volutpat ultricies lorem. Nunc suscipit, 
erat id dignissim iaculis, dolor dui volutpat mi, sed tincidunt odio purus id dui. Sed sit amet dictum libero. Fusce sodales fermentum 
nibh eget finibus. Duis viverra, nisi ac ornare viverra, orci nibh dignissim enim, quis luctus dolor nisl at tellus. Sed quis congue 
quam. #WORLD/#WORLD scelerisque justo tellus. Morbi facilisis magna in diam feugiat vulputate eu vitae lorem. Pellentesque placerat quam in 
neque elementum. Suspendisse facilisis lectus et 1-#WORLD-14 vestibulum. Curabitur ut eros tellus.""")

text_files = [str(a), str(b)]

tokenizer = CharBPETokenizer(split_on_whitespace_only=True)
tokenizer.train(
    text_files,
    special_tokens=[
        '#HELLO',
        '#WORLD',
    ],
)

filename = f"bpe.tokenizer.json"
tokenizer.save(filename)
```

I recognize there are some oddities in this example (`#WORLD/#WORLD` and `1-#WORLD-14` with `split_on_whitespace_only=True`), but I'm not sure why this only resulted in an error when serializing the model.

This example is using `tokenizers==0.8.0.dev1` but the same behavior is occurring on the latest stable release.

**Comment by n1t0** [comment]
Thank you very much for the detailed report @jeremyjordan. I love it when it is so well explained, and reproducible!

This was happening because `#WORLD` is a special token which is given the id `1` at the very beginning of the training. Since we can find it in the corpus too, at some point the BPE creates a merge operation that also results in `#WORLD`, attributing it a new id. The result was that we were missing the id `1` when saving, even though it should have been there, leading to a crash. Now, this shouldn't happen in a real case scenario, because special tokens should be unique enough to never be part of the training corpus.

Your code snippet also helped me reproduce something that had been reported already but that we weren't able to reproduce!

**Comment by jeremyjordan** [comment]
Ah perfect! That makes sense, thanks for the explanation :)
