### ISSUE TITLE
better documentation (versioned with the code)

### ISSUE THREAD

**Issue by jeremyjordan** [huggingface/tokenizers#285]
Would it be possible to have docs for each version of the code released? For example, if someone references the docs regarding how to save the tokenizer, they'll see:

```
tokenizer.save("./path/to/directory/my-bpe.tokenizer.json")
```

whereas the latest stable version of the library still requires:

```
tokenizer.save("./path/to/directory", "my-bpe")
```

**Comment by n1t0** [comment]
Each released version has an associated tag on github. For example, if you want to check `v0.7.0`: https://github.com/huggingface/tokenizers/tree/python-v0.7.0

I don't think we can do much better for now. However, that's something that we will keep in mind for the official doc and guides that we will release in the coming months. Probably on a website separated from github.

**Comment by n1t0** [comment]
The official docs are now there: https://huggingface.co/docs/tokenizers
