### ISSUE TITLE
How to get offsets for ElectraTokenizer

### ISSUE THREAD

**Issue by Aktsvigun** [huggingface/tokenizers#290]
Good afternoon.
Is it possible to get offsets for the text when using models-stacked tokenizers? For instance, I am using ElectraTokenizerFast and I would like it to return the offsets for my texts (the indexes for the first and the last letters of token) - do you probably have any templates of how to do it?
Thanks in advance!

**Comment by Aktsvigun** [comment]
@julien-c @n1t0 ask for help :)

**Comment by n1t0** [comment]
If you are using the `ElectraTokenizerFast` then you should be able to specify `return_offsets_mapping=True` to `encode_plus` or `batch_encode_plus`.

**Comment by Aktsvigun** [comment]
Thanks a lot! Will try now.
