### ISSUE TITLE
Cannot load SentencePieceBPETokenizer pretrained model 

### ISSUE THREAD

**Issue by Ierezell** [huggingface/tokenizers#291]
First, thanks a lot for the binding in node. As my company is doing web stuff and want to keep the stack it's really useful to be able to run NLP tasks in node. 

I get inspired with the [node question answering](https://github.com/huggingface/node-question-answering) repo you made and I wanted to compute embeddings on node the same way (then maybe do other tasks as well)

I get to load hugging face models in `TFJS-node` as you did, same with `BertWordPieceTokenizer` (loaded from the vocabulary text file dumped by python method `save_pretrained`)

I would like to load a `SentencePieceBPETokenizer` but the only pretrained file I can have is the `sentencepiece.bpe.model` given by the python `save_pretrained` method (I'm using `Camembert-base`)

I try to load it with the node  `SentencePieceBPETokenizer.fromOptions` (which is the only function I found) but i cannot encode sentences.

```
async function test_tokenizer(path_tok: string) {
  const tokenizer = await SentencePieceBPETokenizer.fromOptions({
    vocabFile: path.join(path_tok, "sentencepiece.bpe.model"),
  });
  const tok = await tokenizer.encode(
    "Qui est Pierre ?",
    "Pierre est un enseignant"
  );
  console.log(tok);
  console.log(tok.length);
  console.log(tok.tokens);
  console.log(tok.ids);
  console.log(tok.attentionMask);
  console.log(tok.offsets);
  console.log(tok.overflowing);
  console.log(tok.specialTokensMask);
  console.log(tok.typeIds);
  console.log(tok.wordIndexes);
}

test_tokenizer("path_to_camembert_savepretrained")
  .catch((e) => console.log(e))
  .then((_) => console.log("done"));
```

Output : 

```
Encoding { _rawEncoding: Encoding {} }
0
[]
[]
[]
[]
[]
[]
[]
[]
done
```

Thanks in advance for any help or documentation about the node bindings. I'm not a fan of web stuff for NLP but I guess it's a huge demand in the industry

**Comment by leslyarun** [comment]
#53

**Comment by Ierezell** [comment]
I checked #53 but I don't get why the readme says that [it is available](https://github.com/huggingface/tokenizers/tree/master/bindings/node#provided-tokenizers) but then all the method are inexisting.

I saw #225 as well and I guess I will try the [sentencepiece_extractor.py](https://github.com/huggingface/tokenizers/blob/master/bindings/python/scripts/sentencepiece_extractor.py) until the underlying Unigram is available.

in #259 [this comment](https://github.com/huggingface/tokenizers/issues/259#issuecomment-634375554) gave me the answer.

Thanks again for your time and this wonderfull library !

**Comment by n1t0** [comment]
Sorry about the confusion @Ierezell. We only (partially) support `BPE` built with SentencePiece, by using the `sentencepiece_extractor.py`. But the support for Unigram as used in Camembert has yet to be implemented.

**Comment by loretoparisi** [comment]
@n1t0 I recently came across the same issue

```javascript
const bertTokenizer = await SentencePieceBPETokenizer.fromOptions({  vocabFile: "/Users/loretoparisi/Downloads/sentencepiece.bpe.model"  });
    
    let encoder = (tokenizer) => promisify(tokenizer.encode.bind(tokenizer))
    let decoder = (tokenizer) => promisify(tokenizer.decode.bind(tokenizer))

    encode = encoder(bertTokenizer);
    decode = decoder(bertTokenizer);
  
    encoded = await encode("Hello how are you?");
    console.log(encoded.getIds());
    console.log(encoded.getTokens());
    decoded = await decode(encoded.getIds(), true);
    console.log(decoded);
```

**Comment by loretoparisi** [comment]
@n1t0 any update about this issue? I have updated the vocab model file `sentencepiece.bpe.model` downloading directly from [download link](https://huggingface.co/microsoft/Multilingual-MiniLM-L12-H384/resolve/main/sentencepiece.bpe.model) from files here
https://huggingface.co/microsoft/Multilingual-MiniLM-L12-H384/tree/main
