### ISSUE TITLE
GPT2 for fixed length next word prediction

### ISSUE THREAD

**Issue by shampp** [huggingface/tokenizers#293]
Is it possible to use huggingface GPT2 implementation to predict next word of fixed size ? I do not see an option in huggingface documentaion. I think one way to get this done is to use a tokenizer which produces vocabulary containing fixed length words only. But by default ByteLevel BPE tokenizer used in GPT models are not based on words. Is it possible to make ByteLevelBPE tokenizer to create vocabulary containing fixed length words only ?

**Comment by n1t0** [comment]
Hum, no this is not possible. This seems incompatible with the way the BPE works, as it will always have a set of characters (base alphabet) used to build subsequent tokens.
