### ISSUE TITLE
❓ How to see the token frequency ?

### ISSUE THREAD

**Issue by Colanim** [huggingface/tokenizers#296]
I trained a tokenizer on my own data :

```
from tokenizers import ByteLevelBPETokenizer

tokenizer = ByteLevelBPETokenizer()
tokenizer.train(["./data.txt"])
```

I know vocabulary is already ordered based on token frequency, but I'm interested on the precise number of occurence of each vocabulary word. **How can I access this information ?**

**Comment by n1t0** [comment]
There's no way to achieve this at the moment. Can you elaborate on why you need this?

**Comment by Colanim** [comment]
Thanks for your answer !

I'm just trying to apply different preprocessing on my data based on the word frequency.

For example, the words `is`, `company`, `seem` are very frequent in english, but `is` is an order more frequent than the 2 others.

So I wanted to access the word frequency of already trained tokenizers, but since it's impossible, I guess I can count it myself on my own data.

**Comment by beinborn** [comment]
I would also be very interested in this option. I want to compare how splits change with different vocabulary sizes of the tokenizer. If I understand it correctly, the counts are maintained in the variable wc of the trainer (https://docs.rs/tokenizers/latest/src/tokenizers/models/bpe/trainer.rs.html#311), but I do not know how to access them from Python.

**Comment by itay-nakash** [comment]
It would be very beneficial for me as well, as I'm trying to modify existing tokenizers using algorithms that take into account some of the old vocabulary frequency. 
Does anyone here find a way to get this data?

Thanks
