### ISSUE TITLE
Python manylinux wheel files include compiled libraries for multiple Python versions

### ISSUE THREAD

**Issue by Stranger6667** [huggingface/tokenizers#301]
Hello!

In the Python build output, there are the following [lines](https://github.com/huggingface/tokenizers/runs/736452365?check_suite_focus=true#step:4:962)

```
adding 'tokenizers/tokenizers.cpython-35m-x86_64-linux-gnu.so'
adding 'tokenizers/tokenizers.cpython-36m-x86_64-linux-gnu.so'
adding 'tokenizers/tokenizers.cpython-37m-x86_64-linux-gnu.so'
adding 'tokenizers/tokenizers.cpython-38-x86_64-linux-gnu.so
```

And the [published wheel](https://files.pythonhosted.org/packages/04/44/1da09bb16357fb7502b20631170e7b278df4d8567931bd104180dd62d2d8/tokenizers-0.7.0-cp38-cp38-manylinux1_x86_64.whl) indeed includes all these files. As far as my understanding goes - since the wheel is for CPython 3.8, `.so` files for other Python versions are not used anyway and can be removed. They also occupy significant space - each one uncompressed is ~6.4MB. What do you think about removing them? It should be 1 line (probably `rm` call after creating a wheel) in `build-wheels.sh` but will reduce traffic for the users

Cheers!

**Comment by n1t0** [comment]
Indeed, nice catch @Stranger6667!  This is happening for the manylinux wheels, because of the `build-wheels.sh` script. The wheel for python 3.5 contains only one `.so` file, the one for python 3.6 contains two, and so on... Will fix this!
