### ISSUE TITLE
Cannot load BPE model using Flaubert vocabulary

### ISSUE THREAD

**Issue by ierezell** [huggingface/tokenizers#310]
I saved a `Flaubert` model from python hugging face which gives me the `merges.txt` `vocab.json` and `special_token_maps.json`

[merges.txt](https://github.com/huggingface/tokenizers/files/4806199/merges.txt)
[vocab.txt](https://github.com/huggingface/tokenizers/files/4806203/vocab.txt)
(vocab is a json file but I had to put a txt extention to upload it)

I check the doc which says it's a BPE tokenizer, so I tried both BPETokenizer and ByteLevelBPETokenizer but both gives me the error : 
```
Error: Token `trouvécap` out of vocabulary
```

```
import { BPETokenizer, ByteLevelBPETokenizer } from 'tokenizers'
tokenizer = await ByteLevelBPETokenizer.fromOptions({
        vocabFile: path.join(tokenizer_vocab_folder, 'vocab.json'),
        mergesFile: path.join(tokenizer_vocab_folder, 'merges.txt')
      })
```

Thanks in advance for any help.

**Comment by Pierrci** [comment]
Hi @Ierezell, your problem is not directly linked to the node bindings but to the fact that unfortunately `Flaubert` tokenization is not supported for now (it's based on XML tokenization, which itself is not supported, see #251)

**Comment by Ierezell** [comment]
Thanks a lot, I thought it was BPE as said on hugging face models but I guess it's an other story under the hood... 

It would be so nice to have support to this kind of tokenizers, it's the only thing that slow me down to bring huggingface models to node (with onnx).
