### ISSUE TITLE
Tokenizer/ByteLevelBPETokenizer objects are not serializable

### ISSUE THREAD

**Issue by ad6398** [huggingface/tokenizers#313]
I tried to do tokenization step of a file by converting into chunks and distributing it to multiple processes. But the main process is not able to pass tokenizer between subprocess.

```python
def single_work(wid, tokenizer, chunk):
    print("call single process")

def func1(arguments):
    tokenizer = ByteLevelBPETokenizer(
            vocab_file, merges_file, lowercase=lowercase, add_prefix_space=True
        )
    pool = Pool()
    for i in range(workers):
        pool.apply_async(single_work, args=(i,tokenizer, chunks[i]))
    pool.close()
    pool.join()
```

`single_work` function is not being called by pool.apply_async, the reason is that multi-process uses pickling to pass arguments between all the subprocesses, so all the arguments should be serializable.  tokenizer seems here to be that non-serializable argument. 
if I used `tokenizer = BertTokenizer.from_pretrained(bert_model_type)` from transformers this is working fine. 

*update*
using `tokenizer= RobertaTokenizerFast()` or `tokenizer= RobertaTokenizerFast.from_pretrained()` from transformers library are also not serializable, as these are built over tokenizer library.

**Comment by n1t0** [comment]
Indeed, the serialization/pickle capabilities have been added recently and are currently part of the `0.8.0.rc2`. We'll release the final version soon, but in the meantime, you can either use the last version of `transformers` from `master`, or directly `tokenizers == 0.8.0.rc2`.

**Comment by ad6398** [comment]
@n1t0 cool, Thanks.
