### ISSUE TITLE
tokenizer.save produces invalid json (python binding, 0.8.0.rc2)

### ISSUE THREAD

**Issue by pdufter** [huggingface/tokenizers#314]
*Version info:*
`tokenizers==0.8.0.rc2`

*Description:*
tokenizer.save produces invalid json in the field `added_tokens`. As a result it is not possible to load a stored tokenizer from the json file with `tokenizers.Tokenizer.from_file`

The json file should probably be 
```"added_tokens":[{"id":0,"special":true,"content":" ...``` instead of
```"added_tokens":[],{"id":0,"special":true,"content":" ...```.

*Minimal Example:*
```
import tokenizers

with open("corpus.txt", "w") as fp:
	fp.write("This is an example sentence.")
tok = tokenizers.BertWordPieceTokenizer()
tok.train(["corpus.txt"])
tok.save("tokenizer.json")

# try to load the tokenizer
tok_loaded = tokenizers.Tokenizer.from_file("tokenizer.json")
# breaks with 
# >>> Exception: key must be a string at line 1 column 69
```

**Comment by n1t0** [comment]
Thanks @pdufter for reporting this! I am currently fixing this problem and will include it in the `rc3` which should be released very soon.

**Comment by n1t0** [comment]
Closed with https://github.com/huggingface/tokenizers/pull/315
