### ISSUE TITLE
Process automatically get killed during Training ByteLevelBPETokenizer on large datasets

### ISSUE THREAD

**Issue by ad6398** [huggingface/tokenizers#316]
I tried to train it on the open web text corpus,( 30k files, 31GB). but after a few minutes(30 min approx) this process gets killed. Initially, I thought it to be a machine issue, but later on, trying with a better machine I am still getting the same error. The following is code to reproduce this error. I am not getting any other error log/output other than the `killed` message.
```python
tokenizer = ByteLevelBPETokenizer(lowercase=True, add_prefix_space=True)
tokenizer.train(
        files= file_paths_to_open_web_text_corpus,
        vocab_size= vocab_size,
        min_frequency= min_fre,
        special_tokens= ["[CLS]", "[SEP]", "[PAD]", "[MASK]", "[UNK]",],
    )
```
This just gets killed during reading files step.
I have also checked limits on the opening of number of files at a time of the machine, etc.

**Comment by n1t0** [comment]
I think you are probably running out of memory. Training your tokenizer on a subset of the corpus (even just 1GB) should be largely sufficient though.

**Comment by ad6398** [comment]
Will it be a good practice to do so? IMHO, as BPE tokenizer is frequency
based, wont this cause a lot of unknow tokens which might be most frequent
in unused part of data? Thanks

**Comment by n1t0** [comment]
You generally limit your vocabulary size anyway, so you only keep the most frequently seen tokens. For a same language, only including a sample shouldn't completely change the frequencies. Also, last interesting point is that by using a ByteLevelBPE it is impossible to get unknown tokens.

**Comment by ad6398** [comment]
Thanks @n1t0 .
