### ISSUE TITLE
Unable to load T5Tokenizer from pretrained model from tokenizer library

### ISSUE THREAD

**Issue by ncoop57** [huggingface/tokenizers#323]
Not sure if this is the correct library to post this issue, but I am having difficulty training my own T5 tokenizer. When training a BPE tokenizer using the amazing huggingface tokenizer library and attempting to load it via

```python
tokenizer = T5Tokenizer.from_pretrained('./tokenizer')
```
I get the following error:
```
OSError: Model name './tokenizer/' was not found in tokenizers model name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). We assumed './tokenizer/' was a path, a model identifier, or url to a directory containing vocabulary files named ['spiece.model'] but couldn't find such vocabulary files at this path or url.
```

I attempted to train a sentencepiece model instead using the, again amazing, huggingface tokenizer library, I get the same error because the `tokenizer.save` method does not actual generate the `spiece.model` file.

Am I doing something wrong?
Tranformers version: 2.11.0
Tokenizers version: 0.7.0

Here is a colab to reproduce the error: https://colab.research.google.com/drive/1WX1Q2Ze9k0SxFMLLv1aFgVGBFMEVTyDe?usp=sharing

**Comment by TanushGoel** [comment]
I think you have to specify which one you'd like to load. Choose from the given list: (t5-small, t5-base, t5-large, t5-3b, t5-11b). 
I chose "t5-small" for example. 

<img width="607" alt="Screen Shot 2020-07-05 at 6 45 22 AM" src="https://user-images.githubusercontent.com/47517229/86534194-4379aa80-be8b-11ea-8bfd-8dab41ec5c53.png">

**Comment by ncoop57** [comment]
I'm wanting to use my own T5 tokenizer that I've trained on my own dataset though, not a premade one from Huggingface.

**Comment by TanushGoel** [comment]
Oh sorry! I thought you were attempting to load a pretrained tokenizer. If you want to make/train your own, just make a ByteLevelBPETokenizer() object and fit it to your dataset. I used the Bee Movie script as an example. 

<img width="1530" alt="Screen Shot 2020-07-05 at 8 20 30 AM" src="https://user-images.githubusercontent.com/47517229/86535893-68284f00-be98-11ea-8c88-377dcbcb6411.png">

**Comment by ncoop57** [comment]
I did train one that way, but I am unable to load it into the T5Tokenizer, which is what I am trying to achieve as it has some special functions for training the corresponding T5 network.

**Comment by n1t0** [comment]
Hi @ncoop57, tokenizers like the one used in T5 are not compatible with `tokenizers` at the moment. It won't generate a `spiece.model` file. While we are adding this compatibility, you can generate such a file using SentencePiece.

**Comment by Arij-Aladel** [comment]
Hey @ncoop57  @n1t0 Have you find a solution I have tried it  [here](https://drive.google.com/drive/folders/1XFtE723SVmJiFA_4pn1374fhgoXeuKN0?usp=sharing) works but when using it GIVE A CUDA ERROR  when using it inside my model
