### ISSUE TITLE
Encoded Chinese strings become unrecognizable characters

### ISSUE THREAD

**Issue by amyxie361** [huggingface/tokenizers#324]
Hi there,

I want to train a language model from scratch in Chinese. In the first step of tokenization training, I follow [this page](https://github.com/huggingface/transformers/blob/master/notebooks/01-training-tokenizers.ipynb)

When the tokenizer finishes training and I check the results and found the encoder's results are not understandable.

Here are the codes:

```
from tokenizers import Tokenizer
from tokenizers.decoders import ByteLevel as ByteLevelDecoder
from tokenizers.models import BPE
from tokenizers.normalizers import Lowercase, NFKC, Sequence
from tokenizers.pre_tokenizers import ByteLevel

tokenizer = Tokenizer(BPE())
tokenizer.normalizer = Sequence([
    NFKC()
])
tokenizer.pre_tokenizer = ByteLevel()
tokenizer.decoder = ByteLevelDecoder()

from tokenizers.trainers import BpeTrainer

trainer = BpeTrainer(vocab_size=25000, show_progress=True, initial_alphabet=ByteLevel.alphabet())
tokenizer.train(trainer, ["big.txt"])

print("Trained vocab size: {}".format(tokenizer.get_vocab_size()))

tokenizer.model.save('.')

tokenizer.model = BPE('vocab.json', 'merges.txt')
encoding = tokenizer.encode("这是一句中文")

print("Encoded string: {}".format(encoding.tokens))

decoded = tokenizer.decode(encoding.ids)
print("Decoded string: {}".format(decoded))
```
And the output is 
```
Encoded string: ['Ġè¿Ļæĺ¯', 'ä¸Ģåı¥', 'ä¸Ńæĸĩ']
Decoded string:  这是一句中文
```
The decoded string is correct but the characters in the encoded string are not understandable.
How can I solve this? Or am I supposed to use this results to do the next step?

**Comment by n1t0** [comment]
Hi @amyxie361, everything looks good! This is actually the way the byte-level BPE works, and it is totally expected. (cf #203 for a better explanation)

Closing this issue for now, feel free to reopen it!
