### ISSUE TITLE
Improve experience with TOKENIZERS_PARALLELISM

### ISSUE THREAD

**Issue by n1t0** [huggingface/tokenizers#328]
The message is not explicit enough, so some users don't understand that they should set an environment variable. Also, we could probably provide a function that, given a boolean, would set it for the user.

**Comment by cornzz** [comment]
Hi, I am using the zeroscrolls metric to evaluate something and I am getting this message, I have no idea if I should set this variable to true or false since I didnt write the code using the tokenizer and also dont know where this is coming from because the message doesnt tell that. What do I do?

**Comment by ArthurZucker** [comment]
You can probably ignore it, or do something like `export TOKENIZER_PARALLELISM=1`
