### ISSUE TITLE
Matching published performance numbers

### ISSUE THREAD

**Issue by albertoa** [huggingface/tokenizers#331]
Could you give more details on how you obtained "20 seconds to tokenize a GB of text"?

It would be great if you could provide the exact input file, the code used and some information as to the server used.

Using the first 100MB of wikitext-103 I am getting 36 seconds on a Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz. 

I can see only 1 CPU core in use pegged at 100%, so it is unclear if the rust implementation is being used.

here is my code

```
from tokenizers import (ByteLevelBPETokenizer,
                            CharBPETokenizer,
                            SentencePieceBPETokenizer,
                            BertWordPieceTokenizer)
import time
import os

os.environ["TOKENIZERS_PARALLELISM"] = "true"

fn="wikitext-103-100M.txt"

t1 = time.time()
with open(fn, 'rt') as inf:
    txt = inf.read()
t2 = time.time()
print(f"Reading txt took {t2-t1} sec.")

tokenizer = BertWordPieceTokenizer("bert-base-uncased-vocab.txt", lowercase=True)

t1 = time.time()
output = tokenizer.encode(txt)
t2 = time.time()
print(f"Encoding took {t2-t1} sec.")
```

**Comment by n1t0** [comment]
There are no parallelism when encoding a single sequence. You should try this:
```python
output = tokenizer.encode_batch(txt.split('\n'))
```

**Comment by albertoa** [comment]
Thank you. That brings it down to 37 sec per GB on my system so I can see how it would be reduced down to 20 sec per GB with more cores.

So, one of the benefits here is that the multiprocessing is handled without having to do a pool in python. Within the rust code it will automatically use CPUs as available.

It does get difficult to do performance comparisons and reproduce results in some cases. I think I have a hold on this one now.

Personally I tend to push the tokenization to the subprocesses within the pytorch data loader, so they already are parallelized and then do tokens on single sequences.

Thanks,

Alberto
