### ISSUE TITLE
Truncation warning when tokenizing inputs with T5Tokenizer

### ISSUE THREAD

**Issue by mrm8488** [huggingface/tokenizers#332]
Hi guys,
I had this code:

```python
 # tokenize inputs
      tokenized_inputs = self.tokenizer.batch_encode_plus(
          [input_], max_length=self.max_len, pad_to_max_length=True, return_tensors="pt"
      )
```
And it worked without any problem.
But, Maybe because of new updates on the library I get the following message tons of times:
```Truncation was not explicitly activated but max_length is provide, please...```
Am I missing smth?

**Comment by n1t0** [comment]
I think this is related to https://github.com/huggingface/transformers/issues/5505 which has been fixed on `transformers@master` and should be released soon.

**Comment by n1t0** [comment]
Closing this, please reopen if needed.
