### ISSUE TITLE
Cannot save BPE files

### ISSUE THREAD

**Issue by scheiblr** [huggingface/tokenizers#335]
Hi, 

first of all thanks a lot for this amzingly fast implementation!

I just encountered a problem, when trying to save a generated BPE:
```python
from tokenizers import ByteLevelBPETokenizer

# Initialize a tokenizer
tokenizer = ByteLevelBPETokenizer()

# Customize training
tokenizer.train(files=["data.txt"], vocab_size=52_000, min_frequency=2, special_tokens=[
    "<s>",
    "<pad>",
    "</s>",
    "<unk>",
    "<mask>",
])

# Save files to disk
tokenizer.save('.') # <- error here!
```

the error I get: 
```
Traceback (most recent call last):
  File "bpe/create_dict_hf.py", line 21, in <module>
    tokenizer.save(dir_raw)
  File "/somepath/lib/python3.7/site-packages/tokenizers/implementations/base_tokenizer.py", line 332, in save
    return self._tokenizer.save(path, pretty)
Exception: Is a directory (os error 21)
```

With version 0.7.0 it works.

**Comment by n1t0** [comment]
Indeed, there is a breaking change on `0.8.0` with the introduction of the full tokenizer serialization. Before this version, `.save` was saving only the model (ie vocab.json + merges.txt for BPE), but now it saves the entire tokenizer, all added tokens, everything...

So if you want to keep doing exactly what you were doing before, you can just replace `.save(` by `.save_model(` and it will work. But you can also use the new saving/loading method:

```python
# Save
tokenizer.save("byte-level-bpe.tokenizer.json")

# And to reload
tokenizer = Tokenizer.from_file("byte-level-bpe.tokenizer.json")
```

Closing this, feel free to reopen if needed!

**Comment by scheiblr** [comment]
Thank you very much! :+1:
