### ISSUE TITLE
TypeError: sep_token not found in the vocabulary

### ISSUE THREAD

**Issue by cahya-wirawan** [huggingface/tokenizers#337]
Hi,
I have tokenizer version 0.8.1rc1. I have a problem to load the vocabulary with BertWordPieceTokenizer, it says
TypeError: sep_token not found in the vocabulary, even the vocab is just trained and saved with the same version.
Please have a look to this code snippet:

```
>>> from tokenizers import BertWordPieceTokenizer
>>> tokenizer = BertWordPieceTokenizer()
>>> tokenizer.train(["train.txt"], vocab_size=10000)
[00:00:00] Reading files (1 Mo)                     ██████████████████████████████████████████████████████████████████                 100
[00:00:00] Tokenize words                           ██████████████████████████████████████████████████████████████████ 16090    /    16090
[00:00:00] Count pairs                              ██████████████████████████████████████████████████████████████████ 16090    /    16090
[00:00:00] Compute merges                           ██████████████████████████████████████████████████████████████████ 9617     /     9617

>>> tokenizer.save("vocab.txt")
>>> tokenizer = BertWordPieceTokenizer("vocab.txt", lowercase=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wirawan/miniconda3/envs/transformers/lib/python3.7/site-packages/tokenizers/implementations/bert_wordpiece.py", line 57, in __init__
    raise TypeError("sep_token not found in the vocabulary")
TypeError: sep_token not found in the vocabulary

```
Did I miss something? I don't have problem if I train,save and load with ByteLevelBPETokenizer. Thanks

**Comment by n1t0** [comment]
The `BertWordPieceTokenizer` class has a lot of default parameters in its `__init__` that set the usual special tokens that are used in BERT. So the `sep_token` is set to its default `[SEP]` which should probably be `None` in your case since you didn't add it when you called `train`.

You should have a look at the actual implementation to understand how it works under the hood, and how you can customize it: https://github.com/huggingface/tokenizers/blob/master/bindings/python/tokenizers/implementations/bert_wordpiece.py

**Comment by cahya-wirawan** [comment]
Ok, thanks, I will have a look

**Comment by lkluo** [comment]
Same error `TypeError: sep_token not found in the vocabulary`
In fact, I can find there is `[SEP]` in my trained vocab. Why?

**Comment by lkluo** [comment]
> Same error `TypeError: sep_token not found in the vocabulary`
> In fact, I can find there is `[SEP]` in my trained vocab. Why?

I fix it by using `save_model` instead of `save` when saving `vocab_file`.

**Comment by cahya-wirawan** [comment]
@n1t0 I tried your suggestion to add the special tokens if I call train like:
```
tokenizer.train(["train.txt"], 
    special_tokens = [
    "[PAD]",
    "[UNK]",
    "[CLS]",
    "[SEP]",
    "[MASK]",
    ], vocab_size=10000) 
```
but I still get the same issue when I load it with 
```
BertWordPieceTokenizer("vocab.txt", lowercase=True)
     ...
     58             cls_token_id = tokenizer.token_to_id(str(cls_token))
     59             if cls_token_id is None:

TypeError: sep_token not found in the vocabulary
```
Actually setting the special_tokens like above shouldn't be necessary since it is default values.
As @lkluo mentioned, it is fixed when I use `save_model` instead of `save`. It seems, that in version 0.8.1.rc1 `save` saves vocabulary in a new json file format and `save_model` saves it in old file format (the same format that was used in version 0.7.0). And I assume BertWordPieceTokenizer("vocab.txt", lowercase=True) still doesn't understand the new json file format.

**Comment by n1t0** [comment]
My bad I didn't understand that you were trying to load the json file here, indeed it cannot load it and expects a vocab.txt. The `BertWordPieceTokenizer` class is here mainly to show how to build a `Tokenizer`. Once you save it, you shouldn't have to modify it, so then you should be able to load it with
```python
from tokenizers import Tokenizer

tokenizer = Tokenizer.from_file("my-tokenizer.json")
```
The benefit here is that if you decide to use a byte level BPE instead, for example, then you don't need to change the code, just the file.
The `BertWordPieceTokenizer` wouldn't make sense if you loaded it with a json that contains a byte level BPE so it only works with a vocab. Does it make sense?

**Comment by cahya-wirawan** [comment]
Yes, that makes sense. Thanks a lot for the explanation.
