### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'add_special_tokens'

### ISSUE THREAD

**Issue by Samar-080301** [huggingface/tokenizers#342]
`import tokenizers
    bwpt = tokenizers.BertWordPieceTokenizer(
    vocab_file=None,
    add_special_tokens=True,
    unk_token='[UNK]',
    sep_token='[SEP]',
    cls_token='[CLS]',
    clean_text=True,
    handle_chinese_chars=True,
    strip_accents=True,
    lowercase=True,
    wordpieces_prefix='##'
)`
I was trying this code, but the above error occured please help me!

**Comment by n1t0** [comment]
As the error states, you are specifying `add_special_tokens=True` but it is an unexpected argument (cf [`BertWordPieceTokenizer.__init__`](https://github.com/huggingface/tokenizers/blob/7a95ffc/bindings/python/tokenizers/implementations/bert_wordpiece.py#L14-L27)). You should specify this while calling `encode` for example.
