### ISSUE TITLE
How to apply both pre-tokenizer and post-processor

### ISSUE THREAD

**Issue by joverwey** [huggingface/tokenizers#352]
the output of    

```
pub fn with_pre_tokenizer(&mut self, pre_tokenizer: Box<dyn PreTokenizer>) -> &Self
```
is *&Self* which is no longer mutable.

Shouldn't this be *Self* so that you can chain multiple mutating operations like

```
Tokenizer::new(Box::new(bpe))
                .with_post_processor(post_processor)
                .with_pre_tokenizer(pre_tokenizer)

```

**Comment by n1t0** [comment]
You are totally right! It should be returning a `&mut Self` so that we can chain them. Feel free to make a PR if you want to!

**Comment by joverwey** [comment]
I don't think you can return &mut Self because you would end up with multiple borrows.
The builder pattern usually looks more like:

```
fn with_option(mut self, value: usize) -> Self
```
 
I'll take a stab at it and send a pull request.

**Comment by n1t0** [comment]
Yes, you can return `&mut Self`, and I think that's what we want. We don't want to consume `self` otherwise it becomes a pain when we don't chain.
