### ISSUE TITLE
Feature request: min_length argument for CNN

### ISSUE THREAD

**Issue by dsindex** [huggingface/tokenizers#353]
when it comes to encode very short text(say, 5 tokens) using BERT tokenizer,
and going to use 1D convolution with larger kernel size(ex, 6) on the top of the embedding results from BERT,

the convolution over the input might be failed.

so, what about add 'min_length' to 'PretrainedTokenizer' class ?
```
if the input text is shorter than 'min_length', tokenizer will add 'pad_token_id' up to 'min_length'.
```
https://huggingface.co/transformers/main_classes/tokenizer.html

**Comment by n1t0** [comment]
This is already possible using [`tokenizer.enable_padding(length=5)`](https://huggingface.co/docs/tokenizers/python/latest/api/reference.html#tokenizers.Tokenizer.enable_padding)
