### ISSUE TITLE
How to produce an encoder.json and vocab.bpe for GPT-2 encoding ?

### ISSUE THREAD

**Issue by Skylixia** [huggingface/tokenizers#361]
Hello, 

I would like to produce an encoder.json and vocab.bpe file to make the GPT-2 preprocessing/encoding as done for using fairseq library as seen in the [documentation](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md)
It seems to be possible to produce such files with this library but I am not sure how ... any tips ?

**Comment by n1t0** [comment]
Hey @Skylixia, that is indeed something you can do with this library.
You would just have to train a `ByteLevelBPETokenizer` if you want something similar to GPT-2. `encoder.json` is the `vocab.json` file this library generates, and `vocab.bpe` is the `merges.txt` file.

You can have a look [here](https://github.com/huggingface/tokenizers/issues/246) and [there](https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/train_bytelevel_bpe.py)

If you need more help on this kind of things (not a bug, more like general help), we have a Hugging Face Forum here: https://discuss.huggingface.co/

**Comment by Skylixia** [comment]
OK, thank you !
