### ISSUE TITLE
Unicode problem, Exception: Split pre-tokenized string must represent entire orignal String

### ISSUE THREAD

**Issue by wbqtac** [huggingface/tokenizers#367]
Hi there,

I got an issue when tokenizing the following sentence:

Rika Noguchi ( 野口里佳 Noguchi Rika, born 1971 in Tokyo, Japan) is a Japanese photographic artist

Exception: Split pre-tokenized string must represent the entire original string. 

The code is shown as follows,
#####################################################
from tokenizers import (ByteLevelBPETokenizer,
                            CharBPETokenizer,
                            SentencePieceBPETokenizer,
                            BertWordPieceTokenizer)
tokenizer = BertWordPieceTokenizer("bert-base-uncased-vocab.txt", lowercase=True)
original_str = "Rika Noguchi ( 野口里佳 Noguchi Rika, born 1971 in Tokyo, Japan) is a Japanese photographic artist "
output = tokenizer.encode(original_str)

I think the problem comes from the chinese unicode 野口里佳, as the tokenizer works fine if these words are removed.

Is there any way to deal with it? 

Thank you. Sorry if the question should be post somewhere else. 

Best

**Comment by Narsil** [comment]
What version of tokenizers are you using ?
Which version of `bert-base` are you using ?

I got it working by having a raw installation from scratch

```
wget https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt
pip install tokenizers
```

```python
from tokenizers import (                                                          
    ByteLevelBPETokenizer,                                                        
    CharBPETokenizer,                                                             
    SentencePieceBPETokenizer,                                                    
    BertWordPieceTokenizer,                                                       
)                                                                                 
                                                                                  
tokenizer = BertWordPieceTokenizer("bert-base-uncased-vocab.txt", lowercase=True)          
original_str = (                                                                  
    "Rika Noguchi ( 野口里佳 Noguchi Rika, born 1971 in Tokyo, Japan) is a Japanese"   
    " photographic artist "                                                            
)                                                                                 
output = tokenizer.encode(original_str)                                           
print(output.ids)       
# Output: [101, 15544, 2912, 2053, 16918, 1006, 1963, 1788, 1962, 100, 2053, 16918, 15544, 2912, 1010, 2141, 3411, 1999, 5522, 1010, 2900, 1007, 2003, 1037, 2887, 12416, 3063, 102]
```

**Comment by n1t0** [comment]
Thank you for reporting this, I'm on it. This is a bug on `master` following #360.

**Comment by wbqtac** [comment]
Hello Narsil and Anthony,

Thank you for your reply. 
My environment is python 3.6.9, tokenizers: 0.8.1, 
bert dictionary, actually I did not make it right in the beginning, after using wget to crawl it. The problem remains. 

As Anthony mentioned, this might be linked to some ongoing development. 
For Narsil, may I know the version you are working with, wondering why it works in your environment. 

Thank you.

Best

Bingqing

**Comment by Narsil** [comment]
Tokenizers: 0.8.1 Like you
Python: 3.7.1 (from miniconda if that makes any difference)
OS : MacOS Catalina, I can check on other systems but without your error it's hard to tell if that's relevant.

**Comment by n1t0** [comment]
The error message exists only on `master`, there has been no release with it (master is shown as `0.8.1` because the version was not bumped yet). 

@wbqtac If you were to install the last stable using pip, it would work.

**Comment by wbqtac** [comment]
Got it. Thank you.
