### ISSUE TITLE
missing Rust version of `from_pretrained`

### ISSUE THREAD

**Issue by Zhen-hao** [huggingface/tokenizers#369]
Hi, 
It is not clear from the README files and code what's the Rust version of the following Python code.

```python
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
```

Thanks in advance!

**Comment by Zhen-hao** [comment]
here is my own attempt to reproduce the Python code in Rust based on my study of the two projects.

```rust
use tokenizers::models::wordpiece::WordPiece;
use tokenizers::tokenizer::{Result, Tokenizer};
use tokenizers::decoders::wordpiece::WordPiece as WordPieceDecoder;
use tokenizers::normalizers::bert::BertNormalizer;
use tokenizers::pre_tokenizers::bert::BertPreTokenizer;


fn main() -> Result<()> {
   // download from "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-vocab.txt";
    let input_file = "./bert-base-cased-vocab.txt";

    let wordpiece_builder = WordPiece::from_files(input_file);
    let wordpiece = wordpiece_builder
        .build()?;

    let mut tokenizer = Tokenizer::new(Box::new(wordpiece));

    //tokenizer.with_normalizer(Box::new(BertNormalizer::default()));
    tokenizer.with_normalizer(Box::new(BertNormalizer::new(true, true, None, false)));
    tokenizer.with_pre_tokenizer(Box::new(BertPreTokenizer));
    tokenizer.with_decoder(Box::new(WordPieceDecoder::default()));

    let encoding = tokenizer.encode("This is a test sequence", false)?;
    println!("encoding length is {}", encoding.len());
    println!("{:?}", encoding.get_tokens());
    println!("{:?}", encoding.get_ids());  

   Ok(())
``` 

output:
```
encoding length is 5
["This", "is", "a", "test", "sequence"]
[1188, 1110, 170, 2774, 4954]
```

It would be great if someone can tell me if this makes sense or not.

**Comment by jacklanda** [comment]
> Hi, It is not clear from the README files and code what's the Rust version of the following Python code.
> 
> ```python
> from transformers import BertTokenizer
> tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
> ```
> 
> Thanks in advance!

As far as I am concerned, there is no existence of `from_pretrained` method, because I didn't get a result when searched around the source code in tokenizers dir.

**Comment by jacklanda** [comment]
> Hi, It is not clear from the README files and code what's the Rust version of the following Python code.
> 
> ```python
> from transformers import BertTokenizer
> tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
> ```
> 
> Thanks in advance!

As far as I am concerned, there is no existence of `from_pretrained` method, because I didn't get a result when searched around the source code in tokenizers dir.

**Comment by Narsil** [comment]
Hi @jacklanda,

How did you check ? https://github.com/huggingface/tokenizers/search?p=2&q=pretrained

Also, to use this, you need to build from source.

**Comment by jacklanda** [comment]
> 
I use a command `find . | xargs grep -ri` to search the target pattern I want(here it's `from_pretrained`).
And I do this in this cache dir in the image below:
<img width="671" alt="图片" src="https://user-images.githubusercontent.com/54089835/142646008-2242f2ff-6a53-4cbd-9ac9-58edc3dae8b9.png">
However, it seems that this directory I do searching is not complete, right? It misses many files which shows in this url: https://github.com/huggingface/tokenizers/search?p=2&q=pretrained
If it's true, I make a wrong judgement obviously :(

**Comment by Narsil** [comment]
You are using the last version published on crates, which is not master.

This hasn't been released yet.

**Comment by jacklanda** [comment]
> 

Got it, thanks for correcting my misunderstanding 👍🏻

**Comment by bpatter5** [comment]
Support for `from_pretrained` appears to have been dropped in the latest version of Rust tokenizers (0.14.1) where it had been supported in version 0.13.3. See the below:
<img width="1219" alt="version_0141" src="https://github.com/huggingface/tokenizers/assets/25406053/188e30e6-338f-42bd-aecb-63cf1c7f4d41">
<img width="1162" alt="version_0133" src="https://github.com/huggingface/tokenizers/assets/25406053/e95a6c03-8448-490f-9140-a2d44392bc59">
I didn't see a note regarding support for `from_pretrained` being dropped in the release notes so figured I would raise the issue here.

**Comment by bpatter5** [comment]
Updating to reflect that after reviewing the Tokenizer implementation on the 0.14.1 branch you need to add the http feature when installing via cargo add: `cargo add tokenizers@0.14.1 --features http` to get support for `from_pretrained`.
