### ISSUE TITLE
added tokens show strange behaviour 

### ISSUE THREAD

**Issue by dragonshill** [huggingface/tokenizers#370]
When BertTokenizer is used to tokenize compound words, such as 'uncommitted', it uses any known tokens for the first piece (eg 'un') and then only uses continuation tokens (eg '##com') for the remaining pieces.   It does not use known words such as 'committed'.
If add_tokens is used to add a new token such as 'helloxxx', and then the tokenizer is used on a compound word starting with this new token such as 'helloxxxcommitted' the result is ['helloxxx', 'committed'].
I would expect the result to be ['helloxxx', '##com', '##mit', '##ted'].
Furthermore, if the compound word is very long, it will only be the first full known word following the new token that is used, and any subsequent tokens will be continuation tokens.    For example, 'helloxxxcommittedcommitted' would be tokenized as ['helloxxx', 'committed', '##com', '##mit', '##ted'].
One more complication is that the single '#' token seems to behave in the same way as the added tokens.

Is this working as intended?

**Comment by n1t0** [comment]
Added tokens are extracted before it is able to reach the underlying `Model`. So if you add `helloxxx`, then it is extracted, and the `WordPiece` model only gets `committed` which is a known word. So yes, in this case, this is expected.

The second example is expected too, in this case, `WordPiece` gets `committedcommitted`, and the second `committed` is *inside* the part word, so it must start with `##`. Here it could match `##committed` if it was in the vocabulary.
