### ISSUE TITLE
Where can I find the API documentation of tokenizers? 

### ISSUE THREAD

**Issue by rossbrown9879** [huggingface/tokenizers#375]
I have text and I want to tokenize the text using pre-trained sentencepiece tokenizer. How can I do this? I could not find the API documentation of the tokenizers library. If there is one, can someone please provide the link to the API documentation of this library?

**Comment by chadykamar** [comment]
https://huggingface.co/transformers/main_classes/tokenizer.html

**Comment by n1t0** [comment]
@rossbrown9879 The API documentation for `tokenizers` is not available at the moment. It should be soon though. In the meantime, you can have a look at the `.pyi` files in this directory: https://github.com/huggingface/tokenizers/tree/master/bindings/python/py_src/tokenizers

@chadykamar The documentation you linked is actually for the `transformers` library, which uses this library under the hood but still is different.

**Comment by n1t0** [comment]
I'm happy to let you know that a first version of the documentation is alive here: https://huggingface.co/docs/tokenizers
Not everything has been documented yet, but we are getting there!
