### ISSUE TITLE
How to use custom special characters with ByteLevelBPETokenizer?

### ISSUE THREAD

**Issue by jchwenger** [huggingface/tokenizers#376]
Hi,

Thanks as always for the great library, I'm using it to produce custom vocabularies for GPT-2, keep up the good work!

However, one issue is bugging me. I'm trying to add custom special tokens (as well as the famed `<|endoftext|>`, used by OpenAI but not handled by their provided encoder), and that works as a charm when training, I get my json and my merges, but then, how do I use those? Whenever I instantiate my encoder and feed it my files, the decoding will still give me, for instance, `<|endoftext|>` split into many ids, even if it sits there at the beginning of my encoder, `"<|endoftext|>": 2, "!":3`... 

```
$ tok = ByteLevelBPETokenizer(vocab_file="encoder.json", merges_file="vocab.bpe")
$ tok.encode("<|endoftext|>") # [23, 2435, 234, etc...], instead of [2]
```

I've started looking into that, and found a few things here and there, mostly related to pre-established special tokens for BERT and such, but I'd like to be able to specify any special token (that I could then use in my datasets and when generating).

Any help greatly appreciated!

**Comment by n1t0** [comment]
Can you try with `add_special_tokens`? (I saw your comment on the other issue)

**Comment by jchwenger** [comment]
Ha! It works, thanks a lot! Should it not normally do that automatically if one has created the model specifying those special tokens in the first place (with the tangent question: should the special tokens *have been present* in the training dataset for them to be taken into account, i.e. perhaps be present in the bpe somewhere, and not just in the encoder?)

**Comment by jchwenger** [comment]
Hi again,

I can report on a few findings, which might help others, & reformulate my above question regarding training.

1. Adding tokens work just fine, one has to distinguish between already present special tokens (in the encoder but not in the merges) and ones one would add after training. (This is done with the basic GPT-2 model, easy to replicate.)

```python
from tokenizers import ByteLevelBPETokenizer
enc = ByteLevelBPETokenizer(vocab_file="models/117M/encoder.json", merges_file="models/117M/vocab.bpe")
# "<|endoftext|>" is present in encoder.json as 50256, but not in any bpe merge
enc.encode("<|endoftext|>") .ids # [27, 91, 437, 1659, 5239, 91, 29], no good
enc.add_tokens(["<|endoftext|>"]) 
# -> 1 doesn't do anything, because the token is already present in the encoder
enc.encode("<|endoftext|>") .ids # same as before, [27, 91, 437, 1659, 5239, 91, 29]
enc.add_special_tokens(["<|endoftext|>"])
 # -> 1 works, but with the effect that "<|endoftext|>" will not appear in any decoded string, as expected, cf. below
enc.encode("<|endoftext|>").ids  # [50256], yaas!
enc.decode(enc.encode("hello invisible mr. <|endoftext|>").ids) # 'hello invisible mr. '

# with a special token not yet present in encoder.json, things work as expected
enc.encode("<|blah|>").ids # [27, 91, 2436, 993, 91, 29]
enc.add_tokens(["<|blah|>"]) # -> 1
enc.encode("<|blah|>").ids # [50257]
```

2. This question comes up as I'm training new models. What I'm encountering is that whenever I'm giving special tokens for training, the model will contain them at the beginning of the generated encoder.json, but the merges will still have been done as if those did not exist. 
Let's imagine I have a dataset prepared with markers, '<|x|>', '<|y|>', intended to be learnt by the model so that they would pop up during generation and allow for some control. What I do is the standard training procedure:

```python
tok = ByteLevelBPETokenizer()
tok.train(all_the_files, vocab_size=args.vocab_size, special_tokens=args.special_tokens)
tok.save(directory=model_dir)
```
After that, the special tokens do appear at the top of my encoder.json file but I can see that my merges file look like this:
```
#version: 0.2 - Trained by `huggingface/tokenizers`
< |
| >
Ġ d
o u
e s
Ġ p
e n
Ġ l
o n
```
If I load that version, I encounter the same situation as above, where the special tokens have to be specified when initializing the encoder. I would have imagined that the special tokens would be treated separately, and always considered one unit? Given this, I tend to conclude that the current Huggingface implementation focuses on what is known in Sentencepiece as `control_symbols`, and not the `user_defined_symbols` (the same as Sennrich et al.'s `glossaries`, it seems, namely predefined tokens encoded as one piece). (References [here](https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md) and [here](https://github.com/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb) for sp, and [here](https://github.com/rsennrich/subword-nmt#advanced-features) for subword-nmt). Is this a correct assessment? 

Thanks a lot for your time!

**Comment by n1t0** [comment]
Hi @jchwenger. 

There is no way for the tokenizer to know what should be treated as special tokens just by reading the vocabulary and merges files, so if you load a tokenizer using these, you will always have to specify the special tokens after initialization.
Now, starting from `0.8.0` and above, when you call `.save` on a tokenizer, it actually saves a `.json` file with every piece of information about this tokenizer. When you load this file, it knows what are the special tokens, other added tokens, etc.
So you should be able to do something like this:
```python
from tokenizers import ByteLevelBPETokenizer
tok = ByteLevelBPETokenizer()
tok.train(all_the_files, vocab_size=10000, special_tokens=["<|x|>", "<|y|>"])
tok.save("my-tokenizer.json")

# and then later
tok = Tokenizer.from_file("my-tokenizer.json")
enc.encode("<|x|>").ids # [0]
```

The tokens you add using `add_token` or `add_special_tokens` will always resolve to a single ID too, but this process is intended to happen after the training. If the corpus you use to train your tokenizer contains such tokens, they won't be treated differently, and the tokenizer might learn to merge them. When you encode though, it will extract them as single IDs. Does it make sense?

**Comment by jchwenger** [comment]
Hi @n1t0,

Thanks for this! Indeed the specification after initialization makes sense. And great that this will be included in a future update. I definitely learnt quite a few things manipulating these different encoders, it's great.
