### ISSUE TITLE
Building the Python Binding from Source Results in Syntax Error

### ISSUE THREAD

**Issue by strickolas** [huggingface/tokenizers#396]
Hey,

Trying to build tokenizers inside of a [singularity](https://sylabs.io/singularity/) container (pretty much like docker). The container is running ubuntu focal, and is running on ppc64le arch. These are the steps I'm taking inside my container:
```
cd ~/Downloads
git clone https://github.com/huggingface/tokenizers
cd tokenizers/bindings/python  
python3 -m venv .env 
bash -c "source .env/bin/activate" 
pip install setuptools_rust  
python3 setup.py install
```

Here's the full stacktrace: https://pastebin.com/b2iQvuU9
This is where everything goes wrong:
```
     Running `rustc --crate-name build_script_build /root/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.14/build.rs --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="std"' -C metadata=a2f448377b0a260e -C extra-filename=-a2f448377b0a260e --out-dir /root/Downloads/tokenizers/bindings/python/target/release/build/getrandom-a2f448377b0a260e -L dependency=/root/Downloads/tokenizers/bindings/python/target/release/deps --cap-lints allow`
```

I know nothing about rust, so I won't even begin to try to diagnose it. Hoping someone here can help me.

Thanks in advance!

**update**: installing through `pip install -vvv` is giving me the same exact stack trace.

**Comment by Narsil** [comment]
Seems like the rust version is outdated.

Can you try running

`rustup update` 

after `git clone` ?

Can you try running `rustc --version` otherwise in a shell to confirm this ?

If this does not work try running

`pip3 install -e .` It tends to yield better results than `python3 setup.py install` for some reason.

**Comment by strickolas** [comment]
This was exactly the problem. After doing a rustup, successfully got it installed!
