### ISSUE TITLE
Removing some important characters in multilingual

### ISSUE THREAD

**Issue by mkstt** [huggingface/tokenizers#399]
When I use lower_case= True, the tokenizer remove the important characters in multilingual. The characters are in Unicode Characters in the 'Mark, Nonspacing' Category.

**Comment by LysandreJik** [comment]
Hi, could you provide an example with some code as well? Does it still happen if you specify `strip_accents=False`?

**Comment by mkstt** [comment]
It worked by using the BertWordPieceTokenizer and setting strip_accents = False. It appears as the error was in unicode.category in the strip accents function.

**Comment by LysandreJik** [comment]
Very cool to hear this solved your problem. We should probably rename `strip_accents` to something more explicit.
