### ISSUE TITLE
How to tokenize multiple files?

### ISSUE THREAD

**Issue by neel04** [huggingface/tokenizers#402]
@julien-c I have been looking in a lot of places and forums online, but am unable to find out how to resolve my issue. Basically, I am doing a seq2seq task that involves **2 files**- one has the input sequences and the other has corresponding output sequences. I have trained the Tokenizer model and have obtained the 2 files - `merges.txt` and `vocab.json`.

The funny thing is that I had already made the `bpe` files before, but had accidentally deleted them. Now, I can't figure out how to use the 2 obtained files to tokenize my whole dataset. This is the code I was using for the final tokenization:-
```
from transformers import LineByLineTextDataset
from transformers import BartTokenizer

tokenizer = BartTokenizer.from_pretrained("/content/drive/My Drive/HashPro/tokenized/", max_len=512)

dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path= "/content/drive/My Drive/HashPro/hash_out.txt", block_size=128)


dataset_2 = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="/content/drive/My Drive/HashPro/hash.txt", block_size=128)

```
But it doesn't produce any files at all. I know that this is not a very clear request, but admittedly the HF library and docs are not very good for tokenization. I am trying to train a `BART` model for my task. 

Another problem is that I am NOT using the HF transformers for training my model (I am using FairSeq, but it doesn't have tokenization facilities), so I just want a simple `.bpe` file out of the library (containing both the files preferably) which is however very hard to get. So can anyone guide me in the right direction?

**Comment by n1t0** [comment]
Hi @neel04. I'm not sure how to help you here: I am not familiar with FairSeq, and therefore I don't know what you are trying to achieve exactly.

Can you post this on https://discuss.huggingface.co? There will probably be somebody able to help you over there! Closing the issue here.

**Comment by neel04** [comment]
I will try summarising it if it may help someone else- My basic question was how to tokenize a whole document using the HF tokenizer, since in all the examples I have seen it just creates the tokenizer to be called when trained using the HF_transformers library only. It will not tokenize the documents before to be used anywhere. 
I solved this problem by using Google's SentencePiece library which worked much faster than HF. 

Also an off-topic question - why is that the HF tokenizers implementation takes so much more RAM than other tokenization packages? For tokenization of my dataset took 32Gb RAM instance while for SentecePiece 12Gb was enough. Did HF choose speed over memory for it's `rust` implementation? I expected `tokenizers` to use 16Gb max. but it took 32Gb. Is that a bug or is it how `tokenizers` lib works?

**Comment by Narsil** [comment]
Hi @neel04,

The example you used in your first issue does not actually this library (`tokenizers` vs `transformers`). If you want to use this library from transformers your need to use `from transformers import BartTokenizerFast` (or `from tokenizers import BartTokenizer`). The goal is to become the default in transformers somewhere in the future. Hopefully this will come soon, but we need to make sure it's seemless.

In terms of you not finding the relevant documentation, where did you look so we can improve?  I think you were looking for this page : https://github.com/huggingface/tokenizers/tree/master/bindings/python (The README)

If you used `SentencePiece` and found it suit you better, then good for you, you should also check `youtokentome` which is even faster. This library's purpose is to be more versatile to support all different kinds of tokenizations while keeping the same level of efficiency. We also keep something that has a cost, which is the back correspondence between tokens and their position in the original string.
```python
tok = ByteLevelBPETokenizer('tata/vocab.json', 'tata/merges.txt')
tok.encode('I like apples').offsets
# [(0, 1), (1, 6), (6, 13)]
```

That may not sound like much, but it's super useful when you are working with some languages where a lot of normalization happen, some parts are fully ignored, others are rewritten and at the end you might be really confused as to why you get the tokens you are getting.

It might explain your Memory usage, but it could very well be a missed optimization (this library is still quite new). On which dataset did you work, can we reproduce ? Or what was the size of the dataset you used ? Which code did you run ?

Cheers,
