### ISSUE TITLE
Feat : add a loading api like transformers library

### ISSUE THREAD

**Issue by Ierezell** [huggingface/tokenizers#412]
Hi, 

First thanks a lot for this wondefull library, it's really usefull to use Transformers models outside of python (like onnx embedded and stuff). 

I'm proposing here to add a helper to download the correct model from the cloud. 
Like `tokenizer.load_pretrained('bert-base-uncased')` like in transformers which will donwload and instanciate the good tokenizer.  Maybe there is actually a way to do it but except [this comment](https://github.com/huggingface/tokenizers/issues/59#issuecomment-610645970) I didn't found an out of the box solution. 

[The transformer script](https://github.com/huggingface/transformers/blob/206b78d4850d3c6fe85a015654293fc4b803ed7b/src/transformers/convert_graph_to_onnx.py#L52) uses a --tokenizer flag but it doesn't seem to save it with the onnx model... 

I guess it would help many people to use more easily this library and avoid confusion between models tokenizersr etc.

**Comment by Narsil** [comment]
Hi,

Thanks for the suggestion, that's definitely a pain point right now.
I don't think we have a definitive answer as to how to solve this problem but I think we're going to keep the download logic within transformers, so it's maintained in only one place, and kept in sync with the version of `tokenizers` that they use. If you want to use `tokenizers` from source, you might encounter problems for sure (we are changing the file saving mechanism for instance)

So something like
```python
transformer_tokenizer = transformers.AutoTokenizer.from_pretrained('bert-base-uncased')
transformer_tokenizer.save_pretrained(filename)

tokenizer_tokenizer = tokenizers.load_pretrained(filename) # In whatever language we support
```
is something of a target, but unfortunately not working right now.

----

As for the transformer script, you mentionned, the tokenizer is used only to get the proper shape for the ONNX graph, the tokenizer is *not* part of an NN graph so it can't be included. But if you use something embedded you can probably use the rust version of tokenizer to build a binary that can run the tokenizer (Let us know if there are any issues).

**Comment by Ierezell** [comment]
Hi, thanks a lot for your reply !

I made a feature request something looking like [this issue](https://github.com/huggingface/transformers/issues/7132#issue-701393639) is doing the job for me right now.

**Comment by Narsil** [comment]
Yes that's the best bet you have for now, we will document everything when it gets as simple as my proposition, for the mean time sorry it's a bit bothering.

Closing this issue.
