### ISSUE TITLE
Add a normalizer for removing double single quotes

### ISSUE THREAD

**Issue by Narsil** [huggingface/tokenizers#414]
Transformers tokenizer_albert code contains this line:
```python
line = line.replace("``", '"').replace("''", '"')
```

We currently have no way to handle this with normalizers. We need it to be able to emulate this tokenizer.

Either a specialized one, or regexp ?

**Comment by n1t0** [comment]
What do you think about a `Replace` normalizer? It could support both strings and regexp as input, and use the `NormalizedString::replace` method.

I'm currently implementing the bindings for `NormalizedString` so I had to work on the API for the `Pattern` used in `NormalizedString::replace`. We can definitely use all of this to easily implement this `Normalizer`.

**Comment by Narsil** [comment]
Replace seems good, and yes like in Rust string or regexp seems good. If it's a string pattern, it should be faster than regexp and it should be the most used one.
