### ISSUE TITLE
Tokenizer training fails with no error message if passed a Path

### ISSUE THREAD

**Issue by miguelvictor** [huggingface/tokenizers#419]
Passing paths to a training file using `pathlib` library throws a `TypeError` without any helpful message.
 
Please see this [gist](https://gist.github.com/miggymigz/3e0119763ecb8f60f94de96c332b0002) to reproduce this bug.

**Comment by sebpuetz** [comment]
More helpful error messages will be generated once PyO3 is upgraded to 0.12. In this particular case there is no implementation to extract a `String` in Rust from a `pathlib` `Path`. I'm not sure whether there is a simple and sane solution for `tokenizers` to support `Path`s, but the straight forward one is to pass a `str` to the failing function.

**Comment by davidhewitt** [comment]
FYI for PyO3 0.14 you can write functions which take Rust `Path` objects which will accept both strings and `pathlib.Path` objects from Python.
