### ISSUE TITLE
tokenizers.Tokenizer object is not callable with LineByLineTextDataset

### ISSUE THREAD

**Issue by aqibsaeed** [huggingface/tokenizers#424]
Hi,

I want to use a custom tokenizer which defined as follows:

```
tokenizer = Tokenizer(WordLevel("vocb.json"))
tokenizer.pre_tokenizer = WhitespaceSplit(" ")
```

to be used with `LineByLineTextDataset` as:

```
dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="data.txt",
)
```

but I get following error: `TypeError: 'tokenizers.Tokenizer' object is not callable`. 

I am following [How to train a new language model from scratch using Transformers and Tokenizers colab](https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/01_how_to_train.ipynb) to be precise. Any ideas on how to fix this issue?

**Comment by aqibsaeed** [comment]
Any pointers on how to resolve this issue?

**Comment by aqibsaeed** [comment]
@n1t0 I would really appreciate if you provide any hints to resolve this issue.

**Comment by n1t0** [comment]
Hi @aqibsaeed. The `LineByLineTextDataset` is a class from the `transformers` library. You are supposed to give it a tokenizer that comes from `transformers` too. We are moving towards a full support of the tokenizers provided by `tokenizers` but we aren't there yet.

In the meantime, maybe you can try something like this:
```python
from tokenizers import Tokenizer
from tokenizers.implementations import BaseTokenizer
from transformers import PreTrainedTokenizerFast, LineByLineTextDataset

# Load the `tokenizers` Tokenizer somehow
base_tokenizer = ..
# Wrap it in something `transformers` understands
tokenizer = PreTrainedTokenizerFast(BaseTokenizer(base_tokenizer))
```

**Comment by aqibsaeed** [comment]
Thank you for the response. Now it raises following error:
`ValueError: You are attempting to pad samples but the tokenizer you are using (PreTrainedTokenizerFast) does not have one.`

**Comment by n1t0** [comment]
Did you try setting a pad token then?
```python
tokenizer.pad_token = "<my_pad_token>"
```

I'm the maintainer of `tokenizers`, and therefore not really familiar with the internals of `transformers`. So, if you have any further questions on this subject, you might have a better chance of getting an answer on the forum :smile: https://discuss.huggingface.co

**Comment by aqibsaeed** [comment]
Cool! Thanks!

**Comment by maiiabocharova** [comment]
If someone faces this issue: the way to convert your custom trained tokenizer to be same as` transformers` library uses is:

```
from transformers import PreTrainedTokenizerFast
from tokenizers import Tokenizer
tokenizer = Tokenizer.from_file('your/save/file.json')
fast_tokenizer = PreTrainedTokenizerFast(tokenizer_object=tokenizer)
```

And f`ast_tokenizer` is the tokenizer you need.
