### ISSUE TITLE
bug when using special token with uppercase

### ISSUE THREAD

**Issue by guolinke** [huggingface/tokenizers#438]
I train the BERT wordpiece by my own, with do_lowercase=True.
In my corpus, I pre-replace some token to [UNK] and [SEP], and both [UNK] and [SEP] are in the default special tokens. 

after the training finish, I find there are several undesired tokens in the vocab.txt.

```
##sep]
[sep]
[unk
[unk]
```

I grep my traning corpus, and cannot find these tokens.

I guess do_lowercase will break the upper_case special tokens.

**Comment by guolinke** [comment]
even I set `do_lowercase=False`, there are still some undesired tokens.
```
[S
##EP
[SEP
```

**Comment by Narsil** [comment]
That does seem like a bug. Looking into how to fix that properly.
