### ISSUE TITLE
Example for using pretrained tokenizer

### ISSUE THREAD

**Issue by Palipoor** [huggingface/tokenizers#446]
Hi!
I know that we can load pre-trained tokenizers from a folder, but I can't find an example that has done so. Particularly, I want to know what should be there in the folder. 
I want to have a GloVe vectors-based tokenizer.

**Comment by Narsil** [comment]
Hello @Palipoor I think folders are from `transformers`, in this library you're probable want to load from a single File, and if I'm not mistaken for GloVe you'll want to use `WordLevel` tokenizer.

For tokenizers, Python v0.8.1:
```python
from tokenizers import WordLevel, Tokenizer, pre_tokenizers

tokenizer = Tokenizer(WordLevel("myfile.json"))
tokenizer.pre_tokenizer = pre_tokenizers.WhitespaceSplit()
```

and the file contains someting like
```json
{"Hey": 0, "Welcome": 1, "the": 2, "<unk>": 3}
```

Be careful though that the format is going to change (for better uniformity, and simplicity, so you don't have to manually add WhitespaceSplit anymore), but it will be pretty similar.

**Comment by Palipoor** [comment]
Thanks!

**Comment by Palipoor** [comment]
Umm.. I seem to run into this error with the import line:

```
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'WordLevel'
```

**Comment by Narsil** [comment]
Sorry

```python
from tokenizers.models import WordLevel
```
