### ISSUE TITLE
does tokenizer support emoji?

### ISSUE THREAD

**Issue by steveguang** [huggingface/tokenizers#450]
Hi, I have the code below and it always encodes emoji as "unk". Can someone tell me what I should do? Thanks

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
s =" 😃 hello how are you"
tokenizer.tokenize(s)
['[UNK]', 'hello', 'how', 'are', 'you']

**Comment by Narsil** [comment]
Hi steve,

This behaviour is expected as the Bert models does not have a specific token for this emoji, so it's treated as [UNK] (meaning the model does not know what this is).
 
If you have specific emojis you want to use in some finetuning, you could try adding them as `special_tokens`, or you could try retraining a model with a tokenizer that already include emojis (but be wary there are a lot of emojis, you probably can't train a model with *all* of them.

**Comment by steveguang** [comment]
thanks, @Narsil I have another question. When I train using tweets, since there is a lot of noise, a tweet like 'This is soooo good' would be a problem for BERT tokenizer cuz "soooo" is not in the vocabulary. Is there a method to add all of them? Right now I am thinking about a kinda ugly way, just use nltk tweettokenizer to process all tweets and add to vocab with words, emoji, etc that appear frequently

**Comment by Narsil** [comment]
Preprocessing that stuff is an art and is messy. I would advise to be *very* cautious with using code you did not write to fix that, as they might do stuff completely wrong (at least very different from what you think they should do).

You could use a byte level tokenizer (like GPT-2) which would not contain any unk tokens by definition. Also consider retraining a tokenizer. It will be more adapted to your dataset. There is this very nice colab to train a tweet model: https://colab.research.google.com/github/borisdayma/huggingtweets/blob/master/huggingtweets-demo.ipynb#scrollTo=ZSCf6QyF8AG- for inspiration (might not be useful to you but I thought I'd share)

**Comment by n1t0** [comment]
Closing this, feel free to reopen if you needed!
