### ISSUE TITLE
SentencePieceUnigram Tokenizer: index out of bounds

### ISSUE THREAD

**Issue by Skyy93** [huggingface/tokenizers#457]
hi,
i'm currently try to train my own SentencePieceUnigram-Tokenizer and get an error:
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 10 but the index is 10', /__w/tokenizers/tokenizers/tokenizers/src/models/unigram/lattice.rs:173:9
Traceback (most recent call last):
  File "train_tokenizer.py", line 51, in <module>
    tokenizer.train(files=paths, vocab_size=args.vocab_size, special_tokens=[
  File "/home/me/.local/lib/python3.8/site-packages/tokenizers/implementations/sentencepiece_unigram.py", line 78, in train
    self._tokenizer.train(trainer, files)
pyo3_runtime.PanicException: index out of bounds: the len is 10 but the index is 10
```

I wanted to train on the Leipzig English News 2016 Corpora.

If you need further information please let me know

**Comment by Narsil** [comment]
Yes can you give an example to reproduce ?
Also which version are you running ? 0.9.0 should contain the fix, but rc do not.

We introduced a late patch to fix here: https://github.com/huggingface/tokenizers/commit/fbca797b3dca241762448b10f00c88f56f9c4e6f.

**Comment by Skyy93** [comment]
I was on the RC2. The reinstall of tokenizers solved the problem. Thank you very much! Sorry was not up to date with the latest release
