### ISSUE TITLE
tokenize result is empty

### ISSUE THREAD

**Issue by luluxing3** [huggingface/tokenizers#458]
![image](https://user-images.githubusercontent.com/23072928/95830861-e08d8e80-0d6a-11eb-93c5-646a0dad1f9e.png)

I try to use provided tokenizer, but got empty result.
The tokenizers version is 0.9.0.
What's wrong with it? Thanks.

**Comment by n1t0** [comment]
Hi @luluxing3.

The `SentencePieceBPETokenizer` expects both a vocab (a mapping token->id in the format `Dict[str, int]`), as well as a list of merges (A list of tuples of string. Each tuple contains two tokens that should be merged together) (Cf the [python file here](https://github.com/huggingface/tokenizers/blob/master/bindings/python/py_src/tokenizers/implementations/sentencepiece_bpe.py))

**Comment by luluxing3** [comment]
How to get the merges? 

I use hugging face API add_tokens and save the new XLM-Roberta tokenizer.
![image](https://user-images.githubusercontent.com/23072928/95936402-0b79f000-0e08-11eb-8f05-58db2ae67977.png)

The new tokenizer contain those files.
![image](https://user-images.githubusercontent.com/23072928/95936537-64e21f00-0e08-11eb-98fe-147e4845d09a.png)

I want to use the tokenizers repo to make it more fast. How can I get it? Thanks.

**Comment by Narsil** [comment]
The code is a bit tricky as XLMRoberta did use some various odd tokens (they are two 'unks' in the vocabulary for instance).

However, there *is*  a `XLMRobertaTokenizerFast` right now in transformers from source.
So
```
AutoTokenizer.from_pretrained('xlm-roberta-base', use_fast=True)
```
works

If you are unable to use `transformers` from source, you can check out the code we use to do the conversion: https://github.com/huggingface/transformers/blob/7968051aba33ebe47668ef0d8ff2f8888dcf94bd/src/transformers/convert_slow_tokenizer.py#L434

Using those might be the best bet, as `transformers` added quite a lot of testing to make sure they behave in the same way as the *slow* tokenizers.

**Comment by n1t0** [comment]
Closing this, feel free to reopen if needed.
