### ISSUE TITLE
Test fails in `--release` mode

### ISSUE THREAD

**Issue by janpetschexain** [huggingface/tokenizers#461]
The test `test_sample` from `tests/unigram.rs` fails if compiled in release mode.

```
cargo test --test unigram --release

thread 'test_sample' panicked at 'assertion failed: `(left !== right)` (left: `0.294`, right: `0.2496817458757616`, expect diff: `0.03`, real diff: `0.04431825412423837`)', tests/unigram.rs:100:13
```

Two things to note:
- This only happens if compiled with the `--release` flag and excluded otherwise, because the test is annotated with `#[cfg(not(debug_assertions))]`, that's why the CI doesn't catch this.
- The test seems to be non-deterministic, it fails for roughly 9 out of 10 cases and succeeds occasionally.

**Comment by Narsil** [comment]
Ok, this is effectively an heuristic test (to test sampling of Unigram model).

It does fail way too much currently and that's because we don't  accumulate enough samples. I will add 10x more samples so it fails rarely.

**Comment by janpetschexain** [comment]
> Ok, this is effectively an heuristic test (to test sampling of Unigram model).
> 
> It does fail way too much currently and that's because we don't accumulate enough samples. I will add 10x more samples so it fails rarely.

that explains the non-deterministic behavior, thanks for clarification!

**Comment by Narsil** [comment]
That is also why it's behind the `--release` flag. We don't check those in CI (because flaky) and they are super slow to run in debug mode anyway.
