### ISSUE TITLE
Support for binary data

### ISSUE THREAD

**Issue by pdeblanc** [huggingface/tokenizers#474]
I'm trying to train a transformer on a binary data set, but `ByteLevelBPETokenizer` raises `Exception: stream did not contain valid UTF-8`. It seems to me that a byte level tokenizer could operate agnostically on bytes rather than trying to decode unicode strings -- is there no support for binary data?

**Comment by n1t0** [comment]
Indeed, there is no support for binary data. The byte-level here is actually in charge of treating the Unicode at the byte-level as opposed to Unicode code-points.
