### ISSUE TITLE
Is this code correct?

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#475]
This seems to check if the UNK token has been added and if true it adds it again? Shouldn't the test be if is None?

https://github.com/huggingface/tokenizers/blob/91f602f744f7fee72f2f5fa8d6c7c48bb1d72d3b/bindings/python/py_src/tokenizers/implementations/char_level_bpe.py#L55

**Comment by n1t0** [comment]
Hi @david-waterworth. 

I understand that this may be misleading, but it is actually right. The code you mentioned checks if the token exists in the vocabulary, and if it exists, then it lets the `Tokenizer` know to use it as a special token.

If you want to add it anyway, creating a new ID for this special token if it does not exist, then you can absolutely call `tokenizer.add_special_tokens(...)`.
