### ISSUE TITLE
Feature Request: Example of how best to use with datasets

### ISSUE THREAD

**Issue by jamesmf** [huggingface/tokenizers#479]
It'd be helpful if there was a suggestion in the docs of how to best use `tokenizers` and `datasets` together. I can see why the two have different default formats, but an example of  might be helpful - even if it's just something that explains that you have to convert from the arrow format to a text file.

**Comment by Narsil** [comment]
Closing in favor of #198 to keep the discussion centralised (PR open at #512 )
