### ISSUE TITLE
Newline character in merges.txt

### ISSUE THREAD

**Issue by esceptico** [huggingface/tokenizers#482]
How can I correctly read the merges.txt file if it contains \n character (maybe it's the wrong way to save the model)?
In case of `tokenizer.save(model.json)` -> `Tokenizer.from_file(model.json)` I can use \n (json format can handle it)
But if I try to save the model to `vocab.json` and `merges.txt` via `tokenizer.save_model(dir, name)`, I get the following error:
```
Exception: Error while initializing BPE: Merges text file invalid at line 5
````
Аnd I understand why this is happening (line break breaks the file format). But how can I handle this without additional newline character preprocessing?

**Comment by Narsil** [comment]
I don't think you can. 

The format `vocab.json` + `merges.txt` is there for backward compatibility but does not handle some edge cases (for instance `\n` in the vocab). The way some other lib deal with this (and you can do it here too, is to use `Metaspace` normalizer + decoder, to replace `\n` by some other char that will not cause the issue, the decoder will handle it back.

**Comment by esceptico** [comment]
Many thanks!

I understand correctly that I should use a normalizer + decoder pipeline to create the correct corpus for tokenizer training?

**Comment by Narsil** [comment]
It's hard to know what you are exactly looking for (it depends what kinds of normalizers/decoders you already use and so one).

I think a minimal example would be something like

```python
from tokenizers import Tokenizer, normalizers, decoders, models

tokenizer = Tokenizer(models.BPE())
tokenizer.normalizer = normalizers.Metaspace("\n", "▁") # this is *NOT* underscore but a rare unicode char
tokenizer.decoder = decoders.Metaspace("\n", "▁") 

trainer = ....
tokenizer.train(....)
tokenizer.model.save_model(dir, nam)
```
Keep in mind I didn't check this but it's the gist. Keep in mind also that we are reading line by line and explicitly ignoring '\n' in the default case as it's supposed to be separating sentences
But I assume you are already are going around it given your issue.

**Comment by esceptico** [comment]
Now everything is clear to me. Thanks!

**Comment by Narsil** [comment]
I'm closing this. Feel free to reopen.
