### ISSUE TITLE
PostProcessor applied after padding

### ISSUE THREAD

**Issue by bastiscode** [huggingface/tokenizers#484]
According to the docs (https://huggingface.co/docs/tokenizers/python/latest/api/reference.html#tokenizers.Tokenizer.post_process) when calling the `post_process` function the `PostProcessor` is applied before the padding. However, in my case it seems like its the other way around which does not make a lot of sense to me (see the example below).

```
byte_pair_tok # this is a trained ByteLevelBPETokenizer()

byte_pair_tok.enable_padding(pad_id=word_piece_tok.token_to_id('<pad>'), pad_token='<pad>', length=16)
byte_pair_tok.enable_truncation(max_length=16) 
byte_pair_tok.post_processor = processors.TemplateProcessing(single='<bos> $A <eos>',
                                                             pair="$A $B",
                                                             special_tokens=[('<bos>', byte_pair_tok.token_to_id('<bos>')), 
                                                                             ('<eos>', byte_pair_tok.token_to_id('<eos>'))])

sentence = "This is a sentence to test the tokenization."
print(byte_pair_tok.post_process(byte_pair_tok.encode(sentence)).tokens)

# Outputs: ['<bos>',
 'T',
 'his',
 'Ġis',
 'Ġa',
 'Ġsentence',
 'Ġto',
 'Ġtest',
 'Ġthe',
 'Ġtoken',
 'ization',
 '.',
 '<pad>',
 '<pad>',
 '<pad>',
 '<pad>',
 '<pad>',
 '<eos>']
```

As you can see the `<eos>` token comes after the padding tokens. Also the output has a length of 18 instead of the 16 passed to the `enable_padding` function, which is 16 + 2 (for the two added special tokens `<bos>` and `<eos>`)

##### EDIT

Maybe my post was not precise enough. The reason I thought that the `post_process` function has to be called explicitly on the encoding one gets from the`encode` function is that just calling the `encode` function gives the following results:

```
byte_pair_tok.encode(sentence)).tokens
# Outputs: ['T',
 'his',
 'Ġis',
 'Ġa',
 'Ġsentence',
 'Ġto',
 'Ġtest',
 'Ġthe',
 'Ġto',
 'ken',
 'ization',
 '.',
 '<pad>',
 '<pad>',
 '<pad>',
 '<pad>']
```

So the padding is applied and also the length of 16 is correct. However, the special tokens from the TemplateProcessing assigned to `byte_pair_tok.post_processor` are missing.

**Comment by n1t0** [comment]
`encode` already does all the activated post-processing, so in your case the padding too.
When you call `post_process` you actually do it again. 

Can you try doing the same without the call to `post_process`?

**Comment by bastiscode** [comment]
I updated my post above to include more information when I only call `encode`. Since you say that all **activated** post-processing is done in `encode`, do I maybe need to explicitly activate the `post_processor` somehow?

**Comment by n1t0** [comment]
Sorry, I wanted to check why it seems to work after calling `post_process` in your example when it shouldn't work at all, but I didn't find the time yet.
I think the reason why it doesn't do it with `encode` is because, with `ByteLevelBPETokenizer`, you might have to update the `post_processor` by doing:
```python
byte_pair_tok._tokenizer.post_processor = ...
```

**Comment by bastiscode** [comment]
I closed the issue because it works now when using the above code in a regular python script (*.py). The problems just arise when using the code in a notebook in JupyterLab.
