### ISSUE TITLE
How to reuse fairseq's vocab？

### ISSUE THREAD

**Issue by ismymajia** [huggingface/tokenizers#488]
In fairseq i process my corpus by ${data_dir}/fs_dict.txt:
fairseq-preprocess \
                --only-source \
                --srcdict ${data_dir}/fs_dict.txt \
                --trainpref ${data_dir}/train.txt \
                --validpref ${data_dir}/valid.txt \
                --testpref  ${data_dir}/test.txt \
                --destdir   ${data_dir}/data-bin \
                --workers 18 \
                --cpu

Every line in fs_dict.txt consist of word and frequency, like this:
grow 89565
each 89471
joey 89404

How to reuse fairseq's vocab？ because I have filtered the vocab, I don’t want to retrain with Tokenizer.
On the other hand, my corpus has be segmented as my requirment.

**Comment by Narsil** [comment]
@ismymajia you closed, this I assume because you find a way to do it ?

If so, can you please share how you did it for other devs looking for an answer too ?
