### ISSUE TITLE
Node.js GPT2Tokenizer

### ISSUE THREAD

**Issue by kafkas** [huggingface/tokenizers#491]
Is there a JS version of the GPT2Tokenizer? I urgently need one so happy to contribute a PR if you provide instructions on how I can implement it.

**Comment by n1t0** [comment]
Yes, you need to do something like this:

```javascript
import { ByteLevelBPETokenizer } from "tokenizers";

const tokenizer = await ByteLevelBPETokenizer.fromOptions({
   mergesFile,
   vocabFile
});
```
