### ISSUE TITLE
Typos in the docs

### ISSUE THREAD

**Issue by taufique74** [huggingface/tokenizers#496]
I found some (3 to be specific) typos and wrong codes while reading the docs (Quicktour). Readers might have some hard times following the Quicktour.
Which file should I modify to fix those? Or should I post the details here?

**Comment by taufique74** [comment]
I found the docs in the `documentation` branch. Should I submit a PR correcting those?

**Comment by n1t0** [comment]
Thank you for looking at this @taufique74! 

I'm currently finishing up with the `documentation` and will be merging the related PR later today. In the meantime, feel free to comment here: https://github.com/huggingface/tokenizers/pull/494
