### ISSUE TITLE
Feature Request: make tokenizers trainable on arrow files

### ISSUE THREAD

**Issue by fraboniface** [huggingface/tokenizers#501]
Sorry if this is similar to other issues revolving around the apparent incompatibility between your `tokenizers` and `datasets` libraries, such as #479 and #198, but I haven't seen it formulated as such.

It is currently impossible to train a tokenizer from this library on a dataset downloaded with `datasets` because it expects a text file and not an arrow file. This is clearly a desirable feature, as a natural and convenient workflow would be to download a dataset with `datasets` and then use a tokenizer from `tokenizers`.

**Comment by Narsil** [comment]
Closing in favor of #198 to keep the discussion centralised (PR open at #512 )
