### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by abhishekkrthakur** [huggingface/tokenizers#502]
It seems like the documentation is broken now: https://huggingface.co/tokenizers/python/latest

**Comment by n1t0** [comment]
It just seems like a malformed link. Where did you get it?

See:
https://huggingface.co/docs/tokenizers/python/latest

**Comment by abhishekkrthakur** [comment]
README

**Comment by Narsil** [comment]
Thanks for reporting this @abhishekkrthakur
