### ISSUE TITLE
Inconistence between Metaspace and Whitespace tokeniser

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#511]
I noticed that `Metaspace` and `Whitespace` pre-toks seem to have a different definition of whitespace. `Whitespace` uses the regex `\w+|[^\w\s]+` white treats control chars such as \n and \t as whitespace but `Metaspace` seems to treat these as text and doesn't split on them, i.e. 

```
example = 'AC DRIVE 117001\n\tCURRENT'

Metaspace().pre_tokenize_str(example)
[('▁AC', (0, 2)), ('▁DRIVE', (2, 8)), ('▁117001\n\tCURRENT', (8, 24))]

Whitespace().pre_tokenize_str(example)
[('AC', (0, 2)), ('DRIVE', (3, 8)), ('117001', (9, 15)), ('CURRENT', (17, 24))]
```

Also you really cannot use `Metaspace()` in a `Sequence()` or the '▁' can end up as it's own token i.e. 

```
Sequence([Metaspace(), Digits(individual_digits=False), Punctuation()]).pre_tokenize_str(example)
[('▁AC', (0, 2)),
 ('▁DRIVE', (2, 8)),
 ('▁', (8, 9)),
 ('117001', (9, 15)),
 ('\n\tCURRENT', (15, 24))]
```

Also the result depends on the sequence order but I guess that's unavoidable.

**Comment by n1t0** [comment]
You are right! 

We designed all of this to be very versatile. You can combine the components as you wish, and they get executed sequentially (as the name suggests). This indeed means that the results might be different if you change the order, but that is totally expected.

It's also true that these components might be using different definitions for what is a whitespace, or anything else, as often there isn't just one definition that is better than the others. Making a tokenizer is hard, and there are many ways to do it. We think it should be possible to do whatever fits your personal use case, and to try new things too.
