### ISSUE TITLE
"Replace" from "tokenizers.normalizers" not working as expected

### ISSUE THREAD

**Issue by salvacarrion** [huggingface/tokenizers#515]
I was trying to use regex with the Replace function from `tokenizers.normalizers` but it is not working as expected.

Since the signature is `(pattern: str, content: str)`, I'm using two strings. However, **it ignores the regex expression**. Am I doing something wrong?

```
from tokenizers.normalizers import Replace
text = Replace(r"\d+", "").normalize_str('Hello 23423 world!')

// output => Hello 23423 world!
```

**Comment by n1t0** [comment]
In order to use a regex, you must use a `tokenizers.Regex`. This should work:
```python
from tokenizers.normalizers import Replace
from tokenizers import Regex

text = Replace(Regex("\d+"), "").normalize_str('Hello 23423 world!')
```

**Comment by salvacarrion** [comment]
Thank you!

**Comment by adithya8** [comment]
Can you give an example for replacing the matched Regex patterns with custom string? I am trying to replace full URLs with just the domain name. 

Example:
Text -  "Check this funny video: http://www.youtube.com/watch?v=aijeoqneqw21" -> "Check this funny video: http://www.youtube.com/[URL]"
