### ISSUE TITLE
Special tokens are getting encoded.

### ISSUE THREAD

**Issue by Vijayabhaskar96** [huggingface/tokenizers#52]
I'm trying to get SentencePieceBPETokenizer with fastai, As you can see encoding the spec_tokens individually returns the correct tokens but when encoding the same with .encode() doesn't treat them as special tokens. Am I missing something or this is a bug?

![Screenshot_9](https://user-images.githubusercontent.com/17958636/72214629-2f806c00-352c-11ea-8c21-076aee87990f.png)

**Comment by n1t0** [comment]
Before you start encoding, you should use the `add_special_tokens` method on the tokenizer to let it know about these special tokens. It should then work as you expect it!

**Comment by Vijayabhaskar96** [comment]
I tried that already, different encoding results but the problem remains the same.
![Screenshot_10](https://user-images.githubusercontent.com/17958636/72215239-a15db300-3536-11ea-9092-36d5e584798f.png)

**Comment by n1t0** [comment]
Indeed, my bad! There was a bug with the way special tokens were handled. This should now be fixed and you can download the new `0.1.1` version on pip.
