### ISSUE TITLE
Windows: ImportError: DLL load failed while importing tokenizers: The specified module could not be found.

### ISSUE THREAD

**Issue by xjdeng** [huggingface/tokenizers#522]
Steps to reproduce (in anaconda):

1) conda create -n tokenizer -c pytorch pytorch=1.5

2) conda activate tokenizer

3) pip install tokenizers

4) python -c "import tokenizers"

Result:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\*******\AppData\Local\Continuum\anaconda3\envs\tokenizer\lib\site-packages\tokenizers\__init__.py", line 79, in <module>
    from .tokenizers import (
ImportError: DLL load failed while importing tokenizers: The specified module could not be found.

**Comment by n1t0** [comment]
You should be able to get the latest version of tokenizers from conda directly. Can you try this:
```
conda install -c huggingface tokenizers
```
