### ISSUE TITLE
Is there a WordLevel trainer to train a wordlevel tokenizer from scrach?

### ISSUE THREAD

**Issue by Jess0-0** [huggingface/tokenizers#529]
In the trainer folder, there seems to only have trainers for BPE, Unigram, and WordPiece tokenizer. Is there a trainer to train the wordlevel tokenizer? Thanks!

**Comment by n1t0** [comment]
Hi @Jess0-0 

The WordLevel trainer is missing at the moment (tracked here #265) and currently being reviewed here: #519 
Should land on `master` pretty soon, and likely to be included in the next release. You can compile the branch from #519 from source if you want to start using it now!

**Comment by Jess0-0** [comment]
Hi Huggingface/Tokenizers team,

Thank you so much for your quick response! I've compiled the branch from
the source. Currently I'm able to import the WordLevelTrainer but it will
generate "TypeError: Can't convert <WordLevelTrainer object at
0x000001F8EC938DD0> to Sequence" if I called it in
"tokenizer.train(trainer, ["wiki.train.raw", "wiki.valid.raw",
"wiki.test.raw"])". Wondering if there is anything I configured wrong?

Also, I'm wondering if there is an expected date for the next release.
Thank you very much!

Best,
Jiayao

**Comment by pietrolesci** [comment]
Hi @n1t0,

I hope you are doing well. Thank you very much for PR #519 - I was waiting for it! :D

Unfortunately, I am having the same issue of @Jess0-0. Is there anything different that needs to be done to use the WordLevelTrainer?

Best,
Pietro

**Comment by n1t0** [comment]
The first argument to `train` is now supposed to be the list of files since the `trainer` became optional.
You just have to invert them:
```python
tokenizer.train([ ... ], trainer)
```

**Comment by pietrolesci** [comment]
Hi @n1t0, 

Thanks you very much for your quick answer!
Is there any updated doc I can look up next time?

Best,
Pietro

**Comment by n1t0** [comment]
Sure, the documentation is available here: https://huggingface.co/docs/tokenizers/python/master
There is a version selector on the website, and `master` is one of them.
