### ISSUE TITLE
Feature Request: Support for sentencepiece unigram model

### ISSUE THREAD

**Issue by leslyarun** [huggingface/tokenizers#53]
Any plans to add support for sentencepiece unigram model?

**Comment by mfuntowicz** [comment]
Hi @leslyarun :), 

Do mean training or inference ? What is your use case around this kind of model ?

**Comment by leslyarun** [comment]
@mfuntowicz Both for training a vocab and also use it for Tokenization. For example, to use it for building a vocab and Tokenize for  Albert

**Comment by jarednielsen** [comment]
Same here, it would be great to use tokenizers for training Albert :)

**Comment by gthb** [comment]
Same here, have a functioning model using `BertTokenizerFast` and `TFBertMainLayer`, and now wanted to try out Albert instead of Bert — but absolutely need `return_offsets_mapping` support, and that's not there in `AlbertTokenizer`.

**Comment by ck37** [comment]
The new Bostrom & Durrett paper "[Byte Pair Encoding is Suboptimal for Language Model Pretraining](https://arxiv.org/abs/2004.03720)" also encourages unigram tokenization for language modeling. (via @geoffbacon)

**Comment by KeremTurgutlu** [comment]
Does it mean it's not possible to construct a pretrained `xlm-roberta-base` tokenizer similar to `AutoTokenizer.from_pretrained("xlm-roberta-base")` ?

**Comment by marrrcin** [comment]
Is there any timeline for when it's going to be implemented?

**Comment by Narsil** [comment]
I started some work on this, hopefully my proposal will get working at some point:

https://github.com/huggingface/tokenizers/pull/292

**Comment by vivekinvansys** [comment]
can anyone tell, in which version this was  released?

**Comment by Arij-Aladel** [comment]
Yes please, the same question How can I pretrain T5Tokenizer on new language?
