### ISSUE TITLE
WordPiece error: Missing [UNK] token from the vocabulary

### ISSUE THREAD

**Issue by piercefreeman** [huggingface/tokenizers#531]
Hi -

I'm trying to train my own WordPiece tokenizer from scratch, using a custom set of special tokens (ie. `<oov>` instead of bert's default `[UNK]`). Upon training my model and encoding an unseen datapoint it's throwing an error `Missing [UNK] token from the vocabulary`.  I never specify `[UNK]` anywhere - and in fact am trying to override the unk_token at tokenizer creation time.

Tracing the python code doesn't seem to reveal any positions where [UNK] is being provided explicitly as a default, outside of the BERT specific code. I'm thinking there's potentially something happening in the rust layer?

Code to reproduce on 0.9.4.

```
        from tokenizers import Tokenizer as HFTokenizer
        from tokenizers.processors import TemplateProcessing
        from tokenizers.models import WordPiece
        from tokenizers.trainers import WordPieceTrainer
        from tokenizers.normalizers import BertNormalizer
        from tokenizers.pre_tokenizers import BertPreTokenizer
        from typing import Optional
        from tokenizers.decoders import WordPiece as WordPieceDecoder
        from tempfile import NamedTemporaryFile

        dataset = ["My first datapoint"]
        test_dataset = ["My second datapoint"]

        # Create the tokenize as a derivative of Bert's tokenizer
        tokenizer = HFTokenizer(
            WordPiece(
                unk_token="oov",
            ),
        )

        # Create the trainer to execute the training
        trainer = WordPieceTrainer(
            special_tokens=["oov"],
            continuing_subword_prefix="##",
            vocab_size=20000,
            min_frequency=2,
        )

        # Train the tokenizer
        with NamedTemporaryFile("w+") as file:
            for item in dataset:
                file.write(item + "\n")

            # Required to correctly read from the input
            file.seek(0)

            tokenizer.train(trainer, [file.name])

        for data in test_dataset:
            tokenizer.encode(data)
```

**Comment by n1t0** [comment]
There is currently a bug (we are fixing it in #519) that removes some customization on your WordPiece Model during training.

Until it is fixed, you need to reload it after training as following:
```python
files = tokenizer.model.save(".")
tokenizer.model = WordPiece(*files, unk_token="<oov>")
```

**Comment by piercefreeman** [comment]
@n1t0 Happy to hear I'm not going crazy! The confusing thing to me is that AFAIK the `[UNK]` token isn't specified anywhere outside of the BERT tokenization pipeline. Since I'm not using those mixins here why would it have been falling back to that default?

**Comment by n1t0** [comment]
`[UNK]` is the default unk_token for `WordPiece`.

**Comment by n1t0** [comment]
Fixed on master!
