### ISSUE TITLE
BertWordPieceTokenizer encodes without [CLS] and [SEP] 

### ISSUE THREAD

**Issue by mattivi** [huggingface/tokenizers#532]
## Environment info

     
- `tokenizers` version: 0.9.3
- Platform: Windows

### Who can help
@LysandreJik @mfuntowicz
 
## Information
I am training a BertWordPieceTokenizer on custom data.

The problem is that the encoded text does not have [CLS] and [SEP] tokens as expected.

## To reproduce

1. Initialize BertWordPieceTokenizer
2. Train it with custom dataset
3. Encode a sentence

```python
from tokenizers import BertWordPieceTokenizer

# Initialize a tokenizer
tokenizer = BertWordPieceTokenizer(clean_text=False, handle_chinese_chars=False)

# Customize training
tokenizer.train(files=TRAIN_FILE, 
                vocab_size=VOCAB_SIZE, 
                min_frequency=1)
tokenizer.enable_truncation(max_length=MAX_LEN)

# Encode
tokenizer.encode("This is the sentence", add_special_tokens=True).tokens
>> ['this', 'is', 'the', 'sentence']
 ```

## Expected behavior

I would expect the special tokens [CLS] and [SEP] to be in the output, as
 ```python
>> ['[CLS'], 'this', 'is', 'the', 'sentence', '[SEP]']
 ```

I see that BertWordPieceTokenizer has already Bert post processing rule as in bert_wordpiece.py:
 ```python
tokenizer.post_processor = BertProcessing(
                (str(sep_token), sep_token_id), (str(cls_token), cls_token_id)
            )
 ```
However, the output is without CLS and SEP. Any hint?
Thanks!

**Comment by Narsil** [comment]
The line you refer to is only applied if `vocab` is supplied to your `BertWorkPieceTokenizer`. You need to apply it manually if you train:.

[Reference](https://github.com/huggingface/tokenizers/blob/58b618f98ef5dbf0c1d7be8601ff319f4320b1c9/bindings/python/py_src/tokenizers/implementations/bert_wordpiece.py#L62)

```python
tokenizer._tokenizer.post_processor = BertProcessing(                              
      (str("[SEP]"), 0), (str("[CLS]"), 1)                                           
) 

```

**Comment by mattivi** [comment]
Thanks for the quick answer. I have solved as the following and will close the issue.
```python
from tokenizers import BertWordPieceTokenizer

# Initialize a tokenizer
tokenizer = BertWordPieceTokenizer(clean_text=False, handle_chinese_chars=False)

# Customize training
tokenizer.train(files=TRAIN_FILE, 
                vocab_size=VOCAB_SIZE, 
                min_frequency=1)
tokenizer.enable_truncation(max_length=MAX_LEN)

# Save
tokenizer.save_model(CONFIG_DIR)
   
# Load
tokenizer = BertWordPieceTokenizer(
    CONFIG_DIR + "vocab.txt"
)

# Encode
tokenizer.encode("This is the sentence", add_special_tokens=True).tokens
>> ['[CLS]', 'this', 'is', 'the', 'sentence', '[SEP]']
```
