### ISSUE TITLE
Link to docs in "About" section of repo

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/tokenizers#534]
Can we add a link to https://huggingface.co/docs/tokenizers/python/latest/ in the About section similar to how it's done for Transformers: 

![Screenshot from 2020-11-18 11-38-05](https://user-images.githubusercontent.com/23423619/99519763-8ea3de00-2992-11eb-821e-54bcbfc0d873.png)

**Comment by patrickvonplaten** [comment]
I don't seem to have the access rights -> would be happy to do it otherwise :-)

**Comment by n1t0** [comment]
Well, that's weird, you should have access. I updated it anyway, thank you for the suggestion @patrickvonplaten!
