### ISSUE TITLE
Setting parameters of Trainer returned by .get_trainer()

### ISSUE THREAD

**Issue by Tomiinek** [huggingface/tokenizers#540]
First, thank you for the current Trainer changes in #519!

I cannot figure out how to set trainer parameters when using `.get_trainer()`. The PR mentions an option:

``` python
trainer = tokenizer.model.get_trainer()
trainer.vocab_size = s
trainer.special_tokens = st
tokenizer.train(files, trainer=trainer)
```

But it does not work for me and says: `AttributeError: 'WordLevelTrainer' object has no attribute 'vocab_size' `

Is there a way to do this? I can use `trainer = type(trainer)(vocab_size=s, special_tokens=st)`, but it does not seem to be the preferred way.

**Comment by n1t0** [comment]
Indeed, this is something that we are currently adding, it will be possible as soon as we merge https://github.com/huggingface/tokenizers/pull/530

In the meantime, your workaround is necessary.

**Comment by Tomiinek** [comment]
Ok, thanks!
