### ISSUE TITLE
Latest node version 15/14 support

### ISSUE THREAD

**Issue by msahamed** [huggingface/tokenizers#541]
Thank you for making this amazing library that makes our life a whole lot easier. I want to report an issue I faced recently, which is: 
the tokenizers' current version (0.7.0) does not work with the latest node (>=14 (LTS)  or 15.0.0 (current)). I wonder if you can add the latest node support.

**Comment by RichardBosworth** [comment]
Having same issue. Noted that this library was last published on npm ~6 months ago.
Keen to use in a current project.

**Comment by n1t0** [comment]
Version 0.8.0 of `tokenizers` has been released on npm, and it should definitely work with Node version 15 and below!
