### ISSUE TITLE
Exception: Exception: TypeError: Can't convert ('\u6c38', 0) to NormalizedString

### ISSUE THREAD

**Issue by Zenodia** [huggingface/tokenizers#547]
here my code import MicroTokenizer
import os
from typing import List
from tokenizers import Tokenizer, Regex, NormalizedString, PreTokenizedString
from tokenizers.models import BPE, WordPiece
from tokenizers import pre_tokenizers
from tokenizers.pre_tokenizers import Digits

import os
from typing import Optional, List, Tuple

from tokenizers import Tokenizer, Regex, NormalizedString, PreTokenizedString
from tokenizers.models import BPE, WordPiece,WordLevel
from tokenizers.pre_tokenizers import PreTokenizer

class myPretok:                                                             
    def Microcut_split(
        self, i: int, normalized_string: NormalizedString
    ) -> List[Tuple[str, int]]:
        # Just an odd example...
        splits = []
        tokens=MicroTokenizer.cut(str(normalized_string),HMM=True)
        print(tokens)
        n=len(tokens)
        for k in enumerate(tokens):
            #print("i ", i , " char ", char, normalized_string[i])
            print(k)
            idx,token=k

            print(type(token))
            splits.append((token,idx))           
        
        return splits                                                             
                                                                                   
    def pre_tokenize(self, pretok):                                                
        pretok.split(self.Microcut_split)                                                   
                                                                                     
mytok = PreTokenizer.custom(myPretok())
text = "\u6c38\u548c\u670d\u88c5\u9970\u54c1\u6709\u9650\u516c\u53f8"
print("PreTokenize:", text)
mytok.pre_tokenize_str(text) 

here is the output PreTokenize: \u6c38\u548c\u670d\u88c5\u9970\u54c1\u6709\u9650\u516c\u53f8
['\u6c38', '\u548c', '\u670d\u88c5\u9970\u54c1', '\u6709\u9650\u516c\u53f8']
(0, '\u6c38')
<class 'str'>
(1, '\u548c')
<class 'str'>
(2, '\u670d\u88c5\u9970\u54c1')
<class 'str'>
(3, '\u6709\u9650\u516c\u53f8')
<class 'str'>

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-107-be33a43b1969> in <module>
     41 text = "\u6c38\u548c\u670d\u88c5\u9970\u54c1\u6709\u9650\u516c\u53f8"
     42 print("PreTokenize:", text)
---> 43 mytok.pre_tokenize_str(text)
     44 
     45 

Exception: Exception: TypeError: Can't convert ('\u6c38', 0) to NormalizedString

**Comment by n1t0** [comment]
Your function `Microcut_split` should return instances of `NormalizedString`. That is how the `Tokenizer` will keep track of the alignment while normalizing and pre-tokenizing.

There are two main ways to use the provided `NormalizedString`:
```python
# Slicing the original string:
normalized_string[5:10]

# or splitting using a pattern:
normalized_string.split("-", behavior="removed")
```
Both of these methods return some other `NormalizedString`, as expected by the function provided to `pretok.split`. When using these methods, the `NormalizedString` internally keeps track of the alignment and is able to provide offsets for each tokens.

Now, if you don't care about the offsets, you can probably just return a new `NormalizedString` instantiated manually:
```python
from tokenizers import NormalizedString

class myPretok:
    def Microcut_split(
        self, i: int, normalized_string: NormalizedString
    ) -> List[Tuple[str, int]]:
        # Just an odd example...
        splits = []
        tokens=MicroTokenizer.cut(str(normalized_string),HMM=True)
        for token in tokens:
            splits.append(NormalizedString(token))     
        return splits                                                             
                                                                               
    def pre_tokenize(self, pretok):                                                
        pretok.split(self.Microcut_split)      
```
