### ISSUE TITLE
serializing custom tokenizer

### ISSUE THREAD

**Issue by hengdashi** [huggingface/tokenizers#554]
Hi,

I was following the custom component example in python binding, and find that the custom tokenizer cannot be serialized and saved locally.

Is there any way to serialize the custom tokenizer to save it locally for easy loading? It would be very important because the training takes a long time.

**Comment by n1t0** [comment]
Hi @hengdashi. Only the custom Python components can't be serialized. So as a workaround you can probably detach them by assigning a dummy component in their place, and then call `save`. You'll have to re-attach these components manually after loading the tokenizer though, but that should work.
As an alternative, you can also save the model using `tokenizer.model.save` and then load everything manually afterwards.

We should definitely allow assigning `None` to remove a component from the tokenizer, to avoid having to assign a dummy one.

**Comment by hengdashi** [comment]
Thanks! That seems to be a possible solution!

**Comment by n1t0** [comment]
Closing in favor of https://github.com/huggingface/tokenizers/issues/554
