### ISSUE TITLE
What's the unique_no_split_tokens for Fast Tokenizers?

### ISSUE THREAD

**Issue by memray** [huggingface/tokenizers#555]
Hi there,

I would like to add some special tokens by modifying the original vocab files (for example I replace dummy `madeupword0000` with `<sep>` of RoBERTa vocab) and reload the tokenizer by `tokenizer = RobertaTokenizer(vocab_file=bpe_vocab, merges_file=bpe_merges)`.

However, I found that the directly loaded tokenizer cannot process any special tokens correctly, e.g. '\<s\>' will be segmented to ['<', 's', '>']. For slow tokenizers, this could be resolved by adding all special tokens to `tokenizer.unique_no_split_tokens`. But I don't see such a list for fast tokenizers. Could you let me know any workaround for fast models? Or can I convert a well-set slow tokenizer to fast version?

Thank you,
Rui

**Comment by memray** [comment]
Anyone can help?

**Comment by n1t0** [comment]
You probably want to have a look at the `add_special_tokens` method which seem suited for this:
https://huggingface.co/transformers/internal/tokenization_utils.html?highlight=add_special_tokens#transformers.tokenization_utils_base.SpecialTokensMixin.add_special_tokens
