### ISSUE TITLE
Make dropout an argument of encode()?

### ISSUE THREAD

**Issue by memray** [huggingface/tokenizers#562]
Hi there,

In the current implementation, the dropout is set during model initialization and cannot be modified any longer. But there are cases that we want dropout during training and no dropout during validation. Now the only way is to initialize two tokenizers for this purpose. 

I wonder if it is possible to set `dropout` as an argument in tokenize/encode etc., so that we can call dropout more conveniently.

Thanks,
Rui

**Comment by n1t0** [comment]
Hi @memray, using the latest version (`0.10.0rc1`) you can actually set the `dropout` very conveniently:
```python
tokenizer.model.dropout = 0.1
```

**Comment by memray** [comment]
That's awesome! Thank you!

**Comment by vietvo89** [comment]
Hi all

It seems `tokenizer.model.dropout` has been removed or changed in new transformers. What is the replacement of this?
