### ISSUE TITLE
BertWordPieceTokenizer.save_model() doesn't have merges.txt

### ISSUE THREAD

**Issue by chameleonTK** [huggingface/tokenizers#564]
I was trying to run this notebook: https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/01_how_to_train.ipynb 

but used BertWordPieceTokenizer instead. It seems when it saved, there is no `merges.txt` which will be used in the next section.

**Comment by n1t0** [comment]
Indeed the WordPiece tokenizer does not have any merges, these are specific to BPE.

You can instead save the tokenizer using the following:
```python
# Save the tokenizer to a single json file
tokenizer.save("my-tokenizer.json")

# Then reloading it with `tokenizers` is easy:
from tokenizers import Tokenizer
tokenizer = Tokenizer.from_file("my-tokenizer.json")

# And loading from transformers looks like this:
from transformers import PreTrainedTokenizerFast
tokenizer = PreTrainedTokenizerFast(tokenizer_file="my-tokenizer.json")
```
