### ISSUE TITLE
ByteLevelBPETokenizer adding special character at the beginning of most of the words

### ISSUE THREAD

**Issue by psds01** [huggingface/tokenizers#57]
I am trying to train `ByteLevelBPETokenizer` tokenizer. But the tokens that I get have a special character at the beginning of the word: `Ġ` (ord = 288). I don't know why this is happening but this is creating duplicate tokens in the tokenizer vocabulary.

```%python
# file contains a text/sentence on each line.
from tokenizers import ByteLevelBPETokenizer
tokenizer = ByteLevelBPETokenizer()
tokenizer.train(file)

# encode
output = tokenizer.encode("say what?")
output.tokens
>>> ['say', 'Ġwhat', '?'] # what is this weird thing against `what` ??

output = tokenizer.encode("what ever?")
output.tokens
>>> ['what', 'Ġever', '?']
```
Am I doing something wrong here?

**Comment by n1t0** [comment]
This is totally expected, as this character represents a whitespace in the byte-level representation.
So you are not doing anything wrong and you don’t need to worry about these characters.
You can see exactly what is the original text by doing `print(output.original_str[output.offsets[1])` where 1 is the index of the token that you want to check.
