### ISSUE TITLE
BPE and WordPiece yields identical results

### ISSUE THREAD

**Issue by bfelbo** [huggingface/tokenizers#570]
I'm trying to understand subword tokenization more in depth and as part of my explorations I trained BPE and WordPiece on a small corpus of 250K words with identical `continuing_subword_prefix`, `vocab_size`, and `min_frequency`. I know that BPE and WordPiece are quite similar, but I was surprised to find that they yielded completely identical results.

From the [🤗 tokenizer summary](https://huggingface.co/transformers/tokenizer_summary.html):
> In contrast to BPE, WordPiece does not choose the most frequent symbol pair, but the one that maximizes the likelihood of the training data once added to the vocabulary. (...) Intuitively, WordPiece is slightly different to BPE in that it evaluates what it loses by merging two symbols to make ensure it’s worth it.

I've taken a quick glance at the code and can't find the place, where the WordPiece implementation computes the likelihood of the training data. It seems to be mostly a wrapper around the BPE implementation, see e.g. [src/models/wordpiece/trainer.rs 156-168](https://github.com/huggingface/tokenizers/blob/master/tokenizers/src/models/wordpiece/trainer.rs#L156-L168).

What am I missing here? Can you guide me to the part of the code that computes the likelihood and do you have any examples / test cases, where BPE and WordPiece yield different results? :)

**Comment by n1t0** [comment]
Hi @bfelbo 

You are right about this. The `WordPiece` training algorithm has never been publicly released though, only the tokenization part of it. In the various papers talking about it, it is said to be very similar to `BPE`, and so in `tokenizers` we let you train a `WordPiece` by using the `BPE` training algorithm. The resulting vocabulary might be slightly different from the one produced by the original algorithm, but we wouldn't be able to make sure we reproduced it accurately anyway.

What's really different from `BPE` is the output format of the files used in the end, as well as the tokenization algorithm:
 - `BPE` uses merge operations to construct subword units from the characters in the text
 - `WordPiece` uses a greedy algorithm that instead tries to match the whole words first, while decomposing them into multiple subword tokens if necessary.

**Comment by bfelbo** [comment]
Thanks for the detailed explanation! I'm still a bit confused though 😛 The Hugging Face tokenizer summary talks about WordPiece computing the likelihood, but what I'm hearing is that the code doesn't actually do that?

It might be useful to add a line or two about this to the documentation and to the code? I wouldn't be surprised if someone does research with this great library and includes a comparison of BPE vs. WordPiece for their task w/o knowing that this implementation might not do what they thought it did.
