### ISSUE TITLE
BERT WordPiece Tokenizer: some matras missing after tokenization for Hindi Language

### ISSUE THREAD

**Issue by akshat311** [huggingface/tokenizers#572]
We trained our Bert WordPiece Tokenizer using the following dataset : https://drive.google.com/file/d/12MbWKERa7QPfI9F-xnMgIgAhjbN8EaQK/view?usp=sharing

The words ending with certain matras (eg. ए -  े ) are missing these matras in the tokens.
For Eg : for the sentence "अपने पोस्ट ऑफिस में 420 पदों पर भर्ती "
the tokens were as follows : ['अपन', 'पोस्ट' , 'ऑफिस' , 'म' , '420' , 'पदो' , 'पर' , 'भर्ती' ]
The first word (अपने) and third word (में ) are missing the  ए  ki matra after tokenization.

Even for the pretrained huggingface tokenizers, all the uncased tokenizers have the exact same issue. Words ending with ए  ki matra are missing the matra after tokenization. However, cased pretrained tokenizers are working fine. ("bert-base-multilingual-cased" is working perfectly fine, however, "bert-base-multilingual-uncased" has the same issue mentioned above.) 
Tokenization result for "bert-base-multilingual-cased" : [['अपने', 'प', '##ो', '##स्ट', 'ऑफ', '##िस', 'में', '420', '##0', 'पद', '##ों', 'पर', 'भर', '##्ती']
Tokenization result for "bert-base-multilingual-uncased" : ['अपन', 'प', '##ो', '##सट', 'ऑफ', '##िस', 'म', '420', '##0', 'पद', '##ो', 'पर', 'भर', '##ती']

Why are these matras getting omitted after tokenization for our own tokenizer and the uncased bert tokenizers?

**Comment by n1t0** [comment]
Hi @akshat311 

This is happening because the BERT Tokenizer does strip the accents (the matras here) by default when lowercasing is activated.

With the `tokenizers` library you should check the `strip_accents` parameter of the `BertWordPieceTokenizer` class that you can disable before training.

If you are using a fast tokenizer with `transformers`, you can also specify `strip_accents` when using `from_pretrained`.

Keep in mind that if you change this option, the tokenizer should be trained again to accommodate to the new tokens.

**Comment by kushalj001** [comment]
Thank you for replying.

We tried setting the `lowercase` argument to `False`, but it still behaves in a similar way.
Would setting both `lowercase` and `strip_accents` to `False` result in a different behavior?
More context, we're using transformers 3.5.1 and tokenizers 0.9.3.
The tokenizer is being trained by using `tokenizers.implementations.bert_wordpiece.BertWordPieceTokenizer`.

**Comment by n1t0** [comment]
Only setting `strip_accents=False` should be enough. But this option only works with the fast version of the tokenizer.
When the `strip_accents` option is unspecified (`None`), then it it has the same value than `lowercase`.

**Comment by abhishekkrthakur** [comment]
For hindi, I would suggest using a different tokenizer: byte level bpe.

**Comment by n1t0** [comment]
Closing this, feel free to reopen if needed!

**Comment by vs9205** [comment]
> For hindi, I would suggest using a different tokenizer: byte level bpe.

Hi @abhishekkrthakur , I trained byte level BPE GPT2 tokenizer on Hindi dataset of size 170 MB and saved it as new_tokenizer. When I tried the new_tokenizer on a Hindi sentence

`मेरा नाम विनय है`

The number of tokens generated are 12 which are as follows

`['म', 'े', 'र', 'ा', ' न', 'ा', 'म', ' व', 'ि', 'न', 'य', ' ह', 'ै']`

I experimented with vocab size = 500, 1000, 5000, 30K and 50K

Here new_tokenizer is tokenizing more like a character level lm, than as sub-word level lm.
What should be done to improve the tokenizer?
