### ISSUE TITLE
why the python function code is all "pass"

### ISSUE THREAD

**Issue by gwsin** [huggingface/tokenizers#580]
for example, the enable_padding function, it did not work at first. I checked the source code, but it was like this:
`def enable_padding(...):
    # explanation
    pass`
it does nothing in the function. Then, where's its implementation?

**Comment by Narsil** [comment]
Hi @gwsin ,

Those are implemented in Rust (with PyO3 for the linking to Python). The `.py` `.pyi` files that are empty are only there to help code editors and autocompletion tools to work correctly.

**Comment by gwsin** [comment]
Hi @Narsil, Thanks a lot. Now I understand.
