### ISSUE TITLE
How to yield sequence_ids for QA with tokenizer?

### ISSUE THREAD

**Issue by afogarty85** [huggingface/tokenizers#584]
I am following this huggingface tutorial here (https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/question_answering.ipynb#scrollTo=zR10EBaileGu&line=1&uniqifier=1), but I am unable to get `sequence_ids` with the Bert tokenizer. Below is a quick example:

```
from datasets import load_dataset, load_metric
from transformers import BertTokenizerFast
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')
datasets = load_dataset("squad_v2")
example = datasets["train"][0]

# tokenize
tokenized_example = tokenizer(
    example["question"],
    example["context"],
    max_length=384,
    truncation="only_second",
    return_overflowing_tokens=True,
    return_offsets_mapping=True,
    stride=128
)

# fails
tokenized_xample.sequence_ids()
```

**Comment by n1t0** [comment]
Make sure the libraries are up to date, and then after fixing the small typo everything should work:
```python
## Can't work
tokenized_xample.sequence_ids()

## Will work
tokenized_example.sequence_ids()
```

**Comment by afogarty85** [comment]
Thanks, that was just a copy-paste typo. What version should I shoot for?

`pip install tokenizers` claims I am up-to-date.
