### ISSUE TITLE
The Conda package doesn't work on CentOS 7 and Ubuntu 18.04

### ISSUE THREAD

**Issue by bryant1410** [huggingface/tokenizers#585]
`import tokenizers` doesn't work on CentOS 7 (and RHEL 7), because [it has glibc 2.17](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.0_release_notes/sect-red_hat_enterprise_linux-7.0_release_notes-compiler_and_tools-glibc), while the Conda package (at least for Python 3.8) was compiled against a newer version (the error says `version 'GLIBC_2.18' not found`).

I believe CentOS and RHEL 7 are both still popular, though I can't back up this claim (I can't find a link). My university cluster uses it at least. And note version 7 is the latest CentOS version with long-term support.

It does work from PyPI's version, so I just use that one. However, it'd be good it worked from Conda. So it seems it's related to the glibc version specified by Conda, while the one provided by `ubuntu-latest` (Ubuntu 18.04 as of today, IIUC) seems to work fine. Conda docs say [they do provide their own glibc version](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#an-aside-on-cmake-and-sysroots). Because there isn't such a libc package in Conda, [they provide a solution via virtual packages](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#overriding-detected-packages). So it seems that all that's needed is to set an env var like:

```bash
CONDA_OVERRIDE_GLIBC=2.17
```

(note Rust dynamically links the compiled binary to the available glibc version at build time).

Could you take a look at it? Not sure how it can be tested w/o pushing a release.

Related issues (some people also mention CentOS 7):

* rust-lang/libc#1412
* [How to compile rust with a specific GLIBC version for gnueabihf architecture?](https://users.rust-lang.org/t/how-to-compile-rust-with-a-specific-glibc-version-for-gnueabihf-architecture/6680)
* rust-lang/rust#57497

**Update:** it's got a bit worse, as now it requires a newer GLIBC version:

> /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

It's not working for me on Ubuntu 18.04 (GLIBC 2.27).

What this article details may be the solution for it: [Building Rust binaries in CI that work with older GLIBC](https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html)

**Comment by freddycct** [comment]
I face the same issue.

**Comment by Rictus** [comment]
I am facing the same issue too.

**Comment by harrisonbay** [comment]
Yep, same issue here as well on CentOS 7.9

**Comment by AmenRa** [comment]
Same error on Ubuntu 18.04.5 LTS.
Ubuntu 18.04's latest GLIBC version is 2.27.
Conda-installed `tokenizers` (through `transformers` installation) version 0.10.2 requires GLIBC 2.29.

**Comment by rubencart** [comment]
Same thing as @AmenRa

**Comment by e-yi** [comment]
Same issue. Had to uninstall `tokenizers` temporarily.

**Comment by AmenRa** [comment]
> Same issue on Ubuntu 18.04.5 LTS.
> Ubuntu 18.04's latest GLIBC version is 2.27.
> Conda-installed `tokenizers` (through `transformers` installation) version 0.10.2 requires GLIBC 2.29.

As a workaround, I've installed the previous tokenizers version, and everything works fine now:
```
conda install -c huggingface tokenizers=0.10.1 transformers=4.4.2
```

**Comment by zack-kimble** [comment]
Same issue for me on 18.04. I just changed to pip installation, which seems to be working.

**Comment by Leojc** [comment]
use pip instead of conda:
```
conda uninstall tokenizers, transformers
pip install transformers
```

**Comment by bryant1410** [comment]
This article explains how to fix it, if anybody wants to go ahead: https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html

**Comment by brando90** [comment]
same issue here: https://github.com/huggingface/transformers/issues/15062

**Comment by brando90** [comment]
Sure!

https://github.com/huggingface/tokenizers/issues/1080 <https://github.com/huggingface/tokenizers/issues/1080>

-----
Brando Miranda

**Comment by Narsil** [comment]
Closing this

**Comment by bryant1410** [comment]
@Narsil is this really fixed? When? How? Can't test it right now.
