### ISSUE TITLE
How to set UNK token for Unigram tokenizer

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#586]
If I create a tokenizer based on the BPE model, and train as follows

```
tokenizer = Tokenizer(models.BPE(unk_token="<unk>"))
# train
tokenizer.save(tokenizer_file)
```

The Unigram tokenizer has a slightly different interface though. What's the correct way of training from scratch? I tried to use https://github.com/huggingface/tokenizers/blob/master/bindings/python/py_src/tokenizers/implementations/sentencepiece_unigram.py as a template but I keep getting exceptions regarding unknown tokens.

I noticed there's a constructor which accepts a vocab and unk_id so I used that as follows:

```
vocab = [("<s>",0.0),("</s>",0.0),("<unk>",0.0),("<pad>",0.0),("<mask>",0.0)]
unk_id = 2
tokenizer = Tokenizer(models.Unigram(vocab, unk_id))
```

But I'm not sure this is correct? Ideally I could replace BPE with Unigram, i.e.

```
tokenizer = Tokenizer(models.BPE(unk_token="<unk>"))
```

**Comment by n1t0** [comment]
You are right, both interfaces are slightly different, and we should try to make all of this more consistent. That's something to keep in mind for the v1.

For Unigram, you actually give the `unk_token` directly to the trainer, no need to initialize it in the empty model:
```python
from tokenizers import Tokenizer, models, trainers

tokenizer = Tokenizer(models.Unigram())
trainer = trainers.UnigramTrainer(
    unk_token="<unk>",
    special_tokens=["<s>", "</s>", "<unk>", "<pad>", "<mask>"]
)
tokenizer.train(files, trainer=trainer)
```

**Comment by n1t0** [comment]
Closing this, feel free to reopen if needed!
