### ISSUE TITLE
ByteLevel encoder and decoder have inconsistent serialisation

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#587]
`pre_tokenizers.ByteLevel` has a single parameter `add_prefix_space` but `decoders.ByteLevel` doesn't

When I save a tokenizer consisting of ByteLevel encoder / decoder with add_prefix_space=False the json file contains

"pretokenizers":[{"type":"ByteLevel","add_prefix_space":false,"trim_offsets":true}]
"decoder":          {"type":"ByteLevel","add_prefix_space":true,"trim_offsets":true}

I'm not sure if this causes an issue but it seems that `add_prefix_space` isn't exposed consistently

**Comment by n1t0** [comment]
Only the parameters needed for each job are exposed, you don't have to worry about them as they won't change anything.
