### ISSUE TITLE
train a tokenizer in quicktour

### ISSUE THREAD

**Issue by gossebouma** [huggingface/tokenizers#599]
the example in the quicktour has 

tokenizer.train(data,trainer) 

where that should apparently read

tokenizer.train(trainer,data) 

or use explicit keywords maybe for the parameters maybe? (But even the documentation of train suggests it should be the other way round. Not sure why this is exactly)

**Comment by n1t0** [comment]
Are you using the latest version of `tokenizers`?

**Comment by gossebouma** [comment]
I think so. I only installed transformers a few days ago.

**Comment by n1t0** [comment]
In transformers we still use v0.9.4 so it is expected. There is a selector on the documentation website to choose the version you want to check. Once you choose 0.9.4 you'll see the quick tour as expected!
You can also override the version in your env to use the latest one, there is no breaking changes except the training.
