### ISSUE TITLE
Saved wordlevel tokenizer loads as a wordpiece tokenizer.

### ISSUE THREAD

**Issue by ksteverson** [huggingface/tokenizers#600]
Something I noticed recently on version 0.10.0. If I have a trained wordlevel tokenizer, and then I save and load (using tokenizer.save and Tokenizer.from_file) it becomes a wordpiece tokenizer. Specifically, I checked tokenizer.model before and after saving it and it returns <tokenizers.models.WordLevel ...> before saving and <tokenizers.models.WordPiece ...>) after loading. 

Now I did some testing, and the tokenizer still behaves as expected. I guess it makes sense that a wordpiece model without any of the ## tokens in the vocab acts like a wordlevel model. But it would be good to confirm that is the case, and would probably cause less confusion if the model was consistent before and after saving.

**Comment by n1t0** [comment]
Thank you for reporting this @ksteverson, nice catch! This should be fixed on the `0.10.1rc1` version
