### ISSUE TITLE
Is there any implementation for split-by-space tokenizer?

### ISSUE THREAD

**Issue by unclebob7** [huggingface/tokenizers#602]
Instead of using a subword model based tokenizer, is there any way I can use a simple split-by-space tokenizer in huggingface?

**Comment by n1t0** [comment]
Yes, the `WordLevel` model just uses the output of the pre-tokenizer. So if you build a tokenizer with a `Whitespace` pre-tokenizer you'll end up with words, not subwords.
You can check the quicktour and the list of components available in the documentation: https://huggingface.co/docs/tokenizers
