### ISSUE TITLE
403 status code downloading tarball at npm install 

### ISSUE THREAD

**Issue by loretoparisi** [huggingface/tokenizers#603]
In my `package.json` I have `"tokenizers": "^0.7.0",`.
When installing via `npm install` I get a 

```
> tokenizers@0.7.0 install /node_modules/tokenizers
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v83-linux-x64-glibc.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/node_modules/node-pre-gyp/lib/install.js:142:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:327:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/node_modules/request/request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:509:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:309:12)
node-pre-gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:284:9)
node-pre-gyp ERR! System Linux 4.19.121-linuxkit
node-pre-gyp ERR! command "/usr/local/bin/node" "/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /node_modules/tokenizers
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
```

**Comment by huan** [comment]
I have the same issue.

I hope we can support Node.js v14 soon!

**Comment by d-crypt0** [comment]
?? Any updates?

**Comment by d-crypt0** [comment]
?

**Comment by seppestaes** [comment]
Local installation runs just fine (with nodejs v12.21.0). Having the install run on github (specifying the exact same node version) throws the above mentioned error.

**Comment by JAAvander** [comment]
I tried the same in different environments. Neither on my workstation, nor in a fresh docker container with node version 13 does the install work.  
It seems that this link: https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v83-linux-x64-glibc.tar.gz 
is broken for some reason.
Maybe the location for storing releases changed?

**Comment by n1t0** [comment]
Version 0.8.0 of `tokenizers` has been released on npm, and it should definitely work with Node version 15 and below!

**Comment by david-wb** [comment]
I'm getting this 403 error too when trying to install inside in a `node:13-apline` image @n1t0 @huan .

**Comment by Narsil** [comment]
@david-wb , can you try from a non docker environment to check if it's linked to that ?

`tokenizers@0.8.2` is released on `npm` so it should work by default.

**Comment by david-wb** [comment]
@Narsil Yes it works is a non-docker environment. It also works using the `node:13-bullseye` image. So I think this is an issue with alpine linux.

**Comment by Narsil** [comment]
It could be linked to `alpine` using a different glibc or something. Anyway I don't think we are supporting that currently.

If you want to investigate and help us making it compatible you're most welcome.
