### ISSUE TITLE
Training fails in colab

### ISSUE THREAD

**Issue by 8enmann** [huggingface/tokenizers#606]
Copied the code directly from https://huggingface.co/docs/tokenizers/python/latest/pipeline.html#all-together-a-bert-tokenizer-from-scratch

```
PanicException: failed printing to stdout: Broken pipe (os error 32)
```

**Comment by Narsil** [comment]
Do you have more information on your environment ?

I was able to run the example within colab (I used the sample files and not wikitext).

It could be linked to the progressbar, did you try deactivating it ?
```python
trainer = WordPieceTrainer(
    vocab_size=30522, special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"], show_progress=False
)
```

**Comment by 8enmann** [comment]
show_progress=False fixed the problem!
