### ISSUE TITLE
Custom tokenizer adding whitespace at sentence beginning

### ISSUE THREAD

**Issue by jonatasgrosman** [huggingface/tokenizers#608]
Hello guys! 🤗 
I've trained a tokenizer using the following code:

```python
from tokenizers import Tokenizer, models, normalizers, pre_tokenizers, decoders

def batch_iterator(): 
    # There's a custom batch iterator here

tokenizer = Tokenizer(models.BPE())

tokenizer.normalizer = normalizers.NFKC()
tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel()
tokenizer.decoder = decoders.ByteLevel()

trainer = tokenizer.model.get_trainer()
trainer.vocab_size = 50000
trainer.special_tokens = ["<s>", "</s>", "<unk>", "<pad>", "<mask>"] 
trainer.initial_alphabet = pre_tokenizers.ByteLevel.alphabet()

tokenizer.train_from_iterator(batch_iterator(), trainer=trainer)
```

But when I use the decode method, no matter what sentence I try, it always starts with whitespace:

```python
tokenizer.decode(tokenizer.encode("And here we go!").ids)

# outputs: " And here we go!"
```

Looking at the encoded tokens, it seems that encode method always put the whitespace character at the first token:

```python
tokenizer.encode("And here we go!").tokens

# outputs: ['ĠAnd', 'Ġh', 'ere', 'Ġw', 'e', 'Ġgo', '!']
```

But in my vocab file there are the 2 tokens versions, `ĠAnd` and `And`

Am I missing something?

PS: I'm using the tokenizers 0.10.0

**Comment by n1t0** [comment]
The `ByteLevel` pre-tokenizer has an option `add_prefix_space` which is `True` by default. It makes sure there always is a whitespace at the beginning so that the first word is treated the same as if it were in the middle of a sentence. You can change it as following if you want to disable this behavior:
```python
tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)
```

**Comment by jonatasgrosman** [comment]
Got it @n1t0! Thanks for the help :)

I'm just curious now... Why is this the default behavior?

**Comment by n1t0** [comment]
It ensures all tokens representing the start of a word are treated equally, starting with the `Ġ` character representing a space. It means that all tokens that don't have this character can be considered as subparts of a word. To me, this behavior seems fair, plus it was activated by default in `transformers` when we implemented it here, so we just kept the same behavior here.
