### ISSUE TITLE
why train file run slow  use the demo code 

### ISSUE THREAD

**Issue by xxllp** [huggingface/tokenizers#61]
I pip install the python packages  
and train have no progress ~~

**Comment by n1t0** [comment]
I’m sorry but we’ll need more information if you want us to help you.
Can you show us the code you are using as well as the output you get?

**Comment by xxllp** [comment]
I use code from [https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/train_bert_wordpiece.py](https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/train_bert_wordpiece.py)

**Comment by xxllp** [comment]
and the result look like  this 
![QQ截图20200114122006](https://user-images.githubusercontent.com/4278666/72314029-4eb40080-36c8-11ea-99f2-23e50dd81f7a.png)

**Comment by xxllp** [comment]
the text file is an chinese raw ebook

**Comment by tstumm** [comment]
What fixed it for me was re-encoding the file in UTF8
