### ISSUE TITLE
Windows : ImportError : DLL load failed : The specified module could not be found.

### ISSUE THREAD

**Issue by reshinthadithyan** [huggingface/tokenizers#612]
Hello. I have been facing the issue for all the versions from 0.9.0. The last stable version I could use is 0.8.0.
### Configuration

- **OS** - Windows 10(64 bit)
- **Python** 3.6.5

**Comment by DidiDerDenker** [comment]
I'm facing the same problem. Is there a solution?

**Comment by reshinthadithyan** [comment]
No, I couldn't resolve it yet. I'm working with a downgraded version. I also tried to get some specific msr dll files, no luck as such.
