### ISSUE TITLE
cannot encode with custom BPE tokenizer  

### ISSUE THREAD

**Issue by stillmatic** [huggingface/tokenizers#62]
Hi, thanks for the library! I tried training a BPE tokenizer over custom corpus, following your examples.

In one notebook I run:
```{python}
import tokenizers
tokenizer = tokenizers.Tokenizer(tokenizers.models.BPE.empty())
tokenizer.pre_tokenizer = tokenizers.pre_tokenizers.ByteLevel.new(add_prefix_space=True)
tokenizer.decoder = tokenizers.decoders.ByteLevel.new()
trainer = tokenizers.trainers.BpeTrainer.new(vocab_size=30000, min_frequency=5)
tokenizer.train(trainer, ["vocab.txt"])
tokenizer.model.save(folder=".", name="custom_bpe_tokenizer")
``` 
This works fine and I am able to encode text given that tokenizer.

However, if I try to reinitialize that tokenizer in another notebook:
```{python}
from tokenizers import BPETokenizer
tk = BPETokenizer(vocab_file = 'custom_bpe_tokenizer-vocab.json',
                  merges_file = 'custom_bpe_tokenizer-merges.txt', )
tokenized = tk.encode("hello")
```
gives an error:
```
ExceptionTraceback (most recent call last)
<ipython-input-22-d176a55b6c42> in <module>
----> 1 tokenized = tk.encode("hello")

~/miniconda3/lib/python3.7/site-packages/tokenizers/implementations/base_tokenizer.py in encode(self, sequence, pair)
    118             An Encoding
    119         """
--> 120         return self._tokenizer.encode(sequence, pair)
    121 
    122     def encode_batch(self, sequences: List[Union[str, Tuple[str, str]]]) -> List[Encoding]:

Exception: Unk token `<unk>` not found in the vocabulary
```
I'm pretty sure "hello" is in my vocabulary and I tried with a few words from `vocab.json` and always get the same error. Any advice here?

**Comment by stillmatic** [comment]
The tokenizer encodes if I manually add a `<unk>:10` to my json file, but this seems like a bug with the saved encodings.

**Comment by prateekrastogi** [comment]
The issue you `tweeted` seems genuine to me

**Comment by mfuntowicz** [comment]
Hi @stillmatic, thanks for reporting the issue.

`BPETokenizer` is more associated to a character-level tokenizer and is intended to be instanced with vocabs/merges trained with some other normalizations / encoders.

According to the code you provided, you trained a `ByteLevelBPETokenizer`, which is also available in Python.
You should load the trained model through:

```python
from tokenizers import ByteLevelBPETokenizer
tk = ByteLevelBPETokenizer(
    vocab_file = 'custom_bpe_tokenizer-vocab.json',
    merges_file = 'custom_bpe_tokenizer-merges.txt'
)
tokenized = tk.encode("hello")
```

Please note that you can achieve the same training result through:
```python
tokenizer = ByteLevelBPETokenizer(add_prefix_space=True)

# And then train
tokenizer.train(
    files,
    vocab_size=10000,
    min_frequency=2,
    show_progress=True,
    special_tokens=["<s>", "<pad>", "</s>"],
)

# Save the files
tokenizer.save(args.out, args.name)
tokenizer = ByteLevelBPETokenizer('bpe-bytelevel-vocab.json', 'bpe-bytelevel-merges.txt', add_prefix_space=True)
```

@n1t0, @thomwolf  May be we should make more clear distinctions between BPETokenizer and ByteLevelBPETokenizer, what do you think ?

**Comment by stillmatic** [comment]
ha, I was so excited about the library that I misread the docs. definitely a bit confusing, but feel free to close the issue, thanks :)

**Comment by mfuntowicz** [comment]
I've updated the python examples to reflect the behavior above, feel free to reopen if needed :)
