### ISSUE TITLE
How can I get hidden layers' output in evaluation?

### ISSUE THREAD

**Issue by james-robinhood** [huggingface/tokenizers#623]
Hi, I trained a CNN_model using bert_embedding, how can I get hidden layers' output in evaluation?

**Comment by Narsil** [comment]
Hi @james-robinhood , I don't think this question belongs here, I think you should try asking your question here;

https://discuss.huggingface.co/

This is for `tokenizers` specific questions

**Comment by Narsil** [comment]
feel free to reopen if I missed your point and this is actually linked to `tokenizers`.
