### ISSUE TITLE
"train_from_iterator" not working in 0.10.0

### ISSUE THREAD

**Issue by RorroArt** [huggingface/tokenizers#624]
I'm trying to train a tokenizer from a custom dataset using the documentation tutorial:
https://huggingface.co/docs/tokenizers/python/latest/tutorials/python/training_from_memory.html
but It seems that the function train_from_iterator doesn't exists anymore
`TypeError: PyTokenizer.train() missing required positional argument: files`

**Comment by n1t0** [comment]
Looking at the error, it seems like you are trying to call `tokenizer.train` like if it was `tokenizer.train_from_iterator`, as the required positional argument `files` exists only when calling `train`.
Can you share a minimal example to reproduce this?

**Comment by RorroArt** [comment]
`
import torch
from torch.utils.data import DataLoader
from tokenizers import Tokenizer, models, normalizers, pre_tokenizers, decoders, trainers

dataset = WikipediaDataset('./data_test2.parquet')
loader = DataLoader(dataset, batch_size=1)
special_tokens = ['<s>', '</s>', '<unk>', '<pad>', '<sep>']
tokenizer = Tokenizer(models.BPE())
tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel()
tokenizer.normalizer = normalizers.NFKC()
tokenizer.decoders = decoders.ByteLevel()

trainer = trainers.BpeTrainer(
    vocab_size=50000,
    min_frequency=2,
    special_tokens=special_tokens
)
tokenizer.train_from_iterator(dataloader, trainer=trainer)`

This is my code, I'm using a pytorch dataloader

**Comment by RorroArt** [comment]
I'm sorry the first error wasn't the problem I had. The error im getting is this one
`AttributeError: 'tokenizers.Tokenizer' object has no attribute 'train_from_iterator'`

**Comment by n1t0** [comment]
Could you post here the output of the snippet below?
```python
import tokenizers
print(tokenizers.__version__)
```

**Comment by RorroArt** [comment]
yes, is giving me 0.9.4

**Comment by n1t0** [comment]
`Tokenizer.train_from_iterator` is available on v0.10 and up. You just need to update it!

**Comment by RorroArt** [comment]
Thanks, I think I got the 0.9.4 when I updated transformers

**Comment by n1t0** [comment]
Oh yes indeed. We actually just released `transformers` v4.3.0 an hour ago that uses `tokenizers` v0.10.1+. So you can update `transformers` again to use both libraries in their latest version. Sorry about the inconvenience!
