### ISSUE TITLE
Amharic Support

### ISSUE THREAD

**Issue by yosiasz** [huggingface/tokenizers#632]
Greetings,

Amharic NLP related resources are pretty slim. Would like to contribute to huggingface Amharic support. Where do I start?

Thanks!

**Comment by Narsil** [comment]
Hi @yosiasz ,

`tokenizers` should work out-of-the box for any language as it supports unicode.

If you're looking at datasets that could be lacking, you can check out the existing datasets here : https://huggingface.co/datasets?filter=languages:am. For models, check here: https://huggingface.co/models?filter=am

You can add some by following those steps: https://github.com/huggingface/datasets/#add-a-new-dataset-to-the-hub
Finally if you make it to actually making a new model which would be very cool, you can publish it directly on the hub and it will be visible and usable by all !

Thanks for wanting to help !

**Comment by yosiasz** [comment]
@Narsil Don't want to spam here so could you point me to something I can learn the basics for huggingface? Those links take me to something that is a bit hard to absorb for a newbie. But I am ready for a new model! I have been doing a lot of stuff in spaCy but want to explore other nlp related technologies.

Thanks

**Comment by Narsil** [comment]
I guess the best bet is the main doc:

https://huggingface.co/transformers/

If it feels a bit daunting don't hesitate to ask questions or read other's here https://discuss.huggingface.co/.

**Comment by n1t0** [comment]
Let us know how you progress, and if you think anything is missing from this library to better handle Amharic @yosiasz! Closing this issue in the meantime, feel free to reopen it.

**Comment by yosiasz** [comment]
Thanks very much @n1t0 . Would be nice if there was a simple newbie starter page. barrier to entry is way too high to me at least. the help section is overly helpful and you get lost in the weed.
