### ISSUE TITLE
Implementing Custom Decoders?

### ISSUE THREAD

**Issue by talolard** [huggingface/tokenizers#636]
Hi!
So we want to do character level models and **preserve white space**, but make use of the tokenizers library because 1) it's awesome 2) it keeps our code the same between different tokenization approaches. 

## The Good

```python
    tokenizer = Tokenizer(models.WordLevel(unk_token="<UNK>"))
    tokenizer.normalizer = normalizers.NFKC()

    tokenizer.pre_tokenizer = pre_tokenizers.Split(pattern=Regex('.'), behavior="isolated")
    tokenizer.decoder =decoders.WordPiece
```

And now we can do 
```python
tokens = tokenizer.encode("שלום אני טל").ids
decoded = ''.join(map(tokenizer.id_to_token,tokens))
   ...:         
print(tokens,decoded)
```
>[1, 14, 8, 6, 16, 4, 9, 15, 5, 4, 26, 8, 2]
> ```<BOS>שלום אני טל<EOS>```

Success!!

## The Bad
If however we do 
```python
tokenizer.decode(tokens)
```
> Out[13]: 'ש ל ו ם   א נ י   ט ל'

So using the standard decode, the tokenizers library is doing the equivalent of  ```' '.join(...)```  instead of  ```''.join(...)``` 

## The Question(s)
Say we wanted to implement a custom Decoder that does ```''.join(map(tokenizer.id_to_token,tokens))```. 
1) Is it safe to implement that in Python?
2) How do we get access to the tokenizer and it's ```id_to_token``` method in the Decoder ? 

Thanks!

**Comment by n1t0** [comment]
Hi @talolard! 

You can do it in Python, yes. Doing a custom component in Python has two consequences for now:
- It will be slower than having a native component, but for decoding that shouldn't be too much of a problem.
- You can't save the tokenizer with it attached. You'd need to use a placeholder for saving, that you replace when loading. (cf #581)

Here is how to achieve what you described above:
```python
class CustomDecoder:
    def decode(self, tokens: List[str]) -> str:
        return "".join(tokens)

from tokenizers.decoders import Decoder
tokenizer.decoder = Decoder.custom(CustomDecoder())
```
The decoder receives a list of strings and is expected to return the final string. The mapping from ids has already been done.

We could totally add a native version of this decoder if that makes sense! (Just need to think about how to name it, or maybe how to provide something that can easily customized like `Join("_")` or `Join("")` for example.)

**Comment by talolard** [comment]
Thanks!!

> We could totally add a native version of this decoder if that makes sense! (Just need to think about how to name it, or maybe how to provide something that can easily customized like `Join("_")` or `Join("")` for example.)

This would be nice to have, not critical. If you were to do it one day, jow about a flag in the decode method e.g.
```
class Decoder:
    def decode(add_whitespace_between_tokens=True):
        ....
````

**Comment by duskybomb** [comment]
Thank you @n1t0! Did you end up implementing the naive version you mentioned here?
Might be a dumb question, but how can we use the custom decoder with `PreTrainedTokenizerFast`?

**Comment by Rane90** [comment]
@n1t0 
I get this error when trying your proposed solution:

```
Exception: Custom PyDecoder cannot be serialized
```

any idea why this is happening?

Thank you

**Comment by Rane90** [comment]
@n1t0 
When trying your solution I get:
```
Exception: AttributeError: 'CustomDecoder' object has no attribute 'decode_chain'
```

Any idea why this is happening?

Thank you

**Comment by Narsil** [comment]
Hmm the type for decoders changed to be able to chain them to allow for more complex tokenizer support.

**Comment by Narsil** [comment]
HEre is the updated example :

```python
from tokenizers import Tokenizer
from tokenizers.decoders import Decoder
from typing import List

tokenizer = Tokenizer.from_pretrained("gpt2")
class CustomDecoder:
    def decode_chain(self, tokens: List[str]) -> List[str]:
        return [f" {t}" for t in tokens]

tokenizer.decoder = Decoder.custom(CustomDecoder())
print(tokenizer.decode([1, 2]))
```

Does that answer your question ?

Closing this issue since it's so old, feel free to reopen an new one.
