### ISSUE TITLE
Add SplitDelimiterBehavior to Punctuation constructor

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#642]
The `Split` class accepts `SplitDelimiterBehavior` which is really useful. The `Punctuation` however always uses `SplitDelimiterBehavior::Isolated` (and `Whitespace` on the other hand behaves like `SplitDelimiterBehavior::Removed`).

```
impl PreTokenizer for Punctuation {
    fn pre_tokenize(&self, pretokenized: &mut PreTokenizedString) -> Result<()> {
        pretokenized.split(|_, s| s.split(is_punc, SplitDelimiterBehavior::Isolated))
    }
}
```

It would be nice if you could pass a `SplitDelimiterBehavior` to `Punctuation` such as `SplitDelimiterBehavior::Removed`

Also some predefined regex's for Split could be an alternative. That way `Split`  could be used to compose a Whitespace or Punction splitter. Something like

```
Split(SplitPattern::Whitespace, SplitDelimiterBehavior::Isolated)
Split(SplitPattern::Punctuation, SplitDelimiterBehavior::Removed)
```

This isn't urgent as the workaround is to create 1 `Split` instance per punctuation character but that is a little messy.

**Comment by n1t0** [comment]
Indeed, we could add the support for customizing `SplitDelimiterBehavior` on `Punctuation`.

In the meantime, you should be able to do have the desired behavior by doing:
```python
from tokenizers import Regex
from tokenizers.pre_tokenizers import Split

pretok = Split(Regex("\p{Punctuation}"), "removed")
```

I'm not a fan of having predefined regex because everybody wants to do something different and it is impossible to cover all cases and make everybody happy. That's why `Split` exists, and it should cover pretty much any use case.

**Comment by david-waterworth** [comment]
Thanks, I did try the Split option but ran into an issue. When I try and load it via the transformers wrapper `AutoTokenizer.from_pretrained(path_to_tokenizer_json)` I get the exception:

`Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 253 column 3
`

Using transformers 4.0.1. I've not had a chance to check but I suspect it wasn't added until a later version?

**Comment by n1t0** [comment]
That's right, this version of `transformers` is based on a `tokenizers` that doesn't support `Split`. (It was added to `tokenizers==0.10.0` which was supported in `transformers==4.3.0` and up)
