### ISSUE TITLE
BPE tokenization config corrupted without pre-tokenizer

### ISSUE THREAD

**Issue by ZakMiller** [huggingface/tokenizers#645]
When I create a BPE tokenizer without a pre-tokenizer I am able to train and tokenize.
But when I save and then reload the config it does not work.

This reproduces my problem:

``` python
from tokenizers import Tokenizer
from tokenizers.models import BPE

def create_tokenizer():
    tokenizer = Tokenizer(BPE(unk_token="[UNK]"))

    from tokenizers.trainers import BpeTrainer

    trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"])

    return tokenizer, trainer

def initialize_pretrainer(tokenizer):

    from tokenizers.pre_tokenizers import Whitespace
    tokenizer.pre_tokenizer = Whitespace()

def test_encoding(tokenizer):
    encoding = tokenizer.encode('hello, welcome to the jungle')
    print(encoding.tokens)


def create(filename, pretrain):
    tokenizer, trainer = create_tokenizer()
    if pretrain:
        initialize_pretrainer(tokenizer)

    tokenizer.train(["text.raw"], trainer)

    test_encoding(tokenizer)

    tokenizer.save(filename, pretty=True)

def loadAndTest(filename):
    tokenizer = Tokenizer.from_file(filename)
    test_encoding(tokenizer)

withPretraining = 'tokenizer.json'
withoutPretraining = 'tokenizer-without.json'
print('We create tokenizer from scratch with pre-tokenization, tokenize, and save config')
create(withPretraining, True)
print('We create tokenizer from scratch *without* pre-tokenization, tokenize, and save config')
create(withoutPretraining, False)
print('We load our config with pre-tokenization and tokenize without a problem')
loadAndTest(withPretraining)
print('We load our config *without* pre-tokenization and tokenize fails?')
loadAndTest(withoutPretraining)
```

`text.raw` is this:
``` 
 
 = Robert Boulter = 
 
 Robert Boulter is an English film , television and theatre actor . He had a guest @-@ starring role on the television series The Bill in 2000 . This was followed by a starring role in the play Herons written by Simon Stephens , which was performed in 2001 at the Royal Court Theatre . He had a guest role in the television series Judge John Deed in 2002 . In 2004 Boulter landed a role as " Craig " in the episode " Teddy 's Story " of the television series The Long Firm ; he starred alongside actors Mark Strong and Derek Jacobi . He was cast in the 2005 theatre productions of the Philip Ridley play Mercury Fur , which was performed at the Drum Theatre in Plymouth and the Menier Chocolate Factory in London . He was directed by John Tiffany and starred alongside Ben Whishaw , Shane Zaza , Harry Kent , Fraser Ayres , Sophie Stanton and Dominic Hall . 
 In 2006 , Boulter starred alongside Whishaw in the play Citizenship written by Mark Ravenhill . He appeared on a 2006 episode of the television series , Doctors , followed by a role in the 2007 theatre production of How to Curse directed by Josie Rourke . How to Curse was performed at Bush Theatre in the London Borough of Hammersmith and Fulham . Boulter starred in two films in 2008 , Daylight Robbery by filmmaker Paris Leonti , and Donkey Punch directed by Olly Blackburn . In May 2008 , Boulter made a guest appearance on a two @-@ part episode arc of the television series Waking the Dead , followed by an appearance on the television series Survivors in November 2008 . He had a recurring role in ten episodes of the television series Casualty in 2010 , as " Kieron Fletcher " . Boulter starred in the 2011 film Mercenaries directed by Paris Leonti . 
```

Reduced in size to allow easy copy paste (but that exact text reproduces the problem).

* Are you supposed to be able to tokenize without a pre-tokenizer?
* Can you set the pre-tokenizer in a way that mimics the behavior of not having one (if so, I haven't figured out how)?
* Is this just a bug in the save or load functions to not support a valid configuration?

**Comment by ZakMiller** [comment]
To be clearer, the error happens on `Tokenizer.from_file(filename)` and reads: 
```
Exception: data did not match any variant of untagged enum ModelWrapper at line 1573 column 3
```

**Comment by ZakMiller** [comment]
I've investigated the problem further and I know what the issue is.

If you look at the attached 
[tokenizer-bad.txt](https://github.com/huggingface/tokenizers/files/6097554/tokenizer-bad.txt) (this is json) you'll notice that in "merges" we have records like this:

`"e  ",` (two spaces after the e)

This is incompatible with our config deserialization process.

In `src/models/bpe/model.rs`:

``` rust
pub(crate) fn convert_merges_to_hashmap<I: Iterator<Item = String>>(
    iter: I,
    _vocab: &Vocab,
) -> Result<Merges> {
    let mut merges = vec![];

    let lines = iter.filter(|l| !l.starts_with("#version"));
    for (rank, line) in lines.enumerate() {
        let parts = line.split(' ').collect::<Vec<_>>();
        if parts.len() != 2 {
            return Err(Error::BadMerges(rank + 1).into());
        }

        merges.push((parts[0].to_string(), parts[1].to_string()));
    }

    Ok(merges)
}
```

`parts.len() != 2` is triggering because we're splitting on spaces and there are more than one spaces in this merge. The problem is that the config is using spaces as a delimeter in the config file, but spaces are also part of the tokens being merged.

Note that if you remove all the merges (or leave just ones with only one space) then the config loads without an issue.

Also, this error is being swallowed somewhere I think because the error message isn't very helpful.

**Comment by n1t0** [comment]
Hello @ZakMiller, thank you for investigating this!

Indeed the error get swallowed because the deserialization process tries to find the right Model, and does not stop when it sees the actual error. It just considers that it's not a BPE. I don't know how we could improve this, but it would clearly be more helpful with a meaningful error message.

In order to avoid this error from happening in the first place, we could change the format for `merges` in the json file, but then it won't be compatible with the legacy format for `merges.txt` files (not necessarily a problem). And it might be tricky to keep the retrocompatibility with existing json files in the wild.

**Comment by ZakMiller** [comment]
Happy to, it gave me an excuse to learn a little Rust :)

Just FYI, this isn't a blocker for me. I was trying to find the most efficient way to tokenize [ABC songs](https://en.wikipedia.org/wiki/ABC_notation). I just tried all the pre-tokenization options. I ended up finding that WhitespaceSplit did comparably to no tokenizer so this isn't a blocker for me. But it still seems like an issue.

**Comment by Maxlinn** [comment]
same problem here, is replacing space with metaspace and replace back when decoding could possibly help?

**Comment by Narsil** [comment]
This problem shouldn't exist anymore.

However BPE without whitespace pretokenization will 100% be a bad idea, BPE is not a linear algorithm, having very long uncut sequences will trigger huge RAM and CPU usage (most likely process will never finish).

It ofc depends on the dataset, and on a small enough one everything should work correctly.

**Comment by delgermurun** [comment]
Thanks for the response @Narsil.
I wanted to tokenize everything including whitespaces. What is the correct way of doing it?

I tried `Split` but also fails. [Here](https://github.com/huggingface/tokenizers/issues/566#issuecomment-1637035976) is a comment about `Split`'s problem.

Thank you.

**Comment by Narsil** [comment]
You could check out the newly introduced `max_token_length` in BPE

Or `max_piece_length` in Unigram. Mandatory caution: For training Unigram, we fully tested the encoding compared to sentencepiece, however the training always has some differences as the 2 codebases have quite significant different design choices which make it hard to fully reproduce (tread with caution, it will train and output something but verify the quality of the output thoroughly)
