### ISSUE TITLE
Another tokenizers parallelism question

### ISSUE THREAD

**Issue by Guitaricet** [huggingface/tokenizers#646]
Hello there!

I can't understand if what I am observing a bug or an expected behavior.
My Dataset object uses tokenizer during the initialization. It prefetches all of the text data and I do not use it in `__getitem__`.
It looks roughly like this:

```python
class PrefetchDataset(torch.utils.data.Dataset):
    def __init__(self, texts, tokenizer, labels=None):
        self.texts = texts
        self.tokenizer = tokenizer
        self.labels = labels

        self._text_ids = [
            tokenizer.encode(t).ids for t in tqdm(self.texts, desc="Preprocessing Dataset")
        ]

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        vector = self._text_ids[idx]
        label = None if self._labels is None else self._labels[idx]

        if label is None:
            return vector
        return vector, label
```

What I understand about the tokenizers parallelism, it has some concurrency issues with the DataLoaders parallelism. However, in my case the tokenizer is not used during the batch construction, but I do see a bunch of `Avoid using tokenizers before the fork if possible` warnings and I have to turn off tokenizers parallelism via an environment variable.

Is it expected behavior of the warning?

**Comment by n1t0** [comment]
Your tokenizer is not used during the parallelized part (ie `__getitem__`), but it is part of the process being forked, and it will be available for use if you decided to use it. So the warning is just here to let you know that you are forking a process that has been using multithreading, and to avoid any problem, we disable it automatically for you.

You can override this by setting the environment variable to the desired value, and you won't see the warning if you do so.
