### ISSUE TITLE
Request: SentencePieceBPETokenizer.from_str()

### ISSUE THREAD

**Issue by keotic** [huggingface/tokenizers#647]
Is there a way to load SentencePieceBPETokenizer from str?

So we can load it after using SentencePieceBPETokenizer.to_str()

Currently it can be done by:
Saving via SentencePieceBPETokenizer.to_str() and then loading using the base class Tokenizer.from_str()
It works fine, but it is not very consistent in terms of coding and code readability.

Should not there be an implementation in the derived class as well?

**Comment by n1t0** [comment]
`SentencePieceBPETokenizer` and other implementations are here mostly to show how to build a `Tokenizer`, and provide an easy way to import existing tokenizers trained with other libraries. Once you saved/extracted it in the format used by this library, you can just load it back with `Tokenizer`, and it will work the same with every tokenizer. No need for specialization.
Your code would be a lot more complicated if you wanted to use multiple different tokenizers and had to deal with using the right class each time.
