### ISSUE TITLE
Compatibility with Node 14+?

### ISSUE THREAD

**Issue by imranq** [huggingface/tokenizers#648]
I'm not able to use tokenizers 0.7.0 with Node 14 or above. Is it possible to rebuild for these node versions?

**Comment by jameswilsterman** [comment]
This has stopped working for me on Node 12.20.0 also

**Comment by imranq** [comment]
any update on this?

**Comment by bencmbrook** [comment]
cc @Pierrci any details on why this is explicitly set to <14, or do you think we can remove this limit? 

https://github.com/huggingface/tokenizers/commit/25546d00c6217066ac879cda91f66647d19b9395#r51353342

**Comment by JAAvander** [comment]
I tried manually building the package from the sources.
While the package appears to work at first, as soon as a call to encode happens, node exits with a warning about 
```
domain.enter is not a function
```

**Comment by imranq** [comment]
It seems like domain was deprecated in some version after 14. Is there a replacement for it? https://nodejs.org/api/domain.html

**Comment by JAAvander** [comment]
I found that as well, and thought that this causes the need to use versions before 14.  
Thing is, I tried building the package in node version 13, as well as 12. Despite the different node version the same error occurs.

**Comment by n1t0** [comment]
Version 0.8.0 of `tokenizers` has been released on npm, and it should definitely work with Node version 15 and below!

**Comment by markhughes** [comment]
Hey @n1t0 & cc @Narsil - Could we update the package.json file to include node <=15?

Should we also consider updating GitHub actions to recursively test node 12, and 14?
