### ISSUE TITLE
Little grammatical error in the Readme 

### ISSUE THREAD

**Issue by tafodinho** [huggingface/tokenizers#65]
we have  "And training an new vocabulary is just as easy"
Instead of "And training a new vocabulary is just as easy"

around line 39

**Comment by n1t0** [comment]
Thanks for reporting this. It has been fixed by https://github.com/huggingface/tokenizers/pull/60

**Comment by phosseini** [comment]
Speaking of errors, there're bunch of spelling errors too. For example,

"mapping to retrieve the string coresponding to the 10th token" -> should be "corresponding."

You may want to take a quick look!
