### ISSUE TITLE
Assigning type_ids from records using Template Processor

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#651]
I'm concatenating data from multiple records into a single string, i.e.

row = dict(record_1="XXX", record_2="YYY, record_3="ZZZ")

text = f"{row['record_1']}{row['record_2']}{row['record_3']}"

Is it possible to generate type_id's corresponding with the different records (when there's more than 2) using perhaps a Template Processor? All the existing use cases seem to revolve around creating a pair with type_id 0 and 1. 

I'd probably also want to optionally add a [CLS] and [SEP] tokens.

**Comment by n1t0** [comment]
At the moment processors only support 2 sequences, unfortunately.
