### ISSUE TITLE
Bug in BPE

### ISSUE THREAD

**Issue by avacaondata** [huggingface/tokenizers#655]
Hi, I've trained a BPE for spanish using OSCAR corpus and this script:

```{python}
import glob
import os
import random

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.trainers import BpeTrainer

if __name__ == "__main__":
    tokenizer = Tokenizer(BPE())
    tokenizer.pre_tokenizer = Whitespace()
    # tokenizer = ByteLevelBPETokenizer(add_prefix_space=False)

    trainer = BpeTrainer(
        special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"],
        vocab_size=50265,
        continuing_subword_prefix="\u0120",
        min_frequency=1,
    )
    # t = AutoTokenizer.from_pretrained("microsoft/deberta-base")
    files = glob.glob("cleaned_train_data/*.csv")
    files_sample = random.choices(files, k=250)
    tokenizer.train(
        files=files_sample,
        trainer=trainer,
    )
    tokenizer.save("prueba_tok_080/tokenizer.json")
```
There are various bugs here. The first one is that, with versions 0.8.0 and 0.10.1 the saved tokenizer has the correct vocabulary, but something inside it is wrong, as when I tokenize sentences that include words I've seen in the vocab of the tokenizer, it tokenizes the sentence into characters. No complete or partial word is included, only characters, no matter which words I put in the sentence. 
Secondly, I can only use 250 out of the 5500 text files I have because of a memory leak caused by Tokenizers. I'm pretty sure of that because all data files together use 187GB, the BPE algorithm shouldn't use too much memory and my complete RAM memory is 500GB. 
I'm trying to train a BPE tokenizer to train a Roberta model in Spanish, is there any version of Tokenizers that doesn't have memory leaks in BPE algorithm code and which uses its vocabulary correctly so that it doesn't tokenize words it indeed has in its vocabulary as characters? @n1t0

**Comment by n1t0** [comment]
The first bug is related to https://github.com/huggingface/tokenizers/issues/643 and should now be fixed.

Concerning the RAM usage, the fact that it uses more RAM than the size of the original dataset files does not mean there is a memory leak.
