### ISSUE TITLE
AutoTokenizer cannot deserialise a tokeniser with no pre_tokenizer

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#658]
I'm not sure if this belongs in `tokenisers` or `transformers`?

I created a Tokenizer from a vocab as follows.

```
tokenizer = tokenizers.Tokenizer(
    tokenizers.models.Unigram(vocab, unk_id=special_tokens.index(UNK))
    )
tokenizer.normalizer = tokenizers.normalizers.Lowercase()
tokenizer.add_special_tokens(special_tokens)

tokenizer.save("models/tokenizer/tokenizer.json")
```

This works fine (afaik pre-tokenisation isn't required when using Unigram provided you don't need to ignore any characters like whitespace).

But when I try and load the `tokenizer.json` via AutoTokenizer.from_pretrained("models/tokenizer") it throws an exception. The cause is the presence of `"pre_tokenizer": null` in `tokenizer.json`.

The easy fix is to include

`tokenizer.pre_tokenizer = tokenizers.pre_tokenizers.Sequence([])`

Note that both `post_processor` and `decoder` are also null and no exception is thrown for them. So it seems `AutoTokenizer` considered pre_tokenizer as required.

I didn't actually mean to exclude the pre_tokenizers - I intended on adding `Whitespace()` but I don't think that a pre_tokenizers should always be mandatory?

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-119-10daf23d3241> in <module>
>       1 from transformers import AutoTokenizer
> ----> 2 tok = AutoTokenizer.from_pretrained("/home/david/dev/machine-learning-research/src/inception/models/tokenizer")
>       3 
> 
> ~/.pyenv/versions/ontologies/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
>     393             tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
>     394             if tokenizer_class_fast and (use_fast or tokenizer_class_py is None):
> --> 395                 return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
>     396             else:
>     397                 if tokenizer_class_py is not None:
> 
> ~/.pyenv/versions/ontologies/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
>    1786                 logger.info("loading file {} from cache at {}".format(file_path, resolved_vocab_files[file_id]))
>    1787 
> -> 1788         return cls._from_pretrained(
>    1789             resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
>    1790         )
> 
> ~/.pyenv/versions/ontologies/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in _from_pretrained(cls, resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs)
>    1858         # Instantiate tokenizer.
>    1859         try:
> -> 1860             tokenizer = cls(*init_inputs, **init_kwargs)
>    1861         except OSError:
>    1862             raise OSError(
> 
> ~/.pyenv/versions/ontologies/lib/python3.8/site-packages/transformers/models/roberta/tokenization_roberta_fast.py in __init__(self, vocab_file, merges_file, tokenizer_file, errors, bos_token, eos_token, sep_token, cls_token, unk_token, pad_token, mask_token, add_prefix_space, **kwargs)
>     158         **kwargs
>     159     ):
> --> 160         super().__init__(
>     161             vocab_file,
>     162             merges_file,
> 
> ~/.pyenv/versions/ontologies/lib/python3.8/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py in __init__(self, vocab_file, merges_file, tokenizer_file, unk_token, bos_token, eos_token, add_prefix_space, **kwargs)
>     142         )
>     143 
> --> 144         pre_tok_state = json.loads(self.backend_tokenizer.pre_tokenizer.__getstate__())
>     145         if pre_tok_state.get("add_prefix_space", add_prefix_space) != add_prefix_space:
>     146             pre_tok_class = getattr(pre_tokenizers, pre_tok_state.pop("type"))
> 
> AttributeError: 'NoneType' object has no attribute '__getstate__'

**Comment by n1t0** [comment]
This is happening because you end up using the `RobertaTokenizerFast` which expects the tokenizer to have a `ByteLevel` pre-tokenizer. You should instead use `PreTrainedTokenizerFast.from_pretrained` I guess.
