### ISSUE TITLE
rust tokenizer reading directly from S3

### ISSUE THREAD

**Issue by albertoa** [huggingface/tokenizers#661]
We currently train BertWordPieceTokenizer using the rust implementation. Our datasets are in S3, however this is not currently supported and only local files are allowed.

Any chance using S3 directly is planned to be supported in the near future?

**Comment by n1t0** [comment]
I don't think we'll add this kind of feature in the future. You could probably try to stream the content from S3 manually, and use an iterator to train your tokenizer with `tokenizer.train_from_iterator(...)`.
