### ISSUE TITLE
SentencePiece fast tokenizers still have issues with the offsets_mapping

### ISSUE THREAD

**Issue by basma-b** [huggingface/tokenizers#663]
I am using xlm-roberta model with the latest version of Transformers 4.4.0 and tokenizers 0.10.1 and I still have problems with the offsets_mapping even though the new release says it is fixed #616 

## Problem description
* This special character `…` is tokenized as 3 separated dots '...', moreover, as mentioned below the first 3 dots are tokenized separately from the rest of the 3 dots
```
THREE_DOTS_FAIL = "une part, et La Société\u202f……………….dont le siège"
print(THREE_DOTS_FAIL)
# une part, et La Société ……………….dont le siège
tokenizer.tokenize(THREE_DOTS_FAIL)
# ['▁une', '▁part', ',', '▁et', '▁La', '▁Société', '▁...', '................', 'don', 't', '▁le', '▁siège']
# why the same 3 dots produce different tokens '▁...', '................', ?
```

* The character `\x10` makes the tokenizer produce wrong offsets
```
TEST_FAILS_X10 = 'T\x10his \x10\t \n \n    \x10\x10\x10\x10   \nis     \t\t \x10     a \t\n\t         te\x10st\n'
tokenizer.tokenize(TEST_FAILS_X10)
# ['▁This', '▁is', '▁a', '▁test']
tokenizer(TEST_FAILS_X10, add_special_tokens=False, return_offsets_mapping=True).offset_mapping
# [(0, 5), (21, 23), (37, 38), (51, 56)]
# --> The corresponding tokens are:
# TEST_FAILS_X10[0:5] = 'T\x10his'
# TEST_FAILS_X10[21:23] = '  '
# TEST_FAILS_X10[37:38] = ' '
# TEST_FAILS_X10[51:56] = '   te'
```

* For some reasons, the empty token `▁` is produced when tokenizing the sentence and it creates a shift in the offsets_mapping.
```
LONG_CONTEXT = '\'AGREEMENT BY AND BETWEEN COMPANY A, INC. AND ZANDER XXX, INC.\n'
tokenizer.tokenize(LONG_CONTEXT)
# ["▁'",  'A', 'GRE', 'EMENT', '▁BY', '▁AND', '▁BE', 'TW', 'EEN', '▁COMP', 'ANY', '▁A', ',', '▁INC', '.', '▁AND', '▁', 'ZAN', 'DER', '▁XXX', ',', '▁INC', '.']
tokenizer(LONG_CONTEXT, add_special_tokens=False, return_offsets_mapping=True).offset_mapping
# [(0, 1), (1, 2), (2, 5), (5, 10), (11, 13), (14, 17), (18, 20), (20, 22), (22, 25), (26, 30), (30, 33), (34, 35), (35, 36), (37, 40), (40, 41), (42, 45), (46, 47), (46, 49), (49, 52), (53, 56), (56, 57), (58, 61), (61, 62)]
# here the token  '▁' has a corresponding offset (46, 47) however LONG_CONTEXT[46:47] = 'Z'
```
@n1t0 
@sgugger 
Can you help please ?

**Comment by n1t0** [comment]
Hi @basma-b and thank you for reporting all of this! 

> This special character … is tokenized as 3 separated dots '...', moreover, as mentioned below the first 3 dots are tokenized separately from the rest of the 3 dots

The result here is expected. If you add or remove some `…`  you will end up with different combinations of tokens. That's just how the tokenizer works.

> The character \x10 makes the tokenizer produce wrong offsets

This has been fixed recently and will be part of the next release (cf https://github.com/huggingface/tokenizers/pull/652). Here is the result with the current `master`:
```
['<s>', '▁This', '▁is', '▁a', '▁test', '</s>']
[0, 3293, 83, 10, 3034, 2]
[(0, 0), (0, 5), (24, 26), (40, 41), (54, 59), (0, 0)]
(0, 0)
(0, 5) This
(24, 26) is
(40, 41) a
(54, 59) test
(0, 0)
```

> For some reasons, the empty token ▁ is produced when tokenizing the sentence and it creates a shift in the offsets_mapping.

Even though we fixed the conversion with #616, the `tokenizer.json` available on the Hugging Face Hub for `xlm-roberta-base` still contains the bug. We are still in the process of fixing this, but it requires to have several versions of the said `tokenizer.json` as the new version is not compatible with older versions of `transformers`. You can force a conversion by specifying `from_slow=True` as follow:
```python
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base", use_fast=True, from_slow=True)
```
When doing this, I obtain the following result:
```
>>> for token, (start, end) in zip(tokenizer.tokenize(LONG_CONTEXT), offsets):
...     print(token, (start, end), repr(LONG_CONTEXT[start:end]))

▁' (0, 1) "'"
A (1, 2) 'A'
GRE (2, 5) 'GRE'
EMENT (5, 10) 'EMENT'
▁BY (10, 13) ' BY'
▁AND (13, 17) ' AND'
▁BE (17, 20) ' BE'
TW (20, 22) 'TW'
EEN (22, 25) 'EEN'
▁COMP (25, 30) ' COMP'
ANY (30, 33) 'ANY'
▁A (33, 35) ' A'
, (35, 36) ','
▁INC (36, 40) ' INC'
. (40, 41) '.'
▁AND (41, 45) ' AND'
▁ (45, 46) ' '
ZAN (46, 49) 'ZAN'
DER (49, 52) 'DER'
▁XXX (52, 56) ' XXX'
, (56, 57) ','
▁INC (57, 61) ' INC'
. (61, 62) '.'
▁ (62, 63) '\n'
```

**Comment by basma-b** [comment]
Many thanks @n1t0 for the quick answer. We'll wait for the next release then :+1: 
I'm closing the issue

**Comment by basma-b** [comment]
Hello @n1t0 I updated transformers to 4.5.1 and tokenizers to 0.10.2 to solve the above problem and now I'm having an issue with the following:
```
BASIC_CONTEXT = 'This is a test'
tokenizer = XLMRobertaTokenizerFast.from_pretrained('xlm-roberta-base', use_fast=True, from_slow=True)
tokenizer(BASIC_CONTEXT, return_offsets_mapping=True).offset_mapping
# [(0, 0), (0, 4), (4, 7), (7, 9), (9, 14), (0, 0)]
BASIC_CONTEXT[4:7]
# ' is'
BASIC_CONTEXT[7:9]
# ' a'
```
As you can see, there is an extra space before the tokens. Please note that with transformers 4.2.2 and 0.9.4 I don't have this issue and if I remove `use_fast=True, from_slow=True` the problem disappears as well.
