### ISSUE TITLE
BPE Tokenizer uses massive amount of memory

### ISSUE THREAD

**Issue by jafioti** [huggingface/tokenizers#665]
I believe there is a memory leak in the BPE tokenizer, because when I tokenize a large amount of text (~1 GB), the tokenization process takes up to 32 GB of RAM, at which point I am forced to stop it. Here is my entire tokenization function:

```
pub fn tokenize_bpe(strings: Vec<String>, tokenizer: &Tokenizer) -> Vec<Vec<String>> {
    tokenizers::utils::parallelism::set_parallelism(true);

    // Tokenize
    let encodings = tokenizer.encode_batch(strings, false).expect("BPE tokenization failed!");
    // Convert back to strings
    let mut tokens: Vec<Vec<String>> = Vec::with_capacity(encodings.len());
    for encoding in encodings.iter() {
        tokens.push(encoding.get_tokens().to_vec());
    }
    tokens
}
```

**Comment by jafioti** [comment]
I've narrowed it down to the size of tokens being returned from the tokenization. Is there a reason that these tokens would be so much bigger than the original text itself? (20x bigger)

**Comment by enze5088** [comment]
I have the same problem, training model on 15GB of text uses about 600GB of memory.

**Comment by Narsil** [comment]
@enze5088 can you please open up a new issue and join a reproducible script ?

It could be very normal and linked to poor pre-tokenization (BPE is highly sensitive to pretokenization).
Without more information it's hard to provide help.
