### ISSUE TITLE
Using datasets.map with a custom tokenizer does not apply tokenization when wrapped in BatchEncoding

### ISSUE THREAD

**Issue by dkavaler** [huggingface/tokenizers#666]
I've built a custom tokenizer using the `tokenizers` library. When using `datasets.map`, I don't see a way to get the encoded text back in the resulting object without some "hackery".

Example code:

```python
from transformers import BatchEncoding


tokenizer = build_custom_tokenizer()  # Builds a `tokenizer.Tokenizer` object
datasets = load_dataset('text', data_files=data_files, cache_dir=data_args.cache_dir)

# Contents of datasets
# >>> datasets
# DatasetDict({
#     train: Dataset({
#         features: ['text'],
#         num_rows: 1
#     })
# })
# >>> datasets['train']['text']
# ['hello']

# "Proof" that tokenizer should work in the encode call
# >>> tokenizer.encode('hello')
# Encoding(num_tokens=6, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])
# >>> tokenizer.encode('hello').tokens
# ['h', '##e', '##l', '##l', '##o', '<eos>']

# Tokenize wraps the result in a BatchEncoding as I believe that is what `transformers` does when using pretrained tokenizers
def tokenize(examples):
    return BatchEncoding(examples, encoding=tokenizer.encode_batch(examples['text']))

tokenized_datasets = datasets.map(
    tokenize,
    batched=True,
    num_proc=data_args.preprocessing_workers,
    remove_columns=['text'],
    load_from_cache_file=not data_args.overwrite_cache
)

# >>> tokenized_datasets
# DatasetDict({
#     train: Dataset({
#         features: ['text'],
#         num_rows: 1
#     })
# })

# >>> tokenized_datasets['train']['text']
# ['hello']

```

**Expectation**: The contents of `tokenized_datasets['train']['text']` should be encoded as `['h', '##e', '##l', '##l', '##o', '<eos>']` (and I should be able to access all the elements of the `Encoding` class, e.g., `ids`, `type_ids`, etc.)

I believe the core of the issue is the `tokenize` function I defined. I expect that the result of my function would be the same as if one were to do something like:

```python
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

def tokenize(example):
     return tokenizer(example['text'])

tokenized_datasets = datasets.map(
    tokenize,
    batched=True,
    num_proc=data_args.preprocessing_workers,
    remove_columns=['text'],
    load_from_cache_file=not data_args.overwrite_cache
)

# >>> tokenized_datasets
# DatasetDict({
#     train: Dataset({
#         features: ['attention_mask', 'input_ids', 'token_type_ids'],
#         num_rows: 1
#     })
# })
```

but this is not the case.

The following `tokenize` function "fixes" the issue:

```python
def tokenize(examples):
    result = {}
    for e in tokenizer.encode_batch(examples['text']):
        result.setdefault('ids', []).append(e.ids)
        result.setdefault('type_ids', []).append(e.type_ids)
        result.setdefault('tokens', []).append(e.tokens)
        result.setdefault('offsets', []).append(e.offsets)
        result.setdefault('attention_mask', []).append(e.attention_mask)
        result.setdefault('special_tokens_mask', []).append(e.special_tokens_mask)
        result.setdefault('overflowing', []).append(e.overflowing)
    
    return result
```

but this is not particularly elegant, and it seems as though another solution may exist.

I intend to use this downstream using the `transformers` `Trainer` class, and it's not clear how to use the `tokenizers` framework in a compatible manner.

It's very possible I have a complete misunderstanding on how to use `datasets`, `tokenizers`, and `transformers` together, so any help would be greatly appreciated!

**Comment by Maimonator** [comment]
I'm having the same issue.
Apparently the tokenizers in `transformers` are returning an internal object of type `transformers.tokenization_utils_base.BatchEncoding` while enocding with the tokenizers in `tokenizers` you get a list of objects of the type `tokenizers.Encoding`

**Comment by Maimonator** [comment]
@dkavaler I found a possible solution, that worked for me.
You can save the tokenizer using `tokenizer.model.save("tokenizer_name")` this saves it in the same format of the transformers tokenizers so you could use:
`RobertaTokenizerFast.from_pretrained("tokenizer_name")`
I noticed that the documentation states :
[Construct a “fast” BERT tokenizer (backed by HuggingFace’s tokenizers library).](https://huggingface.co/transformers/model_doc/bert.html?highlight=tokenizerfast#transformers.BertTokenizerFast)

Since all the FastTokenizers are based on the tokenizers library I assumed there's some kind of compatibility and this is the solution I found.

Hopefully that will be helpful or maybe someone could enlighten us with a solutin

**Comment by dkavaler** [comment]
@Maimonator Thanks for finding that. Unfortunately, I have a number of specific use cases that don't appear to be directly supported by any existing `PreTrainedTokenizerFast` subclass, and it doesn't seem that instantiating the base class directly will work for me either.

Hopefully a solution will come soon!

**Comment by n1t0** [comment]
If you want to use a Tokenizer from this library with anything built for `transformers`, then indeed you should wrap it somehow in the `transformers.PreTrainedTokenizerFast`. The `transformers` library is using tokenizers based on this class and is expecting this kind of interface.

If the tokenizer you built is based on one of the existing tokenizers, for example if it works like a BERT tokenizer, you can then use the subclass defined for BERT like this:
```python
tokenizer = BertTokenizerFast.from_pretrained("./path/to/folder/with/tokenizer.json/file")
# or
tokenizer = BertTokenizerFast(tokenizer_file="tokenizer.json")
```

If your tokenizer is not based on any existing tokenizer, and does not require specific customization, then you can wrap it the same way with `PreTrainedTokenizerFast` directly:
```python
tokenizer = PreTrainedTokenizerFast.from_pretrained("./path/to/folder/with/tokenizer.json/file")
# or
tokenizer = PreTrainedTokenizerFast(tokenizer_file="tokenizer.json")
```

For any other use case with some required customization, then you could write your own class, that inherits from `PreTrainedTokenizerFast` and overrides what needs to be customized.

The `datasets` library makes no assumption about any of this and lets you do what you want. So it depends on your use-case and what you expect to do with the tokenized data.

Does it make sense?

**Comment by dkavaler** [comment]
Thanks for the response @n1t0 

I've tried the save/load (with `PreTrainedTokenizerFast`) approach, but when I save the tokenizer using the `tokenizers` library:

`tokenizer.save('tokenizer.json')`

and load with `PreTrainedTokenizerFast`:

`tokenizer = PreTrainedTokenizerFast(tokenizer_file='tokenizer.json')`

I receive strange results (in debugger):

```
>>> tokenizer
PreTrainedTokenizerFast(name_or_path='', vocab_size=119, model_max_len=1000000000000000019884624838656, is_fast=True, padding_side='right', special_tokens={})
```

It appears as though I will need to inherit from `PreTrainedTokenizerFast` and write my own class, or otherwise avoid `transformers` endpoints that require a tokenizer.

**Comment by Maimonator** [comment]
> If you want to use a Tokenizer from this library with anything built for `transformers`, then indeed you should wrap it somehow in the `transformers.PreTrainedTokenizerFast`. The `transformers` library is using tokenizers based on this class and is expecting this kind of interface.
> 
> If the tokenizer you built is based on one of the existing tokenizers, for example if it works like a BERT tokenizer, you can then use the subclass defined for BERT like this:
> 
> ```python
> tokenizer = BertTokenizerFast.from_pretrained("./path/to/folder/with/tokenizer.json/file")
> # or
> tokenizer = BertTokenizerFast(tokenizer_file="tokenizer.json")
> ```
> 
> If your tokenizer is not based on any existing tokenizer, and does not require specific customization, then you can wrap it the same way with `PreTrainedTokenizerFast` directly:
> 
> ```python
> tokenizer = PreTrainedTokenizerFast.from_pretrained("./path/to/folder/with/tokenizer.json/file")
> # or
> tokenizer = PreTrainedTokenizerFast(tokenizer_file="tokenizer.json")
> ```
> 
> For any other use case with some required customization, then you could write your own class, that inherits from `PreTrainedTokenizerFast` and overrides what needs to be customized.
> 
> The `datasets` library makes no assumption about any of this and lets you do what you want. So it depends on your use-case and what you expect to do with the tokenized data.
> 
> Does it make sense?

Thanks for the elaborate answer, could you point us to where this is written in the documentation? 
I tried searching for that information but couldn't find it.

**Comment by ylhsieh** [comment]
I am facing the same issue here, namely, trained a custom tokenizer using `tokenizers` package, but could not use it in transformers. 😢

**Comment by n1t0** [comment]
Did you try the solution above?

**Comment by ylhsieh** [comment]
> Did you try the solution above?

Hi yeah I did try both. I am training a model with the masked LM objective using `run_mlm.py`
```
tokenizer = PreTrainedTokenizerFast.from_pretrained("unigram_model.json")
# AND
tokenizer = PreTrainedTokenizerFast(tokenizer_file="unigram_model.json")
```
The first method throws
```
File "...python3.8/site-packages/transformers/tokenization_utils_base.py", line 1623, in from_pretrained
file_id = list(cls.vocab_files_names.keys())[0]
   IndexError: list index out of range
```
The second method loads fine, but presents an error later on
```
This tokenizer does not have a mask token which is necessary for masked language modeling.
You should pass `mlm=False` to train on causal language modeling instead.
```
I can add `tokenizer.mask_token = "[MASK]"` later, but it seems hacky. 
It appears that the tokenizers in `transformers` require more information than what was saved by the `tokenizers.save()` ? 
Forget my ignorance, but is there a way to export customized tokenizer properly from `tokenizers` and use it in `transformers`?

**Comment by Maimonator** [comment]
If you have a custom tokenizer I think you should wrap PreTrainedTokenizerFast with the correct methods.
If let's say you created a tokenizer which works exactly like RobertaTokenizer you could use:
`RobertaTokenizerFast(vocab_file=vocab_file, merges_file=merges_file, tokenizer_file=tokenizer_file)`
This method worked for me ^
