### ISSUE TITLE
Trained tokenizer vocab size exceeds the given limit

### ISSUE THREAD

**Issue by nonlocal** [huggingface/tokenizers#670]
Hi,
I am training BPE tokenizer on some custom data, derived from [dbpedia here](https://drive.google.com/drive/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M).

The `text_list` has all the texts from the `train.csv` file from the dbpedia dataset. The size of `text_list` is `560000`.

code to train BPE:

```python
VOCAB_SIZE = 5000
text_list = [text1, text2, ......] # size = 560000
bpe = Tokenizer(BPE(unk_token="[UNK]"))
bpe.pre_tokenizer = pre_tokenizers.Sequence([Whitespace(), Digits(individual_digits=True)])
bpe_trainer = BpeTrainer(special_tokens=["[UNK]"], vocab_size=VOCAB_SIZE)
bpe.train_from_iterator(text_list, trainer=bpe_trainer)

``` 

In the `BpeTrainer` above, I have set a limit on vocab size of 5000. But the trained `bpe` returns:
```
>>> bpe.get_vocab_size()
7109
```

Ideally this shouldn't happen, the trainer should consider top `vocab_size` byte-pairs only. Really confused by this. Why is this happening? How to resolve this?

@julien-c 
@n1t0 @Narsil  @Pierrci

**Comment by will-rice** [comment]
Did you figure out what was going on with this? Passing `None` here `Tokenizer(WordPiece(vocab=None, unk_token="[UNK]"))` seemed to reduce the vocab, but with `vocab_size=1024` in the trainer, I'm still at `5076`

**Comment by nonlocal** [comment]
I have looked at the code. I don't think it's possible to have that with WP.

**Comment by jusger** [comment]
I'm also finding this to be the case. Running version 0.10.1 (0.10.2 and 0.10.3 both have the GLIBC error). If I set the BpeTrainer vocab_size it seems to always result in the default (30k). I've just been playing with it in an ipython session, if that's of any concern. Will try it later within a script.

**Comment by jusger** [comment]
Update: did manage to install from pip v. 0.10.3, and have observed the same issue in ipython environments. If there's anything I can do to help further debug, would be happy to (or if I'm missing some configuration or something).
