### ISSUE TITLE
Newly added tokens still get split arbitrarily

### ISSUE THREAD

**Issue by glnmario** [huggingface/tokenizers#672]
I add new tokens to the BertTokenizer vocabulary but they get arbitrarily split anyways.

```
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', use_fast=False, do_lower_case=True, do_basic_tokenize=True)
tokenizer.add_tokens(['graft', 'grafts'])
Out: 2
tokenizer.convert_ids_to_tokens(tokenizer.encode('graft'))
Out: ['[CLS]', 'graft', '[SEP]']
tokenizer.convert_ids_to_tokens(tokenizer.encode('grafts'))
Out: ['[CLS]', 'grafts', '[SEP]']
tokenizer.convert_ids_to_tokens(tokenizer.encode('my graft and their grafts'))
Out: ['[CLS]', 'my', 'graft', 'and', 'their', 'graft', 's', '[SEP]']
```

Adding these tokens to the 'never_split' argument has no effect:
`tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', use_fast=False, do_lower_case=True, do_basic_tokenize=True, never_split=['graft', 'grafts'])`.

**Comment by nonlocal** [comment]
Try changing the order? 
```
tokenizer.add_tokens(['graft', 'grafts']) --> tokenizer.add_tokens(['grafts', 'graft'])
```

**Comment by glnmario** [comment]
> Try changing the order?
> 
> ```
> tokenizer.add_tokens(['graft', 'grafts']) --> tokenizer.add_tokens(['grafts', 'graft'])
> ```

Same behaviour unfortunately, but thanks for the suggestion.

**Comment by guyrosin** [comment]
Happened to me as well :(

**Comment by finiteautomata** [comment]
Your example is working ok for me with `transformers==4.8.2`
