### ISSUE TITLE
How to set 'unk_id' in SentencePieceUnigramTokenizer

### ISSUE THREAD

**Issue by ksopyla** [huggingface/tokenizers#679]
I want to use SentencePieceUnigramTokenizer class for training tokenizer and while encoding i got Exception "Encountered an unknown token but `unk_id` is missing"

Here is a minimal example:

```
text_source_itr = ["abcd", "bcde", "acd"]
sample_text="aAc"

special_tokens = [ "<pad>", "<s>", "</s>", "<unk>" ]

tok1 = SentencePieceUnigramTokenizer()
tok1.enable_padding(pad_id=0, pad_token="<pad>")
tok1.train_from_iterator(
    text_source_itr,
    special_tokens=special_tokens,
    vocab_size=200,
    show_progress=True,
)

tok1.encode("aAb") #letter A is not in vocabulary
```
How can i set the **unk_id**?

**Comment by david-waterworth** [comment]
It looks like the `UnigramTrainer` used by `SentencePieceUnigramTokenizer` is constructed without the `unk_token` parameter, and there's no way to set it.

https://github.com/huggingface/tokenizers/blob/0fe9214f44f4e117a85e3880c20631cc70298d86/bindings/python/py_src/tokenizers/implementations/sentencepiece_unigram.py#L55
