### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by muhlbach** [huggingface/tokenizers#685]
Hi there! 

First, I love this library! However, I'm recently facing issues loading the library. I'm running on a Linux server with
```
Python 3.8.8
[GCC 7.3.0] :: Anaconda, Inc. on linux.
```
When I run
`import tokenizers`
it throws the following error
```
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/muhlbach/.conda/envs/stable/lib/python3.8/site-packages/tokenizers/tokenizers.cpython-38-x86_64-linux-gnu.so)
```

I have no idea how to solve this, unfortunately. Please let me know if you need any details on my installation.

**Comment by clairemcwhite** [comment]
I got this same error with 

conda create --name hf-transformers -c huggingface transformers 
`ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/cmcwhite/.conda/envs/hf-transformers/lib/python3.8/site-packages/tokenizers/tokenizers.cpython-38-x86_64-linux-gnu.so)`


I changed the channel  to conda-forge, and now it's working
conda create --name hf-transformers -c conda-forge transformers

**Comment by albertvillanova** [comment]
@tginart, you might be interested in following this issue.

**Comment by tginart** [comment]
Thanks!

**Comment by agni-ai** [comment]
@MaveriQ Thanks, this helps!

**Comment by Narsil** [comment]
Hi @agni-ai Can you try with the latest `0.11.1`  ? It should work on old libc again.

**Comment by shashank140195** [comment]
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/sgu260/.local/lib/python3.8/site-packages/thinc/neural/ops.cpython-38-x86_64-linux-gnu.so)

In my case, it is because of thinc package? How can i resolve it?

**Comment by Narsil** [comment]
As the `thinc` library ?

**Comment by vishnua2j** [comment]
I am getting the below error while trying to run model (mistral-7b-openorca.Q4_K_M) which requires **ctransformers** in AWS server. Can someone help me with the solution?

Error
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /labelligent02/NBA/nba-venv/lib/python3.10/site-packages/ctransformers/lib/avx2/libctransformers.so)

**Comment by Narsil** [comment]
@vishnua2j Ask ctransformers library.

**Comment by aritra3520** [comment]
@vishnua2j Have you got any solution? I am facing the same error

**Comment by vishnua2j** [comment]
@aritra3520 

Try with this command "pip install ctransformers --no-binary ctransformers --no-cache-dir" it may solve your problem. It solved for me

—
