### ISSUE TITLE
How to use the XLMRoBERTa tokenizer?

### ISSUE THREAD

**Issue by hapazv** [huggingface/tokenizers#689]
good day.

first sorry for my english.

code using 'bert-base-multilingual-cased'

to tokenize the phrases I did it like this and got a good result:

![tokenizador bert](https://user-images.githubusercontent.com/70067770/115965349-72324180-a4ee-11eb-82db-ccd047fb5d0d.png)

however when I wanted to do it with XLMRoBERTa I did not get good results, I would like to know how to do it with this other model, I appreciate the help.

![token roberta](https://user-images.githubusercontent.com/70067770/115965292-11a30480-a4ee-11eb-8ed2-f44fc8ba01e8.png)

**Comment by stefan-it** [comment]
Hi @hapazv , could you check that you've installed `sentencepiece` library? If not please  install it via `pip3 install sentencepiece` and check if it's working 🤗

**Comment by hapazv** [comment]
> Hola @hapazv , ¿podrías comprobar que has instalado la `sentencepiece`biblioteca? Si no es así, instálelo a través de `pip3 install sentencepiece`y compruebe si funciona🤗

@stefan-it 
Thank you very much, I have been a fool.
it worked perfectly.
