### ISSUE TITLE
How to combine two tokenizers?

### ISSUE THREAD

**Issue by ameet-1997** [huggingface/tokenizers#690]
Say I have two tokenizers, one for English, and one for Hindi. Both tokenizers are BPE tokenizers, so I have the `vocab.json` and `merges.txt` file for both the tokenizers.

Now if I wanted to train a bilingual model, I will essentially have to combine the English and the Hindi tokenizers. I don't have access to the corpora, so I won't be able to learn a new tokenizer by combining the corpora. What should I do in that case?

The following is the solution I'm thinking about. I'll appreciate it if anyone can verify if it makes sense:

#### Possible solution
1. Take the union of `english_vocab.json` and `hindi_vocab.json` and create a new vocabulary called `combined_vocab.json`.
2. Combine the `merges.txt` file for both the languages, while taking care that there are no duplicates are being added.
3. There could be different merges which result in the same word. Example, `t he` and `th e`. Take care that only one of the merges is chosen.

Would this work?

I'm concerned if the order of the merges in `merges.txt` is important. Is there an easier solution?

**Comment by Narsil** [comment]
Hi ameet, yes it seems reasonable.

It will be underperforming most likely compared to a fully trained tokenizer (because you don't have the correct statistics) but it should definitely work !

Merges DO have a order, and you don't have access to the likelihood that would enable merging in fusing order, but the length of the generated token could be a naive heuristic.

**Comment by ameet-1997** [comment]
But does the order of the `merges.txt` file matter for the tokenization itself? The tokenization should care only about `vocab.json` right?

**Comment by Narsil** [comment]
The merges order is a priority list, meaning the tokens will be formed in order:

# For sanity, ll =1 , lo = 2, llo =3
Let's say you have 3 merges:
```
l  l 
ll  o
l o
```
H, e, l, l, o   -> H e ll o -> H e llo -> x x 3

But if you have 
```
l  o
l   l
ll  o
```
Then
H e l l o -> H e l lo -> x x x 2

Does that make more sense ?
If you have non overlapping alphabets, you should be mostly fine as the merges order should basically mingle very little,
If you have overlapping alphabets (which you seem to imply), then yes your final merge table might be suboptimal, but it shouldn't be drastically bad either. (It's definitely much faster, than re-gathering datasets and retraining a tokenizer, which might be biased towards one language anyway if your datasets are imbalanced)

**Comment by ameet-1997** [comment]
Thanks for the great answer! I wrote a script to do exactly what you suggested.

``` python
"""
Given two tokenizers, combine them and create a new tokenizer
Usage: python combine_tokenizers.py --tokenizer1 ../config/en/roberta_8 --tokenizer2 ../config/hi/roberta_8 --save_dir ../config/en/en_hi/roberta_8
"""


# Libraries for tokenizer
from pathlib import Path
from tokenizers import ByteLevelBPETokenizer
import argparse
import json
import os
from tqdm import tqdm
from transformers import AutoTokenizer
from timeit import default_timer as timer
import sys

def combine_tokenizers(args):
    # Load both the json files, take the union, and store it
    json1 = json.load(open(os.path.join(args.tokenizer1, 'vocab.json')))
    json2 = json.load(open(os.path.join(args.tokenizer2, 'vocab.json')))

    # Create a new vocabulary
    new_vocab = {}
    idx = 0
    for word in json1.keys():
        if word not in new_vocab.keys():
            new_vocab[word] = idx
            idx += 1

    # Add words from second tokenizer
    for word in json2.keys():
        if word not in new_vocab.keys():
            new_vocab[word] = idx
            idx += 1

    # Make the directory if necessary
    if not os.path.exists(args.save_dir):
        os.makedirs(args.save_dir)

    # Save the vocab
    with open(os.path.join(args.save_dir, 'vocab.json'), 'w') as fp:
        json.dump(new_vocab, fp, ensure_ascii=False)

    # Merge the two merges file. Don't handle duplicates here
    # Concatenate them, but ignore the first line of the second file
    os.system('cat {} > {}'.format(os.path.join(args.tokenizer1, 'merges.txt'), os.path.join(args.save_dir, 'merges.txt')))
    os.system('tail -n +2 -q {} >> {}'.format(os.path.join(args.tokenizer2, 'merges.txt'), os.path.join(args.save_dir, 'merges.txt')))

    # Save other files
    os.system('cp {} {}'.format(os.path.join(args.tokenizer1, 'config.json'), args.save_dir))
    os.system('cp {} {}'.format(os.path.join(args.tokenizer1, 'tokenizer_config.json'), args.save_dir))

    # Instantiate the new tokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.save_dir, use_fast=True)


def main():
    parser = argparse.ArgumentParser()

    # Dataset Arguments
    parser.add_argument("--tokenizer1", type=str, required=True, help="")
    parser.add_argument("--tokenizer2", type=str, required=True, help="")
    parser.add_argument("--save_dir", type=str, required=True, help="")

    args = parser.parse_args()

    combine_tokenizers(args)

if __name__ == '__main__':
    main()

```

**Comment by chris-ha458** [comment]
I'm trying this out ATM. But it seems to result it suboptimal vocabs...
