### ISSUE TITLE
Transformers and tokenizers produce different token ids with same vocab

### ISSUE THREAD

**Issue by R4ZZ3** [huggingface/tokenizers#695]
I have case where I really would like to run BERT model in AWS LAMBDA without using contrainers/EFS but instead use lambda layer for tokenizers. I have onnx part working but default example that I have used uses AutoTokenizers.

I first take model from Autotokenizers and then save it to disk.
Then I used tokenizers to download that
![image](https://user-images.githubusercontent.com/25264037/117180584-fe8d1000-addc-11eb-8156-a1db8f71ae7e.png)

Then I compare vocabularies but there are differences. Why this happens?
![image](https://user-images.githubusercontent.com/25264037/117180093-7b6bba00-addc-11eb-8c23-19c686744662.png)

**Comment by n1t0** [comment]
There should be a `tokenizer.json` file in the folder. You can then do:
```python
from tokenizers import Tokenizer
tokenizer = Tokenizer.from_file("tokenizer.json")
```
I believe the tokenizer should behave exactly as you expect it by doing so.

**Comment by R4ZZ3** [comment]
Thanks @n1t0  
I will try this today

**Comment by R4ZZ3** [comment]
@n1t0  

I found the troublemaker.
By default the BertWordPieceTokenizer had lowercase=True and 
I am using TurkuNLP/bert-base-finnish-cased-v1 so I had to add lowercase=False to the initialization. Now it seems to work

**Comment by n1t0** [comment]
Awesome! Glad you were able to find the culprit. 

I would still advise loading from the `tokenizer.json` file if you can though, as it is the only way to ensure you are using the exact same tokenizer. `vocab.txt` only contains the vocabulary, a lot of components on the tokenizer could be different.

Closing this issue, feel free to reopen if needed!

**Comment by R4ZZ3** [comment]
Which method should produce that file?
I mean if I do this from tokenizers autotokenizer I do not get such file if I am correct.
So what is the correct way to produce that tokenizer.json?

![image](https://user-images.githubusercontent.com/25264037/117407477-4912a780-af17-11eb-9edb-63d17ac4f82f.png)
