### ISSUE TITLE
the order of newly trained vocabulary.

### ISSUE THREAD

**Issue by Jimin9401** [huggingface/tokenizers#697]
![image](https://user-images.githubusercontent.com/41858463/117394574-59378080-af31-11eb-9b45-3d1501dd7b9d.png)

this vocab.txt file is the output  of a model of the customized tokenizer.
I wonder what means "the order of newly trained vocabulary with BertWordpiece tokenizer" without special token.

Is it the order of merges?

Thank you.

**Comment by n1t0** [comment]
The `vocab.txt` file contains each token of the vocabulary, in the order they have been created.

In the `tokenizers` library, we use the same algorithm as BPE to train a WordPiece model. So, for each new merge operation computed during training, we create the associated token if it's not already part of the vocabulary.
