### ISSUE TITLE
How to produce correct tokenizer.json

### ISSUE THREAD

**Issue by R4ZZ3** [huggingface/tokenizers#698]
Reopening.

_Originally posted by @n1t0 in https://github.com/huggingface/tokenizers/issues/695#issuecomment-833700452_

**Comment by R4ZZ3** [comment]
Which method should produce that file?
I mean if I do this from tokenizers autotokenizer I do not get such file if I am correct.
So what is the correct way to produce that tokenizer.json?

**Comment by n1t0** [comment]
Closing this, feel free to reopen if needed

**Comment by EeyoreLee** [comment]
> The latest version of `transformers` should save it by default (maybe only the latest `master`). Otherwise, you can use the parameter `legacy_format=False` in `save_pretrained`

Exactly ! I wanna use tokenizer-cpp which need a `tokenizer.json` but the model folder on HF HUB only has `tokenizer_config.json`  and `vocab.txt`. And I generated the `tokenizer.json` through this approach. Thanks so much mate.
