### ISSUE TITLE
tokenizers.normalizers.Strip can not remove all whitespace characters on the right side of chinese character

### ISSUE THREAD

**Issue by zhenzhenleo** [huggingface/tokenizers#706]
```
from tokenizers import Tokenizer, normalizers
from tokenizers.normalizers import Lowercase, Strip, NFKC

normalizer = normalizers.Sequence([NFKC(), Strip()])

normalizer.normalize_str('  你好asa \n')
# output: '你好asa \n'

normalizer.normalize_str(' hello ADAS \n')
# output: 'hello ADAS'
```

**Comment by Narsil** [comment]
Do you have an example ? 

It's most likely a tricky utf-8 encoding, if we had some way to check your string that would help tremendously.

If you have a full script to replicate that's even better.

**Comment by zhenzhenleo** [comment]
> Do you have an example ?
> 
> It's most likely a tricky utf-8 encoding, if we had some way to check your string that would help tremendously.
> 
> If you have a full script to replicate that's even better.

Ok. I add the code above.
