### ISSUE TITLE
Custom model to train

### ISSUE THREAD

**Issue by karims** [huggingface/tokenizers#710]
I am looking a way to create custom model to train a tokenizer. The available ones are `BPE, Unigram, WordLevel and WordPiece`.

I need it because I want to split text using a regex. Also, I want to start clean slate and not use any pre-trained vocab. If I use any of the above 4 splitting techniques, it won't help me.

I see that there is `Model` and `Trainer` class in Python, but I suppose the implementation is all in Rust. Correct me if I am wrong.

Any solution for this would be helpful. I could not find any example of such.

Thank you.

**Comment by karims** [comment]
I tried to do:

```
from tokenizers.models import Model

class CustomModel(Model):
      ....
```

But it says:

`TypeError: type 'tokenizers.models.Model' is not an acceptable base type`.

I tried to look into custom components [link](https://github.com/huggingface/tokenizers/blob/b24a2fc/bindings/python/examples/custom_components.py), but it doesn't have an example for Model. 

If it is not possible to create custom Model, what is the other way to solve this problem?

**Comment by n1t0** [comment]
You shouldn't need a new model to achieve what you described. I think you should have a look at the documentation, especially:
 - https://huggingface.co/docs/tokenizers/python/latest/quicktour.html
 - https://huggingface.co/docs/tokenizers/python/latest/pipeline.html
After you read these two pages, you should have a better understanding of how you can achieve this with `tokenizers`. Finally there is also a page listing all the available components in the docs, let us know if you don't find what you need!

**Comment by brijow** [comment]
@karims You should be able to split using a regex as shown here:

https://huggingface.co/docs/tokenizers/python/latest/api/reference.html#tokenizers.pre_tokenizers.Split
