### ISSUE TITLE
Addition of word prefix for zero-width splits

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#711]
I'm trying to prefix "words" with some form of special character, i.e. the metaspace '▁' character using the Unigram model, i.e. similar to the `SentencePieceUnigramTokenizer` class. My issue is the `MetaSpace` PreTokenizer replaces whitespace with  '▁'; my pre-tokenization pipeline splits on both characters, i.e. whitespace and punctuation, but also splits between "words" using a PascalCase regex. So simple replacing a character with '▁'  is insufficient, I actually have to pre-tokenize into words and then prepend the SentencePiece '▁'.

Is this possible? Perhaps with a custom PreTokenizer that prepends '▁'  to each input without changing the start/end offsets into the original text?

I could use the `WordPieceTrainer`, the `continuing_subword_prefix` is an alternative (my specific requirement is to identify if a token in a tokenised sequence is the first/last token of a word, but that derives from BPE, not Unigram. I've obtained better results from Unigram.

**Comment by david-waterworth** [comment]
Now that I think about it, the `Metaspace` default does do what I want - provided it's the last PreTokenizer. The `add_prefix_space=True` should add a space to all `words` from the previous step including those created by the Pascal Case split.

**Comment by n1t0** [comment]
Indeed the `Metaspace` should let you do what you want. The only thing to note about this, is that obviously the alignment mapping won't be accurate for the "created" whitespace (ie it won't map to the real whitespace in the original text, but to the first character that follows it).

**Comment by david-waterworth** [comment]
Thanks @n1t0 yes everything works fine except `decode` since it has no way of mapping the '▁' back.

**Comment by david-waterworth** [comment]
@n1t0 yes it does what I wanted thanks. Although I've since discovered `word_ids` which I wasn't aware of, they may be a better option (or at least more tokeniser non-specific), I basically want to be able to reconstruct the original word boundaries from tokens so I can ensure that programmatically generated tags are aligned with words (ie don't start/end on a word-piece).
