### ISSUE TITLE
How to train on pre tokenized values?

### ISSUE THREAD

**Issue by hadaev8** [huggingface/tokenizers#723]
For example i have array like this:
```
[[ 66, 113, 113, 113,  66,  66,  66,  66,  66,  66,  66,  66,  66,
        113,  66,  66,  66,  66,  66,  66,  66,  66,  66,  66,  66,  66,
         82,  66,  66,  66,  66],
       [ 57, 263,  57,  57, 263,  57, 263,  57,  57,  57,  57, 263, 263,
         57,  57,  57, 263,  57,  57, 263, 263,  57, 263,  57,  57,  57,
         57,  57,  57,  57,  57]]
```
How should I train WordPiece model on it?

Tried it like this
```
from tokenizers import Tokenizer, models, pre_tokenizers
from tokenizers.processors import TemplateProcessing

tokenizer = Tokenizer(models.WordPiece())
trainer = tokenizer.model.get_trainer()
trainer.vocab_size = 4

tokenizer.train_from_iterator(data, trainer=trainer)
```
But got error
```TypeError: Can't convert 66 to PyString```

**Comment by hadaev8** [comment]
Converting tokens to string type doesnt help too.

**Comment by Narsil** [comment]
Are these bytes ? I am unsure what you're trying to do.

Usually trainers expect strings, but only an iterator of strings, not a list of list of strings for instance.
What is the error when using strings?

**Comment by hadaev8** [comment]
@Narsil 
This is int values, some tokens.
I want to use wordpiece/bpe to merge it into bigger tokens to reduce seq len.
If I convert ints to strings, the algorithm runs without error but does not work as expected.

**Comment by Narsil** [comment]
What is happening ?

This crate is not designed to do what you are trying to do, so I fear that running your own code is the best course for you.

**Comment by hadaev8** [comment]
@Narsil 
```
import numpy as np
features = (np.random.rand(4, 12800)*100).astype('int').astype('str')

from tokenizers import Tokenizer, models
tokenizer = Tokenizer(models.BPE())
trainer = tokenizer.model.get_trainer()
trainer.vocab_size = 1000
tokenizer.train_from_iterator(features, trainer=trainer)
```

This is my code, it learns only to split tokens. Like 66 to 6+6.
While I need basic tokens to be unsplitted.

So, what kind of code I need to train tokenizer on my data?

I have a hacky idea to replace each token of digits with a single unique string symbol.
Kind of stupid tho.

**Comment by Narsil** [comment]
Hmm, the core problem is that you're trying to feed data (ints) that are NOT what the core algorithm was meant to ingest (strings).

I don't really think there's an easy way to solve you're issue. Ofc it could probably be done, but sorry I don't want to give too much thought about it, it's too far off the original intent of this library.

Closing this. If you find a solution, please do share it here as it might help others in the future.
