### ISSUE TITLE
AttributeError: type object 'tokenizers.models.Unigram' has no attribute 'from_file'

### ISSUE THREAD

**Issue by nikitakit** [huggingface/tokenizers#729]
The Unigram model type doesn't implement `from_file`. Interestingly it does have a `save` method, but no easy way to re-load the saved data. For reference, the constructor for Unigram accepts a vocab list and and unk token id, not a filename.

**Comment by Narsil** [comment]
Hi, it is working as intended, as we try to push `save` and `from_file` to be `Tokenizer` function (Unigram is only the model part of the `Tokenizer`). Also the API is uniform no matter the model where `BPE` still has to maintain loading from 2 files etc..

If you `save` the full tokenizer, everything should work correctly: https://huggingface.co/docs/tokenizers/python/latest/pipeline.html

Does this help ?
