### ISSUE TITLE
Decoding to string

### ISSUE THREAD

**Issue by davidstap** [huggingface/tokenizers#73]
Hi, thanks for this awesome library!

I want to decode BPE back to *actual* text, so that I can calculate BLEU scores. When I use the tokenizer.decoder, I get a string without any whitespace. I understand I can use a `pre_tokenizer` to get whitespaces, but in that case the decoded output would be `i can feel the mag i c , can you ?` (or something similar, depending on the BPE model). How do I get the actual text through decoding, so that I can calculate BLEU scores like I normally would?

```
from tokenizers import Tokenizer, models, pre_tokenizers, decoders

# Load a BPE Model
vocab = "./scripts/vocab.json"
merges = "./path/to/merges.txt"
bpe = models.BPE.from_files(vocab, merges)

# Initialize a tokenizer
tokenizer = Tokenizer(bpe)

# Customize pre-tokenization and decoding
tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel.new(add_prefix_space=True)
tokenizer.decoder = decoders.ByteLevel.new()

# And then encode:
encoded = tokenizer.encode("i can feel the magic, can you?")

decoded = tokenizer.decode(encoded.ids)
print(encoded)
print(decoded)
>>> ['i', 'can', 'feel', 'the', 'mag', 'i', 'c', ',', 'can', 'you', '?']
>>> icanfeelthemagic,canyou?

```

**Comment by mfuntowicz** [comment]
Hi @davidstap 

Can you try with the high-level `ByteLevelBPETokenizer` ?

```python
>>> from tokenizers import ByteLevelBPETokenizer
>>> t = ByteLevelBPETokenizer('bpe-bytelevel-vocab.json', 'bpe-bytelevel-merges.txt')
>>> e = t.encode("i can feel the magic, can you?")
>>> t.decode(e.ids)
'i can feel the magic, can you?'
```

Let us know if it works :).

**Comment by davidstap** [comment]
That works as expected, thanks :-)

I still do not understand why the behaviour for BPETokenizer would be different. Is there any way to get the same behaviour for BPETokenizer (i.e., not the ByteLevel one)? I am trying to replicate a paper that uses BPE.

**Comment by mfuntowicz** [comment]
Glad it worked ! 

Sure it's possible but you might have to retrain your tokenizers. 

```python
from tokenizers import BPETokenizer

# Create an empty tokenizers
tokenizer = BPETokenizer()

# Train it
tokenizer.train(
    files,
    vocab_size=30000,
    min_frequency=2,
    special_tokens=["<unk>", "<pad>", "<cls>", "<sep>"],
    limit_alphabet=1000,
    show_progress: bool=True
)

# Save the tokenizer model
tokenizer.save(...)
```

Then you might be able to use it through `tokenizer = BPETokenizer(saved_model_path)`

**Comment by davidstap** [comment]
Thanks for your reply. To clarify, I did train a BPETokenizer, but the decoded result is incorrect. To reproduce:

```python
>>> # Initialize tokenizer
>>> tokenizer = BPETokenizer()

>>> # Train tokenizer
>>> tokenizer.train(files=files,
                    vocab_size=32000,
                    min_frequency=2,
                    special_tokens=["<unk>", "<pad>", "<bos>", "<eos>"],
                    limit_alphabet=1000)

>>> # Save vocabulary and merges
>>> tokenizer.save(...)
>>> e = tokenizer.encode("i can feel the magic, can you?")
>>> d = tokenizer.decode(e.ids)
>>> print(e.tokens)
>>> print(d)
['i', 'can', 'feel', 'the', 'mag', 'i', 'c', ',', 'can', 'you', '?']
icanfeelthemagic,canyou?
```

**Comment by davidstap** [comment]
Hi, can you reproduce? How can I fix the error? :-)

**Comment by n1t0** [comment]
Hi @davidstap!
I just released a new version of the Python `tokenizers` package that should fix this problem. This was happening because the trained model didn't pass some of the configurations back to the Tokenizer after training. Also, there was another discrepancy in the pre-tokenization phase, which has been fixed too.
Can you `pip install tokenizers` the `2.0.0` version and let us know how it goes?

**Comment by davidstap** [comment]
The problem is solved using the newer version. Thank you very much!
