### ISSUE TITLE
How to train a SentencePiece tokenizer?

### ISSUE THREAD

**Issue by mralexis1** [huggingface/tokenizers#732]
The trainer [here](https://huggingface.co/docs/tokenizers/python/master/api/reference.html#module-tokenizers.trainers) doesn't seem to have a `SentencePieceTrainer` and there is no instruction on how to train a SPM in the doc. Could you explain how we could use the tokenizers package to train a SPM, similar to the one in XLM-roberta? Thnks!

**Comment by Narsil** [comment]
SentencePiece is the name of the google program. I think you are looking for UnigramTrainer, unigram is the name of the algorithm which is indeed in the docs.

As to how to train, I recommend reading the docs (for instance: https://huggingface.co/docs/tokenizers/python/latest/tutorials/python/training_from_memory.html), inspecting the xlm-roberta itself (to see the various components).

Does that help ?

**Comment by mralexis1** [comment]
Thanks @Narsil ! This is helpful. 
Could you provide a pointer on the implementation of tokenizer for XLM-roberta or bart using `tokenizers`? I only saw [the one](https://github.com/huggingface/transformers/blob/bc6f51e53925e118f04a76f9a59a3d16fc9684a2/src/transformers/models/xlm_roberta/tokenization_xlm_roberta.py#L55) in `transformers`.

**Comment by Narsil** [comment]
Hi, `tokenizers` is different from `transformers`.

`tokenizers` does not know about any architecture like roberta, bart or others.
It uses lower level elements, which combined together will produce tokenizers compatible for roberta, bart and others.

```
from transformers import AutoTokenizer

tok = AutoTokenizer.from_pretrained("xlm-roberta-large-finetuned-conll03-english")
tok._tokenizer.save("tokenizer.json")
# Look at this file to see how it is architectured
```

**Comment by mralexis1** [comment]
Thanks, @Narsil !
