### ISSUE TITLE
Update crates.io

### ISSUE THREAD

**Issue by jafioti** [huggingface/tokenizers#738]
Please please please update your crates.io crate which hasn't been updated in over a year. I, along with many others I'm sure have had to download this github repo to use in our own projects, or use the github feature of cargo, because I needed features present in the github version but not in the older crates.io version.

So pretty please give the people an update!

**Comment by jafioti** [comment]
Even a beta version would work, if you feel that it's not ready for a full release.

**Comment by n1t0** [comment]
We released `0.11.0` on crates.io. Sorry it took so long!
