### ISSUE TITLE
Publish wheels for arm64?

### ISSUE THREAD

**Issue by etiennedi** [huggingface/tokenizers#740]
Hello all,

in [Weaviate](https://github.com/semi-technologies/weaviate), we're using `transformers` and in turn `tokenizers` when using transformers-based inference. We've [recently](https://github.com/semi-technologies/weaviate/releases/tag/v1.4.0) started supporting `arm64` architectures - mostly so that M1 Mac users can use Weaviate without any restrictions.

Using transformers/tokenizers works great on `arm64`, but there is one major difference to using the `amd64` builds. The `tokenizers` library can no longer be downloaded as a pre-built Python wheel. But instead, it will be built from sources on a `pip install`. After installing a rust compiler in the respective Dockerfile, it compiles successfully. But since we're using QEMU emulation to build our images on non-arm64 architecture, the process is very slow:

<img width="795" alt="Screenshot 2021-06-17 at 09 09 47" src="https://user-images.githubusercontent.com/8974479/122349444-8de52180-cf4c-11eb-8434-fbfb4c089bc5.png">

On Travis CI typical build times went up from 10min to over 60min. There are absolutely ways of how we can optimize this on our side: For example, we could compile it once and push a base image which we use in subsequent builds, etc. But that solution would only help us and not others.

So if possible and not too much effort, it would be great if you could offer the same pre-built wheel that you have for `linux/amd64` also for `linux/arm64`. (Note: I was talking about `darwin` above, but since Docker just uses `linux/arm64` arch on `darwin/arm64`, `linux/arm64` is all we - and other Docker users - would need).

Thanks!
Etienne

**Comment by n1t0** [comment]
Hello @etiennedi 

I'd love to add support for M1 Mac users but unfortunately, I didn't get a chance to dig how to do it with Github actions yet. On top of that, I don't have an M1 Mac to test this out. Would you be willing to help me out?

We are building wheels for manylinux2014-aarch64 but I guess it doesn't work on macOS, right?

**Comment by etiennedi** [comment]
Thanks for the quick response. Here's something that you can try on any AMD/Intel-based Mac/PC on macOS or Linux (`amd64`) using the latest Docker versions:

```
# Dockerfile
FROM python:3.9-slim-buster
RUN pip3 install tokenizers
```

And try to build it with 
```
docker buildx build --platform=linux/arm64 .
```

In this case I don't think it's able to use the `manylinux2014-aarch64` wheel (not sure how/when that decision is made, maybe the above docker setup can help in finding this out), because for me it fails with an error message of a missing Rust compiler.

So I'm currently installing a Rust compiler like so:

```
# Dockerfile
FROM python:3.9-slim-buster
RUN apt-get update && apt-get -y install curl build-essential
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="$PATH:/root/.cargo/bin"
RUN pip3 install tokenizers
```

Then it builds fine. There's also a good chance that my base image `python:3.9-slim-buster` is somehow the issue of why it can't use the existing wheel. If there are any kind of commands that I can run to see how Python decides for whether a wheel fits or doesn't fit, let me know.

> I'd love to add support for M1 Mac users but unfortunately, I didn't get a chance to dig how to do it with Github actions yet

For me, "generic" `linux/arm64` would be absolutely sufficient, since that works great on M1 Macs with Docker.

**Comment by n1t0** [comment]
I just saw that we didn't upload the aarch64 wheels for the latest version of `tokenizers` because the job lasted too long (6h limit). You could try to install `pip3 install tokenizers==0.10.2` to see if it would work with this one.

Also, you can run `pip debug --verbose` to see the compatible wheels and check if `manylinux2014_aarch64` could work for you.

**Comment by etiennedi** [comment]
Thanks, I'll give those a shot and come back to you.

**Comment by n1t0** [comment]
@etiennedi Did you get a chance to test this and get it running?

**Comment by etiennedi** [comment]
Hey @n1t0, I did indeed downgrade to the version you mentioned and no longer have to compile it myself. Thanks for the suggestion. Please let us know when a newer version is published with the same `manylinux2014_aarch64` wheels again, so we can upgrade accordingly.
