### ISSUE TITLE
ByteLevelBPETokenizer does not merge as much as it could

### ISSUE THREAD

**Issue by JellePiepenbrock** [huggingface/tokenizers#745]
Hello, 

I have been using ByteLevelBPETokenizer to tokenize my data. Now, I have noticed that it does not merge certain things. For example, spaces and underscores seem to break the tokens in half, no matter how often the "a_1" or something similar occurs. Other things in the data, such as "# l" (with a space in between) also occur a lot, but it does not merge these into a single token.

Why does this behaviour occur and can it be turned off? Note that certain full words, of > 5 alphabet characters, do get turned into 1 token.

**Comment by david-waterworth** [comment]
I suspect what's happening is the tokenizer you're using has a pre-tokenizer that splits on whitespace and _ (and potentially others). Basically the statistical model only applies to the "words" which are generated by the deterministic pre-tokenisation pipeline. So if you want your BPE model to include spaces or underscores you need to ensure your pre-tokenisation hasn't removed them.
