### ISSUE TITLE
WordLevel does not output [UNK] token

### ISSUE THREAD

**Issue by dringel** [huggingface/tokenizers#746]
1. I trained a WordLevel tokenizer from scratch on the first few lines of the "Zen of Python".
2. I then encoded a sentence that included two words that did not appear in the training data.
3. When I output the tokens, the original words instead of the special [UNK] token appear. Why?

Unknown words: "and", "🤗"
Encode: "sparse is complex and 🤗 beautiful"
Token ids: [1, 16, 6, 9, 0, 0, 11, 2]
Tokens: ['[CLS]', 'sparse', 'is', 'complex', 'and', '🤗', 'beautiful', '[SEP]']
Decode: 'sparse is complex beautiful'

I am using tokenizers 0.10.3 on Python 3.8.5 in Jupyter notebook on MacOS 10.15.7

Here is my code:

INPUT
```
from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.processors import TemplateProcessing
from tokenizers.trainers import WordLevelTrainer

# Tokenizer-Model
bert_tokenizer = Tokenizer(WordLevel(unk_token="[UNK]"))

# Pre-tokenizer
bert_tokenizer.pre_tokenizer = Whitespace()

# Post-processor
bert_tokenizer.post_processor = TemplateProcessing(
    single="[CLS] $A [SEP]",
    pair="[CLS] $A [SEP] $B:1 [SEP]:1",
    special_tokens=[
        ("[CLS]", 1),
        ("[SEP]", 2),
    ],
)

# Define Trainer
trainer = WordLevelTrainer(
     min_frequency=0, show_progress=True, special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"]
)

# Create Data
data = [
    "beautiful is better than ugly."
    "explicit is better than implicit."
    "simple is better than complex."
    "complex is better than complicated."
    "flat is better than nested."
    "sparse is better than dense."
    "readability counts."
]

# Train Tokenizer
bert_tokenizer.train_from_iterator(data, trainer)

# Encode a text: Include 2 unknown words: "and" "🤗" (i.e., words not in training data)
test = bert_tokenizer.encode("sparse is complex and 🤗 beautiful")

# Show token ids: Returns 0 for unknown words
print(test.ids)

# Show Tokens: Instead of the expected special "[UNK]" token for unknown words, returns actual words!
print(test.tokens)

# Decode into sentence: Correct: unknown words are missing
bert_tokenizer.decode(test.ids) 
```

OUTPUT:

[1, 16, 6, 9, 0, 0, 11, 2]
['[CLS]', 'sparse', 'is', 'complex', 'and', '🤗', 'beautiful', '[SEP]']
'sparse is complex beautiful'

**Comment by AguirreNicolas** [comment]
Did you solve this? I'm facing the same ...

**Comment by LautaroEst** [comment]
Any solutions? I can't understand why is implemented this way...

**Comment by mishig25** [comment]
@dringel @AguirreNicolas @LautaroEst thanks for notifying about this issue 😊
this problem should be gone on the next release
