### ISSUE TITLE
When we use the tokenizer from the uploaded model, it differs greatly than when we use the tokenizer and model locally.

### ISSUE THREAD

**Issue by sami10644** [huggingface/tokenizers#749]
We attempted every imaginable method. We followed the uploading instructions precisely. Several times, files are deleted and re-uploaded. It functions flawlessly on a local level! When we download it after uploading, we encounter this strange difficulty. Locally, the tokenizer appears to be okay and the model functions properly, but when we submitted the same tokenizer and model to huggingface, the downloaded tokenizer does not function properly.

**Comment by Narsil** [comment]
Do you mind sharing how you solved your issue for future readers ?

Thanks.
