### ISSUE TITLE
Assist! Why does it occur? does so as a result of tokenizers or the vocabulary text

### ISSUE THREAD

**Issue by sami10644** [huggingface/tokenizers#750]
The weights are fine because theres no issue around the model ! We think the problem is around the tokenizer ! We attempted every imaginable method. We followed the uploading instructions precisely. Several times, files are deleted and re-uploaded. It functions flawlessly on a local level! When we download it after uploading, we encounter this strange difficulty. Locally, the tokenizer appears to be okay and the model functions properly, but when we submitted the same tokenizer and model to huggingface, the downloaded tokenizer does not function properly.
We found a warning . Please Check it out :
to upload token files, it’s worning as
"Saving vocabulary to bert-base-test/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
"

**Comment by Narsil** [comment]
Do you mind adding a bit more context ?

Do you have reproducible code we can run to check what is the issue ?

The warning you are supplying seems to indicate your tokenizer has an issue that's is most likely to corrupt things, which could explain away your problem, but without being able to reproduce or see stacktraces it's quite hard to provide assistance.

**Comment by sami10644** [comment]
Handled the issue !
