### ISSUE TITLE
wrong bpe results for words with strange letters

### ISSUE THREAD

**Issue by fake-warrior8** [huggingface/tokenizers#751]
My dataset has some strange letters, then I got wrong bpe results. Here are some examples.
Input: ænəld͡ʒizɪəz  ænəlɪtəkəl        
BPE result: ĠÃ¦n ÉĻl d Í¡ ÊĴi z Éª ÉĻz  ĠÃ¦n ÉĻl Éªt ÉĻk ÉĻl

**Comment by n1t0** [comment]
I bet you are using a `ByteLevelBPETokenizer` (or any other kind of BPE with a `ByteLevel` pre-tokenizer), in which case the results are totally expected. Please read this pinned issue for more information: https://github.com/huggingface/tokenizers/issues/203

**Comment by fake-warrior8** [comment]
> I bet you are using a `ByteLevelBPETokenizer` (or any other kind of BPE with a `ByteLevel` pre-tokenizer), in which case the results are totally expected. Please read this pinned issue for more information: #203

Thanks for your reply. Now I know that my strange bpe results are caused by the Unicode code conversion preprocessing of the bpe package, then the results in smaller vocabularies, that won't ever need an "unknown" token.

However, in my scenario, I don't need this Unicode code conversion. are there some settings to close this operation?

**Comment by fake-warrior8** [comment]
> > I bet you are using a `ByteLevelBPETokenizer` (or any other kind of BPE with a `ByteLevel` pre-tokenizer), in which case the results are totally expected. Please read this pinned issue for more information: #203
> 
> Thanks for your reply. Now I know that my strange bpe results are caused by the Unicode code conversion preprocessing of the bpe package, then the results in smaller vocabularies, that won't ever need an "unknown" token.
> 
> However, in my scenario, I don't need this Unicode code conversion. are there some settings to close this operation?

I found this problem can be solved by the offsets message of the tokenized result. But now I found there are are some 'encoded.tokens' results start with single 'Ġ', I don't know what's the tokenized difference between single 'Ġ' start and compound  start including 'Ġ' with other tokens. Here are some examples.
single 'Ġ' start: Ġ eÉª eÉª eÉªv i
compound start including 'Ġ': ĠÉĻb Ã¦n Éªk
