### ISSUE TITLE
Some basic doubts

### ISSUE THREAD

**Issue by Chokerino** [huggingface/tokenizers#755]
Hello,

I want to train an encoder on a custom dataset of sequences. The data is not of words but strings, where each alphabet is consider the words so by tokenizer, needs to be just `list(string)`. I just wanted to know what is the purpose of train, test and validation sets for tokenizing because for my case its pretty much useless. Also, is the dataset for tokenizing the same as the dataset used for training the model?

**Comment by Narsil** [comment]
Hi @Chokerino 

You can use every split to train your tokenizer without any issue, or even a larger unanottated sample.
The idea of a tokenizer is to represent best as possible a language, and is not tied to your model (there is no metric for `tokenizer quality`)

Not sure I fully answered your question feel free to reopen.
