### ISSUE TITLE
 How to use the pre training model offline?

### ISSUE THREAD

**Issue by dongteng** [huggingface/tokenizers#757]
In fact I've downloaded the pre training model I really want to use. How to use it?
##
model = SentenceTransformer('/dataset/BERT/paraphrase-multilingual-mpnet-base-v2')
##
then the error:
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 1 column 317718

**Comment by Jiaye-Temp-Datryx** [comment]
The same error and cause.
I solved this by installing sentencepiece == 0.1.96 and tokenizers == 0.10.3, it seems like some kind of version issues.
