### ISSUE TITLE
ByteLevelBPETokenizer to sentencepiece.model

### ISSUE THREAD

**Issue by cakiki** [huggingface/tokenizers#759]
Is there any possibility (no matter how hacky) to convert a huggingface tokenizer (ByteLevelBPETokenizer in this instance) to a sentencepiece.model protobuf file? 

**Context**:
I would like to include the tokenizer as a layer in my TensorFlow model before serving it, and as such would like to load a pretrained huggingface tokenizer into a [`tensorflow_text.SentencepieceTokenizer`](https://www.tensorflow.org/text/api_docs/python/text/SentencepieceTokenizer) object.

**Comment by Narsil** [comment]
Unfortunately nothing exists yet.

But the data should be similar. 

You're very unlikely to achieve 1-1 parity because SPM uses a non standard NFT/NFKC for standardisation (differences are minute but do exist)

**Comment by Narsil** [comment]
Also ByteLevel support in SPM is experimental if I remember correctly.

**Comment by cakiki** [comment]
Thank you for the feedback @Narsil !

**Comment by versae** [comment]
Just found myself needing a similar conversion from ByteLevelBPETokenizer to SPM. Were you able to get around it, @cakiki ?

**Comment by cakiki** [comment]
Sadly not @versae, I don't think that's possible. What's your use case?

**Comment by OhadRubin** [comment]
@versae can you share it?

**Comment by versae** [comment]
@OhadRubin not sure what language are you after, but all the custom spm tokenizerts we used with T5X are now here: https://huggingface.co/NbAiLab/nb-tokenizers-spm. I'll add some documentation soon.
