### ISSUE TITLE
Do I need all the corpura to train the tokenizer?

### ISSUE THREAD

**Issue by allanj** [huggingface/tokenizers#781]
Just a practical question, if I need to train a language model using hundreds of GB of text, do I still need to use the same corpus to train the tokenizer?

Wondering what is the common practice here.

**Comment by Narsil** [comment]
Depending on language you could get away with less, depends how smooth is your dataset.

Tokenizers are extracting much shallower representations of the language so training on a fraction of the full dataset is definitely reasonable. Some models now even stick at raw bytes (byT5 for instance). 

Ofc, more data is always better, but returns are diminishing more rapidly for tokenizers than for models.

Hope that helps.

**Comment by allanj** [comment]
Totally agree. But not sure what is the common practice, I didn't find any papers mentioning their setting.
