### ISSUE TITLE
Tokenizer not adding "BOS", "EOS" tokens

### ISSUE THREAD

**Issue by brand17** [huggingface/tokenizers#785]
I trained my tokenizer with this code:

```
from tokenizers import Tokenizer, trainers
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import Whitespace
tok = Tokenizer(BPE())
trainer = trainers.BpeTrainer(special_tokens=["[BOS]", "[PAD]", "[EOS]", "[UNK]"])
tok.pre_tokenizer = Whitespace()
def it():
  for t in ['one', 'two', 'three']:
    yield t

tok.train_from_iterator(it(), trainer)
from transformers import PreTrainedTokenizerFast
tok = PreTrainedTokenizerFast(
  tokenizer_object=tok,
  bos_token='[BOS]', pad_token='[PAD]', eos_token='[EOS]',
  unk_token='[UNK]', cls_token='[BOS]', sep_token='[EOS]'
  )
output = tok('hello world', add_special_tokens=True)

```
But the tokenizer doesn't add special tokens ("BOS", "EOS") to the output. Should I do it manually ?

**Comment by Narsil** [comment]
You're lacking a TemplatePostProcessor I think: https://huggingface.co/docs/tokenizers/python/latest/api/reference.html?highlight=template#tokenizers.processors.TemplateProcessing

Basically your tokenizer knows that these tokens exist, but you need to specify how to add them systematically.
`sequence_pair` is for encoder_decoder models, feel free to ignore in your use case.
