### ISSUE TITLE
Segmentations of special tokens

### ISSUE THREAD

**Issue by prise6** [huggingface/tokenizers#787]
SentencePiece algorithm introduced two types of "special tokens" : user defined and control symbols. Difference is that control symbols are segmented during tokenization and they have ids associated too. Here is the motivation : [special tokens doc](https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md)

The idea is to prevent user from using special tokens (like SEP, CLS, ...). 

Is this a feature you think of or will introduce ?

Thanks.

**Comment by Narsil** [comment]
Can't vouch for everyone, but I don't think it's on the roadmap.
Most users seem to actually want to parse correctly those special tokens.
If you want to *not* parse some of these, it's as simple as using a new special tokens (like [S], {s} or something even more clever with odd unicode)

**Comment by prise6** [comment]
Thank you for you answer.
I can't see how you solution would work. I mean, let's say i have a class special token: {cls} (or whatever it is). 
1. I want my tokenizer to associate a new id to the segment "{cls}" because you need it later (for token classification for exemple).
2. But I want also my tokenizer to parse this sentence "you need to add {cls}" with this following segmentation ['you', '_need', '_to', '_add', '_{', 'cls', '}'] for example.

My point is that it's only in post processing that i want to add special tokens. Maybe it doesn't matter haha.

**Comment by Narsil** [comment]
In practice it shouldn't matter, if you use a rarely used enough, it won't be seen in your dataset (`{cls}` is likely to be encountered but `[____________CLASS______________]` much less :)

**Comment by prise6** [comment]
Okay i see your point. But even if `[______CLASS______]` won't be in my training dataset. If i add it as a special token, it won't be parsed.
It's more a bias that final user can introduce when they use the model. Equivalent to an "sql injection" to me. But anyway, very theoretical ! I appreciate the time you give to my issue.
