### ISSUE TITLE
When is the next crates.io release planned?

### ISSUE THREAD

**Issue by sweinbach** [huggingface/tokenizers#788]
I am missing the function Tokenizer::from_file() (https://github.com/huggingface/tokenizers/blob/e7dd6436dd4a4ffd9e8a4f110ca68e6a38677cb6/tokenizers/src/tokenizer/mod.rs#L395) in the version available on crates.io. Do you have an update planned?

**Comment by n1t0** [comment]
We released a new `0.11.0` version on crates.io!

**Comment by sweinbach** [comment]
Thank you!
