### ISSUE TITLE
index of sub-tokens after tokenization

### ISSUE THREAD

**Issue by fatihbeyhan** [huggingface/tokenizers#797]
Hello,

I am trying to find if there is any way to get subtoken information after tokenization. I can think of many ways to do it manually but I am curious about whether there is built-in parameter that I can set and make my tokenizer return these. I already checked the parameters but none of them worked. So, I am here to see if anyone know something like that.

Example:

for BERT:
lets say tokens are these >> `["[CLS]", “my”, “token”, “##ized”, “words”, “!”, “[SEP]”, “[PAD]”]`
what I want >> `[0, 0, 0, 1, 0, 0, 0, 0]`

for RoBERTa:
lets say tokens are these >> `[’<s>’, ‘my’, ‘Ġtoken’, ‘ized’, ‘Ġwords’, ‘!’, ‘</s>’, “[PAD]”]`
what I want >> `[0, 0, 0, 1, 0, 0, 0, 0]`

If I implement a function to return these, it will be rule based and model dependent since they use different ways to tokenize.

**WHY I NEED IT:
I am trying to shape my dataset for token classification, hence, I need subtoken and special token information. There is a parameter for special tokens but not for subtoken.

**Comment by Narsil** [comment]
I think you are looking for `.words`:

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
tokenizer._tokenizer.encode("This is a tokenized").word_ids
# [None, 0, 1, 2, 3, 3, None]
```

Would that work for you ? Be careful though, words (or sub-tokens) is an ill defined concept on a lot of tokenizers so it won't always work (bert defines words so you should be good to go, roberta does not, so expect unexpected results)

**Comment by fatihbeyhan** [comment]
Yeah I think this my do the job. It seems like it works for RoBERTa and ALBERT, too. I am pretty surprised about how come there is not an easier way to get sub-token info for each model tho.

Thank you!

**Comment by Narsil** [comment]
Again, `sub-token` does not mean anything for a lot of tokenizers.
And if you look closely enough, words are ill defined in English too actually (space separated items is not quite enough, but that's if you dive deep, on the surface it might work good enough).
