### ISSUE TITLE
tokenizer decode not joining words with continuing_subword_prefix

### ISSUE THREAD

**Issue by wei-ann-Github** [huggingface/tokenizers#802]
Hi,

I trained a tokenizer using BPE using the following code on tokenizers.\_\_version\_\_ = '0.10.3':
```
tokenizer = Tokenizer(BPE(unk_token="[UNK]", continuing_subword_prefix="##"))
tokenizer.normalizer = normalizers.Sequence([NFD(), Lowercase(), StripAccents()])
tokenizer.pre_tokenizer = Whitespace()
tokenizer.post_processor = TemplateProcessing(
        single="[CLS] $A [SEP]",
        pair="[CLS] $A [SEP] $B:1 [SEP]:1",
        special_tokens=[
            ("[CLS]", 1),
            ("[SEP]", 2),
        ],
)
trainer = BpeTrainer(
        vocab_size=vocab_size, special_tokens=["[UNK]", "[CLS]", "[SEP]",
                                               "[PAD]", "[MASK]"],
        continuing_subword_prefix='##',
)
tokenizer.train(files, trainer=trainer)
tokenizer.save(tokenizer_filename)
```

I loaded it using the following code:
```
from transformers import PreTrainedTokenizerFast

tokenizer = PreTrainedTokenizerFast(tokenizer_file=tokenizer_filename)
tokenizer.add_special_tokens({'pad_token': '[PAD]',
                                                'bos_token': '[CLS]',
                                                'eos_token': '[SEP]',
                                               })
```

Then I tried to decode the output_ids using
`tokenizer.decode(output_ids, clean_up_tokenization_spaces=True, skip_special_tokens=True)`
where 
`output_ids = [1, 3492, 3492, 3492, 1805, 1805, 1805, 3427, 3427, 3427, 2] `

The result of the decoding returns the text with the continuing_subword_prefix "##" e.g. "me me me ##i ##i ##i ben ben ben"
but I expected it to be "me me meiii ben ben ben", with the subword prefix removed and joined with previous subword.

May I know if I have missed out anything that's why that continuing subword prefix are not removed?

Thank you!

**Comment by abelfodil** [comment]
I use the WordPiece decoder to fix this issue:
```
from tokenizers.decoders import WordPiece
...
tokenizer.decoder = WordPiece()
```

**Comment by vivek-rd** [comment]
Are there any plans to fix this issue?
