### ISSUE TITLE
Offsets is not right for Chinese language sentences tokenization!

### ISSUE THREAD

**Issue by jia-zhuang** [huggingface/tokenizers#81]
```python
txt = '今天天气很好'
tokened = tokenizer.encode(txt)
for token, offset in zip(tokened.tokens, tokened.offsets):
    print(token, offset)

# output
[CLS] (0, 0)
今 (1, 2)
天 (4, 5)
天 (7, 8)
气 (10, 11)
很 (13, 14)
好 (16, 17)
[SEP] (0, 0)
```

**Comment by n1t0** [comment]
Hi @jia-zhuang. The offsets you see actually represent the position in the normalized string.
You can see the normalized string by printing `tokened.normalized_str`and the original one by printing `tokens.original_str`. Both these fields are actually instances of a class called `IndexableString` that you can index using the given offsets. 
So `tokened.normalized_str[tokened.offsets[1]]` and `tokened.original_str[tokened.offsets[1]]` should both give you the same result.
Does it make sense?

**Comment by jia-zhuang** [comment]
Hi @n1t0, Thanks for your replay! I've understand you point. But I still have some questions. I'm doing sequence labeling using "BIOES" system, for example:
```python
txt = 'Hello Timmy！你去过北京天安门吗？'
label = '天安门'  # index of label is (18, 21)

# as below
Hello, O, (0,5)
Timmy, O, (6,11)
！, O, (11,12)
你, O, (13,14)
去, O, (14,15)
过, O, (15,16)
北, O, (16,17)
京, O, (17,18)
天, B, (18,19)
安, I, (19,20)
门, I, (20,21)
吗, O, (21,22)
？, O, (22,23)
```

After I do tokenize, the index of char in original_str has changed:

```python
for token, offset in zip(tokened.tokens, tokened.offsets):
    print(token, offset)

# output
[CLS] (0, 0)
hello (0, 5)
tim (6, 9)
##my (9, 11)
! (11, 12)
你 (14, 15)
去 (17, 18)
过 (20, 21)
北 (23, 24)
京 (26, 27)
天 (29, 30)
安 (32, 33)
门 (35, 36)
吗 (38, 39)
？ (40, 41)
[SEP] (0, 0)
```
index for English char is ok, but for Chinese char has changed. I can not use index to locate the position of labels.

for example, from token "tim" ->(6, 9) and token "##my" -> (9, 11), I can know i't label is 'O'. But "天" -> (29, 30) is different from original "天"->(18, 19).

So, what is the right way to use tokenized offsets to help to prepare data for sequence labeling task?

**Comment by kzimmer-bah** [comment]
I agree with @jia-zhuang. Being able to reference back to the original string from the tokenization is a great feature for BIO labeling. However the way the offsets currently work, they are not suited for referencing labels that correspond to tokens. 

In my usecase I have an array containing a label for each character in my original string. I wish to use the offsets from the tokenization to reference slices of this array. This may be slightly different from @jia-zhuang's usecase but suffers from a similar issue.

I'm not sure if there is an easy way to map offsets from the normalized string back to the original string or not but that would be a great addition.

**Comment by jia-zhuang** [comment]
@kzimmer-bah there is a slow but easy way, you can reference the code in https://github.com/huggingface/transformers/blob/master/examples/utils_ner.py at line 111~117. It cut the sentence to words, and tokenize each words. If your dataset is not very large, you can use this way.

**Comment by n1t0** [comment]
Hey @jia-zhuang! You should now be able to do what you wanted to do, using the new `v0.3.0`.
You can access the original offsets using `tokened.original_str.offsets[tokened.offsets[1]]`. Let me know how it goes!

**Comment by jia-zhuang** [comment]
Hi @n1t0, big thank your for your excellent work, I've just test this feature and exactly what I want! Buy the way, the right format of using is `tokened.original_str.offsets(tokened.offsets[1])`, thanks again!
