### ISSUE TITLE
encoding issues with ByteLevelBPETokenizer

### ISSUE THREAD

**Issue by glample** [huggingface/tokenizers#813]
Hi,

I followed the instructions of:
https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/train_with_datasets.py

However, when I try to encode tokens that do not exist in the training set ("I can 嗎 feel ₉the magic, can you?") I observe unexpected encoding issues, such as:

![image](https://user-images.githubusercontent.com/8885556/136384399-e792dd24-ef5d-473e-b47f-570830194048.png)

Any ideas why?

Thank you

Note: encoding and decoding the same input sentence with `tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")` does not give me this issue

**Comment by glample** [comment]
Make sense, thank you :)

I think I have a last question regarding the initial alphabet. How should I proceed if I wanted to tell the byte-BPE tokenizer to never split at byte level some specific UTF-8 characters? For instance, I tried to provide `special_tokens=["🐙"]` to `tokenizer.train`, and it seems to work (i.e. this char always appear as a single token). However, it seems that as a result the trainer will never allow 🐙   to be part of some BPE splits. i.e. even if "🐙🐙 " occurs very frequently in my corpus, it will always be tokenized as "🐙", "🐙" and not as a single token. Basically, is it possible to provide a custom initial alphabet to the byte-BPE trainer?

**Comment by n1t0** [comment]
Unfortunately, it's not possible to enforce something like this at the moment. When you specify a `special_token`, you ensure it won't get split, and it won't be part of anything else also. These special tokens are extracted first, even before it gets to the actual tokenization algorithm (like BPE).

For BPE specifically, you actually start from characters (bytes in the case of byte-level) and then you merge them into longer tokens step by step. So the only way I can see would be to try to include many occurrences of these tokens in your training data. It would let you make sure that they become part of the vocabulary, with the merges operations needed to reconstruct them from the bytes.

**Comment by glample** [comment]
Alright, for now I think I'll stick to `special_tokens` then. Thanks!
