### ISSUE TITLE
incompatible with transformers 2.3.0 with tokenizers 0.0.11

### ISSUE THREAD

**Issue by dsindex** [huggingface/tokenizers#82]
```
$ pip install tokenizers --upgrade
ERROR: transformers 2.3.0 has requirement tokenizers==0.0.11, but you'll have tokenizers 0.1.1 which is incompatible.
Installing collected packages: tokenizers
  Found existing installation: tokenizers 0.0.11
    Uninstalling tokenizers-0.0.11:
      Successfully uninstalled tokenizers-0.0.11
Successfully installed tokenizers-0.1.1
```

is it no problem?

**Comment by n1t0** [comment]
Hi @dsindex. We are currently in the process of updating `transformers` with the last version of `tokenizers` so this is totally normal. You will be able to upgrade soon!
Also please note that `tokenizers` being quite young, we sometimes introduce breaking changes, so having a specific version that can be used with `transformers` lets us make sure everything keeps working for you.
