### ISSUE TITLE
'tokenizers.Tokenizer' has no attribute 'from_pretrained'

### ISSUE THREAD

**Issue by dwyane1023** [huggingface/tokenizers#822]
Hi,

when I run

```python

from tokenizers import Tokenizer
tokenizer = Tokenizer.from_pretrained("bert-base-cased")

AttributeError: type object 'tokenizers.Tokenizer' has no attribute 'from_pretrained'
```
is this related to tokenizers.__version__ ?
mine is 0.10.3

**Comment by Narsil** [comment]
Yes it is, can you build from source ?

I don't think `from_pretrained` exists in a released version yet.

**Comment by dwyane1023** [comment]
> Yes it is, can you build from source ?
> 
> I don't think `from_pretrained` exists in a released version yet.

Thanks for the reply

If I want to use 'from_pretrained'. 

Should I trun to 'transformers.PreTrainedTokenizer'?

**Comment by Narsil** [comment]
No no, the code included should work.

**Comment by quant1216** [comment]
I also have same problem. My tokenizers version is 0.10.3
I think this issue should be open.

**Comment by Narsil** [comment]
Yes 0.10.3 doesn't have from_pretrained, 0.11 are the first version to include that (and it's the reason for this minor version change update)

**Comment by quant1216** [comment]
Oh, I see. Thank you!
