### ISSUE TITLE
BPE tokenizer and spaces

### ISSUE THREAD

**Issue by ImanHosseini** [huggingface/tokenizers#823]
How can I make BPE tokenizer not generate tokens which include space in the middle, that is, I don't want something like "abc de" in the dictionary (which has an space in the middle).
```python
tokenizer = Tokenizer(BPE(unk_token='<unk>',continuing_subword_prefix="##"))
tokenizer.pre_tokenizer = pre_tokenizers.Sequence([Whitespace(),Digits(individual_digits=True)])
trainer = BpeTrainer(special_tokens=["<unk>"],vocab_size=VOCAB_LIMIT)
tokenizer.train(srcs,trainer)
```

**Comment by Narsil** [comment]
That should be the case since you are using `Whitespace()` in the pretokenizer.

is `src_tknizer` supposed to be `tokenizer` perhaps ?

**Comment by ImanHosseini** [comment]
yes that's tokenizer.
It is generating tokens with spaces inside them.

**Comment by Narsil** [comment]
Can you provide a file to reproduce ? It shouldn't with `Whitespace` pre_tokenizer.

**Comment by ImanHosseini** [comment]
Demo:
https://colab.research.google.com/drive/1w6KWvkI-utCNbm9aZCs4EbENEJZ7gZOn?usp=sharing

**Comment by Narsil** [comment]
Perfect !
