### ISSUE TITLE
BPE with continuing subword prefix

### ISSUE THREAD

**Issue by ImanHosseini** [huggingface/tokenizers#827]
I expect that with "continuing subword prefix" if a word "abcd" is broken to "ab cd" I can piece it together via the prefix. Say prefix is "##" I'd get ["ab", "##cd"]. 
Demo: https://colab.research.google.com/drive/1w6KWvkI-utCNbm9aZCs4EbENEJZ7gZOn?usp=sharing
What happens here is that _without_ subword_prefix, I get a tokenizer which encodes "vv vv a" as ["vv","vv","a"] but with it it gives me: ['v', 'unk', 'v', 'unk', 'a']] vocabs being:
```
{'avvvvavv': 12, 'a': 1, '<unk>': 0, 'vv': 3, 'avv': 5, 'avvvvavva': 13, 'va': 8, 'vvavv': 10, 'vvv': 6, 'v': 2, 'av': 4, 'vav': 9, 'aa': 7, 'ava': 11}
{'avvvvavv': 12, '<unk>': 0, 'avv': 5, 'aa': 7, 'vav': 9, 'v': 2, 'ava': 11, 'vvavv': 10, 'a': 1, 'vvv': 6, 'vv': 3, 'va': 8, 'av': 4, 'avvvvavva': 13}
```
So what's happening here? And how is this a desirable output? Expectation is that I just pass "continuing_subword_prefix" and later after decoding I use that prefix to piece back together spliced work, but now, "continuing_subword_prefix" just breaks the tokenizer. What is the expected way to do this?

**Comment by Narsil** [comment]
It's hard to answer without access to your colab,

but most yes it's expected since `##v` does not exist in your `with subprefix` tokenizer.

`v` and `##v` need to  be different tokens with that option. Mentally you can think of them to be ` v` and `v` respectively (but it's different in handling beginning of a sentence)

**Comment by ImanHosseini** [comment]
fixed the colab link. So what is the use of "with subprefix" tokenizer? Normally, one would train a tokenizer, and then pass the sentences to it:
```
enced = tk2.encode("this is a sentence")
```
Expecting to get something like: ["th", "##is", "a", "sen", "##tence"] and not: ["th", "UNK","a", "UNK",..]
How else would I use the trained tokenizer?

**Comment by Narsil** [comment]
Your expectations are correct, however I don't know about the details of your training, do you mind sharing your code in an accessible way (either here directly or as a gist if it's long ?). The colab you shared is private.

**Comment by ImanHosseini** [comment]
![tokk](https://user-images.githubusercontent.com/12172889/141483269-31549404-125c-4b4b-a47f-4c12bc38b01d.png)
Thanks for looking into this. Here is the shot of colab notebook. (are you sure it's private? I tested the link in incognito mode and it worked. It's on '_anyone with this link can view this document_' mode.)

**Comment by iamausertoo** [comment]
Is there any resolution for this issue?  It also appears to me that specifying a continuing_subword_prefix does not change the model that is produced.

**Comment by Narsil** [comment]
Hi everyone,

It seems like the `continuing_subword_prefix` needs to be defined in the `trainer` too, not only in the model.
It's a known caveat/surprising behavior that some information doesn't flow from the `model` to the `trainer`.  (For one the vocab doesn't flow from the model to the trainer, and that's pretty obvious, other parameters less so)
This should work:

```python
from tokenizers import Tokenizer, pre_tokenizers, models, trainers


def data():
    for i in range(100):
        yield "aa a a a a a a vvv vvv vv v v  av av ava v a va  vav avvvvavva  a"


def main():
    tk = Tokenizer(models.BPE(unk_token="<unk>"))
    tk.pre_tokenizer = pre_tokenizers.Sequence(
        [pre_tokenizers.Whitespace(), pre_tokenizers.Digits(individual_digits=True)]
    )
    trainer = trainers.BpeTrainer(
        special_tokens=["<unk>"], vocab_size=8000, continuing_subword_prefix="##"
    )
    tk.train_from_iterator(data(), trainer)

    tk.save("tok.json")


if __name__ == "__main__":
    main()
```

Can you confirm it works for you ?

**Comment by iamausertoo** [comment]
Yes, this worked for me.  Thanks!

I had been calling the `ByteLevelBPETokenizer.train()` method, which creates its own Trainer object but doesn't pass  `self.model.continuing_subword_prefix`.  So, it seems that adding that additional parameter in `byte_level_bpe.py` would fix.
