### ISSUE TITLE
Reduce Memory usage for Vocab and VocabR

### ISSUE THREAD

**Issue by zommiommy** [huggingface/tokenizers#829]
My colleague @LucaCappelletti94 and I are starting to use the BERT tokenizers and we are about to start using your great library.

Digging through the code we have found [the following pattern](https://github.com/huggingface/tokenizers/blob/1dc19e0dd4ba73af938ff4dc80b4b1cd40edf4bf/tokenizers/src/models/wordpiece/mod.rs#L37):
```rust
type Vocab = HashMap<String, u32>;
type VocabR = HashMap<u32, String>;
```
This duplicates the strings and thus the memory requirements are ~doubled.
In our [Rust Graph library](https://github.com/AnacletoLAB/ensmallen/tree/approximated_bc) we have solved this problem [in this way](https://github.com/AnacletoLAB/ensmallen/blob/2ebb283e1951309924d4cc8bcb5a1ad08a437e03/graph/src/vocabulary.rs#L24):
```rust
use std::hash::{Hash, Hasher};
use std::collections::HashMap;
use std::collections::hash_map::DefaultHasher;

#[inline]
pub(crate) fn compute_hash<T: Hash>(t: &T) -> u64 {
    let mut s = DefaultHasher::new();
    t.hash(&mut s);
    s.finish()
}

struct Vocabulary {
    map: HashMap<u64, u32>,
    reverse_map: Vec<String>,
}

impl Vocabulary {
    pub fn forward(&self, key: &str) -> Option<u32> {
        self.map.get(&compute_hash(key))
    }

    pub fn backward(&self, id: u32) -> Option<&str> {
        self.reverse_map.get(id).map(|x| x.as_str())
    }
}
```
This assumes that the ids are a dense range that starts from 0.
This has a slightly slower `forward` but faster `backward` and it should approximately half the memory used.

If you think this could be an improvement, we could make a pull request.

Cheers, 
Tommaso

**Comment by Narsil** [comment]
Hi @zommiommy ,

Thank you for this proposition, it's fair and would indeed save some memory.

Currently it's done this way to map to `transformers` way of things, and we have seen in the wild vocabularies that were not dense (with missing ids). It does cause issue in the current library anyway so your approach might be viable, but we definitely need to check for those cases which do exist.

It would also hinder the current serialization format (and reading) so work would be needed there too to support both.
