### ISSUE TITLE
tokenizers.decoders.WordPiece contracts "do not" to "don't" in decoding

### ISSUE THREAD

**Issue by dhdaines** [huggingface/tokenizers#836]
This behaviour (seen at https://github.com/huggingface/tokenizers/blob/master/tokenizers/src/decoders/wordpiece.rs#L40) is quite unexpected (even though I realize tokenization is not invertible):

```
In [34]: tok = transformers.AutoTokenizer.from_pretrained('distilbert-base-uncased')
In [35]: tok.convert_tokens_to_string(tok.convert_ids_to_tokens(tok("I do not like green eggs and spam").input_ids))
Out[35]: "[CLS] i don't like green eggs and spam [SEP]"
In [36]: tok.backend_tokenizer.decoder.decode(["i", "do", "not", "like", "green", "eggs", "and", "spam"])
Out[36]: "i don't like green eggs and spam
In [63]: tok.backend_tokenizer.decoder
Out[63]: <tokenizers.decoders.WordPiece at 0x7f9776eac420>

```

What is the reasoning behind this?  It seems gratuitous to me.  It also *only* applies to "do not" and not any other English contractions (also, is this decoder for English only?)  Note also that the encoder doesn't (and also does not) match the behaviour of the original BERT implementation for "don't":

```
In [64]: tokenizer = official.nlp.bert.tokenization.WordpieceTokenizer([x.strip() for x in open("bert_base/vocab.txt")])
In [65]: tokenizer.tokenize("i don't like green eggs and spam")
Out[65]: ['i', 'don', "##'", '##t', 'like', 'green', 'eggs', 'and', 'spa', '##m']
In [66]: tok.convert_ids_to_tokens(tok("I don't like green eggs and spam").input_ids)
Out[66]: ['[CLS]', 'i', 'don', "'", 't', 'like', 'green', 'eggs', 'and', 'spa', '##m', '[SEP]']
```

**Comment by dhdaines** [comment]
Thank you!  This is very helpful, especially knowing that I can deactivate it - I will go browse in the forums.

You can of course close this if you feel that it isn't a bug, but I think that the divergence in behaviour between tokenizers and the official BERT implementation of SentencePiece is a problem.

**Comment by Narsil** [comment]
I am going to leave this open, just because I don't have the background as to why this was added. 
But it feels intentional enough it's not a bug for sure.
