### ISSUE TITLE
Question about the arguments `add_prefix_space` and `trim_offsets` of `RobertaProcessing`

### ISSUE THREAD

**Issue by SaulLu** [huggingface/tokenizers#843]
# My question
Following a question from a transformers user about offsets ([here](https://github.com/huggingface/transformers/issues/14305#issuecomment-988718522)), I was led to dig a little deeper into `RobertaProcessing` (with python) and wonder if I understand how to use the `add_prefix_space` and `trim_offsets` arguments.

In particular, when I choose `add_prefix_space=true` and `trim_offsets=true` and tokenize an already pre-tokenized words list `text_split_into_words = ['I', 'love', 'IKEA', ' very', 'much', '📸.']` I get :

|    |   word_id | offsets   | decoded_token   | corresponding extract   |
|---:|----------:|:----------|:----------------|:------------------------|
|  0 |         0 | (0, 1)    | ĠI              | 'I'                     |
|  1 |         1 | (1, 1)    | Ġl              | ''                      |
|  2 |         1 | (1, 4)    | ove             | 'ove'                   |
|  3 |         2 | (1, 1)    | ĠI              | ''                      |
|  4 |         2 | (1, 2)    | K               | 'K'                     |
|  5 |         2 | (2, 3)    | E               | 'E'                     |
|  6 |         2 | (3, 4)    | A               | 'A'                     |
|  7 |         3 | (1, 5)    | Ġvery           | 'very'                  |
|  8 |         4 | (1, 4)    | Ġmuch           | 'uch'                   |
|  9 |         5 | (1, 1)    | Ġ               | ''                      |
| 10 |         5 | (0, 1)    | Ł               | '📸'                    |
| 11 |         5 | (0, 1)    | ĵ               | '📸'                    |
| 12 |         5 | (0, 1)    | ¸               | '📸'                    |
| 13 |         5 | (0, 1)    | .               | '📸'                    |

where `corresponding_extract  = text_split_into_words[word_id][offsets[0]:offsets[1]]`

You notice that some offsets miss the first character of the word corresponding to the token is not included (see for example line 3, 8 and 9). But that is not the case for all the words (see for example the line 0)

# Code

I tried to keep this issue as concise as possible and provided in a [google colab notebook](https://colab.research.google.com/drive/1kiwvZwsJZnk-UDzeny6g-kaA7HUAaVMq?usp=sharing) everything to reproduce the previous result (as well as to compare with `tim_offsets=False`).

Maybe @Narsil or @n1t0 , what do you think? (it would help me a lot to know if what I propose in [this PR](https://github.com/huggingface/transformers/pull/14752) is a good idea or not)

**Comment by Narsil** [comment]
OK, it seems that the issue lies in the interaction between `is_pretokenized` and `trim_offsets` and `add_prefix_space`.

The PR should contain most details. High level solution:

The code assumed that `add_prefix_space` was referring to the first token. This assumption is incorrect in the case of `is_pretokenized` since the third token might still contain offsets referring to the start of the original string of the pretokenized part (the second pre_tokenized token for instance).

**Comment by SaulLu** [comment]
Thanks a lot for the fix :confetti_ball:
