### ISSUE TITLE
Unable to use HF Rust implementation but python bindings work fine

### ISSUE THREAD

**Issue by vasudevgupta7** [huggingface/tokenizers#847]
When I run `from_pretrained` using python bindings and check if tokenizer is rust based (using `is_fast`), I get `True`. But when I try to load same tokenizer in rust, it raises an error. Am i missing something or doing something incorrect??

`tokenizers version = "0.11.0"`

## How to reproduce?

**Running in rust**

```rust
use tokenizers::{tokenizer::Tokenizer, Result};

fn main() -> Result<()> {
    
    let tokenizer_id = "KB/bert-base-swedish-cased";
    let tokenizer = Tokenizer::from_pretrained(tokenizer_id, None)?;

    Ok(())
}
```

I get the following error:

```bash
Error: "Model \"KB/bert-base-swedish-cased\" on the Hub doesn't have a tokenizer"
```

**Running in python**

```python
from transformers import AutoTokenizer
tokenizer_id = "KB/bert-base-swedish-cased"
tokenizer = AutoTokenizer.from_pretrained(tokenizer_id)

print(tokenizer.is_fast)
# above returns true
```

Thanks a lot!

**Comment by Narsil** [comment]
Yes, the rust crate hasn't been updated yet, if you use in Cargo the version from github it should work.

**Comment by vasudevgupta7** [comment]
Hey @Narsil, thanks for replying. I just tried `tokenizers = { git = "https://github.com/huggingface/tokenizers" }` in `Cargo.toml` and it gave me the same error.

**Comment by vasudevgupta7** [comment]
Thanks a lot!
