### ISSUE TITLE
Sampling alternative tokenizations

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#849]
In [this](https://colab.research.google.com/github/huggingface/notebooks/blob/master/transformers_doc/tokenizer_summary.ipynb#scrollTo=QCkb-TFs1Wdu) colab it mentions:

> Unigram saves the probability of each token in the training corpus on top of saving the vocabulary so that the probability of each possible tokenization can be computed after training. The algorithm simply picks the most likely tokenization in practice, but also offers the possibility to sample a possible tokenization according to their probabilities.

I'm sure I saw another post that described how to do this but I cannot find it any more - is this possible? i.e. instead of simply calling encode and getting the `best` tokenization I want to select the top-k (and their scores)

**Comment by Narsil** [comment]
hi @david-waterworth, this isn't enabled within this library (it is only possible to do with `Unigram` models anyway).

In `transformers` if you use the `slow` tokenizer, you can pass `sp_model_kwargs` to enable sampling:

```python
AlbertTokenizer(...., sp_model_kwargs={"enable_sampling": True})
```

https://github.com/huggingface/transformers/blob/master/src/transformers/models/albert/tokenization_albert.py#L105

That will use `sentencepiece` under the hood which will just sample from desired sampling policy `NBest` seems to also enable do `top_k`.

PRs welcome to add it to `tokenizers` (the naming is very close to `sentencepiece` so it should be doable).

**Comment by david-waterworth** [comment]
Thanks @Narsil, I'll take a look at the `albert` example and see if I have any bandwidth to implement a unigram version.

**Comment by RuiWang1998** [comment]
Hi, 

Sorry to bother you but if I have trained a Unigram tokenizer using its `UnigramTrainer`, am I correct to understand that the values following the token in the json file is its log-probability?

I followed https://huggingface.co/docs/tokenizers/training_from_memory

Or how best should I interpret the value?


Thanks in advance.

**Comment by Narsil** [comment]
Yes that's something like log probability.

**Comment by kellymarchisio** [comment]
Seconding this request for sampling with Unigram

**Comment by Narsil** [comment]
Unfoprtunately, activity on this is issue seems to suggest this is a very low demand feature, very low probability to see the light anytime soon. 

I'm going to close it. If there's some interest we might reopen.

**Comment by kellymarchisio** [comment]
> Unfoprtunately, activity on this is issue seems to suggest this is a very low demand feature, very low probability to see the light anytime soon.
> 
> I'm going to close it. If there's some interest we might reopen.

Hi Narsil - I’m surprised by the low demand, being that subword regularization is the primary reason one uses sentencepiece with unigram. Is it possible that users *think* it is implemented, and that’s why they haven’t posted issues much?  The documentation suggests it is working.

**Comment by Narsil** [comment]
Most users are using `tokenizers` at inference, not so much at training.

There is dropout for BPE too, which I don't see a lot of issues about (not sure if that means everything's perfect or if not very used).

For the sampling and unigram most of the code is kind of ready, we just never exposed an API for that.
The code is there: https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/models/unigram/lattice.rs#L380 and was taken roughly from spm at the time.

Should be exposable relatively easily if you want it, I'm just not sure about actually making a large change and supporting it officially.
