### ISSUE TITLE
Regex Capture Group?

### ISSUE THREAD

**Issue by SamuelLarkin** [huggingface/tokenizers#855]
Hi,
  I'm trying to replace some regex, more specifically, adding space around a certain token.
  ```
  normalizers.Replace(Regex(r"(AA+"), r" $1 "),
  ```

What is the syntax to do that.

**Comment by SamuelLarkin** [comment]
Any information that could help me here?

**Comment by ArthurZucker** [comment]
Hey! We don't support this, would you like to open a PR ? 🤗
