### ISSUE TITLE
Tokenization Training not working ? 

### ISSUE THREAD

**Issue by manishiitg** [huggingface/tokenizers#86]
I am on a google colab notebook. 

I have vocab.txt file 

![image](https://user-images.githubusercontent.com/1370315/72664105-06764480-3a20-11ea-9759-474438d7b494.png)

I have uploaded above some sample content. 
The full size is 83mb 

i am training a tokenizer on it 

```
from tokenizers import (ByteLevelBPETokenizer,
                            BPETokenizer,
                            SentencePieceBPETokenizer)

tokenizer = BPETokenizer()
tokenizer.train(["vocab.txt"],
                vocab_size=30000,
                min_frequency=2,
                special_tokens=["<unk>", "<pad>", "<cls>", "<sep>"],
                limit_alphabet=1000,
                show_progress=True)

```
and it just keep running forever..... like i stopped it after 20min..

am i doing some mistake?

**Comment by manishiitg** [comment]
any help on this?

**Comment by manishiitg** [comment]
i found the problem, 
in my dataset there was some corrupted text due to which few words got very long. i.e a single word itself was quite long. 

once this was fixed, it works perfectly fine  and very fast

**Comment by epwalsh** [comment]
Awesome, glad you figured it out!

**Comment by epwalsh** [comment]
Maybe we should issue a warning when the tokenizer finds a very long word. What do you think @n1t0?

**Comment by n1t0** [comment]
Well I think a 20 minutes run is really weird, even with a really long word. That would be really great if we could find a way to replicate and check if there is a bug first.
