### ISSUE TITLE
Can't load tokenizer using from_pretrained

### ISSUE THREAD

**Issue by Samirun** [huggingface/tokenizers#867]
I have been testing our auto nlp trained model in the model hub.
we are currently on free plan and we trained model on dec 22nd.
we did not do any custom modifications to the auto nlp model.
but it gives me this error all of a sudden today.
![image](https://user-images.githubusercontent.com/46156330/148042637-cb58fbfd-5139-4f34-b4bd-5b802e18ff32.png)
```
{
    "error": "Can't load tokenizer using from_pretrained, please update its configuration: missing field `direction` at line 1 column 85"
}
```
![image](https://user-images.githubusercontent.com/46156330/148042726-439a93b6-d55f-4385-90a0-ac2103241f14.png)
any help would be greatly appreciated.

our config file is 
```
{
  "_name_or_path": "AutoNLP",
  "_num_labels": 5,
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "id2label": {
    "0": "intent_black_list",
    "1": "intent_outage_fixed",
    "2": "intent_unclassified",
    "3": "intent_unsubscribe",
    "4": "intent_waiting_for_service"
  },
  "initializer_range": 0.02,
  "label2id": {
    "intent_black_list": 0,
    "intent_outage_fixed": 1,
    "intent_unclassified": 2,
    "intent_unsubscribe": 3,
    "intent_waiting_for_service": 4
  },
  "max_length": 256,
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "pad_token_id": 0,
  "padding": "max_length",
  "problem_type": "single_label_classification",
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.8.0",
  "vocab_size": 30522
}

```

@Narsil

**Comment by Narsil** [comment]
Everything should be fixed on the latest `tokenizers` (and on the API).

We recently added the `direction` parameter, but the setup wasn't correct to load old files, we missed that in the test suite. Should be good now.

**Comment by Samirun** [comment]
Thanks for the quick fix. Appreciate it a lot.
you can close this issue.
