### ISSUE TITLE
Enabling in-memory inputs for training a new tokenizer

### ISSUE THREAD

**Issue by yharuvi** [huggingface/tokenizers#88]
Hi,
Thanks for the release!
I was wondering whether there's a possibility to feed BPETokenizer.train() method with input other than list of file names. To be more specific, I'd like to feed it with an in-memory data structure like Pandas Series or list of lists (each representing a doc).
Is that possible without being forced to write to a .txt file? 
Thx!

**Comment by ksopyla** [comment]
Similar to https://github.com/huggingface/tokenizers/issues/198

**Comment by kkpsiren** [comment]
Any hints how to do this?

**Comment by n1t0** [comment]
Closing in favor of duplicate #198
