### ISSUE TITLE
Inference widget errors on tokenizer load with "data did not match any variant of untagged enum PyPreTokenizerTypeWrapper"

### ISSUE THREAD

**Issue by yhavinga** [huggingface/tokenizers#880]
When I run the inference widget on [flax-community/t5-base-dutch-demo](https://huggingface.co/flax-community/t5-base-dutch-demo)

it errors out with the message:

`Can't load tokenizer using from_pretrained, please update its configuration: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 1 column 13014`

This model and tokenizer config used to work half a year ago. Also the model (and tokenizer) work locally.
The error message suggests to update the configuration, but I do not know what it is in the tokenizer config that triggers this error.

**Comment by Narsil** [comment]
You are entirely right, this is unfortunately a regression that prevents new tokenizer versions from loading old tokenizer file.

This is fixed in the linked PR (deploying soon)

**Comment by yhavinga** [comment]
Thanks for looking into it!

**Comment by Narsil** [comment]
It works again on the API.

Thanks for reporting this !

**Comment by ilsilfverskiold** [comment]
@Narsil I'm having this same issue with the albert models, fine-tuning bert-base works fine, but I get this error when using albert:

Can't load tokenizer using from_pretrained, please update its configuration: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 109 column 3

-- the tokenizer is there and has been pushed alongside the model.

**Comment by ArthurZucker** [comment]
Could you share a repro with the tokenizer version you are using and the model you are trying to load @ilsilfverskiold ? 🤗
