### ISSUE TITLE
No conda package for tokenizers-0.11.4

### ISSUE THREAD

**Issue by SamuelLarkin** [huggingface/tokenizers#891]
Hi,
  I was wondering why the last version aka 0.11.4 can be found as a [pypi package](https://pypi.org/project/tokenizers/) but no longer as a conda package.  The last conda package on HuggingFace's channel is for [tokenizers-0.10.3](https://anaconda.org/HuggingFace/tokenizers).
A quick look at the last [action](https://github.com/huggingface/tokenizers/actions/runs/1709966821) for [.github/workflows/python-release-conda.yml](https://github.com/huggingface/tokenizers/blob/a8e07d734fd7b18a5d5e7ffc8315a971898cd234/.github/workflows/python-release-conda.yml) shows that it uses a different channel name [Using "moi_anthony" as upload username](https://github.com/huggingface/tokenizers/runs/4846387959?check_suite_focus=true#step:11:9)
and that step 
[conda package located at: https://anaconda.org/moi_anthony/tokenizers](https://github.com/huggingface/tokenizers/runs/4846387959?check_suite_focus=true#step:11:652)
reports a successful upload to https://anaconda.org/moi_anthony/tokenizers where we can, indeed find tokenizers-0.11.4.

Shouldn't it be uploaded to HuggingFace's official anaconda.org/HuggingFace instead?

**Comment by Narsil** [comment]
It should indeed probably.

@n1t0  Is this linked to the secret used in this repo ? I couldn't find any reference to moi_anthony in the build files.

**Comment by n1t0** [comment]
Yes, it is, and sorry about that! I made a mistake while updating the token last time. Will update and re-run the jobs

**Comment by n1t0** [comment]
Latest version is now available on Conda! https://anaconda.org/HuggingFace/tokenizers
