### ISSUE TITLE
Pretrained LayoutXLMTokenizer emits spurious empty tokens on specific inputs

### ISSUE THREAD

**Issue by quasimik** [huggingface/tokenizers#897]
# Spurious tokens

Minimum replicating example:

```
from transformers import LayoutXLMTokenizer

tokenizer = LayoutXLMTokenizer.from_pretrained('microsoft/layoutxlm-base')

inputs = {
    'text': [['ORIGINAL', 'PULLED', 'TOMATO'], ['ORI', 'PUL', 'TOM'], ['ORIPULTOM', 'PULORITOM', 'TOMORIPUL']],
    'boxes': [[[0,0,0,0], [0,0,0,0], [0,0,0,0]], [[0,0,0,0], [0,0,0,0], [0,0,0,0]], [[0,0,0,0], [0,0,0,0], [0,0,0,0]]],
}

outputs = tokenizer(**inputs)

print(tokenizer.batch_decode(outputs['input_ids'][0]))
print(tokenizer.batch_decode(outputs['input_ids'][1]))
print(tokenizer.batch_decode(outputs['input_ids'][2]))
```

Actual output:

```
['<s>', '', 'ORI', 'GIN', 'AL', '', 'PUL', 'LED', '', 'TOM', 'ATO', '</s>']
['<s>', '', 'ORI', '', 'PUL', '', 'TOM', '</s>']
['<s>', '', 'ORI', 'PUL', 'TOM', '', 'PUL', 'ORI', 'TOM', '', 'TOM', 'ORI', 'PUL', '</s>']
```

Expected output:

```
['<s>', 'ORI', 'GIN', 'AL', 'PUL', 'LED', 'TOM', 'ATO', '</s>']
['<s>', 'ORI', 'PUL', 'TOM', '</s>']
['<s>', 'ORI', 'PUL', 'TOM', 'PUL', 'ORI', 'TOM', 'TOM', 'ORI', 'PUL', '</s>']
```

You can see that spurious `''` tokens are generated at the starts of any word beginning with the offending subwords `ORI`, `PUL`, and `TOM`. This happens with both `LayoutXLMTokenizer` and `LayoutXLMTokenizerFast`.

# Behavior when labels are provided

Additionally, the behavior with labels is different between `LayoutXLMTokenizer` and `LayoutXLMTokenizerFast`.

Minimum replicating example:

```
from pprint import pprint
from transformers import LayoutXLMTokenizer, LayoutXLMTokenizerFast

tokenizer = LayoutXLMTokenizer.from_pretrained('microsoft/layoutxlm-base')
tokenizer_fast = LayoutXLMTokenizerFast.from_pretrained('microsoft/layoutxlm-base')

inputs = {
    'text': ['ORIGINAL', 'PULLED', 'TOMATO'],
    'boxes': [[0,0,0,0], [0,0,0,0], [0,0,0,0]],
    'word_labels': [1, 2, 3],
}

outputs = tokenizer(**inputs)
outputs_fast = tokenizer_fast(**inputs)

pprint(list(zip(tokenizer.batch_decode(outputs['input_ids']), outputs['labels'])))
pprint(list(zip(tokenizer.batch_decode(outputs_fast['input_ids']), outputs_fast['labels'])))
```

Actual output:

```
[('<s>', -100),
 ('', 1),
 ('ORI', -100),
 ('GIN', -100),
 ('AL', -100),
 ('', 2),
 ('PUL', -100),
 ('LED', -100),
 ('', 3),
 ('TOM', -100),
 ('ATO', -100),
 ('</s>', -100)]
[('<s>', -100),
 ('', 1),
 ('ORI', 1),
 ('GIN', -100),
 ('AL', -100),
 ('', 2),
 ('PUL', 2),
 ('LED', -100),
 ('', 3),
 ('TOM', 3),
 ('ATO', -100),
 ('</s>', -100)]
```

Expected output:

```
[('<s>', -100),
 ('ORI', 1),
 ('GIN', -100),
 ('AL', -100),
 ('PUL', 2),
 ('LED', -100),
 ('TOM', 3),
 ('ATO', -100),
 ('</s>', -100)]
[('<s>', -100),
 ('ORI', 1),
 ('GIN', -100),
 ('AL', -100),
 ('PUL', 2),
 ('LED', -100),
 ('TOM', 3),
 ('ATO', -100),
 ('</s>', -100)]
```

You can see that `LayoutXLMTokenizer` labels just get passed on to the spurious tokens, while `LayoutXLMTokenizerFast` labels are still on the first subwords, but also get duplicated on to the spurious tokens.

# Versions

tokenizers library: 0.10.3
OS: Ubuntu 20.04.3 LTS

**Comment by Narsil** [comment]
PInging @NielsRogge which has more knowledge of LayoutXLM.

I will check it out later today, but I can only provide an answer as to where the '' comes from, I cannot really assess if it's normal/desired, or adress difference between Fast/non Fast.

**Comment by Narsil** [comment]
The '' is coming from the prefixed `"▁"` automatically added by sentenncepiece (and by extension `tokenizers`).

So it's actually perfectly normal, it just happens that those words favor this chunking where the "▁" is on its own. It does indicate to the model that the word is a new word so it has its purpose.

For the difference between Fast and NonFast, the issue lies more in `transformers` IMO since the logic is handled there ( `tokenizers` does not deal with boxes and word_labels)

**Comment by quasimik** [comment]
Thanks for the explanation. I do have some prior knowledge of BPE encoding, and after further investigation, it seems you're essentially correct. My confusion stems from the fact that `LayoutXLMTokenizer/Fast` does not prefix `'_'` in its `decode` output for those tokens which actually do include the prefixed space.

To illustrate:

```
from transformers import LayoutXLMTokenizer

tokenizer = LayoutXLMTokenizer.from_pretrained('microsoft/layoutxlm-base')

inputs = {
    'text': ['B BB BBB'],
    'boxes': [[0,0,0,0]],
}

outputs = tokenizer(**inputs)

print(inputs['text'])
print(tokenizer.decode(outputs['input_ids']))

for input_id, output_token in zip(outputs['input_ids'], tokenizer.batch_decode(outputs['input_ids'], clean_up_tokenization_spaces=False)):
    print(f'{input_id:>6} {output_token}')
```

Actual output:

```
['B BB BBB']
<s> B BB BBB</s>
     0 <s>
   335 B
 40746 BB
   335 B
 22312 BB
     2 </s>
```

Expected output:

```
['B BB BBB']
<s> B BB BBB</s>
     0 <s>
   335 _B
 40746 _BB
   335 _B
 22312 BB
     2 </s>
```

It's clear from the example that the `40746 BB` token includes a `'_'` whitespace prefix, while the `22312 BB` token does not. The identical output is misleading.

So the observed behavior is indeed correct, those `''` tokens account for the spaces before those tokens that do not include a `'_'` whitespace prefix.

Still, the discrepancy between how `LayoutXLMTokenizer` and `LayoutXLMTokenizerFast` treat labels might warrant a look. I'll keep this open for now, but I'm happy to open a separate issue if desired.

**Comment by quasimik** [comment]
Also, I'd appreciate some advice here regarding Entity Recognition tasks.

The example I'll be using is `['TOMATO', 'SOUP']` which are words representing a single entity `TOMATO SOUP`, which gets tokenized to `['_', 'TOM', 'ATO', '_SO', 'UP']` (`_`s added for clarity).

Ignoring this issue with the added `'_'` tokens, by default, [`LayoutXLM` only labels the first token of each word](https://huggingface.co/docs/transformers/model_doc/layoutxlm#transformers.LayoutXLMTokenizerFast.only_label_first_subword). This means, using a BIO scheme, only the first token resulting from the tokenization of `'TOMATO'` gets the Beginning label, and only the first token resulting from the tokenization of `'SOUP'` gets the Inside label.


With the `'_'` additions, which of the below approaches would you recommend?

```
Legend:
B - Beginning
I - Inside
O - Other
X - Loss turned off
```
1. `_:B TOM:X ATO:X SO:I UP:X`
2. `_:X TOM:B ATO:X SO:I UP:X`
3. `_:B TOM:B ATO:X SO:I UP:X`, and somehow combine `_` and `TOM` for downstream tasks:
    a. Just sum their vectors
    b. Project with biaffine layer that specifically handles added `_`s

**Comment by quasimik** [comment]
I have chosen to go with approach (2) for now, using `LayoutXLMTokenizerFast` and manually zeroing losses for the prefix token. Closing the issue but please feel free to comment.
