### ISSUE TITLE
Missing Version info in build from source installation instruction

### ISSUE THREAD

**Issue by leo-du** [huggingface/tokenizers#898]
In the build from source instructions: https://huggingface.co/docs/tokenizers/python/latest/installation/main.html#installation-from-sources , if one follows this instruction exactly, they will install the latest commit in `master` branch. Probably should add a warning or tell user to `git checkout` their desired version.

**Comment by Narsil** [comment]
I beg to differ, if you want to install from source you probably are a bit knowledgeable.

How sources and git works is beyond the simple commands which focus on making the thing buildable.

May I ask what surprised you/didn't work when you installed from sources ? Maybe the issue you encountered is the actual issue.

**Comment by leo-du** [comment]
There is nothing surprising or didn't work. I just noticed that the built version is different from the previous version used in another research project. I simply don't know what's changed in between the versions and don't have the time to track them down, and I tend to make a reasonable effort in making research code reproducible which is why I like to follow exact version setup. Since researchers are a main user base of this project I thought they probably want to know which version they're using when they build from the source. That's why I thought a notice in the guide would be nice.

**Comment by leo-du** [comment]
Sure, a PR sounds good. Maybe a simple comment in the bottom like 

> Note that this will install the latest commit. You will need to `git checkout` if you would like to install your desired version.

This doesn't give the entire detail but will speak to those who cares about it. Does that work?

**Comment by Narsil** [comment]
Seems perfectly fine to me.
