### ISSUE TITLE
get_vocab_size() is different from len(get_vocab())

### ISSUE THREAD

**Issue by anatoly-khomenko** [huggingface/tokenizers#900]
### How to reproduce

```
import tokenizers
print(tokenizers.__version__)
tokenizer = tokenizers.Tokenizer.from_pretrained("camembert-base")
print(tokenizer.get_vocab_size(False))
print(len(tokenizer.get_vocab(False)))
```

The above will output:

`
0.11.0
32005
32004
`

This works correctly for some other models that I have tested, like: bert-base-uncased, bert-base-german-cased

Potentially it has to deal with the fact that camambert vocabulary has token with id == 3 missing, wile other models tested have all tokens present and the maximal token ID is vocabulary size - 1.

Here is the code to illustrate the above hypotesis:
```
import operator
sorted_vocab = sorted(tokenizer.get_vocab().items(), key=operator.itemgetter(1))
print(sorted_vocab[:4])
print(sorted_vocab[-1])
```

For camambert-base this will output:
```
[('<s>NOTUSED', 0), ('<pad>', 1), ('</s>NOTUSED', 2), ('<unk>', 4)]
('<mask>', 32004)
```

**Comment by Narsil** [comment]
Hi,

I do agree that the output is confusing to say the least. But I do think the current behavior is correct.

`get_vocab_size()` is intended to provide the `embedding` dimension, and so using `max(vocab_id)` makes sense for this purpose.

The fact that `camembert-base` has a hole, which means an unused slot, is an issue, but it still has a `vocab_size==32005` regarding the valid ids that it can output as tokens.

Would you agree ?
