### ISSUE TITLE
Some questions about building a tokenizer from scratch: vocab size can't decide actual vocab size and token order unstable.

### ISSUE THREAD

**Issue by catqaq** [huggingface/tokenizers#903]
Hi,
I got some strange results when building a tokenizer from scratch followed by your offical demo.(https://huggingface.co/docs/tokenizers/python/latest/quicktour.html#build-a-tokenizer-from-scratch, and https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/train_bert_wordpiece.py)
1.The vocab size we set in training can't decide the actual vocab size. For example, i want a 5000 vocab, but got a 8557 vocab after training.
2.I got the same size vocab with slightly different token orders by runing same training code.

**Comment by Narsil** [comment]
Hi @catqaq ,

do you mind sharing the exact script you created with the doc ?
Also are you using the exact data of the script ? Do you mind sharing the output tokenizer ?

>  want a 5000 vocab, but got a 8557 vocab after training.

We cannot guarantee vocab size when vocab_size < number of different unicode chars in the dataset.
This is already reported here: https://github.com/huggingface/tokenizers/issues/886 if you want a detailed conversation about this. If this is indeed the same thing you're observing.

>  I got the same size vocab with slightly different token orders by runing same training code.

Token order is not guaranteed in case of equality. It shouldn't matter for the downstream model (token_ids order is never used)

**Comment by catqaq** [comment]
@Narsil thanks! Here is the code:
` # Initialize an empty tokenizer
    tokenizer = BertWordPieceTokenizer(
        clean_text=True,
        handle_chinese_chars=True,
        strip_accents=True,
        lowercase=True,
    )
    filepath = "./data/corpus.txt" 
    # training
    tokenizer.train(
        files=[filepath],
        vocab_size=5000,  
        min_frequency=2,
        limit_alphabet=10000, 
    )`
So, as you mentioned "We cannot guarantee vocab size when vocab_size < number of different unicode chars in the dataset.", can we get expected vocab size by set limit_alphabet smaller than vocab size? But i tried several times, found that we can only get expected vocab size when limit_alphabet<vocab size-n, n is decided by experinments on your data .

**Comment by Narsil** [comment]
>  it's a little inconvenient that we can't get expected vocab size easily

As mentionned in the linked issue, if you trigger that behavior based on number of chars alone, it should definitely raise some concern no matter what IMHO. Otherwise the risk of running most of your data into `<unk>` is definitely an issue you want to at least be aware of.
Does `limit_alphabet` work for you ?

>  Here is the code:

Do you mind sharing what is the corpus ? Or provide a sample which triggers the thing? without it I can't reproduce actually

**Comment by catqaq** [comment]
@Narsil Hi, Here is the corpus https://github.com/CLUEbenchmark/SimCLUE. I totally understand your concern. Smaller limit_alphabet works fine for me, as mentioned in above.But how smaller is suitable, e.g. limit_alphabet<vocab size-n. n is decided by your data. So, i said it's a little inconvenient that we can't get expected vocab size easily. But again, I totally understand your concern about the risk of running some data into <unk>. This seems like a dilemma, but I feel that for users who want a small vocabulary (such as a mobile app), a little more token is acceptable to be recognized as unk.

**Comment by Narsil** [comment]
Yes,

I see what you mean. There is some other work that might enable something to be workable with a byte hack too that might enable stricter vocab_size enforcement without too much compromise:

https://github.com/huggingface/tokenizers/issues/929
https://github.com/huggingface/tokenizers/issues/928

**Comment by Narsil** [comment]
Hmm, using pure bytes as a source vocabulary is definittely better as 256 would be the min vocab, and nothing else would be necessary. The main drawback with this approach is that if a model outputs a non-valid utf-8 byte array, then you cannot really recover the string, and it does happen. https://github.com/huggingface/transformers/issues/13779 for instance.

In practice even `ByteLevel` requires the get the initial alphabet (unicode codepoints) and doesn't really treat the strings as a byte array. That is how historically tokenizers have been created/maintained and that fact is quite baked in the current implementation of `tokenizers` which uses `char` quite a bit (and not purely bytes).

Rewriting everything to be much more bytes aligned (or at least allowing it) is definitely not off the table, but it's a very major change, and undertaking it without breaking anything will be a challenge.

The Byte trick that I linked in the previous post are escape hatches, that might enable the pure 256 starting alphabet witthout a full rewrite, and will most definitely be used by BigScience. @thomasw21 Any pointers for @catqaq  ?

**Comment by thomasw21** [comment]
Hi @catqaq Not sure exactly what the question is. But we've indeed gone forward with a byte level tokenizer. The idea is just not to have any unknown tokens. cc @SaulLu

**Comment by catqaq** [comment]
@thomasw21 Hi, the question is that we want to deploy a tiny bert model on the mobile phone. So, we wanna compress the vocab to get smaller size and no noticeable performance penalty. Firstly, we tried your BertWordPieceTokenizer demo code to train a customized tokenizer. In this process, we found that it's a little inconvenient that we can't get expected vocab size easily.
After discussion with @Narsil , we also understand your concerns about performance degradation with small vocabulary (as more tokens are recognized as unk) . Then, we talked about other subword tokenization algorithm such as byte level tokenizer.
Now, the situation is:
1.As for BertWordPieceTokenizer, If we can accept a certain degree of performance degradation (in scenarios such as mobile phones), how can we easily obtain the specified vocab size? We tried to set limit_alphabet<vocab size-n, it works well, but n depends on the experiments on your dataset.
2.Of course it would be better if there are other subword tokenization algorithm or other ways  to achieve a small vocabulary without performance degradation.  A byte level tokenizer will be a good solution? In the previous discussion, @Narsil mentioned "The main drawback with this approach is that if a model outputs a non-valid utf-8 byte array, then you cannot really recover the string, and it does happen. https://github.com/huggingface/transformers/issues/13779 for instance." This only seems to happen in generation tasks. In non-generation task such as sentence embedding task, a byte level tokenizer can work perfectly?

**Comment by thomasw21** [comment]
So I'm not super familiar with all tokenization models. I think for non generation tasks byte level are great:
 - no unknown characters
 - no issue with non valid utf-8 byte array as you would see in generation
 - min vocabulary size should be something like 256? @Narsil @SaulLu can you confirm that one can build a byte level tokenizer with 256 tokens?
 
 The only issue you might see are longer sequences to encode the same string compared to other tokenization algorithms which have a natural cost as some operations in your transformer model are quadratic (if you're using a transformer model).

**Comment by catqaq** [comment]
@thomasw21 Thanks! I will try the byte level tokenizer in our sentence embedding task later. Hopefully it reduces the size significantly without compromising performance, and doesn't have a too severe impact on speed.
