### ISSUE TITLE
Tokenizer does not respect truncation when given a pair

### ISSUE THREAD

**Issue by txus** [huggingface/tokenizers#91]
I have a [custom Sentencepiece tokenizer](https://github.com/codegram/calbert/blob/d34981a21d25746983ea86f8eaaf2b77ad913c41/calbert/tokenizer.py#L20-L107) with BERT post-processing, with padding and truncation enabled to a fixed `max_seq_len`, and it works as long as I don't encode a sentence pair:

```python
encoding = tokenizer.encode('hello, how are you')
assert len(encoding.tokens) == max_seq_len

encoding = tokenizer.encode('hello, how are you', 'fine and you')
assert len(encoding.tokens) == max_seq_len # fails
```

I've had a look at the Rust codebase and everything looks like it should work. This behavior happens both in single encodings and batch encodings. Do you have any idea where the error might be? Is it user error?

**Comment by n1t0** [comment]
Hi @txus! Could you try this again using the last `v0.3.0` release? I wasn't able to reproduce your results so I think it should now be fixed. Let us know!

**Comment by n1t0** [comment]
Closing for now. Feel free to reopen if needed!
