### ISSUE TITLE
BART tokenizer breaks up a word into subtokens unmeaningfully

### ISSUE THREAD

**Issue by chris-opendata** [huggingface/tokenizers#910]
I am using BART model and tokenizer for CNN dailymail. The tokenizer is loaded from the pretrained 'facebook/bart-large-cnn'.
The tokenization process on highlight samples by code below produces more tokens than original text in addition to BOS and EOS.
>>>
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(targets, max_length=None, padding=False, truncation=False)
>>>
where targets are ['Accident happens', 'Sigma Alpha'] (extract from the first two highlights of CNNDM validation samples) for debugging.
By debugging through, I got to _tokenize (tokenization_gpt2.py) which breaks up 
>>>
    'Accident happens' into ['Acc', 'ident', 'Ġhappens'] and subsequentially produced ids [36984, 8009, 2594], and 
    'Sigma Alpha' into ['S', 'igma', 'ĠAlpha'] and ids [104, 34719, 7829].
    With padding, the final token ids are [[0, 36984, 8009, 2594, 2], [0, 104, 34719, 7829, 2]].
>>>
This is not the expected output. I try to get a sense of _tokenize behavior of breaking up a word token unmeaningfully. And is there any setting to avoid it?

Regards

**Comment by Narsil** [comment]
Hi @chris-opendata ,

I think you should read how `tokenizers` work in ML, more specifically BPE and Unigram as the main reason to split a text into chunks is to make it easy on the model. However using pure words, researchers soon found out that there were way too many words and a pure `WordLevel` (the name we give to that approach in this lib) was either too big, or was leaving out to many words (named `<unk>` usually).

`BPE` and `Unigram` are two different approaches to help remove the need of `<unk>` (or limit it drastically) by splitting words up into chunks. 

This is very much how things are supposed to work.

If you are referring to `'Ġhappens'` the `Ġ` then it's also working as intended. It comes from here : https://huggingface.co/docs/tokenizers/python/latest/components.html#pre-tokenizers and the trick to get all `bytes` readable, also make the regular space become `Ġ`. You need to `tokenizer.decode([34])` in order to see the proper string.

**Comment by Narsil** [comment]
Hi linguistic dependency parsing is not something widely targeted by `transformers` models afaik.

The closest that comes to mind is `POS` tagging: https://huggingface.co/models?search=pos

`spacy` does real dependency parsing I think.  

Personal note: Be wary of dependency parsing. It looks nice on the surface, but really breaks down on many texts in the wild (Like nominal phrases, even regular oral sentences which omit part of the sentence, stuff like this).

**Comment by chris-opendata** [comment]
> Hi linguistic dependency parsing is not something widely targeted by `transformers` models afaik.
> 
> The closest that comes to mind is `POS` tagging: https://huggingface.co/models?search=pos
> 
> `spacy` does real dependency parsing I think.
> 
> Personal note: Be wary of dependency parsing. It looks nice on the surface, but really breaks down on many texts in the wild (Like nominal phrases, even regular oral sentences which omit part of the sentence, stuff like this).

Thanks for your suggestion and caution. It is true that deep learning of dependency parsing is not perfect and an ongoing research. But linguistic syntax and semantics are two important language structures to NLP. We are experimenting modeling using powerful Transformers(:

**Comment by Narsil** [comment]
Hi great to see more work in that direction.

Not sure what your direction is, but I do know that `image-segmentation` (more specifically `image-panoptic-segmentation`) shares a lot of similarity with dependency parsing (which is roughly `text-segmentation` with an additional tree of relationship on top).

Image segmentation (panoptic): Every pixel gets affected one or more instance, and one or more classes. And for each (instance, class), a parent is defined to get the tree structure.

So you can have like (car lights, instance: 0) belongs to (car,  instance: 1) and (car lights, instance:  2) belongs to (car, instance: 1) for instance. Just food for thought.

**Comment by chris-opendata** [comment]
> Hi great to see more work in that direction.
> 
> Not sure what your direction is, but I do know that `image-segmentation` (more specifically `image-panoptic-segmentation`) shares a lot of similarity with dependency parsing (which is roughly `text-segmentation` with an additional tree of relationship on top).
> 
> Image segmentation (panoptic): Every pixel gets affected one or more instance, and one or more classes. And for each (instance, class), a parent is defined to get the tree structure.
> 
> So you can have like (car lights, instance: 0) belongs to (car, instance: 1) and (car lights, instance: 2) belongs to (car, instance: 1) for instance. Just food for thought.

Thank you for providing the analogues from your extended knowledge. Good food for thoughts. Meanwhile, I close the issue since you have given me very clear answer and direction. Much appreciated.
