### ISSUE TITLE
Loading of Tokenizer is really slow when there are lots of additional tokens

### ISSUE THREAD

**Issue by PiercarloSlavazza** [huggingface/tokenizers#914]
I noticed this issue in the context of this [other issue](https://github.com/huggingface/transformers/issues/15733) reported on the 🤗 Transformers Github.

When you load a fast tokenizer from a `tokenizer.json` which contains lots of tokens (125936 in my case), it takes hours to loading.

That happens for both the slow and fast tokenizer - given that, in this respect, they behave in the very same way.

Indeed, [here](https://github.com/huggingface/tokenizers/blob/2fecdc10dd2792a2f033a27e510ac828c744d619/tokenizers/src/tokenizer/serialization.rs#L155) you can see that the code loads the tokens one at time - because it checks, after having added each token, that everything is ok.

However, adding a token at the time is really inefficient: in fact, that implies that the trie of the tokenizer is rebuilt each time, and this is the root cause of taking literally hours to load the tokenizer with my 125936 tokens.

I have two points:
1. I need a "quick&dirty" fix in order to have my tokenizer loaded and complete my task: the fix is trivial - just load all the tokens in one shot and - temporary - avoid the "sanity check" of the tokenizer status; however, I am totally new to Rust, and I cannot inderstand how I am supposed to compile everything and, let's say, "hot patch" my 🤗 Transformers installation with the new library; I run cargo build, I found the `tokenizers.d` and `libtokenizers.rlib` (I assume that these are the libs that eventually are somehow embedded in the transformers ), but I cannot find them in my Transformers installation: could you point me at some documenation that let me understand how the tokenizers libs are eventually bundled with the Transformers package?
2. I would like to propose a patch for this code, but - as you can infer from above notes - I didn't found any documentation that explains how to properly build the project and run the tests: could you please point me at the proper documentation?

**Comment by Narsil** [comment]
Hi @PiercarloSlavazza,


Thanks for the reports.

> I need a "quick&dirty" fix in order to have my tokenizer loaded and complete my task: the fix is trivial - just load all the tokens in one shot and - temporary - avoid the "sanity check" of the tokenizer status; however, I am totally new to Rust, and I cannot inderstand how I am supposed to compile everything and, let's say, "hot patch" my hugs Transformers installation with the new library; I run cargo build, I found the tokenizers.d and libtokenizers.rlib (I assume that these are the libs that eventually are somehow embedded in the transformers ), but I cannot find them in my Transformers installation: could you point me at some documenation that let me understand how the tokenizers libs are eventually bundled with the Transformers package?

- Modify the code in rust appropriately.
- Run `cargo test` (from `tokenizers/` directory) Just to make sure it compiles (you might see test failures too but you shouldn't I think)
- Go to `bindings/python` directory
- Run `pip install -e .` To compile the Rust library, and create the python bindings all in one go.

Then, you should be able to test your code classically `from tokenizers import ...` 

> I would like to propose a patch for this code, but - as you can infer from above notes - I didn't found any documentation that explains how to properly build the project and run the tests: could you please point me at the proper documentation?

If you want to propose a patch, that's very welcome. There's no doc per say on that, but the simple steps are:
- File the issue (ideally let's add a reproducible example there, currently there's none)
- Modify the code to fix the issue. Ideally you add a test. (Here it's a performance thing, not really a bug). We could add a benchmark, but really necessary (if you find a very simple way to add one it's welcome for sure)
- Any issue found by the CI, you can try and figure out for yourself, otherwise I'll look into it (bindings errors are not necessarily straightforward to understand for instance).

**Comment by PiercarloSlavazza** [comment]
@Narsil thanks for the hints.

I figured out (well, we'll see, let's say that the test pass for time being) the patch, successfully run `cargo test`, but, when I run `pip install -e .` it gives me the error:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.16.2 requires tokenizers!=0.11.3,>=0.10.1, but you have tokenizers 0.11.3 which is incompatible.

It's unclear to me which version exactly is neede by my version of transformers: I might be wrong, but, by looking at the transformers sources, I found that `tokenizers >=0.10.1,<0.11.0` for transformers 4.16.2.

So let's say that we need the latest in 0.10.*.

However, I noticed that you have tags like `node-v…`, `python-v…` etc: what are exactly the purpose of these different "class" of tags?

I guessed that I would need `python-v0.10.3` (given that it doesn't exist a simple `v0.10.3` or anyway `v0.10.*` at all), and so I checked it out - but when I run `cargo test` I get lots of compile errors ⇒ so, I think that my choice has been a bit naive… Could you please shed some light on this topic (or point me at some documentation)? Thank you.

**Comment by PiercarloSlavazza** [comment]
> I get lots of compile errors

sorry, I get errors when I run `pip install -e .` - compiling is fine.

**Comment by PiercarloSlavazza** [comment]
@Narsil I somehow managed to find the simplest possible setup:
* I have installed transformers from the git master
* I patched the `python-v0.11.5` branch of the tokenizers
* I installed the patch via `python setup.py install` as written in the readme

That way everything pass tests, and compile nicely.

However my patch is bugged:

This is the code I wrote in order to replace the statements referred above:

```python
        info!("optimized tokens loading");
        tokenizer.add_special_tokens(tokens.iter().
            filter(|added_token_with_id| added_token_with_id.special).
            map(|added_token_with_id| added_token_with_id.token.clone()).
            collect::<Vec<_>>().
            as_slice()
        );
        tokenizer.add_tokens(tokens.iter().
            filter(|added_token_with_id| !added_token_with_id.special).
            map(|added_token_with_id| added_token_with_id.token.clone()).
            collect::<Vec<_>>().
            as_slice()
        );

        for token in tokens {
            let tk = token.token.content.clone();

            // Warn the user if the id is different than expected
            let received_id = tokenizer.token_to_id(&tk);
            if received_id != Some(token.id) {
                warn!(
                    "Warning: Token '{}' was expected to have ID '{}' but was given ID '{}'",
                    tk,
                    token.id,
                    if let Some(rid) = received_id {
                        rid.to_string()
                    } else {
                        "None".to_string()
                    }
                );
            }
        }
```

But I messed up with the ids, because when I finally execute `AutoTokenizer.from_pretrained(…, use_fast=True, verbose=True)` I get the following error:

```
[…]
  File "/Users/slp/opt/anaconda3/envs/fast_tok/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 528, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/Users/slp/opt/anaconda3/envs/fast_tok/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1788, in from_pretrained
    return cls._from_pretrained(
  File "/Users/slp/opt/anaconda3/envs/fast_tok/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1966, in _from_pretrained
    raise ValueError(
ValueError: Wrong index found for urnexpltokenslegalref0
: should be 101 but found 31102.
```

And, in fact, the tokenizer.json is as follows (only relevant excerpt):

```json
  "added_tokens": [
    {
      "id": 0,
      "special": true,
      "content": "[PAD]",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": false
    },
    {
      "id": 101,
      "special": true,
      "content": "[UNK]",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": false
    },
...
    {
      "id": 31102,
      "special": false,
      "content": "urnexpltokenslegalref0",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": true
    },
```

Do you have any hint aimed at do not mess up ids while retaining the "optimization" of "bulk" tokens addition?

**Comment by PiercarloSlavazza** [comment]
Note that:
* 31102 is exactly the number of items of vocab.txt
* 101 if the id of UNK in the vocab.txt

**Comment by PiercarloSlavazza** [comment]
I tracked down why it returns 101 - that's because this statements in `tokenization_utils_fast.py`:

```python
    def _convert_token_to_id_with_added_voc(self, token: str) -> int:
        index = self._tokenizer.token_to_id(token)
        if index is None:
            return self.unk_token_id
        return index
```

Simply, the token is not found by `token_to_id()` (which is Rust code), and therefore is return 101 (that is, unk).

It seems that my above patched has been ineffective… but on the other hand all the tokenizers tests passed… @Narsil  any hint?

**Comment by PiercarloSlavazza** [comment]
I have found the culprit - and also some other "sub-optimal" code.

The problem is that, after the pre-training, the "added_tokens" put in the `tokenizer.json` had all a trailing new line character: I found this fact a bit "disturbing", and so I decided to do a clean up by removing that trailing char from every token in that file.

BUT, when the  code in `tokenization_utils_fast.py` checks for consitency of the ids, it turns out that it uses as "master" another file, the `added_tokens.json` (I do ignore why the very same information about these tokens must be recorded in two distinct files), where the tokens still had the trailing new line char.

So, I removed the trailing new line also froom `added_tokens.json` and the error stopped occurring.

Anyway, the loading of the tokenizer was still so slow…

It turns out that in `tokenization_utils_fast.py`, after the "consitency check", tokens are anyway added to the tokenizer - again!

```python
 # Safe to call on a tokenizer fast even if token already there.
tokenizer.add_tokens(token, special_tokens=bool(token in special_tokens))
```

Not really safe, indeed. In this case as well, for each token (re)added the whole trie is rebuilt from scratch…

I merciless removed the call to add_tokens and everything started to run at decent speed.

Obviously, if someone put that "failsafe" call to add_tokens() it does exist for sure some use case where it is needed… If someone has a clue about this hypothetical use case it would be really useful.

**Comment by Narsil** [comment]
Hi @PiercarloSlavazza ,

Do you mind sharing an example of code of how you train a tokenizer, and keeping the unbearably slow call ?
Your solution should be fine, but with a practical example of failure, we can add tests/benchmarks to make sure everything is fast in the future.
The code can be Python in transformers I don't mind.

**Comment by areschen2015** [comment]
@PiercarloSlavazza I have met a lot of warnings when starting the TGI service as following:
tokenizers-0.15.2/src/tokenizer/serialization.rs:159: Warning: Token '<|endoftext|>' was expected to have ID '151643' but was given ID 'None'
...
tokenizers-0.15.2/src/tokenizer/serialization.rs:159: Warning: Token '<|file_sep|>' was expected to have ID '151664' but was given ID 'None'
The content of config.json is as following:
"added_tokens": [
    {
        "id": 151643,
        "content": "<|endoftext|>",
......
    },
......
   {
        "id": 151664,
        "content": "<|file_sep|>",
......
    }
How to eliminate these warnings? 
Thanks!
