### ISSUE TITLE
Rstrip in AddedToken not working as supposed

### ISSUE THREAD

**Issue by AhmedIdr** [huggingface/tokenizers#917]
Hi I am not sure if this is a bug or not. I am trying to add some words to the vocabulary and I noticed there is some strange behavior during tokenization after adding new tokens. 
First  I added tokens using `tokenizers.add_tokens()` but I noticed that this can break tokenization, when a subword from an existing word in Vocab is added. For this reason, I decided to add tokens using AddedToken while setting `single_word=True` to avoid this Problem, but I noticed that this problem still persist but only when there is whitespace after the word. So I used `rstrip=True` in AddedToken but nothing changed. Btw the same problem happens when adding a completely new word and not only with subwords. 

Here is a notebook with some examples: https://colab.research.google.com/drive/1g0wstWW-qEdr77xpbQQR1uwosDW77AZY#scrollTo=UYLxhuEJYUPC

**Comment by Narsil** [comment]
This seems to be exactly the same bug as https://github.com/huggingface/tokenizers/issues/918#issuecomment-1049049640

`single_word` definitely is the option you are looking for to avoid the subword issue.

Can you confirm, this is the case ?

If you want, you can try to checkout the PR branch and build from source https://github.com/huggingface/tokenizers/tree/master/bindings/python#from-sources

**Comment by AhmedIdr** [comment]
After seeing the response in #918, I decided to run some more tests and the problem still persist in the cases that are mentioned in #918 and thats why I am reopening the issue. Here are the examples that I tested:

```
from transformers import AutoTokenizer
from tokenizers import AddedToken
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

tokenizer.tokenize("this is just a test")
# ['this', 'is', 'just', 'a', 'test']

first_word = AddedToken("jus", single_word=True)
tokenizer.add_tokens([first_word])
tokenizer.tokenize("this is just a test")
# ['this', 'is', 'just', 'a', 'test']

tokenizer.tokenize("just ")
# ['just']

tokenizer.tokenize("just.")
# ['just', '.']

second_word = AddedToken("thisisanewword", single_word=True)
tokenizer.add_tokens([second_word])
tokenizer.tokenize("this is just a test of thisisanewword")
# ['this', 'is', 'just', 'a', 'test', 'of', 'thisisanewword']

tokenizer.tokenize("this is just a test of thisisanewword ")
# ['this', 'is', 'just', 'a', 'test', 'of', 'thisisanewword']

tokenizer.tokenize("this is just a test of thisisanewword, ")
# ['this', 'is', 'just', 'a', 'test', 'of', 'this', '##isan', '##ew', '##word', ',']

tokenizer.tokenize("this is just a test of thisisanewworda ")
# ['this', 'is', 'just', 'a', 'test', 'of', 'this', '##isan', '##ew', '##word', '##a']

third_word = AddedToken("thisisanewword2", single_word=True, rstrip=True)
tokenizer.tokenize("this is just a test of thisisanewword2"
# ['this', 'is', 'just', 'a', 'test', 'of', 'thisisanewword2']

tokenizer.tokenize("this is just a test of thisisanewword2 ")
# ['this', 'is', 'just', 'a', 'test', 'of', 'thisisanewword2 ']

tokenizer.tokenize("this is just a test of thisisanewword2, ")
# ['this', 'is', 'just', 'a', 'test', 'of', 'this', '##isan', '##ew', '##word', '##2', ',']
```

**Comment by Narsil** [comment]
@AhmedIdr ,

I just realized the breaking change was much bigger than I thought, we moved away from regex definition and only handled raw space character.

I modified the PR to reflect a better fix.

"thisisanewword, " should match (`,` is not a word character in regexp spec)
"thisisanewworda ", will  not match

**Comment by AhmedIdr** [comment]
Hey @Narsil, I just tried the new PR and it seems to work much better, thank you. And yeah like you mentioned `thisisanewworda`should not match because of `single_word=True`.
