### ISSUE TITLE
Processing long multi-sentence sequences

### ISSUE THREAD

**Issue by binarymax** [huggingface/tokenizers#922]
What would be a reasonable way of processing long text, to get token encodings sentence by sentence?

tokenizers::Tokenizer::encode (https://docs.rs/tokenizers/latest/tokenizers/tokenizer/struct.Tokenizer.html#method.encode) assumes the sequence is only one sentence.  But I don't know the sentence boundaries ahead of time.  Passing in a long sequence (such as a paragraph with multiple sentences) currently stops at the first `<sep>` token and sets the ids to 0 for the rest of the sequence.

Thanks for your help!

**Comment by binarymax** [comment]
OK, nevermind this was my problem!

**Comment by Narsil** [comment]
No worries, just for other readers that might be curious, how did you solve your problem ?

Note: This library's goal doesn't aim at splitting at sentence boundaries, so in general, it's likely that the follow up model should it be a small range transformers, the model would crash. Solving this issue is beyond the scope of this library. Using a long range transformers could be a solution for instance.

**Comment by binarymax** [comment]
Sure - I was mistaken in that the sep was added to the end of the sequence and not sentence boundaries (what I meant when I said it's "my problem" :)).  I also saw that I can use get_overflowing on the tokenized result to get the vec of more tokenizations.  It's not very clear in the documentation/examples (for rust at least), how to handle large text where it gets truncated...so I will try to find some time at one point and add some docs!  In general I'm also confused why I'd use get_overflowing vs take_overflowing vs get_overflowing_mut...but I assume that's for use cases for others that I don't need or haven't thought of yet.

As per my sentence boundary problem - I will likely use a different model ahead of time for the split... https://github.com/bminixhofer/nnsplit looks like the best option...but I am very concerned about speed and don't want too much overhead.

**Comment by Narsil** [comment]
Thanks for sharing that.

>  why I'd use get_overflowing vs take_overflowing vs get_overflowing_mut

Can't even say from the top of my head, but being flexible and explicit and exhaustive seems to work.
Most importantly while writing the bindings it gives flexibility on how to talk with non ownership based languages.

>  https://github.com/bminixhofer/nnsplit

Don't know that lib, but it's unlikely to beat good heuristics splitting in terms of pure speed (but those heuristics will definitely contain more errors).
Good luck in your endeavor!

**Comment by binarymax** [comment]
Thanks!
