### ISSUE TITLE
Implement the Byte->char hack of SPM within BPE

### ISSUE THREAD

**Issue by Narsil** [huggingface/tokenizers#929]
The hack has been added here: 

https://github.com/huggingface/tokenizers/pull/896/files#diff-43edb84c28a212d7240c7e278964efe107d223b755acb42e3ab45ac1db2bd26aR377

To conform with the behavior of `SPM`.

Ideally we should find a way to move it out of `BPE` since this is very specific behavior, and we don't want to enable for all moedls (`Unigram`, `WordLevel`, `WordPiece` ) too.

It might prove hard, so the fallback is simply adding it as an option in the BPE config so we can still make the bigscience tokenizers work.

**Comment by Narsil** [comment]
Closing this as `ByteLevel` already implements this actually, so adding this within BPE is just asking for trouble

**Comment by SaulLu** [comment]
Hi! 

I'd like to revive this discussion because in transformers we are trying to export an spm tokenizer that has been trained with the fallback byte set to True (cf discussion [here](https://github.com/huggingface/transformers/pull/15529#pullrequestreview-930000241))! 

> Closing this as ByteLevel already implements this actually, so adding this within BPE is just asking for trouble

Reading your message @Narsil , I have the impression that you see what should be done to achieve the export, is this the case? :smile:

**Comment by Narsil** [comment]
@SaulLu 

My take on the steps to take to implement it is:

- Add the decoders Sequence functionnality
- Add a ByteFallBackDecoder (in addition to Metaspace)
- Add `byte_fallback` in all models (at least in BPE). Ideally this would be a pre_tokenizer, but currently I have not yet found a good way to handle that, since it's a fallback for when the `unk` token would be used (which is only done in the model itself).

As mentionned in this PR, the `ByteLevel` sort of enables byte level things, and this fallback being necessarily done in the model itself means it does not come as "natural" in this library. So that's why I didn't want to add this before it was necessary.

That being said, if it's used and necessary we should do it. 

Happy to take some time to find a better approach if it exists.

**Comment by SaulLu** [comment]
Thank you very much for offering your help on this :hugs: , I actually think it's a feature that would make sense to have :smile: 

Regarding the design you're proposing, I'm not sure to see why we would need a specific `ByteFallBackDecoder`, could you share a bit more? 

I may have had another design idea in mind (which is still pretty much high-level): I was wondering if it wouldn't make sense to be able to:
1. make the post processors composable (cf #873)
2. add the byte fallback as a post processor (in terms of logic this is the place where I best understand its role as it is not model specific - at least I think so). To achieve this post processor, I wonder if we couldn't use the offsets to go back to the initial text hidden under the unknow token and re-decompose it into bytes.

What do you think about this second design?

**Comment by Narsil** [comment]
I think it's a good design.

It seems super non-obvious the best approach to make `processors` composable, since the `Single`vs `Pair` is engrained in a lot of the code currently and making it composable might require to modify this to handle `lists` so that some processing could either "swallow" or not the lists (TemplateProcessing is in charge of composing multiple sequences, the proposed ByteFallbackProcessor would instead modify the original encodings directly) 

So a lot of work, but definitely a "sounder" approach.

**Comment by dongs0104** [comment]
bump up LlamaTokenizer need fallback option

**Comment by Narsil** [comment]
Post processors AND decoders are now sequential, so it would definitely be doable right now !

I'll try to tackle it not too far into the future.

**Comment by dongs0104** [comment]
ids assigned to the byte. Works for decoders, but <unk> tokens when encoding fall token

When using the Sentence piece model directly, the encoding will be correct
🥲
