### ISSUE TITLE
Prebuilding `tokenizers` for Mac M1.

### ISSUE THREAD

**Issue by Narsil** [huggingface/tokenizers#932]
We're at this point waiting for GH actions to support M1 runners.

Any help to do it differently is appreciated, but for now we will probably resolve to manual builds on a M1 computer we have as cross compilation is rendered hard because of both the CPP dependencies we have, and the PyO3 compatibility requirements (which would require us to cross compile Python too).

**Comment by McPatate** [comment]
Hey, I've added a few binaries for `0.11.6`. Feedback is welcome to see if everything works as expected !

**Comment by itchingpixels** [comment]
@McPatate : It works, thank you! would it be possible to automatically add it to all subsequent releases?

**Comment by McPatate** [comment]
We're waiting for the M1 workers to add it to our CI.

Will build manually for the time being as it's less hassle.

**Comment by moinnadeem** [comment]
Any luck doing this automatically? I think the latest release also requires Rust to build tokenizers, since prebuilt wheels for the M1 aren't available.
