### ISSUE TITLE
add special tokens does not work in GPT2Tokenizer

### ISSUE THREAD

**Issue by ahxchzt** [huggingface/tokenizers#945]
I want to add some special tokens to the GPT2 vocab but the function "add_ special_tokens" do not work.
My code just like this
`tokenizer=GPT2Tokenizer.from_pretrained(gpt2path)`

`kb=torch.load(kbpath)`

`tokenizer.add_special_tokens({'additional_special_tokens':list(kb)})`

`print(tokenizer.tokenize("i'd like to book a table at resto_bombay_expensive_british_4stars_2",add_special_tokens=True))`

`print("resto_bombay_expensive_british_4stars_2" in list(kb))`
The output of last print is 
**"True"**, 
so I think the special tokens in KB has been added into GPT2 vocab, but the output of the tokenizer.tokenize(...) is 
**['i', "'d", 'Ġlike', 'Ġto', 'Ġbook', 'Ġa', 'Ġtable', 'Ġat', 'Ġrest', 'o', '_', 'bomb', 'ay', '_', 'expensive', '_', 'b', 'rit', 'ish', '_', '4', 'stars', '_', '2']**
The special tokens is splited. Why?

**Comment by Narsil** [comment]
Hi, I am not able to reproduce locally:

```python
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

tokenizer.add_special_tokens({"additional_special_tokens": ["resto_bombay_expensive_british_4stars_2"]})

print(
    tokenizer.tokenize("i'd like to book a table at resto_bombay_expensive_british_4stars_2", add_special_tokens=True)
)
# resto_bombay_expensive_british_4stars_2 is correctly splitted away

```
Do you mind sharing a reproducible script ?

Also `GPT2Tokenizer` is actually a slow tokenizer and is being owned by `transformers`. this libary will handle `GPT2TokenizerFast`.  (But they should behave the same)

**Comment by ahxchzt** [comment]
@Narsil Thank you a lot. The reproducible script and the kb file is followed.

**My torch version: 1.6.0
My transformers version: 3.5.0**

`import torch`
`from transformers import GPT2Tokenizer`
`tokenizer=GPT2Tokenizer.from_pretrained("gpt2")`
`kb=torch.load("/home/kb/kb_vocab.pkl")`
`tokenizer.add_special_tokens({'additional_special_tokens':list(kb)})`
`print(tokenizer.tokenize("i'd like to book a table at resto_paris_moderate_indian_8stars_1_address ",add_special_tokens=True))`
