### ISSUE TITLE
Introspect python objects

### ISSUE THREAD

**Issue by cakiki** [huggingface/tokenizers#947]
I am currently doing something like this to get info about created normalizers and pretokenizers:

`eval(pre_tokenizer.__getstate__().decode('utf8'))` which returns the following dict: 

```
{'type': 'Sequence', 
'pretokenizers': [
                            {'type': 'WhitespaceSplit'}, 
                            {'type': 'Punctuation', 'behavior': 'Isolated'}
]
}
```

Is there a better way of doing this? Could this method ever fail?

**Comment by Narsil** [comment]
Hi @cakiki ,

This shouldn't fail in the sense that's it's what is being used for pickling/unpickling. The actual values in there might change though.

And this is definitely not the easiest user experience, having something more pythonic like `repr(pre_tokenizer)` could be interesting but does not exist atm.

**Comment by cakiki** [comment]
Thank you for the explanation @Narsil ! I'll go ahead and close the issue.
