### ISSUE TITLE
Different behaviors in adjusting vocab sizes when training WordPiece and Unigram

### ISSUE THREAD

**Issue by HelloRusk** [huggingface/tokenizers#950]
```python
    tokenizer = Tokenizer(Unigram())

    ...

    trainer = UnigramTrainer(
        vocab_size=30000,
        special_tokens=["[CLS]", "[SEP]", "<unk>", "<pad>", "[MASK]"], 
        unk_token="<unk>"
    )
    tokenizer.train_from_iterator(texts, trainer=trainer)

    ...

    tokenizer.save('foo/bar.json')
```

the resulting file contains 30,005 tokens 

```python
    tokenizer = BertWordPieceTokenizer()

    ...

    tokenizer.train_from_iterator(texts, vocab_size=30000)

    ...

    tokenizer.save('foo/bar.json')
```

the resulting file contains 30,000 tokens

**Comment by HelloRusk** [comment]
Which do you think is the expected way of handling vocab_size?
I mean, I would like to fix this problem as a discoverer.

**Comment by Narsil** [comment]
Hi @HelloRusk,

I am not entirely sure what's the best strategy to solve this atm.

The issues lies fundamentally in the fact that a `Tokenizer` as 2 places where vocab exists, the `AddedVocabulary` (pure list of strings, matched via roughly regexp) and the `Model` (which does the heavy lifting of splitting the string relative to BPE/Unigram algorithm.

You can check how BPETrainer handles this, I don't remember really but I think we force BPE to include the added tokens directly. I am not sure we should do that for Unigram.

You can try simply asking Unigram to train on `vocab_size` - `AddedVocabulary.vocab_size` for instance.
But that's the easy way out, there's probably more to it.

**Comment by HelloRusk** [comment]
It seems to me that all we need to do is change this line from `self.vocab_size` to `self.vocab_size - self.special_tokens.len()`, but is it not that simple?

https://github.com/huggingface/tokenizers/blob/4b6055d4fb6ac8223c57ca087ad37693f13ea196/tokenizers/src/models/unigram/trainer.rs#L135-L137

**Comment by Narsil** [comment]
Well the trainer doesn't have access to ` special_tokens`  I think, does it ?

**Comment by HelloRusk** [comment]
Oh really, I thought it does...

https://github.com/huggingface/tokenizers/blob/4b6055d4fb6ac8223c57ca087ad37693f13ea196/tokenizers/src/models/unigram/trainer.rs#L43-L54

So the field named `special_tokens` in Trainer is not related to the current problem?

Maybe I should start to learn Rust 😅

**Comment by Narsil** [comment]
No no, check it. Maybe it does and that's already taken care of and the trainer should definitely use that information.

If that's true then that's probably just `vocab_size - special_token.len()`.

(But check the variable is correctly populated though :))

**Comment by HelloRusk** [comment]
After struggling with the source, I found my guess was right.

**before:**

```py
from tokenizers import (
    SentencePieceUnigramTokenizer,
    AddedToken,
    models,
    pre_tokenizers,
    normalizers,
    Tokenizer,
    trainers,
)
filename = "tests/data/dummy-unigram-special_tokens-train.txt"
tokenizer = Tokenizer(models.Unigram())
trainer = trainers.UnigramTrainer(vocab_size=100, special_tokens=["[CLS]", "[SEP]", "<unk>", "<pad>", "[MASK]"])
tokenizer.train([filename], trainer=trainer)
tokenizer.save("tests/data/dummy.json")
```

-> `tests/data/dummy.json` has 105 tokens

**after:**

```rs
            if pieces.len() == self.vocab_size as usize - self.special_tokens.len() {
                break;
            }
```

```py
from tokenizers import (
    SentencePieceUnigramTokenizer,
    AddedToken,
    models,
    pre_tokenizers,
    normalizers,
    Tokenizer,
    trainers,
)
filename = "tests/data/dummy-unigram-special_tokens-train.txt"
tokenizer = Tokenizer(models.Unigram())
trainer = trainers.UnigramTrainer(vocab_size=100, special_tokens=["[CLS]", "[SEP]", "<unk>", "<pad>", "[MASK]"])
tokenizer.train([filename], trainer=trainer)
tokenizer.save("tests/data/dummy2.json")
```

-> `tests/data/dummy2.json` has 100 tokens!

**Comment by HelloRusk** [comment]
I can also verify that with `tokenizer.get_vocab_size()`
