### ISSUE TITLE
Ruby bindings

### ISSUE THREAD

**Issue by ankane** [huggingface/tokenizers#955]
Hey, thanks for the great NLP projects! Just wanted to share there are now [Ruby bindings](https://github.com/ankane/tokenizers-ruby) for 🤗 Tokenizers :tada:

It follows the Python API and is fairly basic right now, but should provide a good starting point for Ruby users. If you have any feedback, let me know or feel free to create an issue on the project. Thanks!

**Comment by Narsil** [comment]
This is so nice, would you be willing to make it within `tokenizers` itself ?

I am not sure about the level of maintenance, but definitely seems like a nice addition !

**Comment by Narsil** [comment]
Otherwise we will add a link to your binding !

**Comment by ankane** [comment]
Thanks @Narsil! I think it'll be easiest to manage as a separate project, but it uses the same license, so could be merged in the future if it makes sense.

**Comment by Narsil** [comment]
I created a PR to add a link in the README if you're ok with that !

**Comment by ankane** [comment]
That's great, thanks @Narsil!
