### ISSUE TITLE
Failing tests with python 3.10 due to changed error message

### ISSUE THREAD

**Issue by h-vetinari** [huggingface/tokenizers#957]
This is showing up in https://github.com/conda-forge/tokenizers-feedstock/pull/40, almost certainly because the text of the error being raised changed with python 3.10:
```
____________________ TestCustomNormalizer.test_instantiate _____________________

self = <tests.bindings.test_normalizers.TestCustomNormalizer object at 0x7fd354094ee0>

    def test_instantiate(self):
        bad = Normalizer.custom(TestCustomNormalizer.BadCustomNormalizer())
        good_custom = TestCustomNormalizer.GoodCustomNormalizer()
        good = Normalizer.custom(good_custom)
    
        assert isinstance(bad, Normalizer)
        assert isinstance(good, Normalizer)
        with pytest.raises(Exception, match="TypeError: normalize()"):
>           bad.normalize_str("Hey there!")
E           Exception: TypeError: TestCustomNormalizer.BadCustomNormalizer.normalize() missing 1 required positional argument: 'wrong'
```

The good news is that these seem to be the only relevant errors:
```
=========================== short test summary info ============================
FAILED tests/bindings/test_normalizers.py::TestCustomNormalizer::test_instantiate
FAILED tests/bindings/test_pre_tokenizers.py::TestCustomPreTokenizer::test_instantiate
================== 2 failed, 132 passed, 1 skipped in 57.25s ===================
```

Well, aside from the fact that windows does not support forking, so [this line](https://github.com/huggingface/tokenizers/blob/python-v0.11.6/bindings/python/tests/utils.py#L102) should be guarded to not run on windows.

**Comment by Narsil** [comment]
Yes this is known, we just need to update the test to reflect that, instead of checking the full string we can just check the common part (owned by `tokenizers`)

**Comment by h-vetinari** [comment]
Just noticing now that this is raising an `Exception` masquerading as a `TypeError`. Is there now way to raise the correct error type, or does that get lost in the pyo3-layer somewhere?
