### ISSUE TITLE
Can the `lstrip` argument of `AddedToken` be taken into account with an Unigram model?

### ISSUE THREAD

**Issue by SaulLu** [huggingface/tokenizers#959]
# Summary

It seems to me that when we add add tokens to a tokenizer of type Unigram with the `add_tokens` method the argument `lstrip` is not taken into account. 

# Example

```python
!git clone https://huggingface.co/albert-base-v2

from tokenizers import Tokenizer, AddedToken

backend_tokenizer = Tokenizer.from_file("albert-base-v2/tokenizer.json")

text = "this is a new_token_added_lstrip_false and a new_token_added_lstrip_true to test the tokenizer."
new_token_lstrip_false = "new_token_added_lstrip_false"
new_token_lstrip_true = "new_token_added_lstrip_true"

backend_tokenizer.add_tokens(
    [
        AddedToken(new_token_lstrip_false, lstrip=False, rstrip=False),
        AddedToken(new_token_lstrip_true, lstrip=True, rstrip=False)
    ]
)

print([backend_tokenizer.id_to_token(id) for id in backend_tokenizer.encode(text).ids])
# ['[CLS]', '▁this', '▁is', '▁a', 'new_token_added_lstrip_false', '▁and', '▁a', 'new_token_added_lstrip_true', '▁to', '▁test', '▁the', '▁to', 'ken', 'izer', '.', '[SEP]']
```

I was wondering if there is a reason that I am missing that explains that it is not the `['[CLS]', '▁this', '▁is', '▁a', '▁', 'new_token_added_lstrip_false', '▁and', '▁a', 'new_token_added_lstrip_true', '▁to', '▁test', '▁the', '▁to', 'ken', 'izer', '.', '[SEP]']` output that is sent back?

By comparison this argument seems to be well taken into account by a BPE type tokenizer. The output with the tokenizer of GPT2 is `['this', 'Ġis', 'Ġa', 'Ġ', 'new_token_added_lstrip_false', 'Ġand', 'Ġa', 'new_token_added_lstrip_true', 'Ġto', 'Ġtest', 'Ġthe', 'Ġtoken', 'izer', '.']`. 

If this can be useful, I share with you a [google colab](https://colab.research.google.com/drive/14vUlx1hwuTQGLYmH1LevFE6f22_F8rsN?usp=sharing) which gathers the comparison of these 2 types of tokenizers.

**Comment by Narsil** [comment]
Hi @SaulLu ,

I  think this is not Unigram vs BPE. The `added_tokens` are handled before landing into the model, so behavior cannot be attributed to the model, however I suspect the `decoder` + `pre_tokenizer` can affect it.

I think we can show that `lstrip` works correctly with this code:
I took the liberty of using the new `from_pretrained` directly included in `tokenizers` for simplicity :) (works only when the repo has the `tokenizer.json`.)

```python
from tokenizers import Tokenizer, AddedToken

backend_tokenizer = Tokenizer.from_pretrained("albert-base-v2")

text = "this is a new_token_added_lstrip_false and a new_token_added_lstrip_true to test the tokenizer."
new_token_lstrip_false = "new_token_added_lstrip_false"
new_token_lstrip_true = "new_token_added_lstrip_true"

backend_tokenizer.add_tokens(
    [
        AddedToken(new_token_lstrip_false, lstrip=False, rstrip=False),
        AddedToken(new_token_lstrip_true, lstrip=True, rstrip=False),
    ]
)

encoded = backend_tokenizer.encode(text)
print(encoded.tokens)
# This has the extra space in front.
# ['[CLS]', '▁this', '▁is', '▁a', 'new_token_added_lstrip_false', '▁and', '▁a', ' new_token_added_lstrip_true', '▁to', '▁test', '▁the', '▁to', 'ken', 'izer', '.', '[SEP]']
print([backend_tokenizer.id_to_token(id) for id in encoded.ids])
```

What does suprise me, is that the extra space before the strip is not taken by any token. I suspect `Metaspace` pre_tokenizer is responsible, do you want to me to check ?

**Comment by SaulLu** [comment]
Thank you very much for looking at my question. 

Sorry for not having be clear enough but indeed what surprises me is that the output is not 
```
['[CLS]', '▁this', '▁is', '▁a', '▁', 'new_token_added_lstrip_false', '▁and', '▁a', 'new_token_added_lstrip_true', '▁to', '▁test', '▁the', '▁to', 'ken', 'izer', '.', '[SEP]'] 
```
(the missing `'▁'` before `'new_token_added_lstrip_false'`)
when with `gpt2` it is 
```
['this', 'Ġis', 'Ġa', 'Ġ', 'new_token_added_lstrip_false', 'Ġand', 'Ġa', 'new_token_added_lstrip_true', 'Ġto', 'Ġtest', 'Ġthe', 'Ġtoken', 'izer', '.']
```
(note the `'Ġ'` before `'new_token_added_lstrip_false'`).

At the beginning, I didin't think it was related to the pre-tokenization because the "albert-base-v2" pre-tokenization gives:
```
[('▁this', (0, 4)),
 ('▁is', (5, 7)),
 ('▁a', (8, 9)),
 ('▁new_token_added_lstrip_false', (10, 38)),
 ('▁and', (39, 42)),
 ('▁a', (43, 44)),
 ('▁new_token_added_lstrip_true', (45, 72)),
 ('▁to', (73, 75)),
 ('▁test', (76, 80)),
 ('▁the', (81, 84)),
 ('▁tokenizer.', (85, 95))]
 ```
 
 and the `gpt2` pre-tokenizer gives:
 ```
 [('this', (0, 4)),
 ('Ġis', (4, 7)),
 ('Ġa', (7, 9)),
 ('Ġnew', (9, 13)),
 ('_', (13, 14)),
 ('token', (14, 19)),
 ('_', (19, 20)),
 ('added', (20, 25)),
 ('_', (25, 26)),
 ('lstrip', (26, 32)),
 ('_', (32, 33)),
 ('false', (33, 38)),
 ('Ġand', (38, 42)),
 ('Ġa', (42, 44)),
 ('Ġnew', (44, 48)),
 ('_', (48, 49)),
 ('token', (49, 54)),
 ('_', (54, 55)),
 ('added', (55, 60)),
 ('_', (60, 61)),
 ('lstrip', (61, 67)),
 ('_', (67, 68)),
 ('true', (68, 72)),
 ('Ġto', (72, 75)),
 ('Ġtest', (75, 80)),
 ('Ġthe', (80, 84)),
 ('Ġtokenizer', (84, 94)),
 ('.', (94, 95))]
 ```
 
 It's very kind to propose but I think it can be very valuable if you can check :smile:

**Comment by Narsil** [comment]
Putting back here what we've discussed internally:

The `pretokenizer`of this particular tokenizer is `[WhitespaceSplit(), Metaspace()]`.

That means that the steps that takes the `tokenizer` is 

- Original:  `"this is a new_token_added_lstrip_false and a new_token_added_lstrip_true to test the tokenizer."`
- AddedVocabulary:  `["this is a ", "new_token_added_lstrip_false" , " and a", " new_token_added_lstrip_true", " to test the tokenizer."]`
    The space is at the end of the first part,  all is good. The special tokens are ignored in the following steps, and the tokenizer will only treat non special items:
    `[ "this is a ", " and a",  " to test the tokenizer."]`
- Normalizer: Nothing new
- PreTokenizers:
    - WhitespaceSplit (**culprit**): Splits on every split, and **remove them**: `["this", "is", "a", "and", "a", "to", "test", "the "tokenizer."]`
    - Metaspace(add_prefix=true): readds the missing space on all tokens; ` ["_this", "_is", "_a", "_and", "_a", "_to", "_test", "_the", "_tokenizer"]`
    
And voila we "forgot" the extra space, never to be seen again.

The offsets also reflect that actually as we can see spaces between each words (reflecting that the tokenizer does not "see" the spaces within the original data).

**Comment by SaulLu** [comment]
Let me close this issue as the conclusion is that it is not related to `tokenizers` library! 

Thanks again for having look into it :smile:
