### ISSUE TITLE
Possible BUG in tokenizer.encode_plus

### ISSUE THREAD

**Issue by irenedini** [huggingface/tokenizers#965]
Hi everyone,

I'm currently extracting word representations from xlm-roberta-base. Since I need the representation of whole words, I have pre-tokenized my text and joined it with spaces before passing it to the tokenizer. I then use the method `tokenizer.encode_plus` which parameter `is_split_into_words` is set to `False` by default, according to the [documentation](https://huggingface.co/docs/transformers/v4.17.0/en/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.encode_plus.is_split_into_words). The problem is that I can actually call get the word_ids of the encoded sentence.

My code is:
```
...
sentence = "..." # is a string
encoded_tokens = tokenizer.encode_plus(sentence)
print('Sentence:', sentence)
print('Encoded token:', encoded_tokens)
print('Word ids:', encoded_tokens.word_ids())
```
and produces

```
Sentence: The financial assistance from the World Bank and the International Monetary Fund are not helping .
Encoded tokens: {'input_ids': [0, 581, 53477, 127557, 1295, 70, 6661, 4932, 136, 70, 8357, 103739, 6635, 32897, 621, 959, 120592, 6, 5, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
Word ids: [None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 15, 15, None]
```
My text is actually tokenized but I didn't set `is_split_into_words` to `True`, so I guess I shouldn't be able to get word ids.
Did I miss something?

Thans!!

**Comment by Narsil** [comment]
`words` is a tricky business and means a lot of different things especially in the context of `tokenizers` unfortunately.

In general the concept of `word` does not mean anything for a tokenizer (in the sense we tend to agree on in English).

In this library, as part of the tokenization, there is a preprocessing step call `pretokenization`. This part is essential for splitting up the input before getting to the core of the tokenization. This splitting is usually done along spaces and would be intended to split as "words" (even if not all words are space separated even in English).
Here the `word_ids` you are seeing are just the ids of the things that got pretokenized. `pretokens` could be a better name, but `word_ids` is now being used pretty much everywhere in code. Also there are many ways, and many places where you could pretokenize of chunk yourself the incoming string. which would be see able or not by this library, the naming will get hard no matter what. (and Those ids are usually intended to be representative as words which seems to be the case here).

If you were to presplit the thing yourself, you could see different numbers depending on how you did it.

In any case, what you are seeing is intended, and working as it should.

**Comment by Narsil** [comment]
Marking this as close, feel free to reopen if this wasn't clear or you think there's still an issue I didn't see.
