### ISSUE TITLE
'Can't convert ['test.txt'] to Trainer' when training a BertWordPieceTokenizer

### ISSUE THREAD

**Issue by suchunxie** [huggingface/tokenizers#974]
Hello. Hi Team,

I'm tring to train a Japanese Bert with my own data based on yours, but I  kept receiving the titled error when training my BertWordPieceTokenizer.
When I pass the train data path to train a tokenizer, every time there go's wrong,
the error is "Can't convert ['test.txt'] to Trainer".

here's something I tired:

pass a sigle filename or content of a single file (withine the same folder of the train_tokenizers.py file), the error appears.
pass a list of filenames like
      ['data_file/0.txt', 'data_file/1.txt', 'data_file/2.txt', 'data_file/3.txt', 'data_file/4.txt']
or single sentence list, the same error also occur.

Can you give any advise on this situation? Thanks a lot.

**Comment by suchunxie** [comment]
detailed infomation of the error:
Traceback (most recent call last):
  File "train_tokenizer.py", line 72, in <module>
    main(args)
  File "train_tokenizer.py", line 35, in main
    special_tokens=speical_tokens
  File "C:\Users\suchu\AppData\Roaming\Python\Python37\site-packages\tokenizers\implementations\bert_wordpiece.py", line 117, in train
    self._tokenizer.train(files, trainer)
TypeError: Can't convert ['file_path[:10000]'] to Trainer

**Comment by Narsil** [comment]
Hi @suchunxie,

Do you mind pasting here a minimal code to reproduce the error ?
Which version are you using ?

The error seems that the argument order is incorrect or something like that (since it tries to convert the input files to Trainer which is not what it should do). Without a reproducible example it's hard to answer for sure though.

Cheers.

**Comment by suchunxie** [comment]
Hi @Narsil ,

Thank you for your reply!
I'm using transformer== 3.4.0, and here's the train_tokenizer.py file I'm using (based on tohoku_bert_WWM, only changed the dictionary related settings): 
https://github.com/suchunxie/bert_tokenizer/blob/main/train_tokenizer.py

I input this in my powershell:
PS D:\Data\BERT\Model\bert-try\20200406_new> python train_tokenizer.py --input_files=0.txt\ --output_dir=20200406_new\ --tokenizer_type=word_piece\ --vocab_size=1000

and the error is now turned to : 
TypeError: 'NoneType' object cannot be interpreted as an integer (Detailed pls see the below picture.)

(The error sometimes change when I input different value into the commond line, but I think that's may related with the [bert_wordpiece.py]

![image](https://user-images.githubusercontent.com/85145489/162120637-db39e721-fb1f-4122-94fc-1967fd2cc617.png)

Yours sincerely.

**Comment by Narsil** [comment]
Hey can you try either of those code ?

```python
from tokenizers import Tokenizer, trainers, models, BertWordPieceTokenizer


# Option1
model = BertWordPieceTokenizer()
model = model.train(["data/big.txt"])

# Option2
model = Tokenizer(models.WordPiece())
trainer = trainers.BpeTrainer(min_frequency=12)
model = model.train(trainer, ["data/big.txt"])
```
These should work in your environement, from there you should be able to build your japanese tokenizer, right ?

**Comment by Narsil** [comment]
Also  `0.9` is rather old, don´t hesitate to upgrade if you can (it might change the API but I am not sure)

**Comment by suchunxie** [comment]
Hi Naesul,

I upgrade the tokenizers version and the files I input to is works!
Thank you guys for the great works you have been made.
