### ISSUE TITLE
What is the correct format for file for tokenizer.train_from_files?

### ISSUE THREAD

**Issue by winston0410** [huggingface/tokenizers#979]
I am trying to use this library and train a new model with my own data. But before I start building my corpora, I want to understand what file format should I be looking for, if I am feeding it to [`train_from_files`](https://docs.rs/tokenizers/0.11.3/tokenizers/tokenizer/struct.TokenizerImpl.html#method.train_from_files)? Is there a standard for that? It would be great if that can be documented.

**Comment by Narsil** [comment]
There's no particular format, you just feed text files `utf-8` encoded.

Usually it's strings from the dataset you're going to train your model with.

**Comment by winston0410** [comment]
I have realized that after trying out the quickstart example. Thank you for answer this newbie question!

**Comment by Narsil** [comment]
No worries ! Cheers.
