### ISSUE TITLE
Missing serialization preventing multiprocessing 

### ISSUE THREAD

**Issue by tholor** [huggingface/tokenizers#98]
Hey,

I finally found some time to test the new tokenizers. Seems really promising! Great work!
We measured speedups of about 8x :rocket: 

As mentioned here https://github.com/deepset-ai/FARM/issues/157, the only blocker for us right now:

:x: The Tokenizer objects **can't be pickled** and are therefore not usable with python's multiprocessing. As we make heavy use of multiprocessing during preprocessing, we can't really use them right now . Not sure how much of work is needed for fixing this, but for the XLM-R python tokenizer it was a very easy fix (https://github.com/huggingface/transformers/pull/2414).

Related to https://github.com/huggingface/tokenizers/issues/87

**Comment by n1t0** [comment]
The ability to pickle tokenizers has landed on master and is part of the `0.8.0.dev1` pre-release.
