### ISSUE TITLE
Post processor RobertaProcessing adds multiple [SEP] tokens on sentence pairs

### ISSUE THREAD

**Issue by dctelus** [huggingface/tokenizers#983]
Hi,

It seems as though RobertaProcessing adds multiple [SEP] tokens when passed a sentence pair, while BERT models expect only one (I think?):
```
import transformers
from tokenizers import processors
tokenizer = transformers.AutoTokenizer.from_pretrained("roberta-base")

print(tokenizer._tokenizer.encode("test", "test2").tokens)
# ['<s>', 'test', '</s>', '</s>', 'test', '2', '</s>']

tokenizer._tokenizer.post_processor = processors.ByteLevel()
print(tokenizer._tokenizer.encode("test", "test2").tokens)
# ['▁test', '▁test', '2']

tokenizer._tokenizer.post_processor = processors.RobertaProcessing(
  sep=("</s>", tokenizer._tokenizer.token_to_id("</s>")),
  cls=("<s>", tokenizer._tokenizer.token_to_id("<s>"))
)
print(tokenizer._tokenizer.encode("test", "test2").tokens)
# ['<s>', 'test', '</s>', '</s>', 'test', '2', '</s>']


tokenizer = transformers.AutoTokenizer.from_pretrained("albert-base-v2")
print(tokenizer._tokenizer.encode("test", "test2").tokens)
# ['[CLS]', '▁test', '[SEP]', '▁test', '2', '[SEP]']
```

**Comment by Narsil** [comment]
Hi @dctelus 

What exactly is the issue ? Do you mind sharing what are your expectations here ?

**Comment by dctelus** [comment]
@Narsil

I'd expect RobertaProcessing to only add one sep (`</s>`) token when a sentence pair is passed to the tokenizer. `['<s>', 'test', '</s>', 'test', '2', '</s>']` (like the alBERT tokenizer) instead of `['<s>', 'test', '</s>', '</s>', 'test', '2', '</s>']` above.

It might not be an issue functionally (I don't know), but all the BERT papers (inc. the RoBERTa paper) I've seen only use 1.

**Comment by Aroksak** [comment]
@Narsil

At least some RoBERTa models like CodeBERT (https://github.com/microsoft/CodeBERT) use single sep-token in pre-training, so in order to use them properly I had to use slow tokenizer and replace its build_inputs_with_special_tokens method. 

With RobertaTokenizerFast such workaround is impossible, and I couldn't make it behave like I want it to. I believe some sort of parameter to alternate this behavior would be useful.

**Comment by Narsil** [comment]
Hi @dctelus sorry didn't see your reply somehow.

`RobertaProcessing` is extremely specific, and is not really customizable for your use case.

`tokenizers` tries to provide more flexible processors if you can use them:



If you want a single `</s>`  as separator you can do 

```python
tokenizer._tokenizer.post_processor = TemplateProcessing(
 single="<s> $0 </s>",
 pair="<s> $A </s> $B:1 </s>:1",
 special_tokens=[("<s>", 1), ("</s>", 0)],
)
```

For instance. I am not sure if this will entirely satisfy your needs, (I think there's a few things very Roberta specific that required it to have it's own dedicated class)  but it should do the trick.

Overall the library tries to be designed to be modulable and configurable but `RobertaProcessing` definitely isn't.


@Aroksak 

> With RobertaTokenizerFast such workaround is impossible,

Do you mind giving a little example(s) of what you intend to achieve ? It's hard to know what's limiting you actually. It could be that there is some non obvious answer in the existing lib, or it is actually a limitation of the lib we could try to improve.

**Comment by dctelus** [comment]
AFAICT Roberta has its own class because it needs to combine a BERT post_processor with a ByteLevel post_processor (and post_processor doesn't support multiple post_processors). I might be wrong though.

I have not seen any indication that Roberta needs 2 SEP tokens so I was assuming this was a mistake in the Rust implementation of the post-processor.

**Comment by Narsil** [comment]
> AFAICT Roberta has its own class because it needs to combine a BERT post_processor with a ByteLevel post_processor (and post_processor doesn't support multiple post_processors). I might be wrong though.

You're probably correct.

> I have not seen any indication that Roberta needs 2 SEP tokens so I was assuming this was a mistake in the Rust implementation of the post-processor.


```python
slow_tokenizer = AutoTokenizer.from_pretrained('roberta-base', use_fast=False)
fast_tokenizer = AutoTokenizer.from_pretrained('roberta-base', use_fast=True)
```
And checking parity should help settle the debat, both tokenizers are checked when they get inserted into `transformers` so they should match !

**Comment by LysandreJik** [comment]
Hey @dctelus, we aim to stay as close as possible to the original implementation. If you check the original implementation, you can see that the sequences are built this way:

https://github.com/facebookresearch/fairseq/blob/main/fairseq/models/roberta/hub_interface.py#L58-L65

```
        bpe_sentence = "<s> " + self.bpe.encode(sentence) + " </s>"
        for s in addl_sentences:
            bpe_sentence += " </s>" if not no_separator else ""
            bpe_sentence += " " + self.bpe.encode(s) + " </s>"
        tokens = self.task.source_dictionary.encode_line(
            bpe_sentence, append_eos=False, add_if_not_exist=False
        )
        return tokens.long()
```

The `bpe_sentence` is therefore built as such: `<s> {sequence} </s> </s> {sequence_2} </s>`

**Comment by dctelus** [comment]
makes sense, thx everyone for the answers!

**Comment by Aroksak** [comment]
As a workaround if you still need single sep token (for example to fine-tune CodeBERT), but want to use fast implementation, you can do this:
```
tokenizer = RobertaTokenizerFast.from_pretrained("./checkpoints/codebert-base")
tokenizer._tokenizer.post_processor = processors.BertProcessing(
    sep=("</s>", tokenizer._tokenizer.token_to_id("</s>")),
    cls=("<s>", tokenizer._tokenizer.token_to_id("<s>"))
)
```
