### ISSUE TITLE
Problems in building tokenizer with a not space-separated language 

### ISSUE THREAD

**Issue by seiichiinoue** [huggingface/tokenizers#990]
## What I want to do

When learning vocabulary of a not space-separated language such as Japanese with BPE, I think it is ordinary we use raw text.
However, I often want to build tokenizer using pre-segmented text (segment with morphological analyser) in order to avoid merging across words or morphemes.

There are the examples in Japanese tokenization:

Vocabulary built with raw text (occur merge across morphemes):
```
corpus: ["私はりんごが好きです", "私はみかんが好きです"]
vocab: ["私は", "りんご", "みかん", "が好き", "です"]
```
Vocabulary built with pre-segmented text (intended behavior):
```
corpus: ["私 は りんご が 好き です", "私 は みかん が 好き です"]
vocab: ["私", "は", "りんご", "みかん", "が", "好き", "です"]
```

## Problems in implementation

However, I think that the current implementation does not work as intended because it **does not have a function to remove spaces as delimiter to present word boundaries** in BPE / BBPE tokenizer building.

This means that a space that is merely a delimiter presenting word or morpheme units is treated as one of the symbols like in English (originally space-separeted language).
This causes a language that does not contain spaces, such as Japanese, to be treated as space-separated language.
That is resulting in tokens with having spaces in head of token, such as "\<space\>私" ("\<space\>I") and "\<space\>は" ("\<space\>am") in the example above.

I investigated this strange behavior and may found the reason of this  in `pre_tokenize.rs`.
In `pre_tokenize.rs`, words is segmented using regex:
https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/pre_tokenizers/byte_level.rs#L37
then, unnecessary tokens are removed using split method (delimiter behavior: isolated):
https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/pre_tokenizers/byte_level.rs#L120

I think this process is only for space-separated language (because regex above is such that space+word "\<space\>hoge" is found with priority over space "\<space\>"), so I needed to change source code like below and re-build source to realize intended behavior:
	
```rust
37c37
<         Regex::new(r"\s+")
---
>         Regex::new(r"'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+")
120c120
<                 normalized.split(re_ref, SplitDelimiterBehavior::Removed)
---
>                 normalized.split(re_ref, SplitDelimiterBehavior::Isolated)
```
	
For this kind of demand, I think it would be better to change the implementation to be able to change regex type (I also found TODO comment in source code that you would like to update).
I would like to know if it is possible to achieve the above behavior without such manipulation. Is there any way to realize this with the current implementation? If not, I would like to commit and send Pull Request!

**Comment by Narsil** [comment]
Hi @seiichiinoue ,

Since `0.12.1` you can disable the Regex entirely (`ByteLevel(..., use_regex=false)`)  which should enable you to use another pre_tokenizer as a Regexp if you want.

`tokenizer.pre_tokenizer = Sequence([WhitespaceSplit(), ByteLevel(use_regex=false)])` for instance.

Since you're back in control of the regex here, you can choose the behavior yourself.

Would that solve your issue ?

**Comment by seiichiinoue** [comment]
Thank you! Same results were obtained by adding `add_prefix_space = False` option.

>But bear in mind that this space addition will only be seen by the underlying model, so it shouldn't really affect model performance, it only enables the model to differenciate between start of word and continuation of "word"

I know this. The essential problem is that, as mentioned above, in the case of Japanese, duplicate tokens such as "\<space\>りんご" and "りんご" are created when constructing the tokenizer.
However, following your advice seems to solve the problem! Thank you!

**Comment by enze5088** [comment]
> 您可以通过执行以下操作删除自动“空格添加”：
> 
> ```python
> from tokenizers import trainers, models, Tokenizer, pre_tokenizers
> 
> pre_tokenizer = pre_tokenizers.Sequence(
>     [
>         pre_tokenizers.WhitespaceSplit(),
>         pre_tokenizers.ByteLevel(add_prefix_space=False, use_regex=False),
>     ]
> )
> 
> print(pre_tokenizer.pre_tokenize_str("私 は りんご が 好き です"))
> # [('ç§ģ', (0, 1)), ('ãģ¯', (2, 3)), ('ãĤĬãĤĵãģĶ', (4, 7)), ('ãģĮ', (8, 9)), ('å¥½ãģį', (10, 12)), ('ãģ§ãģĻ', (13, 15))]
> ```
> 
> 但请记住，这种空格添加只会被底层模型看到，因此它不会真正影响模型性能，它只会使模型能够区分单词的开头和“单词”的延续（单词是字符串）原来是分开的）



> You can remove the automated "space addition" by doing this:
> 
> ```python
> from tokenizers import trainers, models, Tokenizer, pre_tokenizers
> 
> pre_tokenizer = pre_tokenizers.Sequence(
>     [
>         pre_tokenizers.WhitespaceSplit(),
>         pre_tokenizers.ByteLevel(add_prefix_space=False, use_regex=False),
>     ]
> )
> 
> print(pre_tokenizer.pre_tokenize_str("私 は りんご が 好き です"))
> # [('ç§ģ', (0, 1)), ('ãģ¯', (2, 3)), ('ãĤĬãĤĵãģĶ', (4, 7)), ('ãģĮ', (8, 9)), ('å¥½ãģį', (10, 12)), ('ãģ§ãģĻ', (13, 15))]
> ```
> 
> But bear in mind that this space addition will only be seen by the underlying model, so it shouldn't really affect model performance, it only enables the model to differenciate between start of word and continuation of "word" (word being however the string was originally splitted)

Hope to add a feature,  for the space-separated language, keep the space prefix, non space-separated language can eliminate the extra space

**Comment by enze5088** [comment]
> You can remove the automated "space addition" by doing this:
> 
> ```python
> from tokenizers import trainers, models, Tokenizer, pre_tokenizers
> 
> pre_tokenizer = pre_tokenizers.Sequence(
>     [
>         pre_tokenizers.WhitespaceSplit(),
>         pre_tokenizers.ByteLevel(add_prefix_space=False, use_regex=False),
>     ]
> )
> 
> print(pre_tokenizer.pre_tokenize_str("私 は りんご が 好き です"))
> # [('ç§ģ', (0, 1)), ('ãģ¯', (2, 3)), ('ãĤĬãĤĵãģĶ', (4, 7)), ('ãģĮ', (8, 9)), ('å¥½ãģį', (10, 12)), ('ãģ§ãģĻ', (13, 15))]
> ```
> 
> But bear in mind that this space addition will only be seen by the underlying model, so it shouldn't really affect model performance, it only enables the model to differenciate between start of word and continuation of "word" (word being however the string was originally splitted)

Hope to add a feature, for the space-separated language, keep the space prefix, non space-separated language can eliminate the extra space

**Comment by enze5088** [comment]
Or provide an interface for custom regular expression
