### ISSUE TITLE
[Docs] Clarify how Tokenizer.pad_to_multiple_of is useful in allowing use of GPU tensor cores

### ISSUE THREAD

**Issue by ldorigo** [huggingface/tokenizers#991]
Hi! I'm not entirely sure of the best place to put this issue; the main Transformers repo links to https://github.com/huggingface/hub-docs/issues for issues about the website, but that seems to be for the Hub website, not the main huggingface documentation? 

In the docs for `Tokenizer.__call__()` ( https://huggingface.co/docs/transformers/main/en/main_classes/tokenizer#transformers.PreTrainedTokenizer.__call__.pad_to_multiple_of ), you write:

> pad_to_multiple_of (int, optional) — If set will pad the sequence to a multiple of the provided value. This is especially useful to enable the use of Tensor Cores on NVIDIA hardware with compute capability >= 7.5 (Volta).

I tried my best but couldn't find any additional information on how to do that. You could maybe consider adding a link to your own or external documentation on how to do that? (for reference, I read your article on optimizing for GPU and tried searching the docs for "Volta" but to no avail).

P.s.: unrelated, but the UX in your docs is absolutely stellar. Keep up the good work.

**Comment by sherlcok314159** [comment]
Maybe you can refer to this [post](https://developer.nvidia.com/blog/optimizing-gpu-performance-tensor-cores/).

**Comment by Narsil** [comment]
Very old issue that I somehow missed. sorry about that.

For future readers, nvidia drivers tend to prefer matrices of shapes of size multiple of eights including the sequence_length that this lib will produce.

However now in 2023, this is less and less true, newer drivers and cuda versions are smarter about this and will be able to use tensorcores even without this aligned padding. Your mileage may vary, and check is always better !

**Comment by karu03** [comment]
the 'pad_to_multiple_of'  is an parameter which is used for padding to resize the embedding layer to use tensor cores for better performance

if you don't pass the arg it will give you the warning
"**You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embedding dimension will be 268525. This might induce some performance reduction as *Tensor Cores* will not be available.** 

it uses int input EX: 4 (TF32) / 8 (FP16) / 16 (INT8)  32 (TF32) / 64 (FP16) / 128 (INT8) 
it depends on the GPU architecture
for easy way 
32 (TF32) / 64 (FP16) / 128 (INT8)  is for high end GPU like A100

for more info visit this article by Nvidia:https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#


you can use this args in you code to resize the embedings as **model.resize_token_embeddings(original_vocab_size,pad_to_multiple_of = 8)**
